objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/fields/Last_Number_Used__c.field-meta.xml
<CustomField>
    <fullName>Last_Number_Used__c</fullName>
    <label>Last Number Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Numbering_Series__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Numbering_Series__c/fields/Separator__c.field-meta.xml
<CustomField>
    <fullName>Separator__c</fullName>
    <label>Separator</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Payroll__c/Payroll__c.object-meta.xml
<CustomObject>
    <label>Payroll</label>
    <nameField>
        <label>Payroll No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payrolls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PayrollTriggersMgmt.cls
public with sharing class PayrollTriggersMgmt {
    public static Map<String,Numbering_Series__c> mapNumberSeries = new Map<String,Numbering_Series__c>();
    public static Numbering_Series__c theNumberingSeries;
    
    //Payroll Header Insert Update
    public static void PRInsertUpdate(Payroll__c[] PRList, Map<Id, Payroll__c> oldPRMap, Boolean isInsert) {
        for (Payroll__c thePR : PRList) {
            if (isInsert) {
                mapNumberSeries = companyMgmt.getNumber('Payroll');
                theNumberingSeries = mapNumberSeries.get('Payroll');
                thePR.Name = theNumberingSeries.Prefix__c + theNumberingSeries.Separator__c + String.valueOf(theNumberingSeries.Last_Number_Used__c);
            } else {
                if ((thePR.Name != oldPRMap.get(thePR.Id).Name) && (!Test.isRunningTest())){
                    thePR.addError('You are not allowed to change Timesheet No: ' + thePR.Name);
                }
            }
        }
        update mapNumberSeries.values();
    }
}