objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/fields/Last_Number_Used__c.field-meta.xml
<CustomField>
    <fullName>Last_Number_Used__c</fullName>
    <label>Last Number Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Numbering_Series__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Numbering_Series__c/fields/Separator__c.field-meta.xml
<CustomField>
    <fullName>Separator__c</fullName>
    <label>Separator</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Service_Center__c/fields/Max_No_of_Emergency_T_M__c.field-meta.xml
<CustomField>
    <fullName>Max_No_of_Emergency_T_M__c</fullName>
    <label>Max No. of Emergency T&amp;M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Service_Center__c/fields/Sales_Order_No_Series__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_No_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order No. Series</label>
    <referenceTo>Numbering_Series__c</referenceTo>
    <relationshipLabel>Service Centers (Job Numbering Series)</relationshipLabel>
    <relationshipName>Service_Centers_Job_Numbering_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/fields/Temporary__c.field-meta.xml
<CustomField>
    <fullName>Temporary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Temporary?</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/fields/TM_No_Series__c.field-meta.xml
<CustomField>
    <fullName>TM_No_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M No. Series</label>
    <referenceTo>Numbering_Series__c</referenceTo>
    <relationshipLabel>Service Centers(TM Numbering Series)</relationshipLabel>
    <relationshipName>Service_Centers_TM_Numbering_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Company__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

classes/ServiceCentersSelectorTest.cls
@IsTest
private class ServiceCentersSelectorTest {

    @IsTest
    private static void test(){

        Numbering_Series__c theNS;
        List<Numbering_Series__c> theNSList = new List<Numbering_Series__c>();

        theNS = new Numbering_Series__c();
        theNS.Name = 'JOB01';
        theNS.Prefix__c = 'NJ';
        theNS.Separator__c = '-';
        theNS.Last_Number_Used__c = 1000000;
        theNSList.add(theNS);
        theNS = new Numbering_Series__c();

        Subsidiary_Company__c subC = new Subsidiary_Company__c(
                Name = '1-REPUBLIC SERVICES',
                Display_Name__c = 'SO'
        );
        insert subC;

        Service_Center__c sc = new Service_Center__c(
                Name = '01',
                Description__c = 'SC01 Elizabeth, NJ Ops',
                Subsidiary_Company__c = subC.Id,
                TM_No_Series__c = theNSList[0].Id,
                //Sales_Order_No_Series__c = theNumberingSeries.Id,
                //Sales_Order_No_Series__c = '',
                Max_No_of_Emergency_T_M__c = 2,
                Code__c = '01',
                City__c = 'Elizabeth',
                Street__c = '201 South First St.',
                Postal_Code__c = '07206',
                State__c = 'NJ',
                Country__c = 'US',
                Temporary__c = true

        );
        insert sc;

        ServiceCentersSelector selector = new ServiceCentersSelector();
        selector.selectById(new Set<Id>{sc.Id});
        selector.selectAll();
        selector.selectByName(sc.name);
    }
}