objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ResourceTypeUOMAssociation__c/ResourceTypeUOMAssociation__c.object-meta.xml
<CustomObject>
    <label>Resource Type Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Type Unit of Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceTypeUOMAssociation__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipName>ResourceTypeUOM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ResourceTypeUOMAssociation__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipName>ResourceTypeUOMAssociation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Unit_of_Measure__c/fields/Hours_UOM__c.field-meta.xml
<CustomField>
    <fullName>Hours_UOM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hours UOM</label>
    <type>Checkbox</type>
</CustomField>

classes/ResourceTypeUnitOfMeasuresSelector.cls
public with sharing class ResourceTypeUnitOfMeasuresSelector extends fflib_SObjectSelector {

    public static ResourceTypeUnitOfMeasuresSelector newInstance(){
        return (ResourceTypeUnitOfMeasuresSelector) Application.Selector.newInstance(ResourceTypeUOMAssociation__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
            ResourceTypeUOMAssociation__c.Id,
            ResourceTypeUOMAssociation__c.Name,
            ResourceTypeUOMAssociation__c.Resource_Type__c,
            ResourceTypeUOMAssociation__c.Unit_of_Measure__c,
            ResourceTypeUOMAssociation__c.Unit_Cost__c,
            ResourceTypeUOMAssociation__c.Unit_Price__c,
            ResourceTypeUOMAssociation__c.ER_Unit_Price__c
        };
    }

    public Schema.SObjectType getSObjectType(){
        return ResourceTypeUOMAssociation__c.SObjectType;
    }

    public List<ResourceTypeUOMAssociation__c> selectById(Set<Id> ids){
        return (List<ResourceTypeUOMAssociation__c>) super.selectSObjectsById(ids);
    }

    public List<ResourceTypeUOMAssociation__c> selectByResTypeId(Set<Id> resTypeIds){
        fflib_QueryFactory resourceTypeUOMAssociationQueryFactory = newQueryFactory();
        //aura <<
        //return Database.query(resourceTypeUOMAssociationQueryFactory.setCondition('Resource_Type__c IN :resTypeIds').toSOQL());
        return Database.query(resourceTypeUOMAssociationQueryFactory
                .selectField('Unit_of_Measure__r.Hours_UOM__c')
                .setCondition('Resource_Type__c IN :resTypeIds').toSOQL());
        //aura >>
    }

    public List<ResourceTypeUOMAssociation__c> selectByResTypeIdByUOMId(Id resTypeId, Id uomId){
        return new List<ResourceTypeUOMAssociation__c>(
                (List<ResourceTypeUOMAssociation__c>) Database.query(newQueryFactory(true).
                    selectField('Unit_of_Measure__r.Name').
                    //aura <<
                    selectField('Unit_of_Measure__r.Hours_UOM__c').
                    //aura >>
                    setCondition('Resource_Type__c = :resTypeId AND Unit_of_Measure__c = :uomId').toSOQL())
                );
    }
}