objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Resource_Class_Code__c.field-meta.xml
<CustomField>
    <fullName>Resource_Class_Code__c</fullName>
    <description>Show the Resource Class Code from EQAI</description>
    <label>Resource Class Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <description>Employee Workday Number</description>
    <label>RSG EIN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ResourcesServiceTest.cls
/*************************************************************************************************
* Name         :  ResourcesServiceTest
* Description  :  Test class for ResourcesService
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Pavithra Periyasamy		03/20/2025             US144300: Resource Sync : Salesforce : Labor : New/Termed Labor Resources sync from EQAI to Salesforce
***********************************************************************************************************/
@isTest
private class ResourcesServiceTest {
    @isTest
    static void testUpsertResources_Success() {
        Test.startTest();
        // Create test data for Resource_Type__c
        Resource_Type__c resourceType = new Resource_Type__c(Name='Test Resource Type', Resource_Class_Code__c='TestCode');
        insert resourceType;
        Id profileId = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1].Id;
        List<User> userList = new List<User>();
        
        User userRecord = new User(
            FirstName = 'Test',
            LastName = 'User1',
            Username = 'testuser1@example.com.test',
            Email = 'testuser1@republicservices.com',
            Alias = 'tus1',
            ProfileId = profileId,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            RSG_EIN__c = '12345'
        );
        User userRecord1 = new User(
            FirstName = 'Test',
            LastName = 'User2',
            Username = 'testuser2@example.com.test',
            Email = 'testuser2@republicservices.com',
            Alias = 'tus2',
            ProfileId = profileId,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            RSG_EIN__c = '12346'
        );
        userList.add(userRecord);
        userList.add(userRecord1);
        
        insert userList;
        
        // Create test data for Service_Center__c
        NewTestData.createTestData();
        Service_Center__c serviceCenter = NewTestData.mapServiceCenterWrappersByName.get('02').ServiceCenter;
        
        
        
        // Create a JSON request body
        ResourceRequest request = new ResourceRequest();
        
        ResourceRequest.ResourceInfo resourceInfo = new ResourceRequest.ResourceInfo();
        
        resourceInfo.Resource_CSID = null;
        resourceInfo.resource_type = 'Labor';
        resourceInfo.First_Name = 'John';
        resourceInfo.Last_Name = 'Doe';
        resourceInfo.Resource_code = 'R123';
        resourceInfo.Resource_Class = 'TestCode';
        resourceInfo.company_id = 72;
        resourceInfo.default_profit_ctr_id = 8;
        resourceInfo.Employee_Id = '12345';
        resourceInfo.resource_status =  'Active';
        
        
        ResourceRequest.ResourceInfo resourceInfo1 = new ResourceRequest.ResourceInfo();
        
        resourceInfo1.Resource_CSID = null;
        resourceInfo1.resource_type = 'Labor';
        resourceInfo1.First_Name = 'John';
        resourceInfo1.Last_Name = 'Doe';
        resourceInfo1.Resource_code = 'R123';
        resourceInfo1.Resource_Class = 'TestCode';
        resourceInfo1.company_id = 72;
        resourceInfo1.default_profit_ctr_id = 8;
        resourceInfo1.Employee_Id = '12346';
        resourceInfo1.resource_status =  'Inactive';
        request.Resources = new List<ResourceRequest.ResourceInfo> { resourceInfo,resourceInfo1 };
            String jsonString = JSON.serialize(request);
        // Create the mock request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueOf(jsonString);
        req.httpMethod = 'PUT';
        RestContext.request = req;
        RestContext.response = res;
        
        
        ResourcesService.upsertResources();
        Test.stopTest();
        
        // Validate the response
        System.assertEquals(200, res.statusCode);
        String responseBody = res.responseBody.toString();
        System.debug('Response Body: ' + responseBody);
        System.assert(responseBody.contains('Resource created successfully'));
    }
    
    @isTest
    static void testUpsertResources_Exception() {
        // Invalid JSON to simulate an exception
        String invalidJsonBody = '{"invalidField": "value"}';
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestBody = Blob.valueOf(invalidJsonBody);
        req.httpMethod = 'PUT';
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        ResourcesService.upsertResources();
        Test.stopTest();
        
        // Validate exception response
        System.assertEquals(500, res.statusCode);
        String responseBody = res.responseBody.toString();
        System.assert(responseBody.contains('Error'));
    }
}