objects/Equipment_Group__c/Equipment_Group__c.object-meta.xml
<CustomObject>
    <label>Equipment Group</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Equipment_Group__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Group</label>
    <referenceTo>Equipment_Group__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Resource_Type__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field is used to prevent users from selecting a resource type if the date selected is prior the current date.  Otherwise it will allow billing to be completed for existing sales lines, TM lines, and billing worksheets.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Resource_Type__c/fields/Equipment_Group__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Group</label>
    <referenceTo>Equipment_Group__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM__c/fields/Scheduled_Date_Weekend__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date_Weekend__c</fullName>
    <formula>IF( 
OR( 
(MOD( Scheduled_Date__c - DATE(1900, 1, 7), 7) == 0), 
(MOD( Scheduled_Date__c - DATE(1900, 1, 7), 7) == 6)), 
true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Date Weekend</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Billing Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <formula>TM__r.Scheduled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/fields/Total_Job_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Job_Hours__c</fullName>
    <label>Total Job Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/EmployeeUtilizationController.cls
public class EmployeeUtilizationController {

    public static String defaultServiceCenter { get; set; }

    /******************* Method called by the generate document functionality *********************/
    public static List<TMLineWrapper> getTMLaborLinesPDF() {
        String ServiceCenter = System.currentPageReference().getParameters().get('ServiceCenter');
        String startDate = System.currentPageReference().getParameters().get('startDate');
        String endDate = System.currentPageReference().getParameters().get('endDate');
        String includeWeekend = System.currentPageReference().getParameters().get('includeWeekend');

        system.debug('***ServiceCenter' + ServiceCenter);
        system.debug('***startDate' + startDate);
        system.debug('***endDate' + endDate);
        system.debug('***includeWeekend' + includeWeekend);
        List<TMLineWrapper> wrapperList = getTMLaborLines(ServiceCenter, startDate, endDate, includeWeekend);
        return wrapperList;
    }

    /******************* Method to return the TM Lines and populate the report *********************/
    @AuraEnabled
    public static List<TMLineWrapper> getTMLaborLines(String ServiceCenter, String startDate, String endDate, String includeWeekend) {
        Map<String, TMHoursWrapper> TMHoursMap = new Map<String, TMHoursWrapper>();
        Map<String, TMLineWrapper> TMLineMap = new Map<String, TMLineWrapper>();

        system.debug('!!ServiceCenter ' + ServiceCenter);
        system.debug('!!startDate ' + startDate);
        system.debug('!!endDate ' + endDate);

        // Setting the default filter for service center
        if (ServiceCenter == null) {
            ServiceCenter = defaultServiceCenter;
        }

        // Setting the default filter for includeWeekend
        if (includeWeekend == null) {
            includeWeekend = 'false';
        }

        // Build query
        Id blankResourceId = null;
        String query;
        if (ServiceCenter != 'All') {
            query = 'SELECT  Id, Name, Description__c, Total_Job_Hours__c, Resource__r.Service_Center__c, Resource__r.Name, TM__r.Service_Center__c, Resource__r.Resource_Type__r.Name, ' +
                    'Service_Center__c, Resource_Type__r.Name, Resource__r.Description__c, Service_Center__r.Name, TM__r.Scheduled_Date__c, Resource__r.Service_Center__r.Name ' +
                    'FROM TM_Line__c ' +
                    'WHERE Category__c = \'Labor\' ' +
                    'AND Resource__r.Service_Center__c =: ServiceCenter AND Resource__c != :blankResourceId ';
        } else {
            query = 'SELECT  Id, Name, Description__c, Total_Job_Hours__c, Resource__r.Service_Center__c, Resource__r.Name, TM__r.Service_Center__c, Resource__r.Resource_Type__r.Name, ' +
                    'Service_Center__c, Resource_Type__r.Name, Resource__r.Description__c, Service_Center__r.Name, TM__r.Scheduled_Date__c, Resource__r.Service_Center__r.Name ' +
                    'FROM TM_Line__c ' +
                    'WHERE Category__c = \'Labor\' ' +
                    'AND Resource__c != :blankResourceId ';
        }
        Date startDateFilter;
        if (startDate != null) {
            startDateFilter = date.valueOf(startDate);
        } else {
            startDateFilter = getLastWeekFirstDate();
        }

        query += 'AND TM__r.Scheduled_Date__c >= :startDateFilter ';

        Date endDateFilter;
        if (endDate != null) {
            endDateFilter = date.valueOf(endDate);
        } else {
            endDateFilter = getLastWeekLastDate();
        }

        query += 'AND TM__r.Scheduled_Date__c <= :endDateFilter ';

        if (!Boolean.valueOf(includeWeekend)) {
            query += 'AND TM__r.Scheduled_Date_Weekend__c != true ';
        }

        query += ' ORDER BY Description__c';

        // Getting only Labor TMLines 
        List<TM_Line__c> TMLines = Database.query(query);
        system.debug('TMLines' + TMLines);
        // Populate HoursMap
        for (TM_Line__c line : TMLines) {
            if (TMHoursMap.containsKey(line.Resource__c)) {
                // Getting existing wrapper
                TMHoursWrapper wrapper = TMHoursMap.get(line.Resource__c);
                wrapper.ResourceId = line.Resource__c;
                if (wrapper.Total_Hours == null) {
                    wrapper.Total_Hours = 0;
                }
                if (wrapper.SC_Hours == null) {
                    wrapper.SC_Hours = 0;
                }
                if (wrapper.IC_Hours == null) {
                    wrapper.IC_Hours = 0;
                }
                // Populating total hours 
                if (wrapper.Total_Hours != null && line.Total_Job_Hours__c != null) {
                    wrapper.Total_Hours = companyMgmt.halfUpTo2D(wrapper.Total_Hours + line.Total_Job_Hours__c);
                }
                // Validate values to populate either SC Hours or IC Hours
                if (line.TM__r.Service_Center__c == line.Resource__r.Service_Center__c) {
                    if (wrapper.SC_Hours != null && line.Total_Job_Hours__c != null) {
                        wrapper.SC_Hours = companyMgmt.halfUpTo2D(wrapper.SC_Hours + line.Total_Job_Hours__c);
                    }
                } else {
                    if (wrapper.IC_Hours != null && line.Total_Job_Hours__c != null) {
                        wrapper.IC_Hours = companyMgmt.halfUpTo2D(wrapper.IC_Hours + line.Total_Job_Hours__c);
                    }
                }
                // Updating wrapper in the map
                TMHoursMap.put(line.Resource__c, wrapper);
            } else {
                // Creating a new wrapper
                TMHoursWrapper wrapper = new TMHoursWrapper();
                wrapper.ResourceId = line.Resource__c;
                // Set initial hours as zero
                wrapper.SC_Hours = 0;
                wrapper.IC_Hours = 0;
                wrapper.Total_Hours = 0;
                // Populate total hours
                if (line.Total_Job_Hours__c != null)
                    wrapper.Total_Hours = companyMgmt.halfUpTo2D(line.Total_Job_Hours__c);
                // Either populate SC Hours or IC Hours
                if (line.TM__r.Service_Center__c == line.Resource__r.Service_Center__c && line.Total_Job_Hours__c != null) {
                    wrapper.SC_Hours = companyMgmt.halfUpTo2D(line.Total_Job_Hours__c);
                } else if (line.Total_Job_Hours__c != null) {
                    wrapper.IC_Hours = companyMgmt.halfUpTo2D(line.Total_Job_Hours__c);
                }
                TMHoursMap.put(line.Resource__c, wrapper);
            }
        }

        //Loop through all resources with proper sortings
        string category = 'Labor';
        List<Resource__c> theResourceList = new List<Resource__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.Resource__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ' , Service_Center__r.Name, Resource_Type__r.Equipment_Group__r.Name, Resource_Type__r.Name ';
        strQuery += ' FROM Resource__c ';
        strQuery += ' WHERE (Start_Date__c = null OR Start_Date__c <=: startDateFilter)';
        strQuery += ' AND (End_Date__c = null OR End_Date__c >=: endDateFilter) AND Category__c =: category ';
        if (ServiceCenter != 'All') {
            strQuery += ' AND Service_Center__c =: ServiceCenter';
        }
        strQuery += ' ORDER BY Service_Center__r.Name, Name';

        system.debug('***strQuery' + strQuery);
        theResourceList = Database.query(strQuery);

        system.debug('***theResourceList' + theResourceList);
        if (theResourceList != null && theResourceList.size() > 0) {
            for (Resource__c line : theResourceList) {
                TMLineWrapper wrapper = new TMLineWrapper();
                // Not used yet
                if (!TMHoursMap.containsKey(line.Id)) {
                    wrapper.ResourceNo = line.Name;
                    wrapper.Description = line.Description__c;
                    wrapper.ServiceCenter = line.Service_Center__r.Name;
                    if (line.Resource_Type__r.Name != null) {
                        wrapper.ResourceType = line.Resource_Type__r.Name;
                    }
                    // Make sure all hours are set to zero instead of null
                    wrapper.Total_Hours = 0;
                    wrapper.SC_Hours = 0;
                    wrapper.IC_Hours = 0;
                    if (startDateFilter != null && endDateFilter != null) {
                        wrapper.utilization = calculateUtilization(wrapper.Total_Hours, startDateFilter, endDateFilter, Boolean.valueOf(includeWeekend)).setScale(2);
                    } else {
                        wrapper.utilization = 0;
                    }
                    TMLineMap.put(line.Id, wrapper);
                } else {
                    wrapper.ResourceNo = line.Name;
                    wrapper.Description = line.Description__c;
                    wrapper.ServiceCenter = line.Service_Center__r.Name;
                    if (line.Resource_Type__r.Name != null) {
                        wrapper.ResourceType = line.Resource_Type__r.Name;
                    }
                    wrapper.Total_Hours = TMHoursMap.get(line.id).Total_Hours;
                    wrapper.SC_Hours = TMHoursMap.get(line.id).SC_Hours;
                    wrapper.IC_Hours = TMHoursMap.get(line.id).IC_Hours;
                    if (startDateFilter != null && endDateFilter != null) {
                        wrapper.utilization = calculateUtilization(wrapper.Total_Hours, startDateFilter, endDateFilter, Boolean.valueOf(includeWeekend)).setScale(2);
                    } else {
                        wrapper.utilization = 0;
                    }
                    TMLineMap.put(line.Id, wrapper);
                }
            }
        }
        return TMLineMap.values();
    }
    /******************* Method to retrieve the service centers and populate the picklist *********************/
    @AuraEnabled
    public static List<ServiceCenterWrapper> getServiceCenters() {
        // Getting all service centers to show up on picklist
        List<Service_Center__c> serviceCenterList = [
                SELECT Id, Name, Description__c
                FROM Service_Center__c
                ORDER BY Description__c
        ];

        // Get current user's service center
        String userServiceCenter = getCurrentUserServiceCenter();

        // Setting the first center found as the default 
        if (defaultServiceCenter == null) {
            defaultServiceCenter = serviceCenterList[0].Id;
        }

        // Populating the service center wrapper list
        List<ServiceCenterWrapper> listServiceCenterWrapper = new List<ServiceCenterWrapper>();

        // Add All
        // Create new wrapper instance
        ServiceCenterWrapper scWrapper = new ServiceCenterWrapper();
        scWrapper.Id = 'ALL';
        scWrapper.Name = 'ALL';
        scWrapper.Description = 'ALL Service Centers';
        scWrapper.isDefault = false;
        // Add wrapper to the list
        listServiceCenterWrapper.add(scWrapper);

        for (Service_Center__c sc : serviceCenterList) {
            system.debug('scott1/' + sc.Name);

            // Create new wrapper instance
            scWrapper = new ServiceCenterWrapper();
            scWrapper.Id = sc.Id;
            scWrapper.Name = sc.Name;
            if (sc.Description__c != null) scWrapper.Description = sc.Description__c; else scWrapper.Description = sc.Name;

            // If it is the user's service center, set it as default
            if (sc.Name == userServiceCenter) {
                scWrapper.isDefault = true;
                defaultServiceCenter = sc.Id;
            } else {
                scWrapper.isDefault = false;
            }

            // Add wrapper to the list
            listServiceCenterWrapper.add(scWrapper);
        }

        // Return service centers
        return listServiceCenterWrapper;
    }

    /******************* Method to return service center from the current user *********************/
    public static String getCurrentUserServiceCenter() {
        // Getting the current user's service center
        String serviceCenter = [
                SELECT Id, Service_Center__c
                FROM User
                WHERE Id = :UserInfo.getUserId()
        ][0].Service_Center__c;

        // Return service center
        return serviceCenter;
    }

    /******************* Method to calculate utilization *********************/
    public static Decimal calculateUtilization(Decimal TotalHours, Date startDate, Date endDate, Boolean includeWeekend) {
        Integer days = verifyNumberOfDays(startDate, endDate, includeWeekend);
        Decimal utilization = TotalHours / (days * 8);
        return utilization;
    }

    /******************* Method to calculate number of days between two dates *********************/
    public static Integer verifyNumberOfDays(Date startDate, Date endDate, Boolean includeWeekend) {
        Integer days = 0;
        if (includeWeekend) {
            days = startDate.daysBetween(endDate + 1);
        } else {
            days = startDate.daysBetween(endDate + 1);

            // Counting number of weekends to exclude from the total 
            Integer countWeekends = 0;
            for (Integer i = 0; i < days; i++) {
                Datetime dt = Datetime.newInstance(startDate.year(), startDate.month(), startDate.day());
                String dayOfWeek = (dt.addDays(i)).format('E');
                if (dayOfWeek == 'Sat' || dayOfWeek == 'Sun') {
                    countWeekends = countWeekends + 1;
                }
            }

            // Subtracting the number of weekends from the total of days
            if (countWeekends != 0) {
                days = days - countWeekends;
            }
        }
        System.debug('days ' + days);
        return days;
    }

    /******************* GET THE DATE FOR LAST MONDAY *********************/
    @AuraEnabled
    public static Date getLastWeekFirstDate() {
        Date firstDate = system.today().toStartOfWeek().addDays(-6);
        return firstDate;
    }

    /******************* GET THE DATE FOR LAST SUNDAY *********************/
    @AuraEnabled
    public static Date getLastWeekLastDate() {
        Date lastDate = system.today().toStartOfWeek();
        return lastDate;
    }

    /******************* TM LINE Wrapper class *********************/
    public class TMHoursWrapper {
        @AuraEnabled
        public String ResourceId { get; set; }
        @AuraEnabled
        public Decimal Total_Hours { get; set; }
        @AuraEnabled
        public Decimal SC_Hours { get; set; }
        @AuraEnabled
        public Decimal IC_Hours { get; set; }
    }

    public class TMLineWrapper {
        @AuraEnabled
        public String ResourceNo { get; set; }
        @AuraEnabled
        public String ServiceCenter { get; set; }
        @AuraEnabled
        public String ResourceType { get; set; }
        @AuraEnabled
        public String Description { get; set; }
        @AuraEnabled
        public Decimal Total_Hours { get; set; }
        @AuraEnabled
        public Decimal SC_Hours { get; set; }
        @AuraEnabled
        public Decimal IC_Hours { get; set; }
        @AuraEnabled
        public Decimal Utilization { get; set; }
    }

    /******************* Service Center Wrapper class *********************/
    public class ServiceCenterWrapper {
        @AuraEnabled
        public String Id { get; set; }
        @AuraEnabled
        public String Name { get; set; }
        @AuraEnabled
        public String Description { get; set; }
        @AuraEnabled
        public Boolean isDefault { get; set; }
    }
}