objects/Pay_Rule__c/Pay_Rule__c.object-meta.xml
<CustomObject>
    <label>Pay Rule</label>
    <nameField>
        <label>Pay Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pay Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Rule__c/fields/Pay_Holiday__c.field-meta.xml
<CustomField>
    <fullName>Pay_Holiday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pay Holiday?</label>
    <type>Checkbox</type>
</CustomField>

objects/Pay_Rule__c/fields/Pay_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Pay_Travel_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pay Travel Time?</label>
    <type>Checkbox</type>
</CustomField>

objects/Pay_Rule__c/fields/Saturday_Pay_Code__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Pay_Code__c</fullName>
    <label>Saturday Pay Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Rate_Code</valueSetName>
    </valueSet>
</CustomField>

objects/Pay_Rule__c/fields/Sunday_Pay_Code__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Pay_Code__c</fullName>
    <label>Sunday Pay Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Rate_Code</valueSetName>
    </valueSet>
</CustomField>

objects/Pay_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Union</fullName>
            </value>
            <value>
                <fullName>Prevailing Wage</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Pay_Rule_Line__c/Pay_Rule_Line__c.object-meta.xml
<CustomObject>
    <label>Pay Rule Line</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Line No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Rule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pay_Rule_Line__c/fields/Double_Time_Rate_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Double_Time_Rate_Multiple__c</fullName>
    <label>Double Time Rate Multiple</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/DT_Fringe_Amount__c.field-meta.xml
<CustomField>
    <fullName>DT_Fringe_Amount__c</fullName>
    <label>DT Fringe Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Fringe__c.field-meta.xml
<CustomField>
    <fullName>Fringe__c</fullName>
    <label>Fringe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Holiday_with_Double_Time_Pay__c.field-meta.xml
<CustomField>
    <fullName>Holiday_with_Double_Time_Pay__c</fullName>
    <label>Holiday with Double Time Pay</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Holiday_List</valueSetName>
    </valueSet>
</CustomField>

objects/Pay_Rule_Line__c/fields/Holidays_with_Overtime_Pay__c.field-meta.xml
<CustomField>
    <fullName>Holidays_with_Overtime_Pay__c</fullName>
    <label>Holiday with Overtime Pay</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Holiday_List</valueSetName>
    </valueSet>
</CustomField>

objects/Pay_Rule_Line__c/fields/OT_Fringe_Amount__c.field-meta.xml
<CustomField>
    <fullName>OT_Fringe_Amount__c</fullName>
    <label>OT Fringe Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Overtime_Rate_Multiple__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Rate_Multiple__c</fullName>
    <label>Overtime Rate Multiple</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Pay_Rule__c.field-meta.xml
<CustomField>
    <fullName>Pay_Rule__c</fullName>
    <label>Pay Rule</label>
    <referenceTo>Pay_Rule__c</referenceTo>
    <relationshipLabel>Pay Rule Lines</relationshipLabel>
    <relationshipName>Pay_Rule_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <value>Labor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Pay Rule Lines</relationshipLabel>
    <relationshipName>Pay_Rule_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Pay_Rule_Line__c/fields/Saturday_Pay_Code__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Pay_Code__c</fullName>
    <label>Saturday Pay Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Rate_Code</valueSetName>
    </valueSet>
</CustomField>

objects/Pay_Rule_Line__c/fields/Sunday_Pay_Code__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Pay_Code__c</fullName>
    <label>Sunday Pay Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Rate_Code</valueSetName>
    </valueSet>
</CustomField>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Holiday_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Christmas Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>CDPWO</fullName>
        <label>Christmas Day PW  Observed</label>
    </customValue>
    <customValue>
        <fullName>Christmas Eve Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Eve Company</fullName>
    </customValue>
    <customValue>
        <fullName>Columbus Day</fullName>
    </customValue>
    <customValue>
        <fullName>Day After Thanksgiving</fullName>
    </customValue>
    <customValue>
        <fullName>Easter</fullName>
    </customValue>
    <customValue>
        <fullName>Election Day</fullName>
    </customValue>
    <customValue>
        <fullName>Good Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Inauguration Day</fullName>
    </customValue>
    <customValue>
        <fullName>Independence Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Independence Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>IDPWO</fullName>
        <label>Independence Day PW Observed</label>
    </customValue>
    <customValue>
        <fullName>Juneteenth Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Juneteenth PW Observed</fullName>
    </customValue>
    <customValue>
        <fullName>Labor Day</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln&apos;s Birthday Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln&apos;s Birthday PW Observed</fullName>
    </customValue>
    <customValue>
        <fullName>Martin Luther King Day</fullName>
    </customValue>
    <customValue>
        <fullName>Memorial Day</fullName>
    </customValue>
    <customValue>
        <fullName>New Year&apos;s Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>New Year&apos;s Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>NYDPWO</fullName>
        <label>New Year&apos;s Day PW Observed</label>
    </customValue>
    <customValue>
        <fullName>Patriots Day</fullName>
    </customValue>
    <customValue>
        <fullName>Presidential Election Day</fullName>
    </customValue>
    <customValue>
        <fullName>Presidents Day</fullName>
    </customValue>
    <customValue>
        <fullName>Thanksgiving</fullName>
    </customValue>
    <customValue>
        <fullName>Veteran&apos;s Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>VDPWO</fullName>
        <label>Veteran&apos;s Day PW Observed</label>
    </customValue>
    <masterLabel>Holiday List</masterLabel>
</GlobalValueSet>

classes/PayRulesSelector.cls
public class PayRulesSelector extends fflib_SObjectSelector implements IPayRulesSelector{

    public static IPayRulesSelector newInstance(){
        return (IPayRulesSelector) Application.Selector.newInstance(Pay_Rule__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return Pay_Rule__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                Pay_Rule__c.Id,
                Pay_Rule__c.Name,
                //Pay_Rule__c.Overhead_Pct__c,
                Pay_Rule__c.Pay_Holiday__c,
                Pay_Rule__c.Pay_Travel_Time__c,
                Pay_Rule__c.Type__c,
                Pay_Rule__c.Mon_Sun_Work_Week__c
        };
    }

    /*
     *  Ticket#21502 - add blocked filter to Pay Rule Lines.
     */
    public List<Pay_Rule__c> selectPayRulesByIdWithLines(Set<Id> idSet) {
        fflib_QueryFactory qf = newQueryFactory();
        qf.setCondition('Id IN :idSet')
                .subselectQuery('Pay_Rule_Lines__r')
                .selectField('Resource_Type__c')
                .selectField('Unit_Cost__c')
                .selectField('Rate__c')
                .selectField('Overtime_Rate_Multiple__c')
                .selectField('Double_Time_Rate_Multiple__c')
                .selectField('Saturday_Pay_Code__c')
                .selectField('Sunday_Pay_Code__c')
                .selectField('Fringe__c')
                .selectField('OT_Fringe_Amount__c')
                .selectField('DT_Fringe_Amount__c')
                .selectField('Holiday_with_Double_Time_Pay__c')
                .selectField('Holidays_with_Overtime_Pay__c')
                .setCondition('Blocked__c != TRUE');
        String soql = qf.toSOQL();
        return (List<Pay_Rule__c>) Database.query(soql);
    }
}