objects/Pay_Rule__c/Pay_Rule__c.object-meta.xml
<CustomObject>
    <label>Pay Rule</label>
    <nameField>
        <label>Pay Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pay Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Union</fullName>
            </value>
            <value>
                <fullName>Prevailing Wage</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Gold_ER_Rate1__c.field-meta.xml
<CustomField>
    <fullName>Gold_ER_Rate1__c</fullName>
    <label>Gold ER Rate1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Gold_ER_Rate4__c.field-meta.xml
<CustomField>
    <fullName>Gold_ER_Rate4__c</fullName>
    <label>Gold ER Rate4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Gold_Rate3__c.field-meta.xml
<CustomField>
    <fullName>Gold_Rate3__c</fullName>
    <label>Gold Rate3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/LTD__c.field-meta.xml
<CustomField>
    <fullName>LTD__c</fullName>
    <inlineHelpText>ACV paid long term disability coverage</inlineHelpText>
    <label>LTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <inlineHelpText>ACV portion of premium paid for employee health insurance coverage (Medical, Dental and/or Vision)</inlineHelpText>
    <label>Medical</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/PTO__c.field-meta.xml
<CustomField>
    <fullName>PTO__c</fullName>
    <inlineHelpText>ACV funded employee Paid Time Off.</inlineHelpText>
    <label>PTO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Silver_ER_Rate3__c.field-meta.xml
<CustomField>
    <fullName>Silver_ER_Rate3__c</fullName>
    <label>Silver ER Rate3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Silver_Rate1__c.field-meta.xml
<CustomField>
    <fullName>Silver_Rate1__c</fullName>
    <label>Silver Rate1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/STD__c.field-meta.xml
<CustomField>
    <fullName>STD__c</fullName>
    <inlineHelpText>ACV paid short term disability insurance</inlineHelpText>
    <label>STD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure1__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure1</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure1)</relationshipLabel>
    <relationshipName>Resources1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure2__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure2</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure2)</relationshipLabel>
    <relationshipName>Resources2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure3__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure3</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure3)</relationshipLabel>
    <relationshipName>Resources3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure4__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure4</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure4)</relationshipLabel>
    <relationshipName>Resources4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/X401K_Match_Pct__c.field-meta.xml
<CustomField>
    <fullName>X401K_Match_Pct__c</fullName>
    <inlineHelpText>ACV contribution to employee’s retirement savings plan based on the amount of employee’s contribution.</inlineHelpText>
    <label>401K Match %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Resource_Type__c/fields/Gold_ER_Rate2__c.field-meta.xml
<CustomField>
    <fullName>Gold_ER_Rate2__c</fullName>
    <label>Gold ER Rate2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Gold_ER_Rate3__c.field-meta.xml
<CustomField>
    <fullName>Gold_ER_Rate3__c</fullName>
    <label>Gold ER Rate3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Gold_ER_Rate__c.field-meta.xml
<CustomField>
    <fullName>Gold_ER_Rate__c</fullName>
    <label>Gold ER Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Resource_Type__c/fields/Gold_Rate1__c.field-meta.xml
<CustomField>
    <fullName>Gold_Rate1__c</fullName>
    <label>Gold Rate1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Gold_Rate2__c.field-meta.xml
<CustomField>
    <fullName>Gold_Rate2__c</fullName>
    <label>Gold Rate2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Gold_Rate__c.field-meta.xml
<CustomField>
    <fullName>Gold_Rate__c</fullName>
    <label>Gold Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_ER_Rate1__c.field-meta.xml
<CustomField>
    <fullName>Silver_ER_Rate1__c</fullName>
    <label>Silver ER Rate1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_ER_Rate2__c.field-meta.xml
<CustomField>
    <fullName>Silver_ER_Rate2__c</fullName>
    <label>Silver ER Rate2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_ER_Rate4__c.field-meta.xml
<CustomField>
    <fullName>Silver_ER_Rate4__c</fullName>
    <label>Silver ER Rate4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_ER_Rate__c.field-meta.xml
<CustomField>
    <fullName>Silver_ER_Rate__c</fullName>
    <label>Silver ER Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_Rate2__c.field-meta.xml
<CustomField>
    <fullName>Silver_Rate2__c</fullName>
    <label>Silver Rate2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_Rate3__c.field-meta.xml
<CustomField>
    <fullName>Silver_Rate3__c</fullName>
    <label>Silver Rate3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_Rate4__c.field-meta.xml
<CustomField>
    <fullName>Silver_Rate4__c</fullName>
    <label>Silver Rate4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource_Type__c/fields/Silver_Rate__c.field-meta.xml
<CustomField>
    <fullName>Silver_Rate__c</fullName>
    <label>Silver Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure1__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure1</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure1)</relationshipLabel>
    <relationshipName>Resource_Types1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure2__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure2</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure2)</relationshipLabel>
    <relationshipName>Resource_Types2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure3__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure3</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure3)</relationshipLabel>
    <relationshipName>Resource_Types3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure4__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure4</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure4)</relationshipLabel>
    <relationshipName>Resource_Types4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/ResourcesSelector.cls
public class ResourcesSelector extends fflib_SObjectSelector implements IResourcesSelector{

    public static IResourcesSelector newInstance() {
        return (IResourcesSelector) Application.Selector.newInstance(Resource__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return Resource__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                Resource__c.Id,
                Resource__c.Name,
                Resource__c.Description__c,
                Resource__c.Service_Center__c,
                Resource__c.Resource_Type__c,
                Resource__c.State__c,
                Resource__c.Medical__c,
                Resource__c.STD__c,
                Resource__c.LTD__c,
                Resource__c.X401K_Match_Pct__c,
                Resource__c.PTO__c,
                Resource__c.Start_Date__c,
                Resource__c.Category__c,
                Resource__c.Unit_of_Measure__c,
                Resource__c.Unit_of_Measure2__c,
                Resource__c.Unit_of_Measure3__c,
                Resource__c.Unit_of_Measure4__c,
                Resource__c.Unit_of_Measure1__c,
                Resource__c.Silver_ER_Rate__c,
                Resource__c.Silver_ER_Rate1__c,
                Resource__c.Silver_ER_Rate2__c,
                Resource__c.Silver_ER_Rate3__c,
                Resource__c.Silver_ER_Rate4__c,
                Resource__c.Silver_Rate__c,
                Resource__c.Silver_Rate1__c,
                Resource__c.Silver_Rate2__c,
                Resource__c.Silver_Rate3__c,
                Resource__c.Silver_Rate4__c,
                Resource__c.Gold_ER_Rate__c,
                Resource__c.Gold_ER_Rate1__c,
                Resource__c.Gold_ER_Rate2__c,
                Resource__c.Gold_ER_Rate3__c,
                Resource__c.Gold_ER_Rate4__c,
                Resource__c.Gold_Rate__c,
                Resource__c.Gold_Rate1__c,
                Resource__c.Gold_Rate2__c,
                Resource__c.Gold_Rate3__c,
                Resource__c.Gold_Rate4__c ,
                Resource__c.Platinum_ER_Rate__c,
                Resource__c.Platinum_ER_Rate1__c,
                Resource__c.Platinum_ER_Rate2__c,
                Resource__c.Platinum_ER_Rate3__c,
                Resource__c.Platinum_ER_Rate4__c,
                Resource__c.Platinum_Rate__c,
                Resource__c.Platinum_Rate1__c,
                Resource__c.Platinum_Rate2__c,
                Resource__c.Platinum_Rate3__c,
                Resource__c.Platinum_Rate4__c,
                Resource__c.Unit_Cost__c,
                Resource__c.Unit_Cost1__c,
                Resource__c.Unit_Cost2__c,
                Resource__c.Unit_Cost3__c,
                Resource__c.Unit_Cost4__c,
                Resource__c.EEC_Surcharge_Exempted__c,
                Resource__c.Employee_Type__c,
                Resource__c.End_Date__c,
                Resource__c.Pay_Rule__c,
                Resource__c.FLSA__c,
                Resource__c.First_Name__c,
                Resource__c.Last_Name__c,
                Resource__c.Used_for_Contract__c,
                Resource__c.Has_Container__c,
                Resource__c.Has_Weight_Volume__c,
                Resource__c.Allow_Zero_Unit_Cost_at_TM_Confirmation__c,
                Resource__c.Allow_Manual_Unit_Cost_Adjustment__c,
                Resource__c.Bypass_Time_Overlap_Checking__c //Ticket#22307
        };
    }

    public List<Resource__c> selectById(Set<Id> idSet){
        return (List<Resource__c>) Database.query(newQueryFactory()
                .selectField('Unit_of_Measure__r.Name')
                .selectField('Unit_of_Measure__r.Hours_UOM__c')
                .selectField('Service_Center__r.Name')
                .selectField('Service_Center__r.Temporary__c')
                .setCondition('Id IN :idSet').toSOQL());
    }

    public List<Resource__c> selectLaborResourcesByIds(Set<Id> ids){
        return (List<Resource__c>) Database.query(newQueryFactory().
                selectField('Service_Center__r.Name').
                selectField('Service_Center__r.Temporary__c').
                selectField('Resource_Type__r.Name').
                selectField('Pay_Rule__r.Type__c').
                selectField('Pay_Rule__r.Mon_Sun_Work_Week__c').
                setCondition('Id IN :ids AND Category__c = \'Labor\' AND Employee_Type__c = \'Employee\' AND Status__c = \'Active\' AND Non_Payroll_Labor_Resource__c = FALSE').
                toSOQL());
    }

    public List<Resource__c> selectLaborResourcesByServiceCenter(Id scId){
        return (List<Resource__c>) Database.query(newQueryFactory().
                selectField('Service_Center__r.Name').
                selectField('Service_Center__r.Temporary__c').
                selectField('Resource_Type__r.Name').
                selectField('Pay_Rule__r.Type__c').
                selectField('Pay_Rule__r.Mon_Sun_Work_Week__c').
                setCondition('Service_Center__c  = :scId AND Category__c = \'Labor\' AND Employee_Type__c = \'Employee\' AND Status__c = \'Active\' AND Non_Payroll_Labor_Resource__c = FALSE').
                toSOQL());
    }

    public List<Resource__c> selectPayrollEmployeeByIdsByActivityDate(Set<Id> resIds, Date activityDate){
        return (List<Resource__c>) Database.query(newQueryFactory().
                selectField('Service_Center__r.Name').
                selectField('Service_Center__r.Temporary__c').
                selectField('Resource_Type__r.Name').
                selectField('Pay_Rule__r.Type__c').
                selectField('Pay_Rule__r.Mon_Sun_Work_Week__c').
                setCondition('Id IN :resIds AND Category__c = \'Labor\' ' +
                        'AND Employee_Type__c != NULL ' +
                        'AND Non_Payroll_Labor_Resource__c = FALSE ' +
                        'AND (End_Date__c >= :activityDate OR End_Date__c = null)').
                toSOQL());
        //'AND Employee_Type__c != \'Temp\' AND Employee_Type__c != NULL ' +
    }

    public List<Resource__c> selectPayrollEmployeeBySCIdByActivityDate(Id scId, Date activityDate){
        return (List<Resource__c>) Database.query(newQueryFactory().
                selectField('Service_Center__r.Name').
                selectField('Service_Center__r.Temporary__c').
                selectField('Resource_Type__r.Name').
                selectField('Pay_Rule__r.Type__c').
                selectField('Pay_Rule__r.Mon_Sun_Work_Week__c').
                setCondition('Service_Center__c = :scId AND Category__c = \'Labor\' ' +
                        'AND Employee_Type__c != NULL ' +
                        'AND Non_Payroll_Labor_Resource__c = FALSE ' +
                        'AND (End_Date__c >= :activityDate OR End_Date__c = null)').
                toSOQL());
        //'AND Employee_Type__c != \'Temp\' AND Employee_Type__c != NULL ' +
    }

    public Map<Id, Resource__c> getResourcesByIdsMapByResIds(Set<Id> resIds){
        Map<Id, Resource__c> resourcesByIds = new Map<Id, Resource__c>();
        resourcesByIds.putAll(selectById(resIds));
        return resourcesByIds;
    }
}