objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Vendor__c/Subsidiary_Vendor__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Vendor</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subsidiary_Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_and_Vendor_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Subsidiary_Vendor__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Center__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Subsidiary Vendors</relationshipLabel>
    <relationshipName>Subsidiary_Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Vendor__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Account_and_Vendor_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SubsidiaryVendorsSelector.cls
public with sharing class SubsidiaryVendorsSelector extends fflib_SObjectSelector{

    public static SubsidiaryVendorsSelector newInstance(){
        return (SubsidiaryVendorsSelector) Application.Selector.newInstance(Subsidiary_Vendor__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType(){
        return Subsidiary_Vendor__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                Subsidiary_Vendor__c.Id,
                Subsidiary_Vendor__c.Name,
                Subsidiary_Vendor__c.Subsidiary_Company__c,
                Subsidiary_Vendor__c.Account__c,
                Subsidiary_Vendor__c.Service_Center__c
        };
    }

    public List<Subsidiary_Vendor__c> selectBySubsidiaryByName(Id subsidiaryId, Set<String> navVenNos){
        return System.Database.query(
                newQueryFactory().setCondition('Subsidiary_Company__c = :subsidiaryId AND Name IN :navVenNos').toSOQL()
        );
    }
}