objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Line_Cost__c.field-meta.xml
<CustomField>
    <fullName>Line_Cost__c</fullName>
    <label>Line Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/InterCompanyCostTrackingControllerTest.cls
@IsTest
private class InterCompanyCostTrackingControllerTest {

    @IsTest
    private static void testCheckDates(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ITMLinesSelector selectorTMLMock = new Mocks.TMLinesSelector(mocks);
        String dateStr = Date.today().month() + '/' + Date.today().day() + '/' + Date.today().year();



        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = 'Test'
        );
        TM__c theTM = new TM__c(
                Id = fflib_IDGenerator.generate(TM__c.SObjectType),
                Service_Center__c = theSC.Id
        );
        TM_Line__c tml1 = new TM_Line__c(
                Id = fflib_IDGenerator.generate(TM_Line__c.SObjectType),
                TM__c = theTM.Id,
                Service_Center__c = theSC.Id,
                Category__c = 'Labor',
                Line_Cost__c = 30
        );
        TM_Line__c tml2 = new TM_Line__c(
                Id = fflib_IDGenerator.generate(TM_Line__c.SObjectType),
                TM__c = theTM.Id,
                Service_Center__c = theSC.Id,
                Category__c = 'Labor',
                Line_Cost__c = 20
        );
        List<TM_Line__c> theTMLList = new List<TM_Line__c>{tml1, tml2};
        mocks.when(selectorTMLMock.sObjectType()).thenReturn(TM_Line__c.SObjectType);
        mocks.when(selectorTMLMock.selectInterCompanyLineByScheduledDateRange(Date.parse(dateStr), Date.parse(dateStr))).thenReturn(theTMLList);
        mocks.stopStubbing();
        Application.Selector.setMock(selectorTMLMock);

        System.currentPageReference().getParameters().put('startingDate', dateStr);
        System.currentPageReference().getParameters().put('endingDate', dateStr);
        ApexPages.StandardController standardController = new ApexPages.StandardController(theTM);
        InterCompanyCostTrackingController controller = new InterCompanyCostTrackingController(standardController);
        controller.checkDates();
        controller.startingDateValue = Date.today().month() + '/' + Date.today().addDays(1).day() + '/' + Date.today().year();
        controller.checkDates();
        controller.saveAsExcel();
        controller.showInterCompanyCost();


        ApexPages.StandardSetController standardSetController = new ApexPages.StandardSetController(new List<TM__c>{theTM});
        InterCompanyCostTrackingController setController = new InterCompanyCostTrackingController(standardSetController);
    }
}