objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Service_Center__c/User_Service_Center__c.object-meta.xml
<CustomObject>
    <label>User Service Center</label>
    <nameField>
        <label>Service Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Service_Center__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>User Service Centers</relationshipLabel>
    <relationshipName>User_Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/User_Service_Center__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Service_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/UserserviceCenterControllerTest.cls
@isTest
private class UserserviceCenterControllerTest {
    private static testMethod void test() {
        Subsidiary_Company__c company = new Subsidiary_Company__c(Name = '1-REPUBLIC SERVICES');
        insert company;
        
        Service_Center__c serviceCenter = new Service_Center__c(Subsidiary_Company__c= company.Id, Name = '01', Code__c = '01');
        insert serviceCenter;
        
        User_Service_Center__c usc = new User_Service_Center__c(Name = '01', User__c = userInfo.getUserId(), Service_Center__c = serviceCenter.Id);
        insert usc;
        
        UserServiceCenterController.getUser(userInfo.getUserId());
        String JSONUserServiceCenters  = UserServiceCenterController.getUserServiceCenters(userInfo.getUserId());
        UserServiceCenterController.saveUserServiceCenters(userInfo.getUserId(), JSONUserServiceCenters);
        
        UserServiceCenterController.deleteUserServiceCenter(usc.Id);
    
    }

}