objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User/fields/Manager_of_SC__c.field-meta.xml
<CustomField>
    <fullName>Manager_of_SC__c</fullName>
    <label>Manager of SC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/User_Service_Center__c/User_Service_Center__c.object-meta.xml
<CustomObject>
    <label>User Service Center</label>
    <nameField>
        <label>Service Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Service_Center__c/fields/Manager_of_SC__c.field-meta.xml
<CustomField>
    <fullName>Manager_of_SC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager of SC</label>
    <type>Checkbox</type>
</CustomField>

objects/User_Service_Center__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>User Service Centers</relationshipLabel>
    <relationshipName>User_Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/User_Service_Center__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Service_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/UserServiceCenterController.cls
/**
 * Created by Kevin on 2/27/2020.
 */

public with sharing class UserServiceCenterController {
    public static Boolean SkipTrigger { set; get; }

    @AuraEnabled
    public static User getUser(Id userId) {
        try {
            List<User> users = [SELECT Id, Name FROM User WHERE Id = :userId];
            if (users.size() > 0) {
                return users[0];
            }
            else {
                throw new DataException('Invalid user id: ' + userId + '.');
            }
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String getUserServiceCenters(Id userId) {
        try {
            List<User_Service_Center__c> userServiceCenters = [SELECT Id, Name, User__c, User__r.Name, Service_Center__c, Service_Center__r.Name, Default__c, Manager_of_SC__c FROM User_Service_Center__c WHERE User__c = :userId ORDER BY Service_Center__r.Name];
            return JSON.serialize(userServiceCenters);
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String addAllServiceCenters(String JSONUser, String JSONUserServiceCenters) {
        try {
            User user = (User)JSON.deserialize(JSONUser, User.class);
            List<User_Service_Center__c> userServiceCenters = (List<User_Service_Center__c>)JSON.deserialize(JSONUserServiceCenters, List<User_Service_Center__c>.class);

            Map<String, User_Service_Center__c> mapUserServiceCentersByName = new Map<String, User_Service_Center__c>();
            for (User_Service_Center__c userServiceCenter : userServiceCenters) {
                mapUserServiceCentersByName.put(userServiceCenter.Service_Center__r.Name, userServiceCenter);
            }

            List<Service_Center__c> serviceCenters = [SELECT Id, Name FROM Service_Center__c ORDER BY Name];
            for (Service_Center__c serviceCenter : serviceCenters) {
                if (!mapUserServiceCentersByName.containsKey(serviceCenter.Name)) {
                    userServiceCenters.add(new User_Service_Center__c(Name = serviceCenter.Name, Service_Center__c = serviceCenter.Id, Service_Center__r = serviceCenter, User__c = user.Id, User__r = user, Manager_of_SC__c = false));
                }
            }
            return JSON.serialize(userServiceCenters);
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteUserServiceCenter(Id userServiceCenterId) {
        try {
            delete [SELECT Id FROM User_Service_Center__c WHERE Id = :userServiceCenterId];
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String saveUserServiceCenters(Id userId, String JSONUserServiceCenters) {
        Savepoint sp = Database.setSavepoint();
        try {
            List<User_Service_Center__c> userServiceCenters = (List<User_Service_Center__c>)JSON.deserialize(JSONUserServiceCenters, List<User_Service_Center__c>.class);

            Set<Id> uscIds = new Set<Id>();
            for (User_Service_Center__c userServiceCenter : [SELECT Id FROM User_Service_Center__c WHERE User__c = :userId]) {
                uscIds.add(userServiceCenter.Id);
            }

            for (User_Service_Center__c userServiceCenter : userServiceCenters) {
                if (userServiceCenter.Id != null) {
                    if (uscIds.contains(userServiceCenter.Id)) {
                        uscIds.remove(userServiceCenter.Id);
                    }
                }
            }

            if (uscIds.size() > 0) {
                delete [SELECT Id FROM User_Service_Center__c WHERE User__c = :userId AND Id IN :uscIds];
            }

            upsert userServiceCenters;

            return getUserServiceCenters(userId);
        }
        catch(exception ex) {
            Database.rollback(sp);
            throw new AuraHandledException(ex.getMessage());
        }
    }
}