objects/Pricing__c/Pricing__c.object-meta.xml
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pricing_Rate_Sheet_Association__c/Pricing_Rate_Sheet_Association__c.object-meta.xml
<CustomObject>
    <label>Price List Rate Sheet Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price List Rate Sheet Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Rate_Sheet_Association__c/fields/Pricing__c.field-meta.xml
<CustomField>
    <fullName>Pricing__c</fullName>
    <label>Price List</label>
    <referenceTo>Pricing__c</referenceTo>
    <relationshipLabel>Price List Rate Sheet Association</relationshipLabel>
    <relationshipName>Pricing_Rate_Sheet_Association</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Pricing_Rate_Sheet_Association__c/fields/Rate_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Rate_Sheet__c</fullName>
    <label>Rate Sheet</label>
    <referenceTo>Rate_Sheet__c</referenceTo>
    <relationshipName>Pricing_Rate_Sheet_Association</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Rate_Sheet__c/Rate_Sheet__c.object-meta.xml
<CustomObject>
    <label>Rate Sheet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rate_Sheet_Line__c/Rate_Sheet_Line__c.object-meta.xml
<CustomObject>
    <label>Rate Sheet Line</label>
    <nameField>
        <displayFormat>RSL-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Sheet Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate_Sheet_Line__c/fields/Rate_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Rate_Sheet__c</fullName>
    <label>Rate Sheet</label>
    <referenceTo>Rate_Sheet__c</referenceTo>
    <relationshipLabel>Rate Sheet Lines</relationshipLabel>
    <relationshipName>Rate_Sheet_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

classes/PriceListSelector.cls
public with sharing class PriceListSelector extends fflib_SObjectSelector {

    public static PriceListSelector newInstance(){
        return (PriceListSelector) Application.Selector.newInstance(Pricing_Rate_Sheet_Association__c.SObjectType);
    }

    public SObjectType getSObjectType(){
        return Pricing_Rate_Sheet_Association__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                Pricing_Rate_Sheet_Association__c.Id,
                Pricing_Rate_Sheet_Association__c.Name,
                Pricing_Rate_Sheet_Association__c.CreatedDate,
                Pricing_Rate_Sheet_Association__c.Rate_Sheet__c,
                Pricing_Rate_Sheet_Association__c.Pricing__c,
                Pricing_Rate_Sheet_Association__c.Effective_Date__c
        };
    }

    public List<Rate_Sheet_Line__c> selectActiveRateSheetLinesByPriceListAndWorkDate(Id priceListId, Date workDate){
        List<Rate_Sheet_Line__c> activeRateSheetLines = new List<Rate_Sheet_Line__c>();
        List<Pricing_Rate_Sheet_Association__c> pricingRateSheetAssociations =
                (List<Pricing_Rate_Sheet_Association__c>) Database.query(newQueryFactory()
                        .setCondition('Pricing__c = :priceListId AND Effective_Date__c <= :workDate')
                        .setOrdering('Effective_Date__c', fflib_QueryFactory.SortOrder.DESCENDING)
                        .toSOQL());

        if(pricingRateSheetAssociations.size() > 0){
            if(String.isNotBlank(pricingRateSheetAssociations[0].Rate_Sheet__c)){
                activeRateSheetLines = RatesheetLinesSelector.newInstance().selectByRateSheetIds(new Set<Id>{pricingRateSheetAssociations[0].Rate_Sheet__c});
            }
        }
        return activeRateSheetLines;
    }

    public Map<Id, Id> getActiveRateSheetIdByPricesListIdsAndWorkDate(Set<Id> priceListIds, Date workDate){
        System.debug('Info: priceListIds ' + priceListIds);
        System.debug('Info: workDate ' + workDate);
        Map<Id, Id> rateSheetIdsByPriceListIds = new Map<Id, Id>();
        List<Pricing_Rate_Sheet_Association__c> pricingRateSheetAssociations =
                (List<Pricing_Rate_Sheet_Association__c>) Database.query(newQueryFactory()
                        .setCondition('Pricing__c IN :priceListIds AND Effective_Date__c <= :workDate')
                        .setOrdering('Effective_Date__c', fflib_QueryFactory.SortOrder.DESCENDING)
                        .toSOQL());

        for(Pricing_Rate_Sheet_Association__c pricingRateSheetAssociation : pricingRateSheetAssociations){
            System.debug('Info: pricingRateSheetAssociation ' + pricingRateSheetAssociation);
            if(!rateSheetIdsByPriceListIds.containsKey(pricingRateSheetAssociation.Pricing__c)){
                rateSheetIdsByPriceListIds.put(pricingRateSheetAssociation.Pricing__c, pricingRateSheetAssociation.Rate_Sheet__c);
            }
        }

        System.debug('Info: rateSheetIdsByPriceListIds ' + rateSheetIdsByPriceListIds);

        return rateSheetIdsByPriceListIds;
    }

    //job task <<
    public List<Pricing_Rate_Sheet_Association__c> getPricingRateSheetAssociationsByPriceListId(Set<Id> priceListIds, Date workDate){
        return (List<Pricing_Rate_Sheet_Association__c>) Database.query(newQueryFactory()
                        .setCondition('Pricing__c IN :priceListIds AND Effective_Date__c <= :workDate')
                        .setOrdering('Effective_Date__c', fflib_QueryFactory.SortOrder.DESCENDING)
                        .toSOQL());
    }
    //job task >>
}