objects/Billing_Worksheet_Line__c/Billing_Worksheet_Line__c.object-meta.xml
<CustomObject>
    <label>Billing Worksheet Line</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Worksheet Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Worksheet_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Cost_Qty__c.field-meta.xml
<CustomField>
    <fullName>Cost_Qty__c</fullName>
    <label>Cost Qty.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Line_Cost__c.field-meta.xml
<CustomField>
    <fullName>Line_Cost__c</fullName>
    <label>Line Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Bill</fullName>
            </value>
            <value>
                <fullName>PM Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/TM_Line__c.field-meta.xml
<CustomField>
    <fullName>TM_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TM_Line__c.TM__c</field>
            <operation>equals</operation>
            <valueField>$Source.TM__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines (T&amp;M Line)</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Mobile Review</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fully Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <isActive>false</isActive>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
                <isActive>false</isActive>
                <label>Partially Invoiced</label>
            </value>
            <value>
                <fullName>Pro forma Review</fullName>
                <isActive>false</isActive>
                <label>Pro forma Review</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <isActive>false</isActive>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Received By Billing</fullName>
                <isActive>false</isActive>
                <label>Received By Billing</label>
            </value>
            <value>
                <fullName>Received By Dispatch</fullName>
                <isActive>false</isActive>
                <label>Received By Dispatch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Billing_Worksheet_Line__c.field-meta.xml
<CustomField>
    <fullName>Billing_Worksheet_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Worksheet Line</label>
    <referenceTo>Billing_Worksheet_Line__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Cost_Qty__c.field-meta.xml
<CustomField>
    <fullName>Cost_Qty__c</fullName>
    <label>Cost Qty.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Line_Cost__c.field-meta.xml
<CustomField>
    <fullName>Line_Cost__c</fullName>
    <label>Line Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/InterCompanyCostTrackingController.cls
public with sharing class InterCompanyCostTrackingController {
    private ApexPages.StandardController standardController;
    private ApexPages.StandardSetController standardSetController;
    public String startingDateValue {get;set;}
    public String endingDateValue {get;set;}
    public User theUser { get; set; }
    public Boolean renderedButton {get;set;}
    public transient List<TM_Line__c> interCompanyTmLines {get; set;}

    public InterCompanyCostTrackingController(ApexPages.StandardController controller){
        standardController = controller;

        if(CompanyMgmt.getVFPageName() == 'InterCompanyCostTrackingExcel' || Test.isRunningTest()){
            startingDateValue = ApexPages.currentPage().getParameters().get('startingDate');
            endingDateValue = ApexPages.currentPage().getParameters().get('endingDate');
            preparePageData();
        }

    }

    public InterCompanyCostTrackingController(ApexPages.StandardSetController controller){
        standardSetController = controller;
        startingDateValue = Date.today().month() + '/' + Date.today().day() + '/' + Date.today().year();
        endingDateValue = startingDateValue;
        selectUser();
        renderedButton = true;
    }

    private void selectUser() {
        theUser = [SELECT Id, Name, FirstName, LastName, Phone, Service_Center__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
    }

    public void checkDates(){
        System.debug('start: ' + startingDateValue);
        System.debug('end: ' + endingDateValue);
        Date startingDate = Date.parse(startingDateValue);
        Date endingDate = Date.parse(endingDateValue);
        //Integer noOfDays = startingDate.daysBetween(endingDate);
        if (startingDate > endingDate) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Days between Starting Date and Ending Date cannot be more than ' +  + ' days.'));
            renderedButton = false; return;
        }
        renderedButton = true;
    }

    public PageReference showInterCompanyCost(){
        try {
           preparePageData();
        } catch (Exception e) {
            System.debug('Error: ' + e.getStackTraceString());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }

    public PageReference saveAsExcel(){
        try{
            PageReference pageReference = new PageReference('/apex/InterCompanyCostTrackingExcel');
            pageReference.getParameters().put('startingDate', startingDateValue);
            pageReference.getParameters().put('endingDate', endingDateValue);
            pageReference.setRedirect(true);
            return pageReference;
        } catch (Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }

    public void preparePageData(){
            interCompanyTmLines = new List<TM_Line__c>();
            interCompanyTmLines = TMLinesSelector.newInstance().selectInterCompanyLineByScheduledDateRange(Date.parse(startingDateValue), Date.parse(endingDateValue));

            //map key => T&M SC:TM Line SC:Category
            Map<String,Decimal> intercoTMLineWithTotal = new Map<String, Decimal>();
            Map<String, List<TM_Line__c>> intercoTMLineByTMSCResSCAndCategory = new Map<String, List<TM_Line__c>>();

            for(TM_Line__c tmLine:interCompanyTmLines){
                String mapKey = tmLine.TM__r.Service_Center__r.Name + ':' + tmLine.Service_Center__r.Name + ':' + tmLine.Category__c;
                Decimal lineCost = 0;
                if(tmLine.TM__r.Status__c == 'Fully Invoiced' && String.isBlank(tmLine.Billing_Worksheet_Line__c)){
                    lineCost = CompanyMgmt.zeroIfNull(tmLine.Line_Cost__c);
                } else {
                    lineCost = CompanyMgmt.zeroIfNull(tmLine.Billing_Worksheet_Line__r.Line_Cost__c);
                }

                System.debug('Info: ' +  mapKey + ' **TM ' + tmLine.TM__r.Name + ' - '  + tmLine.Category__c + ' - ' + lineCost);

                if(intercoTMLineWithTotal.containsKey(mapKey)){
                    intercoTMLineWithTotal.put(mapKey, intercoTMLineWithTotal.get(mapKey) + lineCost);
                } else {
                    intercoTMLineWithTotal.put(mapKey, lineCost);
                }

                if(intercoTMLineByTMSCResSCAndCategory.containsKey(mapKey)){
                    List<TM_Line__c> interCoTmLines = intercoTMLineByTMSCResSCAndCategory.get(mapKey);
                    interCoTmLines.add(tmLine);
                    intercoTMLineByTMSCResSCAndCategory.put(mapKey, interCoTmLines);
                } else{
                    intercoTMLineByTMSCResSCAndCategory.put(mapKey, new List<TM_Line__c>{tmLine});
                }
            }

            List<InterCoCostWrap> interCoCostWraps = new List<InterCompanyCostTrackingController.InterCoCostWrap>();
            for(String mapKey: intercoTMLineByTMSCResSCAndCategory.keySet()){
                //0 => T&M Service Center, 1 => Resource Service Center, 2 => Category
                String[] keyElement = mapKey.split(':');
                InterCoCostWrap interCoCostWrap = new InterCoCostWrap();
                interCoCostWrap.description = 'Service Center ' + keyElement[0] +' Due to Service Center ' + keyElement[1];
                interCoCostWrap.category = keyElement[2];
                interCoCostWrap.totalCost = intercoTMLineWithTotal.get(mapKey);
                System.debug('Info: total cost ' + mapKey + ' -- ' + interCoCostWrap.totalCost);
                List<TM_Line__c> tmLines = intercoTMLineByTMSCResSCAndCategory.get(mapKey);
                /*
                for(TM_Line__c tmLine : tmLines){
                    if(tmLine.TM__r.Status__c == 'Fully Invoiced' && String.isBlank(tmLine.Billing_Worksheet_Line__c)){
                        tmLine.Billing_Worksheet_Line__r = new Billing_Worksheet_Line__c(
                                Cost_Qty__c = tmLine.Cost_Qty__c,
                                Line_Cost__c = tmLine.Line_Cost__c,
                                Unit_Cost__c = tmLine.Unit_Cost__c
                                );
                    }
                }
                 */
                interCoCostWrap.tmLines = tmLines;
                interCoCostWraps.add(interCoCostWrap);
            }

            interCoCostWrapList = interCoCostWraps;
    }

    public class InterCoCostWrap {
        /*
        private AggregateResult ar;
        public String description { get{ return (String)ar.get('Description'); } }
        public Decimal totalCost {get{ return ((Decimal)ar.get('TotalCost')).setScale(2);}}
        public String category {get {return (String)ar.get('Category__c'); }}
        public InterCoCostWrap(AggregateResult ar){
            this.ar = ar;
        */
        public String description {get; set;}
        public Decimal totalCost {get;set;}
        public String category {get;set;}
        public List<TM_Line__c> tmLines {get; set;}
    }

    public transient List<InterCoCostWrap> interCoCostWrapList { get;set; }
}