objects/Billing_Worksheet_Line__c/Billing_Worksheet_Line__c.object-meta.xml
<CustomObject>
    <label>Billing Worksheet Line</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Worksheet Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Worksheet_Line__c/fields/Sales_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Line</label>
    <referenceTo>Sales_Line__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines (Sales Line)</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order_Job_Task__c.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/TM_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>TM_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M Job Task</label>
    <referenceTo>TM_Job_Task__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>Sales_Order_Job_Task__c.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_Job_Task__c/Sales_Order_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Order Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/TM_Job_Task__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;M Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Job Task</label>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Job_Task__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/BillingWorksheetWrapper.cls
global with sharing class BillingWorksheetWrapper {
    @AuraEnabled
    public Sales_Order_Job_Task__c SalesOrderJobTask { set; get; }
    @AuraEnabled
    public List<RelatedInfo> RelatedInfos { set; get; }
    @AuraEnabled
    public List<Sales_Line__c> LumpSumLines { set; get; }
    @AuraEnabled
    public List<Billing_Worksheet_Line__c> WorksheetLines { set; get; }
    @AuraEnabled
    public List<Billing_Worksheet_Line__c> DeletedWorksheetLines { set; get; }
    @AuraEnabled
    public Boolean Collapsed { set; get; }
    //Ticket#19663 >>
    @AuraEnabled
    public Id PayRuleId {set; get; }
    @AuraEnabled
    public Boolean IsPayRuleCostUpdateCall {set; get;}
    //Ticket#19663 >>
    public BillingWorksheetWrapper() {
        this.RelatedInfos = new List<RelatedInfo>(); //by sales order job task
        this.LumpSumLines = new List<Sales_Line__c>();
        this.WorksheetLines = new List<Billing_Worksheet_Line__c>();
        this.DeletedWorksheetLines = new List<Billing_Worksheet_Line__c>();
        //Ticket#19663 >>
        this.PayRuleId = null;
        this.IsPayRuleCostUpdateCall = false;
        //Ticket#19663 >>
    }

    public class RelatedInfo {
        @AuraEnabled
        public TM__c TM { set; get; }
        @AuraEnabled
        //public List<TM_Job_Task__c> TMJobTasks;
        public TM_Job_Task__c TMJobTask;
        @AuraEnabled
        public String FieldTMPDFUrl { set; get; }
        @AuraEnabled
        public Boolean HasToInvoiceLines { set; get; }

        public RelatedInfo() {
            //this.TMJobTasks = new List<TM_Job_Task__c>();
        } 
    }
}