objects/Billing_Worksheet_Line__c/Billing_Worksheet_Line__c.object-meta.xml
<CustomObject>
    <label>Billing Worksheet Line</label>
    <nameField>
        <displayFormat>WL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Worksheet Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Worksheet_Line__c/fields/Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Line</label>
    <referenceTo>Billing_Worksheet_Line__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines (Bundle Line)</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Rolled_up_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Rolled_up_Unit_Price__c</fullName>
    <label>Rolled-up Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Billing Worksheet Lines</relationshipLabel>
    <relationshipName>Billing_Worksheet_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>Tax_Group__c</fullName>
    <label>Tax Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/Tax_Pct__c.field-meta.xml
<CustomField>
    <fullName>Tax_Pct__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Billing_Worksheet_Line__c/fields/xLine_Amount__c.field-meta.xml
<CustomField>
    <fullName>xLine_Amount__c</fullName>
    <label>xLine Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Contract_Line__c/Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Contract Line</label>
    <nameField>
        <label>contract line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Area__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Tax_Liable__c.field-meta.xml
<CustomField>
    <fullName>Tax_Liable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Liable</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>Sales_Line__c.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Line__c</referenceTo>
    <relationshipLabel>Sales Lines (Bundle)</relationshipLabel>
    <relationshipName>Bundle_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Subcontractors</fullName>
                <label>Cost Plus Materials, Equipment and Services</label>
            </value>
            <value>
                <fullName>Waste Disposal</fullName>
            </value>
            <value>
                <fullName>Demurrage</fullName>
                <label>Transportation, Demurrage and Fees</label>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
            <value>
                <fullName>Misc. Charges And Taxes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Line__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Line__c/fields/Rolled_up_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Rolled_up_Unit_Price__c</fullName>
    <label>Rolled-up Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Line__c/fields/Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>Tax_Group__c</fullName>
    <label>Tax Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TaxGroup</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Line__c/fields/Tax_Pct__c.field-meta.xml
<CustomField>
    <fullName>Tax_Pct__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Line__c/fields/xLine_Amount__c.field-meta.xml
<CustomField>
    <fullName>xLine_Amount__c</fullName>
    <label>xLine Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Area__c.Blocked__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Quotes/Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Tax_Liable__c.field-meta.xml
<CustomField>
    <fullName>Tax_Liable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Tax Liable</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Area</label>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Tax_Liable__c.field-meta.xml
<CustomField>
    <fullName>Tax_Liable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Liable</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Billing_Worksheet_Line__c.field-meta.xml
<CustomField>
    <fullName>Billing_Worksheet_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Worksheet Line</label>
    <referenceTo>Billing_Worksheet_Line__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Bundle_Line__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Line</label>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>T&amp;M Lines (Bundle Line)</relationshipLabel>
    <relationshipName>T_M_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>TM__r.Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

globalValueSets/TaxGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NT</fullName>
    </customValue>
    <customValue>
        <fullName>TX</fullName>
        <default>true</default>
        <label>TX</label>
    </customValue>
    <masterLabel>TaxGroup</masterLabel>
</GlobalValueSet>

classes/BillingWorksheetService.cls
global with sharing class BillingWorksheetService {

    private static IBillingWorksheetService service() {
        return (IBillingWorksheetService) Application.Service.newInstance(IBillingWorksheetService.class);
    }

    global static void initStaticVariables(Id salesOrderId, List<BillingWorksheetWrapper> worksheetWrappers) {
        service().initStaticVariables(salesOrderId, worksheetWrappers);
    }

    global static void initStaticVariables(Id salesOrderId, BillingWorksheetWrapper worksheetWrapper) {
        initStaticVariables(salesOrderId, new List<BillingWorksheetWrapper>{
                worksheetWrapper
        });
    }

    global static void initStaticVariables(Id salesOrderId, List<Billing_Worksheet_Line__c> worksheetLines) {
        BillingWorksheetWrapper worksheetWrapper = new BillingWorksheetWrapper();
        worksheetWrapper.WorksheetLines = worksheetLines;
        initStaticVariables(salesOrderId, new List<BillingWorksheetWrapper>{
                worksheetWrapper
        });
    }

    //Ticket#19663
    global static void initStaticVariables(Id salesOrderId, List<Billing_Worksheet_Line__c> worksheetLines, Id payRuleId, Boolean isPayRuleCostUpdateCall){
        BillingWorksheetWrapper worksheetWrapper = new BillingWorksheetWrapper();
        worksheetWrapper.WorksheetLines = worksheetLines;
        worksheetWrapper.PayRuleId = payRuleId;
        worksheetWrapper.IsPayRuleCostUpdateCall = isPayRuleCostUpdateCall;
        initStaticVariables(salesOrderId, new List<BillingWorksheetWrapper>{
                worksheetWrapper
        });
    }

    global static void populateLinesInfo(Id salesOrderId, List<Billing_Worksheet_Line__c> worksheetLines) {
        service().calculateLaborHours(salesOrderId, worksheetLines);
        for (Billing_Worksheet_Line__c worksheetLine : worksheetLines) {
            service().calcUnitPrice(salesOrderId, worksheetLine);
            service().calcUnitCost(salesOrderId, worksheetLine);
            service().assignTaxPercent(salesOrderId, worksheetLine);
            //service().assignDescription(salesOrderId, worksheetLine);
            service().calculateLineTotals(worksheetLine, true);
        }
        //DE37077
        service().populateWasteDisposalLineInfo(worksheetLines);
    }

    //ticket 19130 << temporary disable, not needed for this phase
    /*
    global static List<Billing_Worksheet_Line__c> calculatePresumptiveChildLines(Billing_Worksheet_Line__c worksheetLine, Integer nextWorksheetLineNo) {
        return service().calculatePresumptiveChildLines(worksheetLine, nextWorksheetLineNo);
    }
    */

    //global static Sales_Invoice__c createSalesInvoice(Id salesOrderId, List<Billing_Worksheet_Line__c> worksheetLines) {
    global static Sales_Invoice__c createSalesInvoice(Id salesOrderId, List<BillingWorksheetWrapper> worksheetWrappers) {
        initStaticVariables(salesOrderId, worksheetWrappers);
        service().validateSalesInvoice(salesOrderId, worksheetWrappers);
        return service().createSalesInvoice(salesOrderId, worksheetWrappers);
    }

    global static void validateResourceType(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine) {
        service().assignResourceTypeUOM(worksheetLine);
        service().calcUnitPrice(salesOrderId, worksheetLine);
        service().calcUnitCost(salesOrderId, worksheetLine);
        service().assignTaxPercent(salesOrderId, worksheetLine);
        service().assignDescription(salesOrderId, worksheetLine);
        service().calculateLineTotals(worksheetLine, true);
    }

    global static void validateResource(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine) {
        service().assignResourceUOM(worksheetLine);
        service().calcUnitPrice(salesOrderId, worksheetLine);
        service().calcUnitCost(salesOrderId, worksheetLine);
        service().assignTaxPercent(salesOrderId, worksheetLine);
        service().assignDescription(salesOrderId, worksheetLine);
        service().calculateLineTotals(worksheetLine, true);
    }

    global static void validateContractLine(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine){
        service().validateContractLine(salesOrderId, worksheetLine);
        service().assignTaxPercent(salesOrderId, worksheetLine);
        service().assignDescription(salesOrderId, worksheetLine);
        service().calculateLineTotals(worksheetLine, true);
    }

    /*
    global static void calculatePriceAndCost(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine) {
        service().calcUnitPrice(salesOrderId, worksheetLine);
        service().calcUnitCost(salesOrderId, worksheetLine);
        //service().assignTaxPercent(salesOrderId, worksheetLine);
        service().calculateLineTotals(worksheetLine);
    }*/

    global static void calculatePriceAndCost(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine) {
        service().calcUnitPrice(salesOrderId, worksheetLine);
        service().calcUnitCost(salesOrderId, worksheetLine);
        service().assignTaxPercent(salesOrderId, worksheetLine);
        // service().assignDescription(salesOrderId, worksheetLine);
        service().calculateLineTotals(worksheetLine, true);
    }

    global static void calculatePriceAndCost(Id salesOrderId, List<BillingWorksheetWrapper> worksheets) {
        for (BillingWorksheetWrapper worksheet : worksheets) {
            for (Billing_Worksheet_Line__c worksheetLine : worksheet.WorksheetLines) {
                service().calcUnitPrice(salesOrderId, worksheetLine);
                service().calcUnitCost(salesOrderId, worksheetLine);
                service().assignTaxPercent(salesOrderId, worksheetLine);
                service().assignDescription(salesOrderId, worksheetLine);
                service().calculateLineTotals(worksheetLine, true);
            }
        }
    }

    global static void assignTaxPercent(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine) {
        service().assignTaxPercent(salesOrderId, worksheetLine);
        service().calculateLineTotals(worksheetLine, true);
    }

    /*
        Ticket#19500
        Update Billing Worksheet Line tax info when Sales Order tax info changed.
    */
    global static void calculateLineTax(List<Sales_Order__c> salesOrders){
        Map<Id, Sales_Order__c> salesOrderbyIds = new Map<Id, Sales_Order__c>(salesOrders);
        List<Billing_Worksheet_Line__c> billingWorksheetLines = BillingWorksheetLinesSelector.newInstance().selectOpenLinesBySalesOrderId(salesOrderbyIds.keySet());
        for(Billing_Worksheet_Line__c billingWorksheetLine:billingWorksheetLines) {
            Sales_Order__c salesOrder = salesOrderbyIds.get(billingWorksheetLine.Sales_Order__c);
            if (salesOrder.Tax_Liable__c && billingWorksheetLine.Tax_Group__c != null) {
                billingWorksheetLine.Tax_Pct__c = CompanyMgmt.getSalesTax(salesOrder.Tax_Area__c, billingWorksheetLine.Tax_Group__c);
            } else {
                billingWorksheetLine.Tax_Pct__c = 0;
            }
            service().calculateLineTotals(billingWorksheetLine, false);
        }
        CompanyMgmt.systemCall = true;
        update billingWorksheetLines;
    }

    /*
        Ticket#19820
        Update Billing Worksheet Line Unit Price and Total when Sales Order Type changed.
     */
    global static void validateSalesOrderType(Sales_Order__c salesOrder){
        List<Billing_Worksheet_Line__c> billingWorksheetLines = BillingWorksheetLinesSelector.newInstance().selectOpenLinesBySalesOrderId(new Set<Id>{salesOrder.Id});
        initStaticVariables(salesOrder.Id, billingWorksheetLines);
        for(Billing_Worksheet_Line__c billingWorksheetLine : billingWorksheetLines){
            service().calcUnitPrice(salesOrder.Id, billingWorksheetLine);
            service().calculateLineTotals(billingWorksheetLine, false);
        }
        CompanyMgmt.systemCall = true;
        update billingWorksheetLines;
    }

    global static void calculateLaborHours(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine) {
        List<Billing_Worksheet_Line__c> worksheetLines = new List<Billing_Worksheet_Line__c>{ worksheetLine };
        service().calculateLaborHours(salesOrderId, worksheetLines);
        worksheetLine = worksheetLines[0];
        service().calculateLineTotals(worksheetLine, true);
    }

    //Ticket#20496 >>
    global static void calculateLaborHours(Id salesOrderId, List<Billing_Worksheet_Line__c> billingWorksheetLines){
        initStaticVariables(salesOrderId, billingWorksheetLines);
        service().calculateLaborHours(salesOrderId, billingWorksheetLines);
    }

    global static void calculateLaborHours(Id salesOrderId, List<Billing_Worksheet_Line__c> billingWorksheetLines, Billing_Worksheet_Line__c updatedWorksheetLine){
        initStaticVariables(salesOrderId, billingWorksheetLines);
        service().calculateLaborHours(salesOrderId, billingWorksheetLines, updatedWorksheetLine);
    }
    //Ticket#20496 <<

    global static void calculateUnitCost(Id salesOrderId, Billing_Worksheet_Line__c worksheetLine, Boolean initStaticVariable){
        if(initStaticVariable == true){
            initStaticVariables(salesOrderId, new List<Billing_Worksheet_Line__c>{worksheetLine});
        }
        service().calcUnitCost(salesOrderId, worksheetLine);
    }

    //Ticket#19663 >>
    global static void calculateUnitCost(Id salesOrderId, List<Billing_Worksheet_Line__c> billingWorksheetLines, Boolean initStaticVariable, Id payRuleId, Boolean isPayRuleCostUpdateCall){
        if(initStaticVariable == true){
            initStaticVariables(salesOrderId, billingWorksheetLines, payRuleId, isPayRuleCostUpdateCall);
        }
        for(Billing_Worksheet_Line__c billingWorksheetLine : billingWorksheetLines){
            service().calcUnitCost(salesOrderId, billingWorksheetLine);
            calculateLineTotals(billingWorksheetLine, false);
        }
    }

    global static void calculateLineTotals(Billing_Worksheet_Line__c worksheetLine) {
        service().calculateLineTotals(worksheetLine, true);
    }

    //Ticket#19663 >>
    global static void calculateLineTotals(Billing_Worksheet_Line__c worksheetLine, Boolean reCalCostQty) {
        service().calculateLineTotals(worksheetLine, reCalCostQty);
    }

    global static void rollupBundledLines(List<Billing_Worksheet_Line__c> worksheetLines) {
        Map<Integer, Billing_Worksheet_Line__c> mapLumpSumLinesByLineNo = new Map<Integer, Billing_Worksheet_Line__c>();
        Map<Integer, List<Billing_Worksheet_Line__c>> mapBundledLinesByParentLineNo = new Map<Integer, List<Billing_Worksheet_Line__c>>();
        for (Billing_Worksheet_Line__c worksheetLine : worksheetLines) {
            if (worksheetLine.Category__c == 'Bundled') {
                mapLumpSumLinesByLineNo.put(worksheetLine.Line_No__c.intValue(), worksheetLine);
            }

            if (worksheetLine.Bundle_Line__r != null) {
                Integer parentLineNo = worksheetLine.Bundle_Line__r.Line_No__c.intValue();
                List<Billing_Worksheet_Line__c> bundledLines;
                if (mapBundledLinesByParentLineNo.containsKey(parentLineNo)) {
                    bundledLines = mapBundledLinesByParentLineNo.get(parentLineNo);
                } else {
                    bundledLines = new List<Billing_Worksheet_Line__c>();
                    mapBundledLinesByParentLineNo.put(parentLineNo, bundledLines);
                }
                bundledLines.add(worksheetLine);
            }
        }

        for (Integer parentLineNo : mapBundledLinesByParentLineNo.keySet()) {
            Decimal rollupAmount = 0;
            List<Billing_Worksheet_Line__c> bundledWorksheetLines = mapBundledLinesByParentLineNo.get(parentLineNo);
            for (Billing_Worksheet_Line__c worksheetLine : bundledWorksheetLines) {
                rollupAmount += (worksheetLine.xLine_Amount__c != null ? worksheetLine.xLine_Amount__c : 0);
            }

            if (mapLumpSumLinesByLineNo.containsKey(parentLineNo)) {
                Billing_Worksheet_Line__c lumpSumLine = mapLumpSumLinesByLineNo.get(parentLineNo);
                lumpSumLine.Rolled_up_Unit_Price__c = rollupAmount;
                service().calculateLineTotals(lumpSumLine, true);
            }
        }
    }

    global static Integer calcWorksheetLinesPricing(Sales_Order__c salesOrder){
        Integer recordCount = 0;
        List<TM__c> tms = TMsSelector.newInstance().selectOpenTMsBySalesOrderIdWithLines(salesOrder.Id);
        if(tms.size() > 0) {
            BillingWorksheetWrapper billingWorksheetWrapper = new BillingWorksheetWrapper();
            List<BillingWorksheetWrapper.RelatedInfo> relatedInfos = new List<BillingWorksheetWrapper.RelatedInfo>();
            //Ticket#24525
            Map<TM__c, List<TM_Line__c>> tmLinesByTMs = new Map<TM__c, List<TM_Line__c>>();
            Map<Id, TM__c> tmsByIds = new Map<Id, TM__c>();
            for (TM__c tm : tms) {
                //tm.Contract__c = salesOrder.Contract__c; //Ticket#24525
                tm.From_Sales_Quote__c = salesOrder.From_Sales_Quote__c;
                BillingWorksheetWrapper.RelatedInfo relatedInfo = new BillingWorksheetWrapper.RelatedInfo();
                relatedInfo.TM = tm;
                relatedInfos.add(relatedInfo);

                //Ticket#24525 >>
                //if(tm.Contract__c != salesOrder.Contract__c){
                tm.Contract__c = salesOrder.Contract__c;
                tmsByIds.put(tm.Id, tm);
                tmLinesByTMs.put(tm, tm.TM_Lines__r);
                //System.debug('Info: TMs with different contract: ' + tm.Name + ' -- ' + tm.Contract__c + ' SO contract: ' + salesOrder.Contract__c);
                //}
                //Ticket#24525 <<
            }
            List<Billing_Worksheet_Line__c> billingWorksheetLines = BillingWorksheetLinesSelector.newInstance().selectOpenLinesBySalesOrderId(new Set<Id>{salesOrder.Id});
            if(billingWorksheetLines.size() > 0) {
                billingWorksheetWrapper.relatedInfos = relatedInfos;
                billingWorksheetWrapper.WorksheetLines = billingWorksheetLines;
                service().initStaticVariables(salesOrder.Id, new List<BillingWorksheetWrapper>{
                        billingWorksheetWrapper
                });

                service().calculateLaborHours(salesOrder.Id, billingWorksheetLines);
                for (Billing_Worksheet_Line__c worksheetLine : billingWorksheetLines) {
                    worksheetLine.Contract_Line__c = null;
                    worksheetLine.Sales_Line__c = null;
                    service().calcUnitPrice(salesOrder.Id, worksheetLine);
                    service().calcUnitCost(salesOrder.Id, worksheetLine);
                    service().assignTaxPercent(salesOrder.Id, worksheetLine);
                    service().assignDescription(salesOrder.Id, worksheetLine); //Ticket#24525
                    service().calculateLineTotals(worksheetLine, true); 
                }
            }

            CompanyMgmt.byPassTrigger = true;
            CompanyMgmt.byPassLineTrigger = true;
            
            update tms;
            //Ticket#24525 >>
            if(tmsByIds.size() > 0){
                List<TM_Line__c> tmLinesToUpdate = new List<TM_Line__c>();
                TMLLinesService.initStaticVariables(tmLinesByTMs);
                for(TM__c tm : tmLinesByTMs.keySet()){
                    for(TM_Line__c tmLine : tmLinesByTMs.get(tm)){
                        tmLine.Sales_Line__c = null; //Ticket#24869 force system to re-calculate sales line.
                        tmLine.Contract_Line__c = null; //Ticket#24869 force system to re-calculate contract line.
                        TMLLinesService.validateUnitOfMeasure(tm, tmLine, false);
                        tmLinesToUpdate.add(tmLine);
                    }
                }
                if(tmLinesToUpdate.size() > 0) {
                    recordCount += tmLinesToUpdate.size();                    
                    update tmLinesToUpdate;
                    CompanyMgmt.byPassLineTrigger = false;
                    CompanyMgmt.byPassTrigger = false;
                }
            }
            //Ticket#24525 <<

            if (billingWorksheetLines.size() > 0) {
                CompanyMgmt.systemCall = true;
                recordCount += billingWorksheetLines.size();
                update billingWorksheetLines;
            }
        }
        return recordCount;
    }

    /*
     *  Ticket#24817
     */
    global static void reopenKronosProcessedTMLinesByIds(Set<Id> tmLinesIds){
        List<TM_Line__c> tmLines = [SELECT Id, Kronos_Integration_Note__c, KronosTimeEntriesProcessed__c
        FROM TM_Line__c
        WHERE Id IN :tmLinesIds AND Category__c = :ResourceService.LABOR_CATEGORY AND KronosTimeEntriesProcessed__c = TRUE];
        for(TM_Line__c tmLine : tmLines){
            tmLine.KronosTimeEntriesProcessed__c = false;
            tmLine.Kronos_Integration_Note__c = System.today() + ' TM line reopen, due to resource type change in billing worksheet';
        }

        if(tmLines.size() > 0){
            CompanyMgmt.byPassTrigger = true;
            CompanyMgmt.byPassLineTrigger = true;
            update tmLines;
            CompanyMgmt.byPassTrigger = false;
            CompanyMgmt.byPassLineTrigger = false;
        }
    }

}