objects/Employee_Clocked_Time_for_Kronos__c/Employee_Clocked_Time_for_Kronos__c.object-meta.xml
<CustomObject>
    <label>Employee Clocked Time for Kronos</label>
    <nameField>
        <displayFormat>TFC-{0000000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Clocked Time for Kronos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Entry_Type__c.field-meta.xml
<CustomField>
    <fullName>Entry_Type__c</fullName>
    <label>Entry Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
            <value>
                <fullName>Lunch In</fullName>
            </value>
            <value>
                <fullName>Lunch Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Exported__c.field-meta.xml
<CustomField>
    <fullName>Exported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exported</label>
    <type>Checkbox</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Exported_At__c.field-meta.xml
<CustomField>
    <fullName>Exported_At__c</fullName>
    <label>Exported At</label>
    <type>DateTime</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Kronos_Action__c.field-meta.xml
<CustomField>
    <fullName>Kronos_Action__c</fullName>
    <label>Kronos Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Pay_Rule_Line__c.field-meta.xml
<CustomField>
    <fullName>Pay_Rule_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Rule Line</label>
    <referenceTo>Pay_Rule_Line__c</referenceTo>
    <relationshipLabel>Employee Clocked Time for Kronos</relationshipLabel>
    <relationshipName>Employee_Clocked_Time_for_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Employee Clocked Time for Kronos</relationshipLabel>
    <relationshipName>Employee_Clocked_Time_for_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Employee Clocked Time for Kronos</relationshipLabel>
    <relationshipName>Employee_Clocked_Time_for_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Time_Type__c.field-meta.xml
<CustomField>
    <fullName>Time_Type__c</fullName>
    <label>Time Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeType</valueSetName>
    </valueSet>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Time_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Time_Type_Code__c</fullName>
    <label>Time Type Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Work_Date__c.field-meta.xml
<CustomField>
    <fullName>Work_Date__c</fullName>
    <label>Work Date</label>
    <type>Date</type>
</CustomField>

objects/Pay_Rule__c/Pay_Rule__c.object-meta.xml
<CustomObject>
    <label>Pay Rule</label>
    <nameField>
        <label>Pay Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pay Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Union</fullName>
            </value>
            <value>
                <fullName>Prevailing Wage</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Pay_Rule_Line__c/Pay_Rule_Line__c.object-meta.xml
<CustomObject>
    <label>Pay Rule Line</label>
    <nameField>
        <displayFormat>PRL-{000000}</displayFormat>
        <label>Line No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Rule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pay_Rule_Line__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <externalId>true</externalId>
    <label>RSG EIN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource_Off__c/Resource_Off__c.object-meta.xml
<CustomObject>
    <label>Resource Off</label>
    <nameField>
        <displayFormat>Off-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Off__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

objects/Resource_Off__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Offs</relationshipLabel>
    <relationshipName>Resource_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>Service_Center__r.Shop_Time_Sales_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/D365_Project_ID__c.field-meta.xml
<CustomField>
    <fullName>D365_Project_ID__c</fullName>
    <label>D365 Project ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/Salesforce_Punch_to_Kronos__c.object-meta.xml
<CustomObject>
    <label>Salesforce Punch to Kronos</label>
    <nameField>
        <displayFormat>SPK-{0000000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Punch to Kronos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Punch_to_Kronos__c/fields/Delete_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Delete_Indicator__c</fullName>
    <label>Delete Indicator</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Employee_Clocked_Time_for_Kronos__c.field-meta.xml
<CustomField>
    <fullName>Employee_Clocked_Time_for_Kronos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Clocked Time for Kronos</label>
    <referenceTo>Employee_Clocked_Time_for_Kronos__c</referenceTo>
    <relationshipLabel>Salesforce Punch to Kronos</relationshipLabel>
    <relationshipName>Salesforce_Punch_to_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Exported__c.field-meta.xml
<CustomField>
    <fullName>Exported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exported</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Exported_At__c.field-meta.xml
<CustomField>
    <fullName>Exported_At__c</fullName>
    <label>Exported At</label>
    <type>DateTime</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Salesforce Punch to Kronos</relationshipLabel>
    <relationshipName>Salesforce_Punch_to_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Rule_Id__c.field-meta.xml
<CustomField>
    <fullName>Rule_Id__c</fullName>
    <label>Rule Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Time_Type__c.field-meta.xml
<CustomField>
    <fullName>Time_Type__c</fullName>
    <label>Time Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Time_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Time_Type_Code__c</fullName>
    <label>Time Type Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Billing Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>TM__r.Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/time__c.field-meta.xml
<CustomField>
    <fullName>time__c</fullName>
    <formula>TIMEVALUE( Lunch_Start_Time__c )  &gt;=  Job_End_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lunch Time Exceeds Job End Time</label>
    <type>Checkbox</type>
</CustomField>

globalValueSets/TimeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Job Time</fullName>
    </customValue>
    <customValue>
        <fullName>Prevailing Wage</fullName>
    </customValue>
    <customValue>
        <fullName>PTO</fullName>
    </customValue>
    <customValue>
        <fullName>Shop Time</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Pay</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Travel Time</fullName>
    </customValue>
    <customValue>
        <fullName>Site Time</fullName>
        <isActive>false</isActive>
        <label>Site Time</label>
    </customValue>
    <customValue>
        <fullName>Non-PTO</fullName>
        <isActive>false</isActive>
        <label>Non-PTO</label>
    </customValue>
    <customValue>
        <fullName>PTO FMLA</fullName>
        <isActive>false</isActive>
        <label>PTO FMLA</label>
    </customValue>
    <customValue>
        <fullName>PTO Vacation</fullName>
        <isActive>false</isActive>
        <label>PTO Vacation</label>
    </customValue>
    <customValue>
        <fullName>Lunch Time</fullName>
        <isActive>false</isActive>
        <label>Lunch Time</label>
    </customValue>
    <masterLabel>Time Type</masterLabel>
</GlobalValueSet>

classes/KronosTimeClockEntriesSortingBatch.cls
/*************************************************************************************************
* Name         : KronosTimeClockEntriesSortingBatch
* Description  :  Batch for creating T&M punch data
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Andrew SImons             10/17/2024             Added creation of T&M line report in finish method
* Andrew Simons             10/18/2024             Updated report target list
*************************************************************************************************/

public with sharing class KronosTimeClockEntriesSortingBatch implements Database.Batchable<Employee_Clocked_Time_for_Kronos__c> {
    //Ticket#24469
    public Boolean isMondayExtraRun = false;
    public List<String> targetAddresses = new List<String> {};

    //Ticket#24469
    public KronosTimeClockEntriesSortingBatch(Boolean isMondayExtra){
        isMondayExtraRun = isMondayExtra;
    }

    public List<Employee_Clocked_Time_for_Kronos__c> start(Database.BatchableContext bc){
        List<Employee_Clocked_Time_for_Kronos__c> employeeClockedTimeForKronosLst = [SELECT Id, Resource__r.Description__c,
                Resource__r.RSG_EIN__c, Work_Date__c, Time__c, Time_Type__c, Time_Type_Code__c, Entry_Type__c,
                Pay_Rule_Line__c, Sales_Order__r.Name, Sales_Order__r.D365_Project_ID__c, Kronos_Action__c
        FROM Employee_Clocked_Time_for_Kronos__c
        WHERE Exported__c = FALSE ORDER BY Resource__c, Work_Date__c, Kronos_Action__c DESC NULLS LAST, Time__c];
        return employeeClockedTimeForKronosLst;
    }

    public void execute(Database.BatchableContext bc, List<Employee_Clocked_Time_for_Kronos__c> employeeClockedTimeForKronosLst){
        List<Salesforce_Punch_to_Kronos__c> salesforcePunchToKronosEntries = new List<Salesforce_Punch_to_Kronos__c>();
        List<Employee_Clocked_Time_for_Kronos__c> employeeClockedTimeForKronosEntriesToUpdate = new List<Employee_Clocked_Time_for_Kronos__c>();
        for(Employee_Clocked_Time_for_Kronos__c employeeTimeClock : employeeClockedTimeForKronosLst){
            Salesforce_Punch_to_Kronos__c spk = new Salesforce_Punch_to_Kronos__c();
            spk.Name__c = employeeTimeClock.Resource__r.Description__c;
            spk.EIN__c = employeeTimeClock.Resource__r.RSG_EIN__c;
            spk.Date__c = employeeTimeClock.Work_Date__c;
            spk.Time__c = employeeTimeClock.Time__c;
            spk.Time_Type__c = employeeTimeClock.Time_Type__c;
            spk.Time_Type_Code__c = employeeTimeClock.Time_Type_Code__c;
            spk.Type__c = employeeTimeClock.Entry_Type__c;
            spk.Rule_Id__c = employeeTimeClock.Pay_Rule_Line__c;
            if(employeeTimeClock.Time_Type__c == 'Travel Time'){
                spk.Time_Type__c = 'Travel';
                spk.Rule_Id__c = null;
            }
            if(employeeTimeClock.Sales_Order__c != null){
                if(employeeTimeClock.Sales_Order__r.D365_Project_ID__c != null) {
                    spk.Sales_Order__c = employeeTimeClock.Sales_Order__r.Name + ' - ' + employeeTimeClock.Sales_Order__r.D365_Project_ID__c;
                } else {
                    spk.Sales_Order__c = employeeTimeClock.Sales_Order__r.Name;
                }
            }
            spk.Delete_Indicator__c = employeeTimeClock.Kronos_Action__c;
            salesforcePunchToKronosEntries.add(spk);
            employeeTimeClock.Exported__c = true;
            employeeTimeClock.Exported_At__c = System.now();
            employeeClockedTimeForKronosEntriesToUpdate.add(employeeTimeClock);
        }
        if(salesforcePunchToKronosEntries.size() > 0){
            insert salesforcePunchToKronosEntries;
        }

        if(employeeClockedTimeForKronosEntriesToUpdate.size() > 0){
            CompanyMgmt.systemCall = true; //Ticket#23796
            update employeeClockedTimeForKronosEntriesToUpdate;
        }
    }

    public void finish(Database.BatchableContext bc){
    
        //Ticket#24469 >>
        if(isMondayExtraRun == true) {
            //for United States locale, the start of a week is always Sunday.
            Date processDate = System.today().toStartOfWeek();
            //calculate start of week Monday's date.(Previous Week)
            processDate = TimeUtils.toStartOfWeek(processDate);
            GenerateTimesheetBatch generateTimesheetBatch = new GenerateTimesheetBatch(processDate);
            Database.executeBatch(generateTimesheetBatch, 1);
        }
        //Ticket#24469 <<

        DateTime endDate = DateTime.now();
        DateTime startDate = endDate.addMinutes(-20);
       
        // Fetch all the Employee_Clocked_Time_for_Kronos__c records
        List<Employee_Clocked_Time_for_Kronos__c> employeeClockedTimeForKronosLst = [SELECT Id, Resource__r.Description__c, Resource__r.RSG_EIN__c, Work_Date__c, Time__c, Time_Type__c,
                        Entry_Type__c, Pay_Rule_Line__r.Rate__c, T_M_Line__r.Name, T_M_Line__r.Job_Start_Time__c, T_M_Line__r.Resource_Type__r.Name, Original_Labor_Type__c, 
                        T_M_Line__r.Site_Start_Time__c, T_M_Line__r.Site_End_Time__c, T_M_Line__r.Job_End_Time__c, Pay_Rule_Line__r.PW_Labor_Category__c, Pay_Rule_Line__r.Resource_Type__r.Name,
                        T_M_Line__r.Lunch_Start_Time__c, T_M_Line__r.Lunch_End_Time__c, Sales_Order__r.Name, Sales_Order__r.Pay_Rule__r.Name,
                        Sales_Order__r.D365_Project_ID__c, Kronos_Action__c
                            FROM Employee_Clocked_Time_for_Kronos__c
                            WHERE Exported__c = TRUE
                            AND ((CreatedDate >= :startDate AND CreatedDate <= :endDate) OR (LastModifiedDate >= :startDate AND LastModifiedDate <= :endDate))
                            AND Resource_Off__r.Off_Type__r.Name != 'Shop Time'
                            ORDER BY CreatedDate DESC ,Id, T_M_Line__r.Id
        ];
        System.debug(employeeClockedTimeForKronosLst);

        // Prepare CSV string
        String csvData = 'Name,EIN,Date,Start Job Time,Site Start Time,Site End Time,Job End Time,Start Lunch Time,End Lunch Time,Rate,Labor Type,Pay Rule Name,Sales Order,D365 Project Id,Delete Indicator\n';


        // Map to group records by T&M Line ID
        Map<Id, Employee_Clocked_Time_for_Kronos__c> uniqueTMLineRecords = new Map<Id, Employee_Clocked_Time_for_Kronos__c>();

        // Map to group 'Delete' records by T&M Line ID
        Map<Id, List<Employee_Clocked_Time_for_Kronos__c>> deleteRecordsByTMLine = new Map<Id, List<Employee_Clocked_Time_for_Kronos__c>>();

                for (Employee_Clocked_Time_for_Kronos__c record : employeeClockedTimeForKronosLst) {
                    Id tmLineId = record.T_M_Line__c;
                    if (tmLineId != null) {
                        if (record.Kronos_Action__c == 'Delete') {
                        // Collect delete records for each T&M Line
                        if (!deleteRecordsByTMLine.containsKey(tmLineId)) {
                            deleteRecordsByTMLine.put(tmLineId, new List<Employee_Clocked_Time_for_Kronos__c>());
                }
                    deleteRecordsByTMLine.get(tmLineId).add(record);
                } else {
                    // Keep the first non-delete record for each T&M Line
                    if (!uniqueTMLineRecords.containsKey(tmLineId)) {
                        uniqueTMLineRecords.put(tmLineId, record);
                    }
                }
            }
        }

           
            // process non-delete records
            for (Employee_Clocked_Time_for_Kronos__c record : uniqueTMLineRecords.values()) {
            
                // Iterate through the unique records and add them to the CSV
                    String workDate = formatDateTime(record.Work_Date__c);
                    //Formatting the time fields
                    String jobStartTime = formatTime(record.T_M_Line__r.Job_Start_Time__c);
                    String jobEndTime = formatTime(record.T_M_Line__r.Job_End_Time__c);
                    String siteStartTime = '';
                    String siteEndTime = '';
                    String lunchStartTime = formatTime(record.T_M_Line__r.Lunch_Start_Time__c);
                    String lunchEndTime = formatTime(record.T_M_Line__r.Lunch_End_Time__c);
                    String pwLaborType;
        
                    if (record.Sales_Order__r.Pay_Rule__r.Name != null && record.Sales_Order__r.Pay_Rule__r.Name.startsWith('PW')) {
                        siteStartTime = formatTime(record.T_M_Line__r.Site_Start_Time__c);
                        siteEndTime = formatTime(record.T_M_Line__r.Site_End_Time__c);
                        pwLaborType = (record.Pay_Rule_Line__c != null ? (record.Pay_Rule_Line__r.Resource_Type__r.Name + ' - ' + record.Pay_Rule_Line__r.PW_Labor_Category__c) : record.T_M_Line__r.Resource_Type__r.Name);

                    }
        
                    csvData += '"' + record.Resource__r.Description__c + '",' +
                    '"' + record.Resource__r.RSG_EIN__c + '",' +
                    '"' + workDate + '",' +
                    '"' + jobStartTime + '",' +
                    '"' + siteStartTime + '",' +
                    '"' + siteEndTime + '",' +
                    '"' + jobEndTime + '",' +
                    '"' + lunchStartTime + '",' +
                    '"' + lunchEndTime + '",' +
                    '"' + ((record.Pay_Rule_Line__r.Rate__c != null && record.Sales_Order__r.Pay_Rule__r.Name != null) ? record.Pay_Rule_Line__r.Rate__c : 0.0) + '",' +
                    '"' + (pwLaborType != null ? pwLaborType : record.T_M_Line__r.Resource_Type__r.Name)  + '",' +
                    '"' + (record.Sales_Order__r.Pay_Rule__r.Name != null ? record.Sales_Order__r.Pay_Rule__r.Name : '') + '",' +
                    '"' + record.Sales_Order__r.Name + '",' +
                    '"' + (record.Sales_Order__r.D365_Project_ID__c != null ? record.Sales_Order__r.D365_Project_ID__c : '') + '",' +
                    '"' + (record.Kronos_Action__c != null ? record.Kronos_Action__c : '') + '"\n';
                }

                System.debug( deleteRecordsByTMLine.keySet());
            // process delete records
            for (Id tmLineId : deleteRecordsByTMLine.keySet()) {

                List<Employee_Clocked_Time_for_Kronos__c> deleteRecords = deleteRecordsByTMLine.get(tmLineId);
             
                // Variables to store time values
                Time jobStartTime;
                Time siteStartTime;
                Time siteEndTime;
                Time jobEndTime;
                Time startLunchTime;
                Time endLunchTime;

                // Lists to hold IN and OUT entries
                List<Employee_Clocked_Time_for_Kronos__c> inEntries = new List<Employee_Clocked_Time_for_Kronos__c>();
                List<Employee_Clocked_Time_for_Kronos__c> outEntries = new List<Employee_Clocked_Time_for_Kronos__c>();

                // Loop over delete records for the same T&M Line ID
                for (Employee_Clocked_Time_for_Kronos__c delRecord : deleteRecords) {
                    System.debug(delRecord);
                    if (delRecord.Entry_Type__c == 'IN') {
                        inEntries.add(delRecord);
                    } else if (delRecord.Entry_Type__c == 'OUT') {
                        outEntries.add(delRecord);
                    } else if (delRecord.Entry_Type__c == 'Lunch Out') {
                        startLunchTime = delRecord.Time__c;
                    } else if (delRecord.Entry_Type__c == 'Lunch In') {
                        endLunchTime = delRecord.Time__c;
                    }
                }

                // Process IN entries
                if (inEntries.size() >= 3) {
                   
                    // Assign lesser time to Start Job Time, greater time to Site Start Time
                    if(inEntries[1].Sales_Order__r.Pay_Rule__r.Name.startsWith('PW')) {
                        siteStartTime = inEntries[1].Time__c;
                    }
                    if(inEntries[2].Sales_Order__r.Pay_Rule__r.Name.startsWith('PW')) {
                        siteEndTime = inEntries[2].Time__c;
                    }
                    jobStartTime = inEntries[0].Time__c;
                }

              

                if (inEntries.size() == 1) {
                     jobStartTime = inEntries[0].Time__c;
                }

                // Process OUT entries
                if (outEntries.size() >= 1) {
                    // Sort OUT entries by time
                    jobEndTime = outEntries[0].Time__c;
                }

                    // Build CSV row using the computed times
                    Employee_Clocked_Time_for_Kronos__c firstRecord = deleteRecords[0]; 

                    String workDate = formatDateTime(firstRecord.Work_Date__c);
                    String formattedJobStartTime = formatTime(jobStartTime);
                    String formattedSiteStartTime = formatTime(siteStartTime);
                    String formattedSiteEndTime = formatTime(siteEndTime);
                    String formattedJobEndTime = formatTime(jobEndTime);
                    String formattedStartLunchTime = formatTime(startLunchTime);
                    String formattedEndLunchTime = formatTime(endLunchTime);

                    csvData += '"' + firstRecord.Resource__r.Description__c + '",' +
                            '"' + firstRecord.Resource__r.RSG_EIN__c + '",' +
                            '"' + workDate + '",' +
                            '"' + formattedJobStartTime + '",' +
                            '"' + formattedSiteStartTime + '",' +
                            '"' + formattedSiteEndTime + '",' +
                            '"' + formattedJobEndTime + '",' +
                            '"' + formattedStartLunchTime + '",' +
                            '"' + formattedEndLunchTime + '",' +
                            '"' + ((firstRecord.Pay_Rule_Line__r.Rate__c != null && firstRecord.Sales_Order__r.Pay_Rule__r.Name != null) ? firstRecord.Pay_Rule_Line__r.Rate__c : 0.0) + '",' +
                            '"' + (firstRecord.Original_Labor_Type__c != null ? firstRecord.Original_Labor_Type__c : '' ) + '",' +
                            '"' + (firstRecord.Sales_Order__r.Pay_Rule__r.Name != null ? firstRecord.Sales_Order__r.Pay_Rule__r.Name : '') + '",' +
                            '"' + firstRecord.Sales_Order__r.Name + '",' +
                            '"' + (firstRecord.Sales_Order__r.D365_Project_ID__c != null ? firstRecord.Sales_Order__r.D365_Project_ID__c : '') + '",' +
                            '"' + firstRecord.Kronos_Action__c + '"\n';
        }

        String sortedCsvData = KronosCSVSorter.sortCSVData(csvData);
       
        // Convert the CSV data to a Blob
        Blob csvBlob = Blob.valueOf(sortedCsvData);

        // List of target email addresses (update with your list of recipients)
        List<String> emailAddresses = new List<String>{'SLucas3@republicservices.com', 'DDuncan2@republicservices.com', 'NCentofanti@republicservices.com', 'mrooney@republicservices.com', 'ATaylor@republicservices.com', 'GSwift@republicservices.com', 'JGilchrist@republicservices.com', 'TGamba@republicservices.com'};

        // Create an email message
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(emailAddresses);
        email.setSubject('Kronos Report '+ System.Today());
        email.setPlainTextBody('Please find the attached Kronos report for today.');

        // Attach the CSV as an attachment
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName('Kronos_Report.csv');
        attachment.setBody(csvBlob);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });

        // Send the email
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });

        System.debug('Email sent with Kronos report attached.');
      
}   

    private String formatTime(Time timeValue) {
        if (timeValue == null) return '';
        String hourStr = (timeValue.hour() < 10 ? '0' : '') + timeValue.hour();
        String minuteStr = (timeValue.minute() < 10 ? '0' : '') + timeValue.minute();
        String secondStr = (timeValue.second() < 10 ? '0' : '') + timeValue.second();
        return hourStr + ':' + minuteStr + ':' + secondStr;
    } 
    
    private String formatDateTime(Date dateValue) {
        if (dateValue == null) {
            return '';
        }

        return dateValue.format();
    }

}