objects/Employee_Clocked_Time_for_Kronos__c/Employee_Clocked_Time_for_Kronos__c.object-meta.xml
<CustomObject>
    <label>Employee Clocked Time for Kronos</label>
    <nameField>
        <displayFormat>TFC-{0000000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Clocked Time for Kronos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Kronos_Action__c.field-meta.xml
<CustomField>
    <fullName>Kronos_Action__c</fullName>
    <label>Kronos Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Employee Clocked Time for Kronos</relationshipLabel>
    <relationshipName>Employee_Clocked_Time_for_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/T_M__c.field-meta.xml
<CustomField>
    <fullName>T_M__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Employee Clocked Time for Kronos</relationshipLabel>
    <relationshipName>Employee_Clocked_Time_for_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee_Clocked_Time_for_Kronos__c/fields/T_M_Line__c.field-meta.xml
<CustomField>
    <fullName>T_M_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M Line</label>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>Employee Clocked Time for Kronos</relationshipLabel>
    <relationshipName>Employee_Clocked_Time_for_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Employee_No__c.field-meta.xml
<CustomField>
    <fullName>Employee_No__c</fullName>
    <label>Employee No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Service</fullName>
                <label>OOS-On Lot</label>
            </value>
            <value>
                <fullName>OOS-Pending</fullName>
                <label>OOS-Pending Sale</label>
            </value>
            <value>
                <fullName>Gone</fullName>
            </value>
            <value>
                <fullName>Junked</fullName>
                <isActive>false</isActive>
                <label>Junked</label>
            </value>
            <value>
                <fullName>OOS-Under Repair</fullName>
                <isActive>false</isActive>
                <label>OOS-Under Repair</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Stolen</fullName>
                <isActive>false</isActive>
                <label>Stolen</label>
            </value>
            <value>
                <fullName>Under Repair</fullName>
                <isActive>false</isActive>
                <label>Under Repair</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Salesforce_Punch_to_Kronos__c/Salesforce_Punch_to_Kronos__c.object-meta.xml
<CustomObject>
    <label>Salesforce Punch to Kronos</label>
    <nameField>
        <displayFormat>SPK-{0000000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Punch to Kronos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Punch_to_Kronos__c/fields/Employee_Clocked_Time_for_Kronos__c.field-meta.xml
<CustomField>
    <fullName>Employee_Clocked_Time_for_Kronos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Clocked Time for Kronos</label>
    <referenceTo>Employee_Clocked_Time_for_Kronos__c</referenceTo>
    <relationshipLabel>Salesforce Punch to Kronos</relationshipLabel>
    <relationshipName>Salesforce_Punch_to_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Salesforce_Punch_to_Kronos__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Salesforce Punch to Kronos</relationshipLabel>
    <relationshipName>Salesforce_Punch_to_Kronos</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Temporary__c.field-meta.xml
<CustomField>
    <fullName>Temporary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Temporary?</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Mobile Review</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fully Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <isActive>false</isActive>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
                <isActive>false</isActive>
                <label>Partially Invoiced</label>
            </value>
            <value>
                <fullName>Pro forma Review</fullName>
                <isActive>false</isActive>
                <label>Pro forma Review</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <isActive>false</isActive>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Received By Billing</fullName>
                <isActive>false</isActive>
                <label>Received By Billing</label>
            </value>
            <value>
                <fullName>Received By Dispatch</fullName>
                <isActive>false</isActive>
                <label>Received By Dispatch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Job_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_End_Time__c</fullName>
    <label>Job End Time</label>
    <type>Time</type>
</CustomField>

objects/TM_Line__c/fields/Job_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_Start_Time__c</fullName>
    <label>Job Start Time</label>
    <type>Time</type>
</CustomField>

objects/TM_Line__c/fields/KronosTimeEntriesProcessed__c.field-meta.xml
<CustomField>
    <fullName>KronosTimeEntriesProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>KronosTimeEntriesProcessed</label>
    <type>Checkbox</type>
</CustomField>

objects/TM_Line__c/fields/Lunch_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Lunch_Start_Time__c</fullName>
    <label>Lunch Start Time</label>
    <type>Time</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <formula>TM__r.Scheduled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Site_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Site_End_Time__c</fullName>
    <label>Site End Time</label>
    <type>Time</type>
</CustomField>

objects/TM_Line__c/fields/Site_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Site_Start_Time__c</fullName>
    <label>Site Start Time</label>
    <type>Time</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/KronosTimeClockBatchTest.cls
@IsTest
private class KronosTimeClockBatchTest {
    @IsTest
    static void testKronosTimeClockBatch() {
        NewTestData.createTestData();
        Test.startTest();
        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        //TM__c tm = [SELECT Id, Status__c, Scheduled_Date__c FROM TM__c WHERE Name = :NewTestData.TEST_TM_NAME_01 LIMIT 1];
        tm.Status__c = TMsService.CONFIRMED_STATUS;
        CompanyMgmt.byPassTrigger = true;
        CompanyMgmt.byPassLineTrigger = true;
        update tm;

        TM_Line__c tmLine = [SELECT Id, Resource__r.Employee_No__c, TM__c, Job_Start_Time__c, Job_End_Time__c, Category__c, Lunch_Start_Time__c, Lunch_End_Time__c,
                Site_Start_Time__c, Site_End_Time__c, Resource__c, Service_Center__c, Scheduled_Date__c, Service_Center__r.Temporary__c
        FROM TM_Line__c WHERE Category__c = 'Labor' AND TM__c = :tm.Id LIMIT 1];

        System.debug('Info: tmLine.Resource__r.Employee_No__c ' + tmLine.Resource__r.Employee_No__c);
        tmLine.Site_Start_Time__c = Time.newInstance(9,0,0,0);
        tmLine.Site_End_Time__c = Time.newInstance(15,0,0,0);
        tmLine.Lunch_Start_Time__c = Time.newInstance(12,0,0,0);
        tmLine.Lunch_End_Time__c = Time.newInstance(12,30,0,0);
        update tmLine;

        GenerateKronosTimeClockBatch kronosTimeClockBatch = new GenerateKronosTimeClockBatch();
        Database.executeBatch(kronosTimeClockBatch, 1);

        /*
        tmLine = [SELECT Id, KronosTimeEntriesProcessed__c FROM TM_Line__c WHERE Category__c = 'Labor' AND TM__c = :tm.Id LIMIT 1];
        System.assertEquals(true, tmLine.KronosTimeEntriesProcessed__c);

        List<Employee_Clocked_Time_for_Kronos__c> employeeClockedTimeForKronosLst = [SELECT Id FROM Employee_Clocked_Time_for_Kronos__c];
        Boolean employeeTimeClockEntriesCreated = false;
        if(employeeClockedTimeForKronosLst.size() > 0){
            employeeTimeClockEntriesCreated = true;
        }

        System.assertEquals(true, employeeTimeClockEntriesCreated);

        List<Salesforce_Punch_to_Kronos__c> salesforcePunchToKronos = [SELECT Id FROM Salesforce_Punch_to_Kronos__c];
        Boolean spkEntriesCreated = false;
        if(salesforcePunchToKronos.size() > 0){
            spkEntriesCreated = true;
        }
        System.assertEquals(true, spkEntriesCreated);
         */
        Test.stopTest();
    }
    
    @isTest
    static void testKronosTimeClockBatch2() {
        NewTestData.createTestData();
        Test.startTest();
        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
      
        //TM__c tm = [SELECT Id, Status__c, Scheduled_Date__c FROM TM__c WHERE Name = :NewTestData.TEST_TM_NAME_01 LIMIT 1];
        tm.Status__c = TMsService.SCHEDULED_STATUS;
        CompanyMgmt.byPassTrigger = true;
        CompanyMgmt.byPassLineTrigger = true;
        update tm;

        TM_Line__c tmLine = [SELECT Id, Resource__r.Employee_No__c, TM__c, Job_Start_Time__c, Job_End_Time__c, Category__c, Lunch_Start_Time__c, Lunch_End_Time__c,
                Site_Start_Time__c, Site_End_Time__c, Resource__c, Service_Center__c, Scheduled_Date__c, Service_Center__r.Temporary__c
        FROM TM_Line__c WHERE Category__c = 'Labor' AND TM__c = :tm.Id LIMIT 1];

        System.debug('Info: tmLine.Resource__r.Employee_No__c ' + tmLine.Resource__r.Employee_No__c);
        tmLine.Site_Start_Time__c = Time.newInstance(9,0,0,0);
        tmLine.Site_End_Time__c = Time.newInstance(15,0,0,0);
        tmLine.Lunch_Start_Time__c = Time.newInstance(12,0,0,0);
        tmLine.Lunch_End_Time__c = Time.newInstance(12,30,0,0);
        update tmLine;

        // List<Employee_Clocked_Time_for_Kronos__c> empClockedList = new List<Employee_Clocked_Time_for_Kronos__c>();
        Employee_Clocked_Time_for_Kronos__c emp = new Employee_Clocked_Time_for_Kronos__c();
        
        emp.Kronos_Action__c = 'Delete';
        emp.T_M_Line__c = tmLine.Id;
        emp.T_M__c = tm.Id;
        insert emp;

        Employee_Clocked_Time_for_Kronos__c emp2 = new Employee_Clocked_Time_for_Kronos__c();
    
        emp2.Kronos_Action__c = 'Delete';
        emp2.T_M_Line__c = tmLine.Id;
        emp2.T_M__c = tm.Id;
        insert emp2;

        GenerateKronosTimeClockBatch kronosTimeClockBatch = new GenerateKronosTimeClockBatch();
        Database.executeBatch(kronosTimeClockBatch, 1);


        Test.stopTest();
    }
}