objects/Integration_Setting__mdt/Integration_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

objects/Integration_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <label>Base URL</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Integration_Setting__mdt/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Coupa_Asset_Lookup_Id__c.field-meta.xml
<CustomField>
    <fullName>Coupa_Asset_Lookup_Id__c</fullName>
    <label>Coupa Asset Lookup Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Coupa_Sales_Order_Lookup_Id__c.field-meta.xml
<CustomField>
    <fullName>Coupa_Sales_Order_Lookup_Id__c</fullName>
    <label>Coupa Sales Order Lookup Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Integration_Setting__mdt/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/IntegrationSettingUtil.cls
public with sharing class IntegrationSettingUtil {
    //Ticket25259 - add Client_Id__c, Client_Secret__c, Scope__c, Grant_Type__c to query
    public static Integration_Setting__mdt coupaSetting {
        get{
            if(coupaSetting == null){
                coupaSetting = [
                        SELECT Id, Label, API_Key__c, Base_URL__c, Coupa_Sales_Order_Lookup_Id__c, Coupa_Asset_Lookup_Id__c, Enabled__c,
                                Client_Id__c, Client_Secret__c, Scope__c, Grant_Type__c
                        FROM Integration_Setting__mdt
                        WHERE Label = 'Coupa'
                        LIMIT 1];
            }
            return coupaSetting;
        }
        private set;
    }
}