objects/Operating_Expense__c/Operating_Expense__c.object-meta.xml
<CustomObject>
    <label>Operating Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operating Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Operating_Expense__c/fields/Operating_Expense_Cost_Pct__c.field-meta.xml
<CustomField>
    <fullName>Operating_Expense_Cost_Pct__c</fullName>
    <label>Operating Expense Cost %</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

classes/OperatingExpenseService.cls
public with sharing class OperatingExpenseService {

    public static Decimal getOperatingExpense(Id serviceCenterId, Date operationDate){
        Decimal operatingExpensePct = 0;
        Operating_Expense__c operatingExpense = OperatingExpensesSelector.newInstance().selectByServiceCenterIdAndEffectiveDate(serviceCenterId, operationDate);
        if(operatingExpense != null){
            operatingExpensePct = operatingExpense.Operating_Expense_Cost_Pct__c;
        }
        return operatingExpensePct;
    }

}