objects/Operating_Expense__c/Operating_Expense__c.object-meta.xml
<CustomObject>
    <label>Operating Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operating Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Operating_Expense__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Operating_Expense__c/fields/Operating_Expense_Cost_Pct__c.field-meta.xml
<CustomField>
    <fullName>Operating_Expense_Cost_Pct__c</fullName>
    <label>Operating Expense Cost %</label>
    <precision>18</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Operating_Expense__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Operating Expenses</relationshipLabel>
    <relationshipName>Operating_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OperatingExpensesSelector.cls
public with sharing class OperatingExpensesSelector extends fflib_SObjectSelector {

    public static OperatingExpensesSelector newInstance(){
        return (OperatingExpensesSelector) Application.Selector.newInstance(Operating_Expense__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType(){
        return Operating_Expense__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                Operating_Expense__c.Id,
                Operating_Expense__c.Name,
                Operating_Expense__c.Service_Center__c,
                Operating_Expense__c.Operating_Expense_Cost_Pct__c,
                Operating_Expense__c.Effective_Date__c
        };
    }

    public Operating_Expense__c selectByServiceCenterIdAndEffectiveDate(Id serviceCenterId, Date dateValue){
        List<Operating_Expense__c> operatingExpenses = System.Database.query(
                newQueryFactory(true)
                        .setCondition('Service_Center__c = :serviceCenterId AND Effective_Date__c <= :dateValue')
                        .setOrdering('Effective_Date__c', fflib_QueryFactory.SortOrder.DESCENDING).toSOQL()
        );

        if(operatingExpenses.size() > 0){
            return operatingExpenses[0];
        } else {
            return null;
        }
    }

}