objects/Off_Type__c/Off_Type__c.object-meta.xml
<CustomObject>
    <label>Off Type</label>
    <nameField>
        <label>Off Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Off Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Rule__c/Pay_Rule__c.object-meta.xml
<CustomObject>
    <label>Pay Rule</label>
    <nameField>
        <label>Pay Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pay Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Pay_Rule__c.field-meta.xml
<CustomField>
    <fullName>Pay_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Rule</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Pay_Rule__c.Type__c</field>
            <operation>equals</operation>
            <value>Union</value>
        </filterItems>
        <filterItems>
            <field>Pay_Rule__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pay_Rule__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/Resource_Off__c.object-meta.xml
<CustomObject>
    <label>Resource Off</label>
    <nameField>
        <displayFormat>Off-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Off__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

objects/Resource_Off__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Resource_Off__c/fields/Lunch_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Lunch_End_Time__c</fullName>
    <label>Lunch End Time</label>
    <type>Time</type>
</CustomField>

objects/Resource_Off__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Resource_Off__c/fields/Off_Type__c.field-meta.xml
<CustomField>
    <fullName>Off_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Off Type</label>
    <referenceTo>Off_Type__c</referenceTo>
    <relationshipLabel>Resource Offs</relationshipLabel>
    <relationshipName>Resource_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Pay_Rule__c.field-meta.xml
<CustomField>
    <fullName>Pay_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Rule</label>
    <referenceTo>Pay_Rule__c</referenceTo>
    <relationshipLabel>Resource Off</relationshipLabel>
    <relationshipName>Resource_Off</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/PTO_Type__c.field-meta.xml
<CustomField>
    <fullName>PTO_Type__c</fullName>
    <label>PTO Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PTO-Sick</fullName>
            </value>
            <value>
                <fullName>PTO-Vacation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Off__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Offs</relationshipLabel>
    <relationshipName>Resource_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Resource_Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Resource_Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resource Off (Resource Service Center)</relationshipLabel>
    <relationshipName>Resource_Off1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resource Off</relationshipLabel>
    <relationshipName>Resource_Off</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Shop_Time_Category__c.field-meta.xml
<CustomField>
    <fullName>Shop_Time_Category__c</fullName>
    <label>Shop Time Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shop_Time_Category</valueSetName>
    </valueSet>
</CustomField>

objects/Resource_Off__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Resource_Off__c/fields/Unavailable_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unavailable_Reason__c</fullName>
    <label>Unavailable Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discipline</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Call Out</fullName>
                <isActive>false</isActive>
                <label>Call Out</label>
            </value>
            <value>
                <fullName>DOT Reset</fullName>
                <isActive>false</isActive>
                <label>DOT Reset</label>
            </value>
            <value>
                <fullName>FMLA</fullName>
                <isActive>false</isActive>
                <label>FMLA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Shop_Time_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>Inside Decon</fullName>
    </customValue>
    <customValue>
        <fullName>Inside Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Light Duty</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Training _ACV-U</fullName>
        <label>Training - ACV-U</label>
    </customValue>
    <customValue>
        <fullName>Training_Customer</fullName>
        <label>Training - Customer</label>
    </customValue>
    <customValue>
        <fullName>Training - General</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
        <label>Training - New Hire</label>
    </customValue>
    <customValue>
        <fullName>Training_Refresher</fullName>
        <label>Training - Refresher</label>
    </customValue>
    <customValue>
        <fullName>Training - Tech to Driver Program</fullName>
        <label>*Training - Tech to Driver Program*</label>
    </customValue>
    <customValue>
        <fullName>Training_LMS</fullName>
        <isActive>false</isActive>
        <label>Training - LMS</label>
    </customValue>
    <customValue>
        <fullName>New hire</fullName>
        <isActive>false</isActive>
        <label>New hire</label>
    </customValue>
    <masterLabel>Shop Time Category</masterLabel>
</GlobalValueSet>

classes/ResourceOffsSelector.cls
public class ResourceOffsSelector extends fflib_SObjectSelector{

    public static ResourceOffsSelector newInstance(){
        return (ResourceOffsSelector) Application.Selector.newInstance(Resource_Off__c.SObjectType);
    }

    public SObjectType getSObjectType(){
        return Resource_Off__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList(){
        return new List<SObjectField>{
                Resource_Off__c.Id,
                Resource_Off__c.Name,
                Resource_Off__c.Date__c,
                Resource_Off__c.Resource__c,
                Resource_Off__c.Service_Center__c,
                Resource_Off__c.Resource_Service_Center__c,
                Resource_Off__c.Off_Type__c,
                Resource_Off__c.Pay_Rule__c,
                Resource_Off__c.Start_Time__c,
                Resource_Off__c.End_Time__c,
                Resource_Off__c.Lunch_Start_Time__c,
                Resource_Off__c.Lunch_End_Time__c,
                Resource_Off__c.Hours__c,
                Resource_Off__c.Total_Hours__c,
                Resource_Off__c.Description__c,
                Resource_Off__c.PTO_Type__c,
                Resource_Off__c.Shop_Time_Category__c,
                Resource_Off__c.Unavailable_Reason__c,
                Resource_Off__c.Note__c
        };
    }

    public List<Resource_Off__c> selectBorrowedResOffByDate(String workingSCName, Date workingDate){
        System.debug('Info: workingSC ' + workingSCName);
        System.debug('Info: workingDate ' + workingDate);
        return (List<Resource_Off__c>) Database.query(
                newQueryFactory(true).selectField('Resource__r.Name').
                        selectField('Off_Type__r.Name').
                        selectField('Service_Center__r.Name').
                        selectField('Resource_Service_Center__r.Name').
                        setCondition('Resource_Service_Center__r.Name != :workingSCName AND Resource_Service_Center__c != null AND ' +
                                'Service_Center__r.Name = :workingSCName AND Service_Center__c != null AND Date__c = :workingDate').toSOQL()
        );
    }
}