objects/Job_Task_Template_Line__c/Job_Task_Template_Line__c.object-meta.xml
<CustomObject>
    <label>Job Task Template Line</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Task Template Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>Sales_Order_Job_Task__c.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order_Job_Task__c/Sales_Order_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Order Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Order_Job_Task__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Job Tasks</relationshipLabel>
    <relationshipName>Sales_Order_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

classes/ISalesOrdersService.cls
public interface ISalesOrdersService {
    //job task <<
    //void calcEstimatedDateInfo(Sales_Order__c theSO, List<Sales_Line__c> theSLList, Integer duration);
    void calcEstimatedDateInfo(Sales_Order__c salesOrder, List<ACVSalesOrderJobTaskWrapper> jobTaskWrappers, Integer duration);
    //job task >>
    void updateSalesLinesForBillAsLumpSumAllAction(List<Sales_Line__c> theSLList);
    Sales_Order__c createNewSalesQuoteOrSalesOrder(String documentType, Id billToCustomerId, String serviceCenter, String contract, String quote);
    void updateSalesOrderBillingAndTax(Sales_Order__c theSO, Boolean isNewSO);
    //job task <<
    //String cloneSalesOrder(Set<Id> salesOrderIds, String documentType, String serviceCenter, String billToCustomer, Id billToParentId);
    String cloneSalesOrder(Set<Id> salesOrderIds, String documentType, String serviceCenter, String billToCustomer, Id billToParentId, String jobDescription, String poNumber);
    //job task >>
    String convertQuoteToOrder(Set<Id> salesOrderIds);
    void setSurchargePct(Sales_Order__c salesOrder);

    //ticket 19672 <<
    //void addRemoveSurchargeLine(Sales_Order__c salesOrder, List<Sales_Line__c> salesLines);
    //void addRemoveManifestFeeLines(Sales_Order__c salesOrder, List<Sales_Line__c> salesLines); //Ticket#15225
    //ticket 19672 >>

    //void createManifestFeeLines(Sales_Order__c salesOrder, List<Sales_Line__c> salesLines); //Ticket#15225
    //deprecated <<
    //void prepareManifestFeeLines(Sales_Order__c salesOrder, List<Sales_Line__c> salesLines, List<Sales_Line__c> wasteDisposalLines, Integer currentLineNo);
    //deprecated >>
    void updateSQWhenNewSOCreated(Id salesQuoteId);

    //aura <<
    //Decimal calcSurchargeAmount(Sales_Order__c salesOrder, List<Sales_Line__c> salesLines);

    //ticket 19672 <<
    //void calcSurchargeAmount(Sales_Order__c salesOrder, List<Sales_Line__c> salesLines);
    void calcSurchargeAmount(Sales_Order__c salesOrder, List<Sales_Order_Job_Task__c> jobTasks, List<Sales_Line__c> salesLines);
    void calcJobTaskAmountFields(Sales_Order__c salesOrder, Sales_Order_Job_Task__c jobTask, List<Sales_Line__c> salesLines, Decimal taxPct);
    //ticket 19672 >>

    void updateTMAndSISuperUserChangeBTC(Sales_Order__c theSO);
    Integer updateTMPriceFromSO(Sales_Order__c theSO, List<TM__c> tms);
    //aura >>

    //job task <<
    void createSalesLinesFromJobTaskTemplateLines(Sales_Order__c salesOrder, ACVSalesOrderJobTaskWrapper jobTaskWrapper, Integer nextSalesLineNo, List<Job_Task_Template_Line__c> jobTaskTemplateLines);
    void cloneJobTask(Sales_Order__c salesOrder, ACVSalesOrderJobTaskWrapper fromJobTaskWrapper, ACVSalesOrderJobTaskWrapper newJobTaskWrapper, Integer nextSalesLineNo);
    //job task >>
}