objects/Job_Task_Template_Line__c/Job_Task_Template_Line__c.object-meta.xml
<CustomObject>
    <label>Job Task Template Line</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Task Template Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Template_Line__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <label>Job Task Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>Job Task Template Lines</relationshipLabel>
    <relationshipName>Job_Task_Template_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Job_Task_Template_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Job Task Template Lines</relationshipLabel>
    <relationshipName>Job_Task_Template_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signer_Role__c.field-meta.xml
<CustomField>
    <fullName>Signer_Role__c</fullName>
    <label>Signer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Customer A</fullName>
            </value>
            <value>
                <fullName>Customer B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Request_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Email Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Site_Access__c.field-meta.xml
<CustomField>
    <fullName>Site_Access__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Access</label>
    <referenceTo>Site_Access__c</referenceTo>
    <relationshipLabel>Signature Requests</relationshipLabel>
    <relationshipName>Signature_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Site_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Site_Email_Address__c</fullName>
    <label>Site Email Address</label>
    <type>Email</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>TM__r.Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Service_Rating__c/TM_Service_Rating__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Service Rating</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Service Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Service_Rating__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Service Rating</relationshipLabel>
    <relationshipName>TM_Service_Rating</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/Mobile_TMControllerTest.cls
@IsTest
private class Mobile_TMControllerTest {

    @IsTest
    private static void test() {
        NewTestData.createTestData();
        Test.startTest();
        Sales_Order__c salesOrder = NewTestData.mapSalesOrdersByName.get(NewTestData.TEST_SO_NAME_01);
        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        TM_Line__c tmLine = NewTestData.mapTMLinesByTMIdByCategory.get(tm.Id).get(ResourceService.LABOR_CATEGORY);
        MobileTMController.getSalesOrder(tm.Sales_Order__c);
        String tmJobTaskWrapper = MobileTMController.getJobTaskWrappers(tm.Id);
        MobileTMController.validateResourceType(JSON.serialize(tmLine));
        MobileTMController.getVersion();
        //List<Job_Task_Template_Line__c> jobTaskTemplateLines = NewTestData.mapJobTaskTemplateWrappersByName.get(NewTestData.JOB_TEMPLATE_NAME).JobTaskTemplateLines;
        Job_Task_Template__c jobTaskTemplate = NewTestData.mapJobTaskTemplateWrappersByName.get(NewTestData.JOB_TEMPLATE_NAME).JobTaskTemplate;
        MobileTMController.getJobTaskTemplateQuestionLines(jobTaskTemplate.Id);
        /*
        tm = MobileTMController.GetData(tm.Id);
        tm = MobileTMController.GetTMDetail(tm.Id);
        Resource__c resource = MobileTMController.GetResource(sc.Id, resourceType.Id, equipment.Name);
        
        List<TM_Line__c> tmls = TMLinesSelector.newInstance().selectByTmId(new Set<Id>{tm.Id}, null);
        
        //Mobile_TMController.validateResourceType(JSON.serialize(tmls[0]));

        MobileTMController.GetTermsAndConditions(tm.Sales_Order__c);

        MobileTMController.SaveTM(JSON.serialize(tm));

        tm.Site_Email_Address__c = 'kchen@micro-datanet.com';        
        tm.Customer_Not_Available__c = true;
        update tm;
        
        //signature request <<
        //Signature__c sig = new Signature__c(Related_To_Object_Name__c = 'TM__c', Related_To_Id__c = tm.Id, Name = 'customer_signature', Customer_Not_Available__c = true);
        //insert sig;          
        
        List<Site_Access__c> accesses = new List<Site_Access__c>();
        accesses.add(SiteAccessController.createSiteAccess(tm.Id, 'TMSignature', Datetime.now().addHours(48)));
        accesses.add(SiteAccessController.createSiteAccess(tm.Id, 'TMSignature', Datetime.now().addHours(48)));
        
        List<Signature_Request__c> requests = new List<Signature_Request__c>();
        requests.add(new Signature_Request__c(Print_Name__c = 'Customer A', Email__c = 'kchen@micro-datanet.com', Request_Email_Sent__c = true, Request_Date__c = Datetime.now(), Site_Access__c = accesses[0].Id));
        requests.add(new Signature_Request__c(Print_Name__c = 'Customer B', Email__c = 'kchen@micro-datanet.com', Request_Email_Sent__c = true, Request_Date__c = Datetime.now(), Site_Access__c = accesses[1].Id));        
        insert requests;
              
        List<Signature__c> signatures = new List<Signature__c>();
        signatures.add(new Signature__c(TM__c = tm.Id, Name = 'supervisor_signature', Signer_Role__c = 'Supervisor', Print_Name__c = 'Kevin', Email__c = 'kchen@micro-datanet.com'));
        signatures.add(new Signature__c(TM__c = tm.Id, Name = 'customer_signature', Signer_Role__c = 'Customer A', Customer_Not_Available__c = true, Request_Signature__C = true, Print_Name__c = 'Customer A', Email__c = 'kchen@micro-datanet.com', Signature_Request__c = requests[0].Id));
        signatures.add(new Signature__c(TM__c = tm.Id, Name = 'customer_signature', Signer_Role__c = 'Customer B', Customer_Not_Available__c = true, Request_Signature__C = true, Print_Name__c = 'Customer B', Email__c = 'kchen@micro-datanet.com', Signature_Request__c = requests[1].Id));
        insert signatures;
        //signature request >>


        MobileTMController.processPdf(tm.Id);
        
        
        //signature request <<        
        List<Attachment> attachments = new List<Attachment>();
        attachments.add(new Attachment(ParentId = signatures[1].Id, Name = tm.Name + '.pdf', body = Blob.valueOf('test')));
        attachments.add(new Attachment(ParentId = signatures[2].Id, Name = tm.Name + '.pdf', body = Blob.valueOf('test')));
        insert attachments;
        
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(tm);
        SignatureRequestController controller = new SignatureRequestController(standardController );
        controller.sendSignatureRequestEmail();
        
        
        SignatureRequestController.processEmailAsync(tm.Id);
        
        for (Signature_Request__c request : requests) {
            request.Signed__c = true;
            request.Signature_Date__c = Datetime.now();
        }
        update requests;
        attachments = new List<Attachment>();
        attachments.add(new Attachment(ParentId = requests[0].Id, Name = tm.Name + '_signature_request.pdf', body = Blob.valueOf('test')));
        attachments.add(new Attachment(ParentId = requests[1].Id, Name = tm.Name + '_signature_request.pdf', body = Blob.valueOf('test')));
        insert attachments;
        SignatureRequestController.processSignature(tm);
        
        for (Integer i = 1; i < signatures.size(); i++) {
            signatures[i].Signed__c = true;
        }
        update signatures;
        MobileTMController.processPdf(tm.Id);
        //signature request <<        
        
        
        CompanyMgmt.ByPassTrigger = true;
        tm.Status__c = 'Mobile Review';
        update tm;
        MobileTMController.ChangeToScheduled(tm.Id);
        
        tmls[0].Job_Start_Time__c = null; //set null to avoid time deserialization error. salesforce deserialization bug
        tmls[0].Job_End_Time__c = null;
        String data = JSON.serialize(tmls);
        MobileTMController.saveTMLines(data);

        MobileTMController.DeleteTMLine(equipmentLine.Id);
         */
        Test.stopTest();
    }

    @IsTest
    private static void testServiceRating(){
        NewTestData.createTestData();
        Test.startTest();
        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        List<TM_Service_Rating__c> tmServiceRatings = new List<TM_Service_Rating__c>();
        TM_Service_Rating__c tmServiceRating = new TM_Service_Rating__c();
        tmServiceRating.TM__c = tm.Id;
        tmServiceRating.Customer_Review__c = 'ASDFASDFASDF';
        tmServiceRating.Customer_Name__c = 'Test Name';
        tmServiceRating.Customer_Email__c = 'test@test.com';
        tmServiceRating.Rating__c = 1;
        tmServiceRatings.add(tmServiceRating);
        insert tmServiceRatings;

        String jsonServiceRating = MobileTMController.getServiceRating(tm.Id);
        MobileTMController.saveServiceRating(jsonServiceRating);

        Test.stopTest();
    }
  
}