objects/Equipment_Type__c/Equipment_Type__c.object-meta.xml
<CustomObject>
    <label>Equipment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Division__c/PD_Division__c.object-meta.xml
<CustomObject>
    <label>PD Division</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Division__c/fields/Division_Number__c.field-meta.xml
<CustomField>
    <fullName>Division_Number__c</fullName>
    <label>Division Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/PD_Equipment_Code__c/PD_Equipment_Code__c.object-meta.xml
<CustomObject>
    <label>PD Equipment Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD Equipment Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Equipment_Code__c/fields/Equip_Group__c.field-meta.xml
<CustomField>
    <fullName>Equip_Group__c</fullName>
    <label>Equip Group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/PD_Equipment_Code__c/fields/Nav_Equip_Code__c.field-meta.xml
<CustomField>
    <fullName>Nav_Equip_Code__c</fullName>
    <label>Nav Equip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PD_EZ_Pass_Code__c/PD_EZ_Pass_Code__c.object-meta.xml
<CustomObject>
    <label>PD EZ Pass Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD EZ Pass Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Resource_Type__c/PD_Resource_Type__c.object-meta.xml
<CustomObject>
    <label>PD Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Resource_Type__c/fields/Resource_Description__c.field-meta.xml
<CustomField>
    <fullName>Resource_Description__c</fullName>
    <label>Resource Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PD_Roll_Off_Box__c/PD_Roll_Off_Box__c.object-meta.xml
<CustomObject>
    <label>PD Roll Off Box</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD Roll Off Boxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Roll_Off_Box__c/fields/Division_Number__c.field-meta.xml
<CustomField>
    <fullName>Division_Number__c</fullName>
    <label>Division Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PD_Roll_Off_Box__c/fields/Equipment_type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_type__c</fullName>
    <label>Equipment type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PD_State_Permit__c/PD_State_Permit__c.object-meta.xml
<CustomObject>
    <label>PD State Permit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD State Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_State_Permit__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <label>Agency</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/PD_Vehicle_Information__c/PD_Vehicle_Information__c.object-meta.xml
<CustomObject>
    <label>PD Vehicle Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PD Vehicle Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PD_Vehicle_Information__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/PD_Vehicle_Information__c/fields/GL_Prefix__c.field-meta.xml
<CustomField>
    <fullName>GL_Prefix__c</fullName>
    <label>GL_Prefix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/PD_Vehicle_Information__c/fields/NAV_Equip_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>NAV_Equip_Type_Code__c</fullName>
    <label>NAV Equip Type Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/PD_Vehicle_Information__c/fields/resource_type__c.field-meta.xml
<CustomField>
    <fullName>resource_type__c</fullName>
    <label>resource_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PermitDatabaseTest.cls
@isTest
private class PermitDatabaseTest {
    
    private static testMethod void test() {
        PD_Vehicle_Information__c vehicle = new PD_Vehicle_Information__c();
        PD_Division__c division = new PD_Division__c();
        PD_Equipment_Code__c equipGroup = new PD_Equipment_Code__c();
        PD_EZ_Pass_Code__c ezPassCode = new PD_EZ_Pass_Code__c();
        PD_Resource_Type__c resourceType = new PD_Resource_Type__c();
        PD_Roll_Off_Box__c rollOffBox = new PD_Roll_Off_Box__c();
        PD_State_Permit__c permit = new PD_State_Permit__c();
        
        insert new Resource_Type__c(Name = 'Rolloff Container');
        
        division.Division_Number__c = '02';
        insert division;
        

        equipGroup.Equip_Group__c = 'TRUCK';
        equipGroup.Name = 'Heavy Truck';
        equipGroup.Nav_Equip_Code__c = 'TRUCK';
        insert equipGroup;
        
        resourceType.Name = 'Heavy Truck (>5000)';
        resourceType.Resource_Description__c = 'Heavy Truck (>5000)';
        insert resourceType;
        
        rollOffBox.Division_Number__c = '02';
        rollOffBox.Equipment_Type__c = 'Heavy Truck';
        rollOffBox.Name = 'Container 1';
        insert rollOffBox;
        
        vehicle.Name = 'Heavy Truck';
        vehicle.GL_Prefix__c = '02';
        vehicle.NAV_Equip_Type_Code__c = 'TRUCK';
        vehicle.resource_type__c = 'Heavy Truck';
        insert vehicle;
        
        
        permit.Name = 'NY';
        permit.Agency__c = 'NYC';
        insert permit;
        
        PermitDatabase.matchDivisions();
        PermitDatabase.matchEquipmentGroups();
        PermitDatabase.matchResourceTypes();
        PermitDatabase.createEquipmentTypes();
        PermitDatabase.matchRollOffBoxes();
        PermitDatabase.matchVehicles();
        PermitDatabase.createResourcesFromRollOffBoxes();
        PermitDatabase.createResourcesFromVehicles();
        PermitDatabase.createStatePermits();
    }

}