objects/Sales_Invoice_Job_Task__c/Sales_Invoice_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Invoice__c</field>
            <operation>equals</operation>
            <valueField>Sales_Invoice_Job_Task__c.Sales_Invoice__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ACVSalesInvoiceJobTaskWrapper.cls
global with sharing class ACVSalesInvoiceJobTaskWrapper {
    @AuraEnabled
    public Sales_Invoice_Job_Task__c JobTask { get; set; }

    @AuraEnabled
    public List<Sales_Invoice_Line__c> SalesInvoiceLines { set; get; }

    @AuraEnabled
    public Boolean Collapsed { set; get; }

    public ACVSalesInvoiceJobTaskWrapper() {
        this.JobTask = new Sales_Invoice_Job_Task__c();
        this.SalesInvoiceLines = new List<Sales_Invoice_Line__c>();
    }

    public ACVSalesInvoiceJobTaskWrapper(Sales_Invoice_Job_Task__c jobTask, List<Sales_Invoice_Line__c> invoiceLines) {
        this.JobTask = jobTask;
        this.SalesInvoiceLines = invoiceLines;
    }
}