objects/Portal_Login__c/Portal_Login__c.object-meta.xml
<CustomObject>
    <label>Portal Login</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Portal_Login__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portal Logins</relationshipLabel>
    <relationshipName>Portal_Logins</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Portal_Login__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal Logins</relationshipLabel>
    <relationshipName>Portal_Logins</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Portal_Login__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

objects/Portal_Login__c/fields/Last_Login_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Login_Date__c</fullName>
    <label>Last Login Date</label>
    <type>DateTime</type>
</CustomField>

objects/Portal_Login__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

objects/Portal_Login__c/fields/Session_Expires__c.field-meta.xml
<CustomField>
    <fullName>Session_Expires__c</fullName>
    <label>Session Expires</label>
    <type>DateTime</type>
</CustomField>

objects/Portal_Login__c/fields/Session_Token__c.field-meta.xml
<CustomField>
    <fullName>Session_Token__c</fullName>
    <label>Session Token</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Portal_Login__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Staging_Account__c/Staging_Account__c.object-meta.xml
<CustomObject>
    <label>Staging Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staging_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Salesforce Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Staging Accounts</relationshipLabel>
    <relationshipName>Staging_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Staging_Contact__c/Staging_Contact__c.object-meta.xml
<CustomObject>
    <label>Staging Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staging_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Staging Contacts</relationshipLabel>
    <relationshipName>Staging_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Staging_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Salesforce Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staging Contacts</relationshipLabel>
    <relationshipName>Staging_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/CustomerPortalController.cls
public without sharing class CustomerPortalController {
    /*
    private ApexPages.StandardSetController setController;
    
    public CustomerPortalController(ApexPages.StandardSetController controller) {
        this.setController = controller;
    }
    
    
    public PageReference SendAccountUpdateRequestEmails() {
        try {
            StagingAccountUpdateRequestEmailBatch batch = new StagingAccountUpdateRequestEmailBatch ();
            batch.EmailAddress = userInfo.getUserEmail();
            Database.executeBatch(batch, 100);
            return new ApexPages.Action('{!List}').invoke();
        }
        catch(exception ex) {
            ApexPages.addMessages(ex);
            return null;
        }
    }
  */  
    
    @AuraEnabled
    public static LoginInfo checkSession(String session) {
        try {
            List<Portal_Login__c> portalLogins = [SELECT Id, Name, Account__c, Account__r.Name, Contact__c, Password__c, Disabled__c, Expiration_Date__c, Session_Token__c, Session_Expires__c FROM Portal_Login__c WHERE Session_Token__c != null AND Session_Token__c = :session];
            if (portalLogins.size() == 0) {
                throw new AuraException('INVALID_SESSION');
            }
            
            if (portalLogins[0].Session_Expires__c < system.now()) {
                throw new AuraException('EXPIRED_SESSION');
            }
            
            if (portalLogins[0].Disabled__c == true) {
                throw new AuraException('DISABLED_LOGIN');
            }
            
            if (portalLogins[0].Expiration_Date__c != null && portalLogins[0].Expiration_Date__c < system.today()) {
                throw new AuraException('EXPIRED_LOGIN');
            }
            
            LoginInfo loginInfo = new LoginInfo();
            loginInfo.PortalLogin = portalLogins[0];      
            loginInfo.PortalLogin.Session_Expires__c = system.now().addHours(1); //refresh hours to expire
            update loginInfo.PortalLogin;

            Staging_Account__c sa = StagingAccountController.getRecord(null, loginInfo.PortalLogin.Account__c);
            if (sa != null) {
                loginInfo.StagingAccountId = sa.Id;
            }

            Staging_Contact__c sc = StagingContactController.getRecord(null, loginInfo.PortalLogin.Contact__c);
            if (sc != null) {
                loginInfo.StagingContactId = sc.Id;
            }
            loginInfo.Authorized = true;
            
            return loginInfo;
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static LoginInfo login(String username, String password) {
        try {
            List<Portal_Login__c> portalLogins = [SELECT Id, Name, Account__c, Account__r.Name, Contact__c, Password__c, Disabled__c, Expiration_Date__c, Session_Token__c, Session_Expires__c FROM Portal_Login__c WHERE Username__c = :username];
            if (portalLogins.size() == 0) {
                throw new AuraException('INVALID_CREDENTIAL');
            }
            
            if (!portalLogins[0].Password__c.equals(password)) {
                throw new AuraException('INVALID_CREDENTIAL');
            }
            
            if (portalLogins[0].Disabled__c == true) {
                throw new AuraException('DISABLED_LOGIN');
            }
            
            if (portalLogins[0].Expiration_Date__c != null && portalLogins[0].Expiration_Date__c < system.today()) {
                throw new AuraException('EXPIRED_LOGIN');
            }
            
            LoginInfo loginInfo = new LoginInfo();
            loginInfo.PortalLogin = portalLogins[0];
            
            String session = generateRandomString(20);
            while ([SELECT Id FROM Portal_Login__c WHERE Session_Token__c = :session FOR UPDATE].size() > 0) {
                session = generateRandomString(20);
            }
            loginInfo.PortalLogin.Session_Token__c = session;            
            loginInfo.PortalLogin.Session_Expires__c = system.now().addHours(1); //1 hours to expire
            loginInfo.PortalLogin.Last_Login_Date__c= system.now();
            update loginInfo.PortalLogin;

            Staging_Account__c sa = StagingAccountController.getRecord(null, loginInfo.PortalLogin.Account__c);
            if (sa != null) {
                loginInfo.StagingAccountId = sa.Id;
            }

            Staging_Contact__c sc = StagingContactController.getRecord(null, loginInfo.PortalLogin.Contact__c);
            if (sc != null) {
                loginInfo.StagingContactId = sc.Id;
            }
            loginInfo.Authorized = true;
            
            return loginInfo;
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
           Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }

    public class LoginInfo {
        @AuraEnabled
        public Portal_Login__c PortalLogin { set; get; }
        
        @AuraEnabled
        public Id StagingAccountId { set; get; }
        
        @AuraEnabled
        public Id StagingContactId { set; get; }
        
        @AuraEnabled
        public Boolean Authorized { set; get; }
        
    }

}