objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Declined__c.field-meta.xml
<CustomField>
    <fullName>Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Declined</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/IP_Address__c.field-meta.xml
<CustomField>
    <fullName>IP_Address__c</fullName>
    <label>IP Address</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/PDF_Email_Pending__c.field-meta.xml
<CustomField>
    <fullName>PDF_Email_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PDF Email Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Pending__c.field-meta.xml
<CustomField>
    <fullName>Signature_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Site_Access__c.field-meta.xml
<CustomField>
    <fullName>Site_Access__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Access</label>
    <referenceTo>Site_Access__c</referenceTo>
    <relationshipLabel>Signature Requests</relationshipLabel>
    <relationshipName>Signature_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/fields/Site_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Site_Access_Token__c</fullName>
    <formula>Site_Access__r.Token__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Access Token</label>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

objects/Site_Access__c/Site_Access__c.object-meta.xml
<CustomObject>
    <label>Site Access</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Accesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site_Access__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

classes/TMSiteController.cls
public without sharing class TMSiteController {
    @AuraEnabled
    public static String getSignature(String token) {
        try {
            Site_Access__c siteAccess = SiteAccessController.getSiteAccess('TMSignature', token);
            if (siteAccess == null) {
                throw new DataException('You don\'t have access to this page or your token has expired. Please contact Republic Services customer service for assistance.');
            }

            //ticket 21770 <<
            //List<Signature_Request__c> signatureRequests = [SELECT Id, Print_Name__c, Email__c, Accept_Terms_and_Conditions__c, Signed__c, Signature_Date__c, Site_Access_Token__c FROM Signature_Request__c WHERE Site_Access__r.Token__c = :token];
            //ticket 21113 <<
            //List<Signature_Request__c> signatureRequests = [SELECT Id, Print_Name__c, Email__c, Accept_Terms_and_Conditions__c, Terms_and_Conditions__c, Signed__c, Signature_Date__c, Site_Access_Token__c FROM Signature_Request__c WHERE Site_Access__r.Token__c = :token];
            List<Signature_Request__c> signatureRequests = [SELECT Id, Related_To_Object_Name__c, Related_To_Id__c, Print_Name__c, Email__c, Accept_Terms_and_Conditions__c, Terms_and_Conditions__c, Signed__c, Signature_Date__c, Site_Access_Token__c, Declined__c, Customer_PO_No__c, Customer_Comment__c FROM Signature_Request__c WHERE Site_Access__r.Token__c = :token AND Voided__c != TRUE];
            //ticket 21113 >>
            //ticket 21770 >> 

            if (signatureRequests.size() > 0) {
                Signature_Request__c signatureRequest = signatureRequests[0];
                SignatureWrapper signatureWrapper = new SignatureWrapper();
                signatureWrapper.AcceptTerms = signatureRequest.Accept_Terms_and_Conditions__c;
                signatureWrapper.PrintName = signatureRequest.Print_Name__c;
                signatureWrapper.Email = signatureRequest.Email__c;
                signatureWrapper.SiteAccessToken = signatureRequest.Site_Access_Token__c;
                signatureWrapper.Signed = signatureRequest.Signed__c;
                signatureWrapper.SignatureDate = signatureRequest.Signature_Date__c;

                //ticket 21113 <<
                signatureWrapper.RelatedToId = signatureRequest.Related_To_Id__c;
                signatureWrapper.RelatedToObjectName = signatureRequest.Related_To_Object_Name__c;
                signatureWrapper.Declined = signatureRequest.Declined__c;
                signatureWrapper.CustomerPONo = signatureRequest.Customer_PO_No__c;
                signatureWrapper.CustomerComment = signatureRequest.Customer_Comment__c;
                //ticket 21113 >>

                //ticket 21770 <<
                if (signatureRequests[0].Terms_and_Conditions__c != null) {
                    signatureWrapper.TermsAndConditions = signatureRequests[0].Terms_and_Conditions__c;
                }
                //ticket 21770 >>
                List<Attachment> attachments = [SELECT Id, Name, ParentId, Body FROM Attachment WHERE ParentId = :signatureRequest.Id];
                if (attachments.size() > 0) {
                    signatureWrapper.SignatureData = EncodingUtil.base64Encode(attachments[0].Body);
                }

                return JSON.serialize(signatureWrapper);
            }
            else {
                //ticket 21113 <<
                //throw new DataException('System is unable to locate the request record for you. Please contact Republic Services customer service for assistance.');
                throw new DataException('The signature request is no longer valid. Please contact Republic Services customer service for assistance.');
                //ticket 21113 >>
            }
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String saveSignature(String JSONSignatureWrapper) {
        Savepoint sp = Database.setSavepoint();
        try {
            SignatureWrapper signatureWrapper = (SignatureWrapper)JSON.deserialize(JSONSignatureWrapper, SignatureWrapper.Class);

            List<Signature_Request__c> signatureRequests = [SELECT Id FROM Signature_Request__c WHERE Site_Access_Token__c = :signatureWrapper.SiteAccessToken];

            if (signatureRequests.size() > 0) {
                Signature_Request__c signatureRequest = signatureRequests[0];
                signatureRequest.Signature_Date__c = Datetime.now();

                //ticket 21113 <<
                //signatureRequest.Signed__c = true;
                signatureRequest.Declined__c = signatureWrapper.Declined;
                signatureRequest.Customer_PO_No__c = signatureWrapper.CustomerPONo;
                signatureRequest.Customer_Comment__c = signatureWrapper.CustomerComment;
                if (signatureWrapper.Declined == true) {
                    signatureWrapper.Signed = false;
                }
                else {
                    signatureWrapper.Signed = true;
                }
                signatureRequest.Signed__c = signatureWrapper.Signed;
                //ticket 21113 >>

                //additional signature request changes <<
                signatureRequest.Signature_Pending__c = true;
                signatureRequest.PDF_Email_Pending__c = true;
                //additional signature request changes >>
                signatureRequest.Accept_Terms_and_Conditions__c = signatureWrapper.AcceptTerms;
                signatureRequest.Print_Name__c = signatureWrapper.PrintName;
                signatureRequest.Email__c = signatureWrapper.Email;
                signatureRequest.IP_Address__c = signatureWrapper.IPAddress;
                update signatureRequest;

                if (signatureWrapper.SignatureData != null) {
                    Attachment attachment;
                    List<Attachment> attachments = [SELECT Id FROM Attachment WHERE ParentId = :signatureRequest.Id LIMIT 1];
                    if (attachments.size() > 0) {
                        attachment = attachments[0];
                    } else {
                        attachment = new Attachment();
                        attachment.ParentId = signatureRequest.Id;
                    }
                    attachment.Body = EncodingUtil.base64Decode(signatureWrapper.SignatureData);
                    attachment.ContentType = 'image/png';
                    attachment.Name = 'customer signature';
                    attachment.IsPrivate = false;
                    upsert attachment;
                }
            }
            return getSignature(signatureWrapper.SiteAccessToken);
        }
        catch(exception ex) {
            Database.rollback(sp);
            throw new AuraHandledException(ex.getMessage());
        }
    }
}