objects/ContentVersion/fields/Type_fileupload__c.field-meta.xml
<CustomField>
    <fullName>Type_fileupload__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifest_BOL</fullName>
            </value>
            <value>
                <fullName>Weight Ticket</fullName>
            </value>
            <value>
                <fullName>EH&amp;S</fullName>
            </value>
            <value>
                <fullName>Site Photo</fullName>
            </value>
            <value>
                <fullName>Customer Specific Doc</fullName>
            </value>
            <value>
                <fullName>Receipt</fullName>
            </value>
            <value>
                <fullName>Delivery Ticket</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Job_Task_Template__c/Job_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Job Task Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signer_Role__c.field-meta.xml
<CustomField>
    <fullName>Signer_Role__c</fullName>
    <label>Signer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Customer A</fullName>
            </value>
            <value>
                <fullName>Customer B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Request_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Email Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Site_Access__c.field-meta.xml
<CustomField>
    <fullName>Site_Access__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Access</label>
    <referenceTo>Site_Access__c</referenceTo>
    <relationshipLabel>Signature Requests</relationshipLabel>
    <relationshipName>Signature_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Site_Access__c/Site_Access__c.object-meta.xml
<CustomObject>
    <label>Site Access</label>
    <nameField>
        <displayFormat>SA-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Accesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Site_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Site_Email_Address__c</fullName>
    <label>Site Email Address</label>
    <type>Email</type>
</CustomField>

objects/TM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Mobile Review</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fully Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <isActive>false</isActive>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
                <isActive>false</isActive>
                <label>Partially Invoiced</label>
            </value>
            <value>
                <fullName>Pro forma Review</fullName>
                <isActive>false</isActive>
                <label>Pro forma Review</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <isActive>false</isActive>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Received By Billing</fullName>
                <isActive>false</isActive>
                <label>Received By Billing</label>
            </value>
            <value>
                <fullName>Received By Dispatch</fullName>
                <isActive>false</isActive>
                <label>Received By Dispatch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TM__c/recordTypes/Scheduled.recordType-meta.xml
<RecordType>
    <fullName>Scheduled</fullName>
    <active>true</active>
    <label>Scheduled</label>
    
    
</RecordType>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Linked_Line__c.field-meta.xml
<CustomField>
    <fullName>Linked_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Line</label>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>T&amp;M Lines (Linked Line)</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>TM__r.Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Service_Rating__c/TM_Service_Rating__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Service Rating</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Service Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Service_Rating__c/fields/Customer_Review__c.field-meta.xml
<CustomField>
    <fullName>Customer_Review__c</fullName>
    <label>Customer Review</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/TM_Service_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Service_Rating__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Service Rating</relationshipLabel>
    <relationshipName>TM_Service_Rating</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/MobileTMControllerTest.cls
@IsTest
private class MobileTMControllerTest {

    private static testMethod void test() {
        NewTestData.createTestData();

        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        tm.Status__c = 'Scheduled';
        CompanyMgmt.byPassTrigger = true;
        update tm;

        test.startTest();

        CompanySettingUtil.acvSetting.Mobile_TM_Version_No__c = '1.0';

        String JSONSalesOrder = MobileTMController.getSalesOrder(tm.Sales_Order__c);
        String JSONTMs = MobileTMController.getTMs('', System.today(), 'TM', '1.0');

        String JSONTM = MobileTMController.getTM(tm.Id);

        String JSONJobTaskWrappers = MobileTMController.getJobTaskWrappers(tm.Id);

        String JSONTMLines = MobileTMController.getTMLines(tm.Id, 'Labor');

        //ticket 19130 <<
        MobileTMController.getJobTaskTemplateQuestionLines([SELECT Id FROM Job_Task_Template__c LIMIT 1][0].Id);
        List<ACVTMJobTaskWrapper> jobTaskWrappersLabor = (List<ACVTMJobTaskWrapper>)JSON.deserialize(JSONTMLines, List<ACVTMJobTaskWrapper>.class);
        List<ACVTMJobTaskWrapper> jobTaskWrappersEquipment = (List<ACVTMJobTaskWrapper>)JSON.deserialize(MobileTMController.getTMLines(tm.Id, 'Equipment'), List<ACVTMJobTaskWrapper>.class);

        TM_Line__c laborLine = jobTaskWrappersLabor[0].TMLines[0];
        TM_Line__c equipmentLine = jobTaskWrappersEquipment[0].TMLines[0];
        equipmentLine.Linked_Line__c = laborLine.Id;
        update equipmentLine;
        //ticket 19130 >>


        List<ACVTMJobTaskWrapper> jobTaskWrappers = (List<ACVTMJobTaskWrapper>)JSON.deserialize(JSONJobTaskWrappers, List<ACVTMJobTaskWrapper>.class);
        if (jobTaskWrappers.size() > 0) {
            if (jobTaskWrappers[0].TMLines.size() > 0) {
                TM_Line__c tmLine = jobTaskWrappers[0].TMLines[0];
                MobileTMController.validateResourceType(JSON.serialize(tmLine));
                //ticket 19130 <<
                MobileTMController.validateResource(JSON.serialize(tmLine));
                MobileTMController.validateUnitOfMeasure(JSON.serialize(tmLine));

                //insert a new line
                TM_Line__c newTMLine = laborLine.clone(false, true);
                newTMLine.Id = null;
                newTMLine.Line_No__c = 999;
                jobTaskWrappers[0].TMLines.add(newTMLine);
                //ticket 19130 >>
            }
        }

        MobileTMController.SaveTMHeader(JSONTM);

        MobileTMController.saveTM(JSONTM, 'Labor', JSON.serialize(jobTaskWrappers));

        MobileTMController.SaveTMAndLines(JSONTM, JSONJobTaskWrappers);

        String JSONRating = MobileTMController.getServiceRating(tm.Id);
        TM_Service_Rating__c serviceRating = new TM_Service_Rating__c();
        serviceRating.TM__c = tm.Id;
        serviceRating.Rating__c = 1;
        serviceRating.Customer_Review__c = 'test';
        MobileTMController.saveServiceRating(JSON.serialize(serviceRating));

        tm.Site_Email_Address__c = 'kchen@micro-datanet.com';
        tm.Customer_Not_Available__c = true;
        update tm;

        test.stopTest();
    }

    private static testMethod void test2() {
        NewTestData.createTestData();

        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        tm.Status__c = 'Scheduled';
        CompanyMgmt.byPassTrigger = true;
        update tm;

        test.startTest();

        CompanySettingUtil.acvSetting.Mobile_TM_Version_No__c = '1.0';

        String JSONSalesOrder = MobileTMController.getSalesOrder(tm.Sales_Order__c);
        String JSONTMs = MobileTMController.getTMs('', System.today(), 'TM', '1.0');

        String JSONTM = MobileTMController.getTM(tm.Id);

        String JSONJobTaskWrappers = MobileTMController.getJobTaskWrappers(tm.Id);

        String JSONTMLines = MobileTMController.getTMLines(tm.Id, 'Labor');

        List<Site_Access__c> accesses = new List<Site_Access__c>();
        accesses.add(SiteAccessController.createSiteAccess(tm.Id, 'TMSignature', Datetime.now().addHours(48)));
        accesses.add(SiteAccessController.createSiteAccess(tm.Id, 'TMSignature', Datetime.now().addHours(48)));

        List<Signature_Request__c> requests = new List<Signature_Request__c>();
        requests.add(new Signature_Request__c(Print_Name__c = 'Customer A', Email__c = 'kchen@micro-datanet.com', Request_Email_Sent__c = true, Request_Date__c = Datetime.now(), Site_Access__c = accesses[0].Id));
        requests.add(new Signature_Request__c(Print_Name__c = 'Customer B', Email__c = 'kchen@micro-datanet.com', Request_Email_Sent__c = true, Request_Date__c = Datetime.now(), Site_Access__c = accesses[1].Id));
        insert requests;

        List<Signature__c> signatures = new List<Signature__c>();
        signatures.add(new Signature__c(TM__c = tm.Id, Name = 'supervisor_signature', Signer_Role__c = 'Supervisor', Print_Name__c = 'Kevin', Email__c = 'kchen@micro-datanet.com'));
        signatures.add(new Signature__c(TM__c = tm.Id, Name = 'customer_signature', Signer_Role__c = 'Customer A', Customer_Not_Available__c = true, Request_Signature__C = true, Print_Name__c = 'Customer A', Email__c = 'kchen@micro-datanet.com', Signature_Request__c = requests[0].Id));
        signatures.add(new Signature__c(TM__c = tm.Id, Name = 'customer_signature', Signer_Role__c = 'Customer B', Customer_Not_Available__c = true, Request_Signature__C = true, Print_Name__c = 'Customer B', Email__c = 'kchen@micro-datanet.com', Signature_Request__c = requests[1].Id));
        insert signatures;
        //signature request >>


        MobileTMController.processPDF(tm.Id);


        //signature request <<
        List<Attachment> attachments = new List<Attachment>();
        attachments.add(new Attachment(ParentId = signatures[1].Id, Name = tm.Name + '.pdf', body = Blob.valueOf('test')));
        attachments.add(new Attachment(ParentId = signatures[2].Id, Name = tm.Name + '.pdf', body = Blob.valueOf('test')));
        insert attachments;


        ApexPages.StandardController standardController = new ApexPages.StandardController(tm);
        SignatureRequestController controller = new SignatureRequestController(standardController );
        controller.sendSignatureRequestEmail();

        try {
            controller.processSignatureAndEmail();
        }
        catch(exception ex) {

        }

        SignatureRequestController.processEmailAsync(tm.Id);


        for (Signature_Request__c request : requests) {
            request.Signed__c = true;
            request.Signature_Date__c = Datetime.now();
        }
        update requests;
        attachments = new List<Attachment>();
        attachments.add(new Attachment(ParentId = requests[0].Id, Name = tm.Name + '_signature_request.pdf', body = Blob.valueOf('test')));
        attachments.add(new Attachment(ParentId = requests[1].Id, Name = tm.Name + '_signature_request.pdf', body = Blob.valueOf('test')));
        insert attachments;
        SignatureRequestController.processSignature(tm);

        for (Integer i = 1; i < signatures.size(); i++) {
            signatures[i].Signed__c = true;
        }
        update signatures;
        MobileTMController.processPDF(tm.Id);
        //signature request <<


        CompanyMgmt.ByPassTrigger = true;
        tm.Status__c = 'Mobile Review';
        update tm;
        MobileTMController.changeToScheduled(tm.Id);

        MobileTMController.sendFieldTMPDF(tm, Blob.valueOf('test pdf'));

        test.stopTest();
    }

    private static testMethod void testFileUpload() {
        NewTestData.createTestData();

        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        tm.Status__c = 'Scheduled';
        CompanyMgmt.byPassTrigger = true;
        update tm;

        test.startTest();

        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'Test 12345';
        contentVersion.PathOnClient = 'c:\test.jpg';
        contentVersion.VersionData = Blob.valueOf('test');
        contentVersion.IsMajorVersion = true;
        contentVersion.Type_fileupload__c = 'Manifest_BOL';
        insert contentVersion;

        List<ContentDocument> contentDocuments = [SELECT Id FROM ContentDocument WHERE Title = 'Test 12345'];
        ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
        contentDocumentLink.ContentDocumentId = contentDocuments[0].Id;
        contentDocumentLink.LinkedEntityId = tm.Id;
        contentDocumentLink.ShareType = 'V';
        contentDocumentLink.Visibility = 'AllUsers';
        insert contentDocumentLink;

        Attachment attachment = new Attachment();
        attachment.ParentId = tm.Sales_Order__c;
        attachment.Body = Blob.valueOf('TEST');
        attachment.IsPrivate = false;
        attachment.Description = 'test';
        attachment.Name = 'Test';
        insert attachment;

        FileUploaderController.updateTitle(tm.Id, contentDocuments[0].Id);

        FileExplorerController.getFiles(tm.Sales_Order__c, 'Service_Orders__r');
        test.stopTest();
    }
    //test12
}