objects/Job_Task_Template__c/Job_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Job Task Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Surcharge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Amount__c</fullName>
    <label>Surcharge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Type</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Operating_Expense_Cost_Pct__c.field-meta.xml
<CustomField>
    <fullName>Operating_Expense_Cost_Pct__c</fullName>
    <label>Operating Expense Cost %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Order__c/fields/Surcharge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Amount__c</fullName>
    <label>Surcharge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Sales_Line__c.Line_Amount__c</summarizedField>
    <summaryForeignKey>Sales_Line__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Sales_Order__c/fields/Total_Amount_Incl_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Incl_Tax__c</fullName>
    <label>Total Amount Incl. Tax</label>
    <summarizedField>Sales_Line__c.Line_Amt_Incl_Tax__c</summarizedField>
    <summaryForeignKey>Sales_Line__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Sales_Order_Job_Task__c/Sales_Order_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Order Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Order_Job_Task__c/fields/Amount_To_Bill__c.field-meta.xml
<CustomField>
    <fullName>Amount_To_Bill__c</fullName>
    <label>Amount To Bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Task-Based</fullName>
                <isActive>false</isActive>
                <label>Task-Based</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption10__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption10__c</fullName>
    <label>Custom Assumption 10</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption1__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption1__c</fullName>
    <label>Custom Assumption 1</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption2__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption2__c</fullName>
    <label>Custom Assumption 2</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption3__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption3__c</fullName>
    <label>Custom Assumption 3</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption4__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption4__c</fullName>
    <label>Custom Assumption 4</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption5__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption5__c</fullName>
    <label>Custom Assumption 5</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption6__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption6__c</fullName>
    <label>Custom Assumption 6</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption7__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption7__c</fullName>
    <label>Custom Assumption 7</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption8__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption8__c</fullName>
    <label>Custom Assumption 8</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Custom_Assumption9__c.field-meta.xml
<CustomField>
    <fullName>Custom_Assumption9__c</fullName>
    <label>Custom Assumption 9</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price__c</fullName>
    <label>Fixed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Fixed_Price_Surcharge_Option__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Surcharge_Option__c</fullName>
    <label>Fixed Price Surcharge Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price Does Not Include Surcharge</fullName>
            </value>
            <value>
                <fullName>Fixed Price Includes Surcharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Task Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>Sales Order Job Tasks</relationshipLabel>
    <relationshipName>Sales_Order_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Pct_Billed__c.field-meta.xml
<CustomField>
    <fullName>Pct_Billed__c</fullName>
    <label>% Billed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Pct_To_Bill__c.field-meta.xml
<CustomField>
    <fullName>Pct_To_Bill__c</fullName>
    <label>Percentage To Bill</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Rolled_Up_Sales_Lines_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rolled_Up_Sales_Lines_Amount__c</fullName>
    <label>Rolled-Up Sales Lines Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Job Tasks</relationshipLabel>
    <relationshipName>Sales_Order_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Surcharge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Amount__c</fullName>
    <label>Surcharge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Task_No__c.field-meta.xml
<CustomField>
    <fullName>Task_No__c</fullName>
    <label>Task No.</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>Tax_Group__c</fullName>
    <label>Tax Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Total_Amount_Incl_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Incl_Tax__c</fullName>
    <label>Total Amount Incl. Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/TM_Job_Task__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;M Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/fields/Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price__c</fullName>
    <label>Fixed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/TM_Job_Task__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Task Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>T_M_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Job_Task__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Job_Task__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Job Task</label>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Job_Task__c/fields/Task_No__c.field-meta.xml
<CustomField>
    <fullName>Task_No__c</fullName>
    <formula>Sales_Order_Job_Task__r.Task_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Job_Task__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

globalValueSets/Billing_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>T&amp;M</fullName>
        <default>true</default>
        <label>T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Per Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Plus</fullName>
    </customValue>
    <masterLabel>Billing Type</masterLabel>
</GlobalValueSet>

classes/SalesOrderJobTasksSelector.cls
public with sharing class SalesOrderJobTasksSelector extends fflib_SObjectSelector implements ISalesOrderJobTasksSelector {
    public static ISalesOrderJobTasksSelector newInstance() {
        return (ISalesOrderJobTasksSelector) Application.Selector.newInstance(Sales_Order_Job_Task__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType() {
        return Sales_Order_Job_Task__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Sales_Order_Job_Task__c.Id,
                Sales_Order_Job_Task__c.Name,
                Sales_Order_Job_Task__c.Line_No__c,
                Sales_Order_Job_Task__c.Task_No__c,
                Sales_Order_Job_Task__c.Sales_Order__c,
                Sales_Order_Job_Task__c.Job_Task_Template__c,
                Sales_Order_Job_Task__c.Billing_Type__c, 
                Sales_Order_Job_Task__c.Fixed_Price__c,
                Sales_Order_Job_Task__c.Surcharge_Amount__c,
                Sales_Order_Job_Task__c.Rolled_Up_Sales_Lines_Amount__c,
                Sales_Order_Job_Task__c.Tax__c,
                Sales_Order_Job_Task__c.Tax_Pct__c,
                Sales_Order_Job_Task__c.Tax_Group__c,
                Sales_Order_Job_Task__c.Pct_Billed__c,
                Sales_Order_Job_Task__c.Pct_To_Bill__c,
                Sales_Order_Job_Task__c.Amount_To_Bill__c,
                Sales_Order_Job_Task__c.Custom_Assumption1__c,
                Sales_Order_Job_Task__c.Custom_Assumption2__c,
                Sales_Order_Job_Task__c.Custom_Assumption3__c,
                Sales_Order_Job_Task__c.Custom_Assumption4__c,
                Sales_Order_Job_Task__c.Custom_Assumption5__c,
                Sales_Order_Job_Task__c.Custom_Assumption6__c,
                Sales_Order_Job_Task__c.Custom_Assumption7__c,
                Sales_Order_Job_Task__c.Custom_Assumption8__c,
                Sales_Order_Job_Task__c.Custom_Assumption9__c,
                Sales_Order_Job_Task__c.Custom_Assumption10__c,
                Sales_Order_Job_Task__c.Total_Amount__c,
                Sales_Order_Job_Task__c.Total_Amount_Incl_Tax__c,
                //ticket 19672 <<
                Sales_Order_Job_Task__c.Fixed_Price_Surcharge_Option__c
                //ticket 19672 >>
        };
    }

    public List<Sales_Order_Job_Task__c> selectById(Set<Id> idSet){
        return (List<Sales_Order_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('Sales_Order__r.Name')
                .selectField('Sales_Order__r.Operating_Expense_Cost_Pct__c') //Ticket#24560
                .selectField('Job_Task_Template__r.Name')
                .setCondition('Id IN :idSet')
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }

    public List<Sales_Order_Job_Task__c> selectBySalesOrderId(Set<Id> idSet){
        return selectByJobTaskId(idSet, null);
    }

    //ticket 20566 <<
    public List<Sales_Order_Job_Task__c> selectBySalesOrderId2(Set<Id> salesOrderIds){
        List<String> filters = new List<String>();
        filters.add('Sales_Order__c IN :salesOrderIds');

        return (List<Sales_Order_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('Job_Task_Template__r.Name')
                .setCondition(String.join(filters, ' AND '))
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }
    //ticket 20566 >>

    public List<Sales_Order_Job_Task__c> selectByJobTaskId(Set<Id> salesOrderIds, Set<Id> jobTaskIds){
        List<String> filters = new List<String>();
        filters.add('Sales_Order__c IN :salesOrderIds');
        if (jobTaskIds != null && jobTaskIds.size() > 0) {
            filters.add('Id IN :jobTaskIds');
        }

        //ticket 20177 <<
        /*
        return (List<Sales_Order_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('Job_Task_Template__r.Name')
                .setCondition(String.join(filters, ' AND '))
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
        */
        fflib_QueryFactory queryFactory = newQueryFactory(true);
        queryFactory.selectField('Job_Task_Template__r.Name')
                .setCondition(String.join(filters, ' AND '))
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true);
        queryFactory.subselectQuery('TM_Job_Tasks__r')
                .selectField('Id')
                .selectField('TM__r.Sales_Invoice__c');
        return (List<Sales_Order_Job_Task__c>) Database.query(queryFactory.toSOQL());
        //ticket 20177 >>
    }
}