objects/Job_Task_Template__c/Job_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Job Task Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job_Task_Template_Line__c/Job_Task_Template_Line__c.object-meta.xml
<CustomObject>
    <label>Job Task Template Line</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Task Template Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Task_Template_Line__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <label>Job Task Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>Job Task Template Lines</relationshipLabel>
    <relationshipName>Job_Task_Template_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/JobTaskTemplateWrapper.cls
public with sharing class JobTaskTemplateWrapper {
    @AuraEnabled
    public Job_Task_Template__c JobTaskTemplate { set; get; }

    @AuraEnabled
    public List<Job_Task_Template_Line__c> JobTaskTemplateLines { set; get; }

    public JobTaskTemplateWrapper() {

    }

    public JobTaskTemplateWrapper(Job_Task_Template__c jobTaskTemplate, List<Job_Task_Template_Line__c> jobTaskTemplateLines) {
        this.JobTaskTemplate = jobTaskTemplate;
        this.JobTaskTemplateLines = jobTaskTemplateLines;
    }
}