objects/Job_Task_Template__c/Job_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Job Task Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order_Type__c/Sales_Order_Type__c.object-meta.xml
<CustomObject>
    <label>Sales Order Type</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order_Type__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order_Type__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order_Type__c/fields/Emergency_Response__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Response</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order_Type__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wizard Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>Sales Order Types</relationshipLabel>
    <relationshipName>Sales_Order_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

classes/SalesOrderTypesSelector.cls
public class SalesOrderTypesSelector extends fflib_SObjectSelector {

    public static SalesOrderTypesSelector newInstance(){
        return (SalesOrderTypesSelector) Application.Selector.newInstance(Sales_Order_Type__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType(){
        return Sales_Order_Type__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                Sales_Order_Type__c.Blocked__c,
                Sales_Order_Type__c.Code__c,
                Sales_Order_Type__c.CreatedById,
                Sales_Order_Type__c.CreatedDate,
                Sales_Order_Type__c.Description__c,
                Sales_Order_Type__c.Emergency_Response__c,
                Sales_Order_Type__c.Id,
                Sales_Order_Type__c.Name,
                //job task <<
                Sales_Order_Type__c.Job_Task_Template__c
                //job task >>
        };
    }

    public List<Sales_Order_Type__c> selectByIds(Set<Id> salesOrderTypeIds){
        return System.Database.query(
                newQueryFactory().setCondition('Id IN :salesOrderTypeIds').toSOQL());
    }

    public Map<Id, Sales_Order_Type__c> getSalesOrderTypesByIdsMap(Set<Id> salesOrderTypeIds){
        Map<Id, Sales_Order_Type__c> salesOrderTypesByIds = new Map<Id, Sales_Order_Type__c>();
        salesOrderTypesByIds.putAll(selectByIds(salesOrderTypeIds));
        return salesOrderTypesByIds;
    }
}