objects/Job_Task_Template__c/Job_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Job Task Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order_Job_Task__c/Sales_Order_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Order Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Order_Job_Task__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Task-Based</fullName>
                <isActive>false</isActive>
                <label>Task-Based</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Task Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>Sales Order Job Tasks</relationshipLabel>
    <relationshipName>Sales_Order_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Task_No__c.field-meta.xml
<CustomField>
    <fullName>Task_No__c</fullName>
    <label>Task No.</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/TM_Job_Task__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;M Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/fields/Job_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Task Template</label>
    <referenceTo>Job_Task_Template__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>T_M_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Job_Task__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Job_Task__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Job Task</label>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Job_Task__c/fields/Task_No__c.field-meta.xml
<CustomField>
    <fullName>Task_No__c</fullName>
    <formula>Sales_Order_Job_Task__r.Task_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Job_Task__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/TMJobTasksSelector.cls
public with sharing class TMJobTasksSelector extends fflib_SObjectSelector implements ITMJobTasksSelector {
    public static ITMJobTasksSelector newInstance() {
        return (ITMJobTasksSelector) Application.Selector.newInstance(TM_Job_Task__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType() {
        return TM_Job_Task__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                TM_Job_Task__c.Id,
                TM_Job_Task__c.Name,
                TM_Job_Task__c.Line_No__c,
                TM_Job_Task__c.Task_No__c,
                TM_Job_Task__c.TM__c,
                TM_Job_Task__c.Job_Task_Template__c,
                TM_Job_Task__c.Billing_Type__c,
                TM_Job_Task__c.Sales_Order_Job_Task__c
        };
    }

    public List<TM_Job_Task__c> selectByTMId(Set<Id> idSet){
        return (List<TM_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('TM__r.Name')
                .selectField('Job_Task_Template__r.Name')
                .selectField('Sales_Order_Job_Task__c.Name')
                .setCondition('TM__c IN :idSet')
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }

    public List<TM_Job_Task__c> selectById(Set<Id> idSet){
        return (List<TM_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('TM__r.Name')
                .selectField('Job_Task_Template__r.Name')
                .selectField('Sales_Order_Job_Task__c.Name')
                .setCondition('Id IN :idSet')
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }

    public List<TM_Job_Task__c> selectBySalesOrderJobTaskId(Set<Id> idSet){
        return (List<TM_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('TM__r.Name')
                .selectField('Job_Task_Template__r.Name')
                .selectField('Sales_Order_Job_Task__c.Name')
                .setCondition('Sales_Order_Job_Task__c IN :idSet')
                .setOrdering('Task_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }
}