objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/EmployeeUtilizationControllerTest.cls
@isTest
public class EmployeeUtilizationControllerTest {

    public static Map<String, Numbering_Series__c> mapNumberSeries = new Map<String, Numbering_Series__c>();
    public static Numbering_Series__c theNumberingSeries;
    @testSetup static void SetupData() {
        //Setup Data
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
        List<Company_Setup__c> theCSList = [SELECT Id From Company_Setup__c WHERE Id = : companySetup.Id];
        System.assertEquals(theCSList.size(), 1);
    }

    public static testmethod void GetServiceCenters() {

        Service_Center__c sc = TestDataUtil.ServiceCenterRecord;
        TM__c TMRecord = TestDataUtil.TMRecord;

        Test.startTest();
        TM_Line__c TMLineLaborRecord = TestDataUtil.TMLineLaborRecord ;
        List<EmployeeUtilizationController.ServiceCenterWrapper> scList = EmployeeUtilizationController.getServiceCenters();
        List<EmployeeUtilizationController.TMLineWrapper> twrap = EmployeeUtilizationController.getTMLaborLinesPDF();
        EmployeeUtilizationController.TMLineWrapper wrp = New EmployeeUtilizationController.TMLineWrapper();
        wrp.ResourceNo = 'test';
        wrp.ResourceType = 'test';
        wrp.Description = 'test';
        wrp.Total_Hours = 10;
        wrp.SC_Hours = 10;
        wrp.IC_Hours = 10;
        wrp.Utilization = 10;
        EmployeeUtilizationController.verifyNumberOfDays(Date.Today().AddDays(-7), Date.Today().AddDays(7), True);
        EmployeeUtilizationController.verifyNumberOfDays(Date.Today().AddDays(-7), Date.Today().AddDays(7), False);
        EmployeeUtilizationController.calculateUtilization(10, Date.Today().AddDays(-7), Date.Today().AddDays(7), False);

        String SD = String.valueof(Date.Today().AddDays(-10).Year()) + '-' + String.valueof(Date.Today().AddDays(-10).Month()) + '-' + String.valueof(Date.Today().AddDays(-10).Day());
        String ED = String.valueof(Date.Today().AddDays(10).Year()) + '-' + String.valueof(Date.Today().AddDays(10).Month()) + '-' + String.valueof(Date.Today().AddDays(10).Day());
        EmployeeUtilizationController.getTMLaborLines(TMLineLaborRecord.Service_Center__c, SD, ED, 'true');

        Test.stopTest();
    }

}