objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Service</fullName>
                <label>OOS-On Lot</label>
            </value>
            <value>
                <fullName>OOS-Pending</fullName>
                <label>OOS-Pending Sale</label>
            </value>
            <value>
                <fullName>Gone</fullName>
            </value>
            <value>
                <fullName>Junked</fullName>
                <isActive>false</isActive>
                <label>Junked</label>
            </value>
            <value>
                <fullName>OOS-Under Repair</fullName>
                <isActive>false</isActive>
                <label>OOS-Under Repair</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Stolen</fullName>
                <isActive>false</isActive>
                <label>Stolen</label>
            </value>
            <value>
                <fullName>Under Repair</fullName>
                <isActive>false</isActive>
                <label>Under Repair</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Off__c/Resource_Off__c.object-meta.xml
<CustomObject>
    <label>Resource Off</label>
    <nameField>
        <displayFormat>Off-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Off__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Offs</relationshipLabel>
    <relationshipName>Resource_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resource Off</relationshipLabel>
    <relationshipName>Resource_Off</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <label>Timesheet No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <value>Labor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payroll Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Timesheet__c/fields/Week_No__c.field-meta.xml
<CustomField>
    <fullName>Week_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Week No.</label>
    <referenceTo>Week_Number__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Line__c/Timesheet_Line__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Timesheet Line No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Timesheet_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Timesheet Lines</relationshipLabel>
    <relationshipName>Timesheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Line__c/fields/Resource_Off__c.field-meta.xml
<CustomField>
    <fullName>Resource_Off__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Off</label>
    <referenceTo>Resource_Off__c</referenceTo>
    <relationshipLabel>Timesheet Lines</relationshipLabel>
    <relationshipName>Timesheet_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Timesheet_Line__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Lines</relationshipLabel>
    <relationshipName>Timesheet_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/TimesheetControllerTest.cls
@isTest
public class TimesheetControllerTest {

    public static Map<String, Numbering_Series__c> mapNumberSeries = new Map<String, Numbering_Series__c>();
    public static Numbering_Series__c theNumberingSeries;
    @testSetup static void SetupData() {
        //Setup Data
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
        List<Company_Setup__c> theCSList = [SELECT Id From Company_Setup__c WHERE Id = :companySetup.Id];
        System.assertEquals(theCSList.size(), 1);
    }

    private static testMethod void Test_TimesheetSetController() {
        List<Timesheet__c>TSList = New List<Timesheet__c>();
        TSList.add(TestDataUtil.TimesheetRecord);

        ApexPages.StandardSetController StdCon = new ApexPages.StandardSetController (TSList);
        TimesheetController TC = new TimesheetController(StdCon);
    }

    private static testMethod void Test_TimesheetController() {

        Test.startTest();
        CompanyMgmt.byPassTrigger = true;
        PageReference pref = Page.Timesheet;
        Test.setCurrentPage(pref);
        Timesheet__c TimesheetRecord = new Timesheet__c (Name = 'Test TimesheetName', Resource__c = TestDataUtil.ResourceLaborRecord.Id, Service_Center__c = TestDataUtil.ServiceCenterRecord.Id, Status__c = 'Approved', Week_No__c = TestDataUtil.WeekNumberRecord.Id);
        insert TimesheetRecord ;
        pref.getParameters().put('id', TimesheetRecord.Id);
        ApexPages.StandardController StdCon = new ApexPages.StandardController(TestDataUtil.TimesheetRecord);
        TimesheetController TC = new TimesheetController(StdCon);

        Timesheet_Line__c TimesheetLineRecord = TestDataUtil.TimesheetLineRecord;
        List<Timesheet_Line__c> timesheetLineList = New List<Timesheet_Line__c>();
        timesheetLineList.add(TimesheetLineRecord);
        Map<String, Timesheet__c> mapTS = New Map<String, Timesheet__c>();
        Set<String> tmIdSet = New Set<String>();
        mapTS.put(TestDataUtil.TimesheetRecord.Id, TestDataUtil.TimesheetRecord);
        tmIdSet.add(TestDataUtil.TimesheetRecord.Id);

        List<TM_Line__c > TMLineList = New List<TM_Line__c >();
        TMLineList.Add(TestDataUtil.TMLineLaborRecord);
        TC.RefreshTimesheet();
        pref.getParameters().put('lineNo', '0');
        pref.getParameters().put('fieldName', 'theJobPosition');
        pref.getParameters().put('newFieldValue', '');
        String title = TC.title;
        Timesheet__c TS = TC.TS;

        List<Timesheet_Line__c > TSLList = TC.TSLList;
        Company_Setup__c CompanySetup = TC.CompanySetup;
        TC.msave();
        TC.save();
        TC.quickSave();
        TC.saveNapprove();
        TC.insertLine();
        TC.deleteLine();
        TC.cancel();
        TC.release();
        TC.reopen();
        Tc.validateWeekNo();
        TC.returnBack();
        TC.returnToTimesheetList();
        Service_Center__c ServiceCenterRecord = TestDataUtil.ServiceCenterRecord;
        TC.theSC = ServiceCenterRecord;
        TC.weekStartingDate = Date.Today().toStartofWeek();
        TC.weekEndingDate = Date.Today().toStartofWeek().addDays(7);
        TC.listTMNotReadyForTimesheet();
        TC.listLaborResNotReadyForTimesheet();
        Set<String> pwJobIds = new Set<String>();
        //TC.CreateTimesheet();
        mapTS.Put(TestDataUtil.ResourceRecord.Id, TestDataUtil.TimesheetRecord);
        Resource_Off__c ResourceOffRecord = TestDataUtil.ResourceOffRecord;
        TC.refreshTimesheets();
        mapTS.Clear();
        mapTS.Put(TestDataUtil.ResourceLaborRecord.Id, TestDataUtil.TimesheetRecord);
        tmIdSet.add(TestDataUtil.TMRecord.Id);
        CompanyMgmt.byPassTrigger = false;
        Test.stopTest();
    }

    private static testMethod void Test_TimesheetValidate() {
        PageReference pref = Page.Timesheet;
        Test.setCurrentPage(pref);
        pref.getParameters().put('id', TestDataUtil.TimesheetRecord.Id);
        ApexPages.StandardController StdCon = new ApexPages.StandardController(TestDataUtil.TimesheetRecord);
        TimesheetController TC = new TimesheetController(StdCon);
        Test.StartTest();
        Timesheet_Line__c TimesheetLineRecord = TestDataUtil.TimesheetLineRecord;
        List<Timesheet_Line__c> theTSLList = new List<Timesheet_Line__c>();
        theTSLList.Add(TimesheetLineRecord);
        TC.theTSLList = theTSLList;
        pref.getParameters().put('lineNo', '0');
        pref.getParameters().put('fieldName', 'theResourceOff');
        pref.getParameters().put('newFieldValue', TestDataUtil.ResourceOffRecord.Id);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theParentLine');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theSalesOrder');
        pref.getParameters().put('newFieldValue', TestDataUtil.SalesOrderRecord.Id);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theSalesOrderSC');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theTM');
        pref.getParameters().put('newFieldValue', TestDataUtil.TMRecord.Id);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theTML');
        pref.getParameters().put('newFieldValue', TestDataUtil.TMLineLaborRecord.Id);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theCertifiedPWJob');
        pref.getParameters().put('newFieldValue', 'True');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theCustomerName');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theJobDescription');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theLunchHours');
        pref.getParameters().put('newFieldValue', '1');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theNetHours');
        pref.getParameters().put('newFieldValue', '2');
        TC.validateField();

        pref.getParameters().put('fieldName', 'thePrevailingWageJob');
        pref.getParameters().put('newFieldValue', 'true');
        TC.validateField();

        pref.getParameters().put('fieldName', 'thePWJobTypeCode');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();
        /*
        pref.getParameters().put('fieldName', 'theRateType');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();
        */
        pref.getParameters().put('fieldName', 'theSalesOrderDescription');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theSalesOrderType');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theScheduledDate');
        pref.getParameters().put('newFieldValue', '03/03/2019');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theTimeType');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theTotalHours');
        pref.getParameters().put('newFieldValue', '10');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theWeekDay');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();
        /*
        pref.getParameters().put('fieldName', 'theRateType');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theRateType');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();
          */
        pref.getParameters().put('fieldName', 'theLunchStartTime');
        pref.getParameters().put('newFieldValue', '2');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theLunchEndTime');
        pref.getParameters().put('newFieldValue', '10:2');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theStartTime');
        pref.getParameters().put('newFieldValue', Null);
        TC.validateField();

        pref.getParameters().put('fieldName', 'theLunchStartTime');
        pref.getParameters().put('newFieldValue', '2');
        TC.validateField();

        pref.getParameters().put('fieldName', 'theEndTime');
        pref.getParameters().put('newFieldValue', '2');
        TC.validateField();

        Test.StopTest();
    }


    private static testMethod void Test_TimesheetMgmt() {

        Test.StartTest();
        Timesheet__c TimesheetRecord = TestDataUtil.TimesheetRecord;
        Timesheet_Line__c TimesheetLineRecord = TestDataUtil.TimesheetLineRecord;
        List<Timesheet_Line__c> theTSLList = new List<Timesheet_Line__c>();
        theTSLList.add(TimesheetLineRecord);
        TimesheetMgmt.checkSave(TimesheetRecord, theTSLList);
        TimesheetMgmt.updateTSL(TimesheetRecord, TimesheetLineRecord, 'theScheduledDate');
        TimesheetMgmt.updateTSL(TimesheetRecord, TimesheetLineRecord, 'theTimeType');
        TimesheetMgmt.updateTSL(TimesheetRecord, TimesheetLineRecord, 'theStartTime');
        TimesheetMgmt.updateTSL(TimesheetRecord, TimesheetLineRecord, 'theEndTime');
        TimesheetMgmt.updateTSL(TimesheetRecord, TimesheetLineRecord, 'theLunchStartTime');
        TimesheetMgmt.getDatetimeInUserTZ(System.now());
        //TimesheetMgmt.calculateHours(Time.newInstance(1, 2, 3, 4),Time.newInstance(2, 2, 3, 4));
        TimesheetMgmt.validateWeekNo(TimesheetRecord);
        TimesheetMgmt tsMgmt = new TimesheetMgmt();
        tsMgmt.deleteTimesheetLine(theTSLList);
        TimesheetMgmt.nullRelationshipFields(TimesheetRecord);
        Test.StopTest();
    }
    private static testMethod void Test_TimesheetController1() {
        Test.startTest();
        PageReference pref = Page.Timesheet;
        Test.setCurrentPage(pref);
        Timesheet__c TimesheetRecord = new Timesheet__c (Name = 'Test TimesheetName', Resource__c = TestDataUtil.ResourceLaborRecord.Id, Service_Center__c = TestDataUtil.ServiceCenterRecord.Id, Status__c = 'Approved', Week_No__c = TestDataUtil.WeekNumberRecord.Id);
        insert TimesheetRecord ;
        pref.getParameters().put('id', TimesheetRecord.Id);
        ApexPages.StandardController StdCon = new ApexPages.StandardController(TimesheetRecord);
        TimesheetController TC = new TimesheetController(StdCon);
        Service_Center__c ServiceCenterRecord = TestDataUtil.ServiceCenterRecord;
        TC.theSC = ServiceCenterRecord;
        TC.weekStartingDate = Date.Today().toStartofWeek();
        TC.weekEndingDate = Date.Today().toStartofWeek().addDays(7);
        TC.CreateTimesheet();
        Test.stopTest(); 
    }
    //test
}