objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Quote_Contact__c.field-meta.xml
<CustomField>
    <fullName>Quote_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signer_Role__c.field-meta.xml
<CustomField>
    <fullName>Signer_Role__c</fullName>
    <label>Signer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Customer A</fullName>
            </value>
            <value>
                <fullName>Customer B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Pending__c.field-meta.xml
<CustomField>
    <fullName>Signature_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

classes/SignaturePadControllerTest.cls
@isTest
private class SignaturePadControllerTest {
    private static testMethod void test() {
        Company_Setup__c setup = TestDataUtil.CompanySetupRecord;
        TM__c tm = TestDataUtil.TMRecord;
        
        test.startTest();
        
        //signature request <<
        //Signature__c sig = new Signature__c(Name='customer_signature', Related_To_Object_Name__c='TM__c', Related_To_Id__c=tm.Id, Print_Name__c='Smith', Signature_Date__c=DateTime.now(), Customer_Not_Available__c = true, Accept_Terms_and_Conditions__c=true, Email__c='abc@abc.com');
        //String data = 'blob value';
        //SignaturePadController.SignatureWrapper wrapper = new SignaturePadController.SignatureWrapper(sig);
        Signature__c sig = new Signature__c(Name='customer_signature', TM__c=tm.Id, Print_Name__c='Smith', Signer_Role__c='Customer A', Signature_Date__c=DateTime.now(), Customer_Not_Available__c = true, Accept_Terms_and_Conditions__c=true, Email__c='abc@abc.com');
        String data = 'blob value';
        SignatureWrapper wrapper = new SignatureWrapper(sig);
        //signature request >>

        String JSONData = JSON.serialize(wrapper);        
        
        //SignaturePadController.uploadSignature(null, 'blob value string', 'TM__c', tm.Id, tm.Id, 'Smith', true, DateTime.now(), false, 'abc@abc.com'); 
        SignaturePadController.saveSignature(JSONData);

        //signature request <<
        //JSONData = SignaturePadController.getSignature(tm.Id, 'customer_signature');
        //wrapper = (SignaturePadController.SignatureWrapper)JSON.deserialize(JSONData, SignaturePadController.SignatureWrapper.class);
        JSONData = SignaturePadController.getSignature(tm.Id, 'Customer A');

        //ticket 21113 <<
        Signature__c signature = [SELECT Id FROM Signature__c WHERE TM__c = :tm.Id LIMIT 1];
        signature.Customer_Not_Available__c = true;
        update signature;
        JSONData = SignaturePadController.getSignature(tm.Id, 'Customer A');
        JSONData = SignaturePadController.getSignature(tm.Id, 'Customer B');
        //ticket 21113 >>

        wrapper = (SignatureWrapper)JSON.deserialize(JSONData, SignatureWrapper.class);

        //ticket 21113 <<
        wrapper.SignatureData = EncodingUtil.base64Encode(Blob.valueOf('image data'));
        SignaturePadController.saveSignature(JSON.serialize(wrapper));
        //ticket 21113 >>
        //signature request >>

        wrapper.SignatureData = null;
        JSONData = JSON.serialize(wrapper); 
        
        //SignaturePadController.uploadSignature(wrapper.Id, 'blob value string', 'TM__c', tm.Id, tm.Id, 'Smith', true, DateTime.now(), false, 'abc@abc.com'); 
        SignaturePadController.saveSignature(JSONData);

        //ticket 21113 <<
        wrapper.RequestSignature = true;
        SignaturePadController.requestSignature(wrapper);

        ApexPages.StandardController standardController = new ApexPages.StandardController(tm);
        SignatureRequestController controller = new SignatureRequestController(standardController);
        controller.sendSignatureRequestEmail();


        Sales_Order__c quote = TestDataUtil.SalesOrderRecord;
        Contact quoteContact = TestDataUtil.Contact2Record;
        quote.Document_Type__c = 'Sales Quote';
        quote.Quote_Contact__c = quoteContact.Id;
        quote.Payment_Term__c = TestDataUtil.PaymentTermRecord.Id;
        update quote;
        Signature__c signature2 = (Signature__c)JSON.deserialize(SignatureRequestController.createQuoteSignatureRequest(quote.Id), Signature__c.class);
        signature2.Request_Signature__c = true;
        signature2.Signed__c = false;
        signature2.TM__c = tm.Id; //force the signature to link to the TM for testing
        signature2.Signer_Role__c = 'Customer A';
        update signature2;

        Signature_Request__c signatureRequest = [SELECT Id FROM Signature_Request__c WHERE Id = :signature2.Signature_Request__c LIMIT 1];
        signatureRequest.Signature_Pending__c = true;
        signatureRequest.Signed__c = true;
        update signatureRequest;

        Attachment attachment =  new Attachment();
        attachment.Body = Blob.valueOf('test');
        attachment.ParentId = signatureRequest.Id;
        attachment.Name = 'customer signature';
        attachment.IsPrivate = false;
        insert attachment;

        controller.processSignatureAndEmail();
        SignatureRequestController.processSignature(tm);
        SignatureRequestController.UpdateSignatureRequest(JSON.serialize(signature2));

        ApexPages.currentPage().getParameters().put('id', quote.Id);
        SignatureProcessController processController = new SignatureProcessController();
        processController.processSignatures();
        SignatureProcessController.sendUnansweredSignatureRequestReminderEmail(new List<Signature_Request__c>{ signatureRequest });
            SignatureProcessController.getUnansweredSignatureRequests(quote.Id);
        processController.cancel();

        //ticket 21113 >>
                        
        test.stopTest();
    }
    //test123
}