objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Setup__c/fields/Allow_Posting_From__c.field-meta.xml
<CustomField>
    <fullName>Allow_Posting_From__c</fullName>
    <label>Allow Posting From</label>
    <type>Date</type>
</CustomField>

objects/Company_Setup__c/fields/Allow_Posting_To__c.field-meta.xml
<CustomField>
    <fullName>Allow_Posting_To__c</fullName>
    <label>Allow Posting To</label>
    <type>Date</type>
</CustomField>

objects/GL_Account__c/GL_Account__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>GL_Entry__c.Amount__c</summarizedField>
    <summaryForeignKey>GL_Entry__c.GL_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/GL_Account__c/fields/No_of_Lines__c.field-meta.xml
<CustomField>
    <fullName>No_of_Lines__c</fullName>
    <label>No. of Lines</label>
    <summaryForeignKey>GL_Entry__c.GL_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/GL_Batch__c/GL_Batch__c.object-meta.xml
<CustomObject>
    <label>GL Batch</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Batch__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

objects/GL_Batch__c/fields/No_of_Lines__c.field-meta.xml
<CustomField>
    <fullName>No_of_Lines__c</fullName>
    <label>No. of Lines</label>
    <summaryForeignKey>GL_Entry__c.GL_Batch__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/GL_Batch__c/fields/Sync_d__c.field-meta.xml
<CustomField>
    <fullName>Sync_d__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync'd</label>
    <type>Checkbox</type>
</CustomField>

objects/GL_Entry__c/GL_Entry__c.object-meta.xml
<CustomObject>
    <description>For outbound GL entries</description>
    <label>GL Entry</label>
    <nameField>
        <displayFormat>GL-{0000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GL_Entry__c/fields/GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GL_Account__c</fullName>
    <label>GL Account</label>
    <referenceTo>GL_Account__c</referenceTo>
    <relationshipLabel>GL Entries</relationshipLabel>
    <relationshipName>GL_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/GL_Entry__c/fields/GL_Batch__c.field-meta.xml
<CustomField>
    <fullName>GL_Batch__c</fullName>
    <label>GL Batch</label>
    <referenceTo>GL_Batch__c</referenceTo>
    <relationshipLabel>GL Entries</relationshipLabel>
    <relationshipName>GL_Entries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CompanyTriggerMgmtTest.cls
@isTest
public class CompanyTriggerMgmtTest {

    @testSetup static void SetupData() {
        Company_Setup__c testCompanySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c testNumberSerRecord = TestDataUtil.NumberingSeriesRecord;
        GL_Batch__c testGLBatchRecord = TestDataUtil.GLBatchRecord;
        GL_Entry__c testGLEntryRecord = TestDataUtil.GLEntryRecord;
        GL_Account__c testGLAccountRecord = TestDataUtil.GLAccountRecord;
    }
    private static testMethod void Test_CompanyTriggerMgmt() {

        Company_Setup__c CompanySetup = [SELECT Id, Allow_Posting_From__c,Allow_Posting_To__c FROM Company_Setup__c Limit 1];
        List<Company_Setup__c>companySetupList=New List<Company_Setup__c>();
        companySetupList.add(companySetup);
        Map<Id, Company_Setup__c>companySetupMap=New Map<Id, Company_Setup__c>();
        companySetupMap.put(companySetup.id,companySetup);
        CompanyTriggerMgmt.CSInsertUpdate(companySetupList,True,companySetupMap);
        CompanyTriggerMgmt.CSInsertUpdate(companySetupList,False,companySetupMap);

        CompanyTriggerMgmt.CSDelete(companySetupList);

        GL_Batch__c GLBatchRecord =[SELECT Id, No_of_Lines__c, Sync_d__c, Closed__c FROM GL_Batch__c Limit 1];
        List<GL_Batch__c>GLBatchList=New List<GL_Batch__c>();
        GLBatchList.add(GLBatchRecord);
        CompanyTriggerMgmt.GLB_D(GLBatchList);
		GL_Entry__c testGLEntryRecord = [SELECT Id FROM GL_Entry__c Limit 1];
        List<GL_Entry__c>GLList=New List<GL_Entry__c>();
        GLList.add(testGLEntryRecord);
        CompanyTriggerMgmt.GL_I_U_Trigger(GLList);
        CompanyTriggerMgmt.GL_D_Trigger(GLList);
        try{
            CompanyMgmt.systemCall = false;
            for(GL_Entry__c gle:GLList){
                gle.Amount__c = 200;
                update gle;
                throw new myException('You are not allowed to modify General Ledger Entry.!');
            }
        } catch (Exception e){
            Boolean expectedResult = e.getMessage().contains('You are not allowed to modify General Ledger Entry.')?true:false;
            System.assertEquals(expectedResult, true);
        }
        GL_Account__c testGLAccountRecord = [SELECT Id, No_of_Lines__c FROM GL_Account__c Limit 1];
        List<GL_Account__c> theGLAList=New List<GL_Account__c>();
        theGLAList.add(testGLAccountRecord);
        CompanyTriggerMgmt.GLA_D(theGLAList);

    }

}