objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Quote_Contact__c.field-meta.xml
<CustomField>
    <fullName>Quote_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Site_Scope__c.field-meta.xml
<CustomField>
    <fullName>Site_Scope__c</fullName>
    <label>Project Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Pending_Approval</fullName>
        <label>Pending Approval</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

classes/SalesQuoteEmailingTest.cls
@IsTest
private class SalesQuoteEmailingTest {
    @IsTest
    private static void testEmailSalesQuote(){
        Company_Setup__c setup = TestDataUtil.CompanySetupRecord;
        Test.startTest();


        Sales_Order__c salesQuote = TestDataUtil.SalesOrderRecord;
        salesQuote.Document_Type__c = 'Sales Quote';
        salesQuote.Quote_Contact__c = TestDataUtil.Contact2Record.Id;
        salesQuote.Site_Scope__c = 'test';
        salesQuote.Approval_Status__c = 'Approved';
        update salesQuote;
        
        Signature__c currSign = new Signature__c();
        currSign.Sales_Order__c = salesQuote.id;
        currSign.Email__c = 'Test@gmail.com';
        currSign.Signed__c = True;
        currSign.Request_Signature__c = True;
        insert currSign;

        PageReference pageReference = Page.EmailSalesQuote;
        Test.setCurrentPage(pageReference);
        pageReference.getParameters().put('id', salesQuote.Id);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(salesQuote);
        SalesQuoteEmailing controller = new SalesQuoteEmailing(stdCon);
        List<SelectOption> options = controller.lstPrintType;
        String title = controller.title;
        controller.EmailSalesQuote();
        controller.returnBack();


        Blob pdf = SalesQuoteEmailing.generateQuotePDF(salesQuote.Id);
        

        Signature_Request__c signatureRequest = new Signature_Request__c();
        signatureRequest.Related_To_Id__c = salesQuote.Id;
        signatureRequest.Related_To_Object_Name__c = 'Sales_Order__c';
        signatureRequest.Print_Name__c = 'Smith';
        signatureRequest.Email__c = 'test@abc.com';
        signatureRequest.Customer_PO_No__c = '1222';
        signatureRequest.Customer_Comment__c = 'Comment';
        signatureRequest.Request_Date__c = System.today().addDays(-2);
        insert signatureRequest;

        salesQuoteEmailing.notifySignedQuote(signatureRequest);
        salesQuoteEmailing.notifyRejectedQuote(signatureRequest);
        salesQuoteEmailing.notifyUnansweredSignatureRequest(signatureRequest);
        SalesQuoteEmailing.saveQuotePDF(salesQuote,pdf,'test');
        SalesQuoteEmailing.sendQuotePDF(salesQuote, pdf);
       

    }
}