objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Retainage_Ledger_Entry__c/Retainage_Ledger_Entry__c.object-meta.xml
<CustomObject>
    <label>Retainage Ledger Entry</label>
    <nameField>
        <displayFormat>RLE-{00000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retainage Ledger Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Retainage_Ledger_Entry__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Retainage Ledger Entries (Sales Invoice)</relationshipLabel>
    <relationshipName>Retainage_Ledger_Entries2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Retainage_Ledger_Entry__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Retainage Ledger Entries</relationshipLabel>
    <relationshipName>Retainage_Ledger_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RetainageTest.cls
@IsTest
private class RetainageTest {
    @IsTest
    static void testBehavior() {
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Sales_Invoice__c salesInvoice = TestDataUtil.SalesInvoiceRecord;
        Sales_Order__c salesOrder = TestDataUtil.SalesOrderRecord;
        Retainage_Ledger_Entry__c retainageLedgerEntry = new Retainage_Ledger_Entry__c();
        retainageLedgerEntry.Sales_Order__c = salesOrder.Id;
        retainageLedgerEntry.Sales_Invoice__c = salesInvoice.Id;
        retainageLedgerEntry.Amount__c = 0;
        try{
            insert retainageLedgerEntry;
        } catch (Exception e){

        }
        try{
            CompanyMgmt.systemCall = true;
            insert retainageLedgerEntry;
        } catch (Exception e){

        }
    }
}