objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/FieldLogActivityTest.cls
@IsTest
private class FieldLogActivityTest {

    public static Map<String, Numbering_Series__c> mapNumberSeries = new Map<String, Numbering_Series__c>();
    public static Numbering_Series__c theNumberingSeries;

    @TestSetup
    static void SetupData(){
        CompanyMgmt.byPassTrigger = true;
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
        TM__c TMRecord = TestDataUtil.TMRecord;
        TM_Line__c TMLineLaborRecord = TestDataUtil.TMLineLaborRecord;
        TM_Line__c TMLineEquipmentRecord = TestDataUtil.TMLineEquipmentRecord;
        Resource__c eqRes = TestDataUtil.ResourceEquipmentRecord;
        CompanyMgmt.byPassTrigger = false;
    }

    @IsTest
    static void testFieldLogActivityController() {
        TM__c tm = [SELECT Id FROM TM__c LIMIT 1];
        TM_Line__c tmLine = [SELECT Id FROM TM_Line__c WHERE Category__c = 'Labor' LIMIT 1];
        Resource__c equipmentRes = [SELECT Id FROM Resource__c WHERE Category__c = 'Equipment' LIMIT 1];

        Test.startTest();
        PageReference pageReference = Page.FieldLogEntry;
        Test.setCurrentPage(pageReference);
        pageReference.getParameters().put('tmId', tm.Id);
        pageReference.getParameters().put('tmlId', tmLine.Id);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(tm);
        FieldLogActivityController fieldLogActivityController = new FieldLogActivityController(stdCon);
        fieldLogActivityController.addLine();

        pageReference.getParameters().put('fieldName', 'theEquipment');
        pageReference.getParameters().put('indexNo', '0');
        pageReference.getParameters().put('newFieldValue', equipmentRes.Id);
        fieldLogActivityController.validateField();

        pageReference.getParameters().put('fieldName', 'startTime');
        pageReference.getParameters().put('indexNo', '0');
        pageReference.getParameters().put('newFieldValue', '10:00');
        fieldLogActivityController.validateField();

        pageReference.getParameters().put('fieldName', 'endTime');
        pageReference.getParameters().put('indexNo', '0');
        pageReference.getParameters().put('newFieldValue', '11:00');
        fieldLogActivityController.validateField();

        fieldLogActivityController.save();

        pageReference.getParameters().put('displayId', '0');
        fieldLogActivityController.deleteLine();
        fieldLogActivityController.returnToTM();
        Test.stopTest();
    }
}