objects/Case/fields/Billing_Package__c.field-meta.xml
<CustomField>
    <fullName>Billing_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Package</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Case/fields/Billing_Package_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Package_Number__c</fullName>
    <label>Billing Package Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Case/recordTypes/Case_Record.recordType-meta.xml
<RecordType>
    <fullName>Case_Record</fullName>
    <active>true</active>
    <businessProcess>Cases</businessProcess>
    <label>Salesforce Support</label>
</RecordType>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Recall_Submitted_EQAI_BPR_clicked__c.field-meta.xml
<CustomField>
    <fullName>Recall_Submitted_EQAI_BPR_clicked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recall Submitted EQAI BPR clicked</label>
    <type>Checkbox</type>
</CustomField>

objects/Task/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

classes/RecallSubmittedEQAIBillingPackageCtrl.cls
/******************************************************************************************************
* Class Name: RecallSubmittedEQAIBillingPackageCtrl
* Description: This class is utilized by the RecallSubmittedEQAIBillingPackageRequest LWC to create a case record for
                System Admin to recall the EQAI Billing Package for related Sales Invoice.
* ***************************************************************************************************
* Owner		        Task #			Date		Description
* Andrew Simons     82347           4/1/2024    Initial implementation
* Andrew Simons     84318           4/9/2024    added salesforce support record type
* ******************************************************************************************************/

public with sharing class RecallSubmittedEQAIBillingPackageCtrl {

    @AuraEnabled
    public static String createCaseRecord(Id invoiceId){

        Sales_Invoice__c salesInvoice = [SELECT Id, Name, Recall_Submitted_EQAI_BPR_clicked__c  FROM Sales_Invoice__c WHERE Id = :invoiceId];
        Group caseOwners = [SELECT Id FROM Group WHERE type='Queue' AND DeveloperName = 'Case_Owners'];
        RecordType salesforceSupport = [SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND DeveloperName = 'Case_Record' LIMIT 1];

        if(!salesInvoice.Recall_Submitted_EQAI_BPR_clicked__c) {
            System.debug(invoiceId);
            Case newCase = new Case();
            newCase.Reason = 'Recall EQAI Billing Package';
            newCase.Priority = 'Medium';
            newCase.Billing_Package_Number__c = salesInvoice.Name;
            newCase.OwnerId = caseOwners.Id;
            newCase.Subject = 'Recall Billing Package Number '+salesInvoice.Name;
            newCase.Description = 'Recall Billing Package Number '+salesInvoice.Name;
            newCase.Billing_Package__c = salesInvoice.Id;
            newCase.RecordTypeId = salesforceSupport.Id;
            insert newCase;

            salesInvoice.Recall_Submitted_EQAI_BPR_clicked__c = true;
            update salesInvoice;

            return 'Success';
        } else {
            return 'Exists';
        }

    }
}