objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>To replace 'Queue' in OTRS</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Computer</fullName>
            </value>
            <value>
                <fullName>Desk Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>MDM</fullName>
            </value>
            <value>
                <fullName>MFD</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Pending Pickup</fullName>
            </value>
            <value>
                <fullName>Pending Return</fullName>
            </value>
            <value>
                <fullName>Phishing/SPAM</fullName>
            </value>
            <value>
                <fullName>Samsara</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Invoices (Sell-to Contact)</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice__c/fields/Invoice_Amt_Incl_Tax__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amt_Incl_Tax__c</fullName>
    <label>Billing Package Amt Incl. Tax</label>
    <summarizedField>Sales_Invoice_Line__c.Line_Amt_Incl_Tax__c</summarizedField>
    <summaryForeignKey>Sales_Invoice_Line__c.Sales_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Sales_Invoice__c/fields/Retainage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Retainage_Amount__c</fullName>
    <label>Retainage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Invoice__c/fields/Retainage_Pct__c.field-meta.xml
<CustomField>
    <fullName>Retainage_Pct__c</fullName>
    <label>Retainage %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Invoice__c/fields/Site_Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Invoices (Site Contact)</relationshipLabel>
    <relationshipName>Sales_Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Area__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Line_Amt_Incl_Tax__c.field-meta.xml
<CustomField>
    <fullName>Line_Amt_Incl_Tax__c</fullName>
    <label>Line Amt Incl. Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Tax_Area__c/Tax_Area__c.object-meta.xml
<CustomObject>
    <label>Tax Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Detail__c/Tax_Detail__c.object-meta.xml
<CustomObject>
    <label>Tax Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Detail__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Area</label>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Tax Details</relationshipLabel>
    <relationshipName>Tax_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Tax_Detail__c/fields/Tax_Pct__c.field-meta.xml
<CustomField>
    <fullName>Tax_Pct__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/SalesInvoiceWithPaginationController.cls
public with sharing class SalesInvoiceWithPaginationController {
    private final ApexPages.StandardController theController;
    public Sales_Invoice__c theSI;
    public List<Sales_Invoice_Line__c> theSILList;
    private String SIId;
    public static Company_Setup__c theCompanySetupValue;
    public Company_Setup__c theCompanySetup{
        get{
            if(theCompanySetupValue == null) {
                theCompanySetupValue = CompanyMgmt.getCompanySetup();
            }
            return theCompanySetupValue;
        }
        set;
    }
    public Decimal SILSubtotal { get; set; }
    public Decimal SILTaxTotal { get; set; }
    public Decimal SILTotal { get; set; }
    public Decimal SILProfitMargin {get;set;} // AES-437
    public Decimal SILTotalCost {get;set;}

    public Contact theBTContact {get; set; } //Ticket# AES-401
    public Contact theSiteContact {get; set; } //Ticket# AES-401

    public SalesInvoiceWithPaginationController(ApexPages.StandardController controller) {
        theController = controller;
        SIId = ApexPages.currentPage().getParameters().get('id');
        theBTContact = new Contact();
        theSiteContact = new Contact();
        if (SIId != null) {
            selectSI();
            selectSILList();
            // Ticket# AES-401 >>
            if (!String.isEmpty(theSI.Contact__c)){
                theBTContact.Id = theSI.Contact__c;
                theBTContact = theSI.Contact__r;
            }
            if (!String.isEmpty(theSI.Site_Contact_2__c)){
                theSiteContact.Id = theSI.Site_Contact_2__c;
                theSiteContact = theSI.Site_Contact_2__r;
            }
        }
        CalculateTotalOrder();
    }

    public Boolean allowDataOverride { get {return CompanyMgmt.allowDataOverride();} }

    private void selectSI() {
        theSI = SalesInvoicesSelector.newInstance().selectById(new Set<Id>{SIId})[0];
    }

    private void selectSILList() {
        theSILList = SalesInvoiceLinesSelector.newInstance().selectLinesByInvoiceId(SIId);
        //theSILList = SalesInvoiceLinesSelector.newInstance().selectByInvoiceId(SIId);
    }

    public Sales_Invoice__c SI {
        get {
            return theSI;
        }
    }

    public Boolean posted {
        get {
            if (theSI.Document_Status__c == 'Posted' || theSI.Document_Status__c == 'Void') {
                return true;
            } else {
                return false;
            }
        }
    }

    public Company_Setup__c CompanySetup {
        get {
            return theCompanySetup;
        }
    }

    public List<String> getMessages() {
        return new List<String>{
                'Document Status: ' + theSI.Document_Status__c, '', ''
        };
    }

    public void validateBillToCustomer() {
        theSI = SalesInvoiceMgmt.validateBillToCustomer(theSI);
    }

    public void validateInvoiceDate() {
        validatePaymentTerm();
    }

    public void validatePaymentTerm() {
        theSI = SalesInvoiceMgmt.validatePaymentTerm(theSI);
    }

    public void validateTaxArea() {
        theSI = SalesInvoiceMgmt.validateTaxArea(theSI);
        reInsertSIL();
    }

    public void validateTaxLiable() {
        reInsertSIL();
    }

    public void validateContact() {
        String contactId = ApexPages.currentPage().getParameters().get('contactId');
        String fieldId = ApexPages.currentPage().getParameters().get('fieldId');
        if (!String.isEmpty(contactId)){
            List<Contact> contacts = [SELECT Id, FirstName, LastName, Name FROM Contact WHERE Id = :contactId];
            if (contacts.size() > 0){
                if(fieldId == 'theBTContact') {
                    theSI.Contact__c = contacts[0].Id;
                    theSI.Contact__r = contacts[0];
                    theBTContact = contacts[0];
                } else {
                    theSI.Site_Contact_2__c = contacts[0].Id;
                    theSI.Site_Contact_2__r = contacts[0];
                    theSiteContact = contacts[0];
                }
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Contact does not exist!' + contactId));
            }
        }
    }

    public void calcRetainageAmt(){
        try{
            if(theSI.Retainage_Pct__c > 100){
                throw new DataException('Retainage % cannot be greater than 100%!');
            }
            theSI.Retainage_Amount__c = SalesInvoicesService.calcRetainageAmount(theSI.Invoice_Amt_Incl_Tax__c, theSI.Retainage_Pct__c);
        } catch (Exception e){
            theSI.Retainage_Pct__c = 0;
            theSI.Retainage_Amount__c = 0;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
    }

    public void msave() {
        CompanyMgmt.systemCall = true;

        Sales_Invoice__c oldSI = theSI.clone(true);
        List<Sales_Invoice_Line__c> oldSILList = new List<Sales_Invoice_Line__c>();
        // Savepoint
        Savepoint sp = Database.setSavepoint();

        //Check Errors
        List<String> errorList = new List<String>();
        errorList = SalesInvoiceMgmt.checkSave(theSI, theSILList);

        if (errorList.size() > 0) {
            Integer i = 0;
            for (i = 0; i < errorList.size(); i++) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorList[i]));
            }
            return;
        } else {
            try {
                //Save SIL first in case upsert theSI has error
                for (Sales_Invoice_Line__c SIL : theSILList) {
                    oldSILList.add(SIL.clone(true));
                }

                theSI = SalesInvoiceMgmt.nullRelationshipFields(theSI);
                upsert theSI;
                upsert theSILList;
                return;
            } catch (Exception e) {
                Database.rollback(sp);
                theSI = oldSI;
                theSILList = oldSILList;
                System.debug('Error: ' + e.getStackTraceString());
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return;
            }
        }
    }

    public PageReference save() {
        msave();
        if (!ApexPages.hasMessages()) {
            PageReference SalesInvoicePage = new PageReference('/' + theSI.Id);
            SalesInvoicePage.setRedirect(true);
            return SalesInvoicePage;
        } else {
            return null;
        }
    }

    public PageReference quickSaveForLinePaginationPage() {
        msave();
        if (!ApexPages.hasMessages()) {
            PageReference SalesInvoicePage = new PageReference('/apex/SalesInvoiceWithLinePagination?id=' + theSI.Id);
            SalesInvoicePage.setRedirect(true);
            return SalesInvoicePage;
        } else {
            return null;
        }
    }

    public PageReference cancel() {
        return theController.cancel();
    }

    public PageReference returnBack() {
        return theController.view();
    }

    private void CalculateTotalOrder() {
        SILSubtotal = 0.00;
        SILTaxTotal = 0.00;
        SILTotal = 0.00;
        SILProfitMargin = 0.00;
        SILTotalCost = 0.00;

        for(Sales_Invoice_Line__c salesInvoiceLine : theSILList){
            SILSubtotal += CompanyMgmt.zeroIfNull(salesInvoiceLine.Line_Amount__c);
            SILTotal += CompanyMgmt.zeroIfNull(salesInvoiceLine.Line_Amt_Incl_Tax__c);
            SILTaxTotal = SILTotal - SILSubtotal;
            SILTotalCost += CompanyMgmt.zeroIfNull(salesInvoiceLine.Line_Cost__c);
        }

        if (SILSubtotal !=0 ){
            SILProfitMargin = (1 - SILTotalCost / SILSubtotal) * 100;
        }
    }

    public PageReference reInsertSIL() {
        CompanyMgmt.systemCall = true;

        Savepoint sp = Database.setSavepoint();
        try {
            Set<String> setTaxGroup = new Set<String>();
            Set<String> setItemDiscGrp = new Set<String>();
            for (Resource__c theResource : SalesInvoiceMgmt.mapResource.values()) {
                setTaxGroup.add(theResource.Tax_Group__c);
                setItemDiscGrp.add(theResource.Category__c);
            }
            for (Tax_Detail__c theTaxDetail : [
                    SELECT Tax_Pct__c, Tax_Area__c, Tax_Group__c
                    FROM Tax_Detail__c
                    WHERE Tax_Area__c = :theSI.Tax_Area__r.Name AND Tax_Group__c IN :setTaxGroup
            ]) {

                if (String.isEmpty(theTaxDetail.Tax_Area__c) || String.isEmpty(theTaxDetail.Tax_Group__c)) continue;

                if (SalesInvoiceMgmt.mapSalesTax.get(theTaxDetail.Tax_Area__c + ';' + theTaxDetail.Tax_Group__c) == null) {
                    SalesInvoiceMgmt.mapSalesTax.put(theTaxDetail.Tax_Area__c + ';' + theTaxDetail.Tax_Group__c, theTaxDetail.Tax_Pct__c);
                } else {
                    SalesInvoiceMgmt.mapSalesTax.put(theTaxDetail.Tax_Area__c + ';' + theTaxDetail.Tax_Group__c, SalesInvoiceMgmt.mapSalesTax.get(theTaxDetail.Tax_Area__c + ';' + theTaxDetail.Tax_Group__c) + theTaxDetail.Tax_Pct__c);
                }
            }

            CompanyMgmt.mapSalesTax = SalesInvoiceMgmt.mapSalesTax;
            SalesInvoiceMgmt.isReinsertSL = true;

            List<Sales_Invoice_Line__c> theNewSILList = new List<Sales_Invoice_Line__c>();

            for (Sales_Invoice_Line__c SIL : theSILList) {
                Sales_Invoice_Line__c newSIL = new Sales_Invoice_Line__c();
                newSIL = SIL.clone(true);
                newSIL = SalesInvoiceMgmt.updateSIL(theSI, newSIL, 'theTaxGroup');
                theNewSILList.add(newSIL);
            }

            if (theSI.Id != null) {
                theSI = SalesInvoiceMgmt.nullRelationshipFields(theSI);
                try {
                    upsert theSI;
                    update theNewSILList;
                } catch (Exception e) {
                    System.debug('Error: ' + e.getMessage());
                }
                selectSI();
            }
            theSILList.clear();
            theSILList.addAll(theNewSILList);
            CalculateTotalOrder();
        } catch (Exception e) {
            // Rollback
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }

    /*Sales Invoice Line Pagination*/
    public Integer noOfRecords{get; set;}
    public Integer size{get; set;}
    public final Integer Page_Size=25;

    public ApexPages.StandardSetController setCon{
        get{
            if(setCon == null){
                size = Page_Size;
                setCon = new ApexPages.StandardSetController(theSILList);
                setCon.setPageSize(size);
                noOfRecords = setCon.getResultSize();
            }

            return setCon;
        }
        set;
    }

    public Boolean hasNext{
        get{
            return setCon.getHasNext();
        }
        set;
    }

    public Boolean hasPrevious{
        get{
            return setCon.getHasPrevious();
        }
        set;
    }

    public Integer pageNumber{
        get{
            return setCon.getPageNumber();
        }
        set;
    }

    public void previous(){
        setCon.save();
        setCon.previous();
    }

    public void next(){
        setCon.save();
        setCon.next();

    }

    transient public List<Sales_Invoice_Line__c> salesInvoiceLines{
        get{
        return (List<Sales_Invoice_Line__c>) setCon.getRecords();
    }
        set;
    }

}