objects/EQAI_API_URL_Extensions__mdt/EQAI_API_URL_Extensions__mdt.object-meta.xml
<CustomObject>
    <description>URL Extensions for EQAI API Endpoints</description>
    <label>EQAI API URL Extensions</label>
    <pluralLabel>EQAI API URL Extensions</pluralLabel>
</CustomObject>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Extension__c.field-meta.xml
<CustomField>
    <fullName>API_Extension__c</fullName>
    <label>API Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/Sales_Order_EQAI_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data Mapping of Sales Order Field Values to EQAI Field Values</description>
    <label>Sales Order EQAI Mapping</label>
    <pluralLabel>Sales Order EQAI Mapping</pluralLabel>
</CustomObject>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Name__c</fullName>
    <label>EQAI Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>company_id</fullName>
                <default>true</default>
                <label>company_id</label>
            </value>
            <value>
                <fullName>profit_ctr_id</fullName>
            </value>
            <value>
                <fullName>project_code</fullName>
            </value>
            <value>
                <fullName>country_code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Value__c</fullName>
    <label>EQAI Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Table_Name__c</fullName>
    <label>EQAI Table Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkOrderQuoteHeader</fullName>
                <default>true</default>
                <label>WorkOrderQuoteHeader</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service_Center__r.Name</fullName>
                <default>true</default>
                <label>Service_Center__r.Name</label>
            </value>
            <value>
                <fullName>Payment_Term__r.Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Value__c</fullName>
    <label>Salesforce Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ManifestService.cls
/*************************************************************************************************
* Name         :  ManifestService
* Description  :  Sends request to external service and retrieves manifest records
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Shahwaz Khan             12-09-2024             US117942:  Salesforce - Manifest lookup on T&M
*************************************************************************************************/
public class ManifestService {
    public static HTTPResponse sendRequestToEQAI(String tsdfApprovalCode, String tmId) {
        ApplicationLog.ApplicationlogInformation logData = new ApplicationLog.ApplicationlogInformation();
        logData.className = 'ManifestService';
        logData.methodName = 'sendRequestToEQAI'; 
        Map<String, String> company_Id_EQIMap = new Map<String, String>();
        Map<String, String> profit_Ctr_Id_EQIMap = new Map<String, String>();
        try {
            for (Sales_Order_EQAI_Mapping__mdt salesOrderEQIMappingRecord : [SELECT Id, EQAI_Field_Name__c, EQAI_Field_Value__c, EQAI_Table_Name__c, Salesforce_Field_API_Name__c, Salesforce_Field_Value__c FROM Sales_Order_EQAI_Mapping__mdt]) {
                if (salesOrderEQIMappingRecord.EQAI_Field_Name__c == 'company_id') {
                    company_Id_EQIMap.put(salesOrderEQIMappingRecord.Salesforce_Field_Value__c, salesOrderEQIMappingRecord.EQAI_Field_Value__c);
                } else if (salesOrderEQIMappingRecord.EQAI_Field_Name__c == 'profit_ctr_id') {
                    profit_Ctr_Id_EQIMap.put(salesOrderEQIMappingRecord.Salesforce_Field_Value__c, salesOrderEQIMappingRecord.EQAI_Field_Value__c);
                }
            }
            
            TM__c tm = [SELECT Id, Sales_Order__r.Service_Center__r.Name,Sales_Order__r.Name FROM TM__c WHERE Id = :tmId LIMIT 1];

            Integer company_id;
            Integer profit_ctr_id;
            if (tm.Sales_Order__r.Service_Center__r.Name != null) {
                company_id = Integer.valueOf(company_Id_EQIMap.get(tm.Sales_Order__r.Service_Center__r.Name));
                profit_ctr_id = Integer.valueOf(profit_Ctr_Id_EQIMap.get(tm.Sales_Order__r.Service_Center__r.Name));
            }

            EQAI_API_URL_Extensions__mdt apiDetails = [SELECT API_Extension__c, API_Key__c, API_Token__c FROM EQAI_API_URL_Extensions__mdt WHERE DeveloperName = 'GetManifestDetails' LIMIT 1];
            String endpoint = apiDetails.API_Extension__c;
            endpoint += 'TsdfApprovalCode=' + EncodingUtil.urlEncode(tsdfApprovalCode, 'UTF-8');
            endpoint += '&CompanyId=' + company_id;
            endpoint += '&ProfitCenterId=' + profit_ctr_id;
            endpoint += '&QuoteProject='+ EncodingUtil.urlEncode(tm.Sales_Order__r.Name, 'UTF-8');

            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:EQAI_Base_URL' + endpoint);
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('x-api-key', apiDetails.API_Key__c);
            req.setHeader('x-secret-token', apiDetails.API_Token__c);
            req.setMethod('GET');
            req.setTimeout(20000);

            Http http = new Http();
            HTTPResponse res = http.send(req);
            logData.serviceRequest = 'ManifestServiceReq>>' + 'callout:EQAI_Base_URL'+endpoint;
            logData.serviceResponse = 'ManifestServiceRes>>' + res.getBody();
            ApplicationLog.startLog(JSON.serialize(logData));

            return res;

        } catch (Exception e) {
            System.debug('Error in sendRequestToEQAI: ' + e.getMessage());
            System.debug('line::'+e.getLineNumber());
            return null;
        }
    }
}