objects/EQAI_API_URL_Extensions__mdt/EQAI_API_URL_Extensions__mdt.object-meta.xml
<CustomObject>
    <description>URL Extensions for EQAI API Endpoints</description>
    <label>EQAI API URL Extensions</label>
    <pluralLabel>EQAI API URL Extensions</pluralLabel>
</CustomObject>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Extension__c.field-meta.xml
<CustomField>
    <fullName>API_Extension__c</fullName>
    <label>API Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/Sales_Order_EQAI_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data Mapping of Sales Order Field Values to EQAI Field Values</description>
    <label>Sales Order EQAI Mapping</label>
    <pluralLabel>Sales Order EQAI Mapping</pluralLabel>
</CustomObject>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Name__c</fullName>
    <label>EQAI Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>company_id</fullName>
                <default>true</default>
                <label>company_id</label>
            </value>
            <value>
                <fullName>profit_ctr_id</fullName>
            </value>
            <value>
                <fullName>project_code</fullName>
            </value>
            <value>
                <fullName>country_code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Value__c</fullName>
    <label>EQAI Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Table_Name__c</fullName>
    <label>EQAI Table Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkOrderQuoteHeader</fullName>
                <default>true</default>
                <label>WorkOrderQuoteHeader</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service_Center__r.Name</fullName>
                <default>true</default>
                <label>Service_Center__r.Name</label>
            </value>
            <value>
                <fullName>Payment_Term__r.Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Value__c</fullName>
    <label>Salesforce Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/D365_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>D365_Business_Unit__c</fullName>
    <label>D365 Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/fields/D365_LE__c.field-meta.xml
<CustomField>
    <fullName>D365_LE__c</fullName>
    <label>D365 LE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/D365CustomerService.cls
/*************************************************************************************************
* Name         :  D365CustomerService
* Description  :  D365 Project Lookup Functionality Service Class 
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Shahwaz Khan             02-14-2025            US141063:  Add D365 Project Lookup Functionality
  Shahwaz Khan             03-06-2025            US142841:  Update D365 Project Lookup(Update Request Endpint)
*************************************************************************************************/
public class D365CustomerService {
    public static HttpResponse fetchCustomerIds(String d365CustomerId,Service_Center__c serviceCenter,String keyword) {
        try {
            ApplicationLog.ApplicationlogInformation logData = new ApplicationLog.ApplicationlogInformation();
            logData.className = 'D365CustomerService';
            logData.methodName = 'fetchCustomerIds'; 
            Integer companyId;
            Integer profitCenId;
            /*Commented as part of US142841*/
            /*map<String,String> company_Id_EQIMap = new map<String,String>();
            map<String,String> profit_Ctr_Id_EQIMap = new map<String,String>();
            for(Sales_Order_EQAI_Mapping__mdt salesOrderEQIMappingRecord :[select Id,EQAI_Field_Name__c,EQAI_Field_Value__c,EQAI_Table_Name__c,Salesforce_Field_API_Name__c,Salesforce_Field_Value__c from Sales_Order_EQAI_Mapping__mdt]){
                if(salesOrderEQIMappingRecord.EQAI_Field_Name__c =='company_id'){
                    company_Id_EQIMap.put(salesOrderEQIMappingRecord.Salesforce_Field_Value__c,salesOrderEQIMappingRecord.EQAI_Field_Value__c);
                }
                else if(salesOrderEQIMappingRecord.EQAI_Field_Name__c=='profit_ctr_id'){
                    profit_Ctr_Id_EQIMap.put(salesOrderEQIMappingRecord.Salesforce_Field_Value__c,salesOrderEQIMappingRecord.EQAI_Field_Value__c);
                }
            }
            if(serviceCenter.Name != null && company_Id_EQIMap !=null && company_Id_EQIMap.containskey(serviceCenter.Name)) 
                companyId = Integer.valueOf(company_Id_EQIMap.get(serviceCenter.Name));
            if(serviceCenter.Name != null && profit_Ctr_Id_EQIMap !=null && profit_Ctr_Id_EQIMap.containskey(serviceCenter.Name)) 
                profitCenId = Integer.valueOf(profit_Ctr_Id_EQIMap.get(serviceCenter.Name));
            */
            EQAI_API_URL_Extensions__mdt CustomerDetails = [select API_Extension__c, API_Key__c, API_Token__c, DeveloperName from EQAI_API_URL_Extensions__mdt where DeveloperName='get365CustomerDetails'];
            String endpoint = CustomerDetails.API_Extension__c;
            endpoint += d365CustomerId;
            endpoint += '&D365LegalEntity=' + serviceCenter.D365_LE__c;
            endpoint += '&D365BusinessUnit=' + serviceCenter.D365_Business_Unit__c;
            /*Commented as part of US142841*/
            //endpoint += '&D365ProjectId=' + (keyword != null ? keyword : '');
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:EQAI_Base_URL'+endpoint);
            req.setHeader('Content-Type','application/json');
            req.setHeader('x-api-key',CustomerDetails.API_Key__c);
            req.setHeader('x-secret-token',CustomerDetails.API_Token__c);
            req.setMethod('GET');
            req.setTimeout(120000);
            Http http = new Http();
            HttpResponse res = http.send(req);
            logData.serviceRequest = 'D365CustomerReq>>' + 'callout:EQAI_Base_URL'+endpoint;
            logData.serviceResponse = 'D365CustomerRes>>' + res.getBody();
            ApplicationLog.startLog(JSON.serialize(logData));           
            if (res.getStatusCode() == 200) {
                return res;
            } else {
                System.debug('Error in API response: ' + res.getStatusCode() + ' - ' + res.getBody());
                return res;
            }
        } catch (Exception e) {
            System.debug('Error in Customer D365 API: ' + e.getMessage());
            return null;
        }
    }
}