objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ResourceTypeUOMAssociation__c/ResourceTypeUOMAssociation__c.object-meta.xml
<CustomObject>
    <label>Resource Type Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Type Unit of Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceTypeUOMAssociation__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipName>ResourceTypeUOM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ResourceTypeUOMAssociation__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipName>ResourceTypeUOMAssociation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Memo</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Cost_Qty__c.field-meta.xml
<CustomField>
    <fullName>Cost_Qty__c</fullName>
    <label>Cost Qty.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Inter_Company_Resource__c.field-meta.xml
<CustomField>
    <fullName>Inter_Company_Resource__c</fullName>
    <formula>AND(ISNULL(Service_Center__c) == FALSE,AND(Service_Center__c != Sales_Invoice__r.Service_Center__c,Service_Center__r.Temporary__c != TRUE))</formula>
    <label>Inter Company Resource</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Unit_Cost_Updated__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit Cost Updated</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/UOM_Exists__c.field-meta.xml
<CustomField>
    <fullName>UOM_Exists__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UOM Exists</label>
    <type>Checkbox</type>
</CustomField>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/SILUnitCostUpdateBatchable.cls
public with sharing class SILUnitCostUpdateBatchable implements Database.Batchable<Sales_Invoice_Line__c> {
    public List<Sales_Invoice_Line__c> start(Database.BatchableContext bc) {
        List<Sales_Invoice_Line__c> sils = [
        SELECT Id, Sales_Invoice__r.Credit_Memo__c,
            Category__c, Resource__c, Resource_Type__c, Quantity__c, Cost_Qty__c,
            Unit_of_Measure__c, Unit_Cost__c, Resource__r.Resource_Type__c
        FROM Sales_Invoice_Line__c
        WHERE Unit_Cost_Updated__c <> TRUE
            AND (Unit_Cost__c = 0 OR Unit_Cost__c = NULL OR Line_Cost__c = NULL OR Line_Cost__c = 0)
            AND Inter_Company_Resource__c = TRUE
            AND Sales_Invoice__r.Credit_Memo__c = FALSE
            AND (Category__c = 'Labor' OR Category__c = 'Equipment')
            AND Sales_Invoice__r.Document_Status__c != 'Void'
        ];
        return sils;
    }
    
    public void execute(Database.BatchableContext bc, List<Sales_Invoice_Line__c> sils) {
        //Set<Id> resIds = new Set<Id>();
        Set<Id> resTypeIds = new Set<Id>();
        for (Sales_Invoice_Line__c sil : sils) {
            System.debug('Info: sil ' + sil);
            System.debug('Info: sil Category ' + sil.Category__c);
            if (sil.Category__c == 'Labor' || sil.Category__c == 'Equipment' || sil.Category__c == 'Bundled') {
                if(sil.Resource_Type__c != sil.Resource__r.Resource_Type__c && String.isNotBlank(sil.Resource__r.Resource_Type__c)){
                    resTypeIds.add(sil.Resource__r.Resource_Type__c);
                } else if (sil.Resource_Type__c != null) {
                    resTypeIds.add(sil.Resource_Type__c);
                }
            }
        }

        Map<Id, Map<Id, Decimal>> costByUOMIdsByResTypes = new Map<Id, Map<Id, Decimal>>(); //by resource type, by uom
        List<ResourceTypeUOMAssociation__c> resourceTypeUOMAssociations = ResourceTypeUnitOfMeasuresSelector.newInstance().selectByResTypeId(resTypeIds);
        for(ResourceTypeUOMAssociation__c resourceTypeUOMAssociation : resourceTypeUOMAssociations){
            Map<Id, Decimal> resTypeCostByUOMIds = new Map<Id, Decimal>();
            if(costByUOMIdsByResTypes.containsKey(resourceTypeUOMAssociation.Resource_Type__c)){
                resTypeCostByUOMIds = costByUOMIdsByResTypes.get(resourceTypeUOMAssociation.Resource_Type__c);
            }
            resTypeCostByUOMIds.put(resourceTypeUOMAssociation.Unit_of_Measure__c, CompanyMgmt.zeroIfNull(resourceTypeUOMAssociation.Unit_Cost__c));
            costByUOMIdsByResTypes.put(resourceTypeUOMAssociation.Resource_Type__c, resTypeCostByUOMIds);
        }
        
        for (Sales_Invoice_Line__c sil : sils) {
            Decimal unitCost = 0;    //unit cost = 0 if not cost record found    
            Boolean uomExists = false;
            if (sil.Category__c == 'Labor' || sil.Category__c == 'Equipment') {
                Id costResTypeId;
                if(sil.Resource_Type__c != sil.Resource__r.Resource_Type__c && String.isNotBlank(sil.Resource__r.Resource_Type__c)){
                    costResTypeId = sil.Resource__r.Resource_Type__c;
                } else if (sil.Resource_Type__c != null) {
                    costResTypeId = sil.Resource_Type__c;
                }

                if (costByUOMIdsByResTypes.containsKey(costResTypeId)) {
                    Map<Id, Decimal> costs = costByUOMIdsByResTypes.get(costResTypeId);
                    if (costs.containsKey(sil.Unit_of_Measure__c)) {
                        uomExists = true;
                        if (costs.get(sil.Unit_of_Measure__c) > 0) {
                            unitCost = costs.get(sil.Unit_of_Measure__c);
                        }
                    }
                }
            }

            sil.UOM_Exists__c = uomExists;
            sil.Unit_Cost__c = unitCost;
            if(sil.Cost_Qty__c != 0 && sil.Cost_Qty__c != null) {
                sil.Line_Cost__c = CompanyMgmt.zeroIfNull(sil.Unit_Cost__c) * sil.Cost_Qty__c;
            } else {
                sil.Line_Cost__c = CompanyMgmt.zeroIfNull(sil.Unit_Cost__c) * CompanyMgmt.zeroIfNull(Math.abs(sil.Quantity__c));
            }

            if(sil.Unit_Cost__c != 0) {
                sil.Unit_Cost_Updated__c = true;
            }
        }
        update sils;
    }
    
    public void finish(Database.BatchableContext bc) {
    
    }
}