objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ResourceTypeUOMAssociation__c/ResourceTypeUOMAssociation__c.object-meta.xml
<CustomObject>
    <label>Resource Type Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Type Unit of Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceTypeUOMAssociation__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipName>ResourceTypeUOM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ResourceTypeUOMAssociation__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipName>ResourceTypeUOMAssociation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Line_Amt_Incl_Tax__c.field-meta.xml
<CustomField>
    <fullName>Line_Amt_Incl_Tax__c</fullName>
    <label>Line Amt Incl. Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/TM_Line__c.field-meta.xml
<CustomField>
    <fullName>TM_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M Line</label>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Billing Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Line</label>
    <referenceTo>Sales_Invoice_Line__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>Service_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/SILUnitCostUpdateBatchableTest.cls
@isTest
public class SILUnitCostUpdateBatchableTest {
    private static testMethod void Test() {
        Test.startTest();
        CompanyMgmt.byPassTrigger = true;
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
        
        List<Sales_Invoice_Line__c> salesInvoiceLines = new List<Sales_Invoice_Line__c>();
        Sales_Invoice_Line__C SalesInvoiceLineRecord1 = new Sales_Invoice_Line__c(
                Sales_Invoice__c = TestDataUtil.SalesInvoiceRecord.Id,
                Resource_Type__c = TestDataUtil.ResourceTypeEquipmentRecord.Id,
                Resource__c = TestDataUtil.ResourceEquipmentRecord.Id,
                Category__c = 'Equipment',
                Description__c = 'Test',
                Line_No__c = 5,
                Quantity__c = 5,
                Unit_Price__c = 2,
                Line_Amount__c = 0,
                Line_Amt_Incl_Tax__c = 0,
                Tax__c = 0,
                Tax_Group__c = 'NT',
                Unit_of_Measure__c = TestDataUtil.UnitMeasureRecord.Id,
                TM_Line__c = TestDataUtil.TMLineLaborRecord.id,
                TM__c = TestDataUtil.TMRecord.id
        );
        //insert SalesInvoiceLineRecord1;
        salesInvoiceLines.add(SalesInvoiceLineRecord1);

        Sales_Invoice_Line__C SalesInvoiceLineRecord2 = new Sales_Invoice_Line__c(
                Sales_Invoice__c = TestDataUtil.SalesInvoiceRecord.Id,
                Resource_Type__c = TestDataUtil.ResourceTypeEquipmentRecord.Id,
                Resource__c = TestDataUtil.ResourceLaborRecord.Id,
                Category__c = 'Labor',
                Description__c = 'Test',
                Line_No__c = 5,
                Quantity__c = 5,
                Cost_Qty__c = 5,
                Unit_Price__c = 2,
                Line_Amount__c = 0,
                Line_Amt_Incl_Tax__c = 0,
                Tax__c = 0,
                Tax_Group__c = 'NT',
                Unit_of_Measure__c = TestDataUtil.UnitMeasureRecord.Id,
                TM_Line__c = TestDataUtil.TMLineMaterialRecord.id,
                TM__c = TestDataUtil.TMRecord.id
        );
        //insert SalesInvoiceLineRecord2;
        salesInvoiceLines.add(SalesInvoiceLineRecord2);

        insert salesInvoiceLines;

        ResourceTypeUOMAssociation__c resourceTypeUOMAssociation = new ResourceTypeUOMAssociation__c();
        resourceTypeUOMAssociation.Resource_Type__c = TestDataUtil.ResourceTypeEquipmentRecord.Id;
        resourceTypeUOMAssociation.Unit_of_Measure__c = TestDataUtil.UnitMeasureRecord.Id;
        resourceTypeUOMAssociation.Unit_Cost__c = 100;
        resourceTypeUOMAssociation.Unit_Price__c = 150;
        resourceTypeUOMAssociation.ER_Unit_Price__c = 150;
        insert resourceTypeUOMAssociation;

        SILUnitCostUpdateBatchable batchable = new SILUnitCostUpdateBatchable();
        Database.executeBatch(batchable, 200);
        CompanyMgmt.byPassTrigger = false;
        Test.stopTest();
    }

//    private static testMethod void Test2() {
//        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
//        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
//
//        List<Sales_Invoice_Line__c> salesInvoiceLines = new List<Sales_Invoice_Line__c>();
//        Sales_Invoice_Line__C SalesInvoiceLineRecord2 = new Sales_Invoice_Line__c(
//                Sales_Invoice__c = TestDataUtil.SalesInvoiceRecord.Id,
//                Resource__c = TestDataUtil.ResourceMaterialRecord.Id,
//                Category__c = 'Materials',
//                Description__c = 'Test',
//                Line_No__c = 5,
//                Quantity__c = 5,
//                Unit_Price__c = 2,
//                Line_Amount__c = 0,
//                Line_Amt_Incl_Tax__c = 0,
//                Tax__c = 0,
//                Tax_Group__c = 'NT',
//                Unit_of_Measure__c = TestDataUtil.UnitMeasureRecord.Id,
//                TM_Line__c = TestDataUtil.TMLineMaterialRecord.id,
//                TM__c = TestDataUtil.TMRecord.id
//        );
//        //insert SalesInvoiceLineRecord2;
//        salesInvoiceLines.add(SalesInvoiceLineRecord2);
//
//        insert salesInvoiceLines;
//
//        Test.startTest();
//        SILUnitCostUpdateBatchable batchable = new SILUnitCostUpdateBatchable();
//        Database.executeBatch(batchable, 200);
//        Test.stopTest();
//    }
}