objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Equipment_Group__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Group</label>
    <referenceTo>Equipment_Group__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Fleet_Number__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Number__c</fullName>
    <label>Fleet Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Goal_hours__c.field-meta.xml
<CustomField>
    <fullName>Goal_hours__c</fullName>
    <label>Goal (hours)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Resource__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <label>Vehicle Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <label>VIN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Resource_Type__c/fields/Equipment_Group__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Group</label>
    <referenceTo>Equipment_Group__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Closed.recordType-meta.xml
<RecordType>
    <fullName>Closed</fullName>
    <active>true</active>
    <label>Closed</label>
    
    
</RecordType>

objects/TM__c/recordTypes/Confirmed.recordType-meta.xml
<RecordType>
    <fullName>Confirmed</fullName>
    <active>true</active>
    <label>Confirmed</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Billing Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Fleet_No__c.field-meta.xml
<CustomField>
    <fullName>Fleet_No__c</fullName>
    <label>Fleet No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/fields/Total_Job_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Job_Hours__c</fullName>
    <label>Total Job Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/EquipmentUtilizationController.cls
public class EquipmentUtilizationController {

    public static String defaultServiceCenter { get; set; }

    /******************* Method called by the generate document functionality *********************/
    public static List<TMLineWrapper> getTMEquipLinesPDF() {
        String ServiceCenter = System.currentPageReference().getParameters().get('ServiceCenter');
        String startDate = System.currentPageReference().getParameters().get('startDate');
        String endDate = System.currentPageReference().getParameters().get('endDate');

        /*
        system.debug('***ServiceCenter' + ServiceCenter);
        system.debug('***startDate' + startDate);
        system.debug('***endDate' + endDate);
         */
        List<TMLineWrapper> wrapperList = getTMEquipLines(ServiceCenter, startDate, endDate);
        return wrapperList;
    }

    /******************* GET THE DATE FOR LAST MONDAY *********************/
    @AuraEnabled
    public static Date getLastWeekFirstDate() {
        Date firstDate = system.today().toStartOfWeek().addDays(-6);
        return firstDate;
    }

    /******************* GET THE DATE FOR LAST SUNDAY *********************/
    @AuraEnabled
    public static Date getLastWeekLastDate() {
        Date lastDate = system.today().toStartOfWeek();
        return lastDate;
    }

    public static Decimal getNoWeeks(Date startDate, Date endDate){
        integer noDays = startDate.daysBetween(endDate);
        return (decimal.valueOf(noDays+1)/7).setScale(2,RoundingMode.HALF_UP);
    }
    /******************* Method to retrieve the service centers and populate the picklist *********************/
    @AuraEnabled
    public static List<ReportsUtils.ServiceCenterWrapper> getServiceCenters() {
        // Getting all service centers to show up on picklist
        List<Service_Center__c> serviceCenterList = [
                SELECT Id, Name, Description__c
                FROM Service_Center__c
                ORDER BY Description__c
        ];

        // Get current user's service center
        String userServiceCenter = ReportsUtils.getCurrentUserServiceCenter();

        // Setting the first center found as the default 
        if (defaultServiceCenter == null) {
            defaultServiceCenter = serviceCenterList[0].Id;
        }

        // Populating the service center wrapper list
        List<ReportsUtils.ServiceCenterWrapper> listServiceCenterWrapper = new List<ReportsUtils.ServiceCenterWrapper>();

        // Add All
        // Create new wrapper instance
        ReportsUtils.ServiceCenterWrapper scWrapper = new ReportsUtils.ServiceCenterWrapper();
        scWrapper.Id = 'ALL';
        scWrapper.Name = 'ALL';
        scWrapper.Description = 'ALL Service Centers';
        scWrapper.isDefault = false;
        // Add wrapper to the list
        listServiceCenterWrapper.add(scWrapper);

        for (Service_Center__c sc : serviceCenterList) {

            // Create new wrapper instance
            //ReportsUtils.ServiceCenterWrapper scWrapper = new ReportsUtils.ServiceCenterWrapper();
            scWrapper = new ReportsUtils.ServiceCenterWrapper();
            scWrapper.Id = sc.Id;
            scWrapper.Name = sc.Name;
            if (sc.Description__c != null) scWrapper.Description = sc.Description__c; else scWrapper.Description = sc.Name;

            // If it is the user's service center, set it as default
            if (sc.Name == userServiceCenter) {
                scWrapper.isDefault = true;
                defaultServiceCenter = sc.Id;
            } else {
                scWrapper.isDefault = false;
            }

            // Add wrapper to the list
            listServiceCenterWrapper.add(scWrapper);
        }

        // Return service centers
        return listServiceCenterWrapper;
    }

    /******************* Method to return the TM Lines and populate the report *********************/
    @AuraEnabled
    public static List<TMLineWrapper> getTMEquipLines(String ServiceCenter, String startDate, String endDate) {
        Map<String, TMHoursWrapper> TMHoursMap = new Map<String, TMHoursWrapper>();
        Map<String, TMLineWrapper> TMLineMap = new Map<String, TMLineWrapper>();

        /*
        system.debug('!!ServiceCenter ' + ServiceCenter);
        system.debug('!!startDate ' + startDate);
        system.debug('!!endDate ' + endDate);
         */

        // Setting the default filter for service center
        if (ServiceCenter == null) {
            ServiceCenter = defaultServiceCenter;
        }

        // Build query
        Id blankResourceId = null;
        String query;
        if (ServiceCenter != 'All') {
            query = 'SELECT Id, Resource_Type__r.Name, Resource__r.Make__c, Resource__r.Model__c, Quantity__c,Resource__r.Resource_Type__r.Name,' +
                    ' Resource__r.VIN__c, Resource__r.Vehicle_Year__c, Resource__r.Name, Fleet_No__c, Resource__r.Fleet_Number__c, ' +
                    ' Total_Job_Hours__c, Resource__r.Service_Center__c, Resource__r.Equipment_Group__c, Resource__r.Resource_Type__r.Equipment_Group__r.Name, ' +
                    ' Resource__r.Goal_hours__c, Resource__r.Service_Center__r.Name, TM__r.Service_Center__c ' +
                    ' FROM TM_Line__c ' +
                    ' WHERE Category__c = \'Equipment\' ' +
                    //	' AND TM__r.Status__c IN (\'Confirmed\', \'Received by Billing\', \'Ready to Bill\', \'Fully Invoiced\' ,\'Closed\')' +
                    ' AND Resource__r.Service_Center__c =: ServiceCenter AND Resource__c != :blankResourceId ';
        } else {
            query = 'SELECT Id, Resource_Type__r.Name, Resource__r.Make__c, Resource__r.Model__c, Quantity__c,Resource__r.Resource_Type__r.Name,' +
                    ' Resource__r.VIN__c, Resource__r.Vehicle_Year__c, Resource__r.Name, Fleet_No__c, Resource__r.Fleet_Number__c, ' +
                    ' Total_Job_Hours__c, Resource__r.Service_Center__c, Resource__r.Equipment_Group__c, Resource__r.Resource_Type__r.Equipment_Group__r.Name, ' +
                    ' Resource__r.Goal_hours__c, Resource__r.Service_Center__r.Name, TM__r.Service_Center__c ' +
                    ' FROM TM_Line__c ' +
                    ' WHERE Category__c = \'Equipment\' ' +
                    //	' AND TM__r.Status__c IN (\'Confirmed\', \'Received by Billing\', \'Ready to Bill\', \'Fully Invoiced\' ,\'Closed\')' +
                    ' AND Resource__c != :blankResourceId ';
        }
        Date startDateFilter;
        if (startDate != null) {
            startDateFilter = date.valueOf(startDate);
        } else {
            startDateFilter = getLastWeekFirstDate();
        }

        query += 'AND TM__r.Scheduled_Date__c >= :startDateFilter ';

        Date endDateFilter;
        if (endDate != null) {
            endDateFilter = date.valueOf(endDate);
        } else {
            endDateFilter = getLastWeekLastDate();
        }

        query += 'AND TM__r.Scheduled_Date__c <= :endDateFilter ';

        query += ' ORDER BY Resource__r.Name';

        // Getting only Equipment TMLines 
        List<TM_Line__c> TMLines = Database.query(query);

        //system.debug('TMLines' + TMLines);
        // Populate TMHoursMap
        for (TM_Line__c line : TMLines) {
            if (TMHoursMap.containsKey(line.Resource__c)) {
                // Getting existing wrapper
                TMHoursWrapper wrapper = TMHoursMap.get(line.Resource__c);
                //wrapper = populateFields(line,wrapper);
                if (wrapper.Total_Hours == null) {
                    wrapper.Total_Hours = 0;
                }
                if (wrapper.SC_Hours == null) {
                    wrapper.SC_Hours = 0;
                }
                if (wrapper.IC_Hours == null) {
                    wrapper.IC_Hours = 0;
                }
                // Populating total hours
                if (wrapper.Total_Hours != null && line.Total_Job_Hours__c != null) {
                    wrapper.Total_Hours = companyMgmt.halfUpTo2D(wrapper.Total_Hours + line.Total_Job_Hours__c);
                }
                // Validate values to populate either SC Hours or IC Hours
                if (line.TM__r.Service_Center__c == line.Resource__r.Service_Center__c) {
                    if (wrapper.SC_Hours != null && line.Total_Job_Hours__c != null) {
                        wrapper.SC_Hours = companyMgmt.halfUpTo2D(wrapper.SC_Hours + line.Total_Job_Hours__c);
                    }
                } else {
                    if (wrapper.IC_Hours != null && line.Total_Job_Hours__c != null) {
                        wrapper.IC_Hours = companyMgmt.halfUpTo2D(wrapper.IC_Hours + line.Total_Job_Hours__c);
                    }
                }
                // Updating wrapper in the map
                TMHoursMap.put(line.Resource__c, wrapper);
            } else {
                // Creating a new wrapper
                TMHoursWrapper wrapper = new TMHoursWrapper();
                wrapper.ResourceId = line.Resource__c;
                // Set initial hours as zero
                wrapper.SC_Hours = 0;
                wrapper.IC_Hours = 0;
                wrapper.Total_Hours = 0;
                // Populate total hours
                if (line.Total_Job_Hours__c != null)
                    wrapper.Total_Hours = companyMgmt.halfUpTo2D(line.Total_Job_Hours__c);
                // Either populate SC Hours or IC Hours
                if (line.TM__r.Service_Center__c == line.Resource__r.Service_Center__c && line.Total_Job_Hours__c != null) {
                    wrapper.SC_Hours = companyMgmt.halfUpTo2D(line.Total_Job_Hours__c);
                } else if (line.Total_Job_Hours__c != null) {
                    wrapper.IC_Hours = companyMgmt.halfUpTo2D(line.Total_Job_Hours__c);
                }
                TMHoursMap.put(line.Resource__c, wrapper);
            }
        }

        //Loop through all resources with proper sortings
        string category = 'Equipment';
        List<Resource__c> theResourceList = new List<Resource__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.Resource__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ' , Service_Center__r.Name, Resource_Type__r.Equipment_Group__r.Name, Resource_Type__r.Name ';
        strQuery += ' FROM Resource__c ';
        strQuery += ' WHERE (Start_Date__c = null OR Start_Date__c <=: endDateFilter)';
        strQuery += ' AND (End_Date__c = null OR End_Date__c >=: startDateFilter) AND Category__c =: category ';
        if (ServiceCenter != 'All') {
            strQuery += ' AND Service_Center__c =: ServiceCenter';
        }
        strQuery += ' ORDER BY Service_Center__c, Name';

        //system.debug('***strQuery' + strQuery);
        theResourceList = Database.query(strQuery);

        //system.debug('***theResourceList' + theResourceList);
        if (theResourceList != null && theResourceList.size() > 0) {
            for (Resource__c line : theResourceList) {
                TMLineWrapper wrapper = new TMLineWrapper();
                if (!TMHoursMap.containsKey(line.Id)) {
                    wrapper.HomeServiceCenter = line.Service_Center__r.Name;
                    wrapper.ResourceNo = line.Name;
                    wrapper.ResourceName = line.Description__c;
                    wrapper.FleetNumber = line.Fleet_Number__c;
                    wrapper.EquipmentGroup = line.Resource_Type__r.Equipment_Group__r.Name;
                    wrapper.ResourceType = line.Resource_Type__r.Name;
                    //Ticket 13360 >>
                    wrapper.Year = line.Vehicle_Year__c;
                    //Ticket 13360 <<
                    wrapper.Make = line.Make__c;
                    wrapper.Model = line.Model__c;
                    wrapper.VIN = line.VIN__c;
                    wrapper.SC_Hours = 0;
                    wrapper.IC_Hours = 0;
                    wrapper.Total_Hours = 0;
                    wrapper.Utilization = 0;
                    //wrapper.GoalHoursAssigned = 5 * CompanyMgmt.zeroIfNull(line.Goal_hours__c);
                    //wrapper.GoalHoursAssigned = getDaysBetweenExcludeingWeekends(startDateFilter, endDateFilter) * CompanyMgmt.zeroIfNull(line.Goal_hours__c);
                    wrapper.GoalHoursAssigned = 5 * CompanyMgmt.zeroIfNull(line.Goal_hours__c) * getNoWeeks (startDateFilter,endDateFilter);
                    wrapper.Delta = wrapper.Total_Hours - wrapper.GoalHoursAssigned;
                    TMLineMap.put(line.Id, wrapper);
                } else {
                    wrapper.HomeServiceCenter = line.Service_Center__r.Name;
                    wrapper.ResourceNo = line.Name;
                    wrapper.ResourceName = line.Description__c;
                    wrapper.FleetNumber = line.Fleet_Number__c;
                    wrapper.EquipmentGroup = line.Resource_Type__r.Equipment_Group__r.Name;
                    wrapper.ResourceType = line.Resource_Type__r.Name;
                    //Ticket 13360 >>
                    wrapper.Year = line.Vehicle_Year__c;
                    //Ticket 13360 <<
                    wrapper.Make = line.Make__c;
                    wrapper.Model = line.Model__c;
                    wrapper.VIN = line.VIN__c;
                    wrapper.Total_Hours = TMHoursMap.get(line.id).Total_Hours;
                    wrapper.SC_Hours = TMHoursMap.get(line.id).SC_Hours;
                    wrapper.IC_Hours = TMHoursMap.get(line.id).IC_Hours;
                    if (CompanyMgmt.zeroIfNull(wrapper.Total_Hours) != 0) {
                        wrapper.Utilization = wrapper.Total_Hours / (50 * getNoWeeks (startDateFilter,endDateFilter));
                    } else {
                        wrapper.Utilization = 0;
                    }
                    //wrapper.GoalHoursAssigned = 5 * CompanyMgmt.zeroIfNull(line.Goal_hours__c);
                    //wrapper.GoalHoursAssigned = getDaysBetweenExcludeingWeekends(startDateFilter, endDateFilter) * CompanyMgmt.zeroIfNull(line.Goal_hours__c);
                    wrapper.GoalHoursAssigned = 5 * CompanyMgmt.zeroIfNull(line.Goal_hours__c) * getNoWeeks (startDateFilter,endDateFilter);
                    wrapper.Delta = wrapper.Total_Hours - wrapper.GoalHoursAssigned;
                    TMLineMap.put(line.Id, wrapper);
                }
            }
        }

        return TMLineMap.values();
    }
    /******************* TM LINE Wrapper class *********************/
    public class TMHoursWrapper {
        @AuraEnabled
        public String ResourceId { get; set; }
        @AuraEnabled
        public Decimal Total_Hours { get; set; }
        @AuraEnabled
        public Decimal SC_Hours { get; set; }
        @AuraEnabled
        public Decimal IC_Hours { get; set; }
    }

    public class TMLineWrapper {
        @AuraEnabled
        public String HomeServiceCenter { get; set; }
        @AuraEnabled
        public String ResourceNo { get; set; }
        @AuraEnabled
        public String ResourceName {get; set; }
        @AuraEnabled
        public String FleetNumber { get; set; }
        @AuraEnabled
        public String EquipmentGroup { get; set; }
        @AuraEnabled
        public String ResourceType { get; set; }
        @AuraEnabled
        public String Year { get; set; } //Ticket# 13360
        @AuraEnabled
        public String Make { get; set; }
        @AuraEnabled
        public String Model { get; set; }
        @AuraEnabled
        public String VIN { get; set; }
        @AuraEnabled
        public Decimal Total_Hours { get; set; }
        @AuraEnabled
        public Decimal SC_Hours { get; set; }
        @AuraEnabled
        public Decimal IC_Hours { get; set; }
        @AuraEnabled
        public Decimal Utilization { get; set; }
        @AuraEnabled
        public Decimal GoalHoursAssigned { get; set; }
        @AuraEnabled
        public Decimal Delta { get; set; }
    }
}