objects/Contact/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ContactsSelector.cls
public class ContactsSelector extends fflib_SObjectSelector
{
    public static ContactsSelector newInstance()
    {
        return (ContactsSelector) Application.Selector.newInstance(Contact.SObjectType);
    }

    public SObjectType getSObjectType()
    {
        return Contact.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList()
    {
        return new List<SObjectField>{
                Contact.Id,
                Contact.Name,
                Contact.FirstName,
                Contact.LastName,
                Contact.Title,
                Contact.AccountId,
                Contact.Email,
                Contact.Phone,
                Contact.Contact_Type__c,
                Contact.Mobile_Email__c,
                Contact.Contact_Type__c,
                Contact.Blocked__c
        };
    }

    public List<Contact> selectContactsByIds(Set<Id> contactIds){
        return (List<Contact>) Database.query(newQueryFactory()
                .setCondition('Id IN :contactIds AND Blocked__c != TRUE')
                .toSOQL());
    }
    
    public List<Contact> selectBillingContactsByAccount(Set<Id> accountIds)
    {
        return (List<Contact>) Database.query(newQueryFactory().setCondition('AccountId IN :accountIds AND Contact_Type__c INCLUDES (\'Billing\') AND Blocked__c != TRUE').toSOQL());
    }

    public List<Contact> selectQuoteContactsByAccount(Set<Id> accountIds)
    {
        return (List<Contact>) Database.query(newQueryFactory().setCondition('AccountId IN :accountIds AND Contact_Type__c INCLUDES (\'Quote\') AND Blocked__c != TRUE').toSOQL());
    }
}