objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-REPUBLIC SERVICES</fullName>
            </value>
            <value>
                <fullName>5-RS-ES Gulf Coast</fullName>
            </value>
            <value>
                <fullName>1-ACV ENVIRO</fullName>
                <isActive>false</isActive>
                <label>1-ACV ENVIRO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/cwbtool__ErrorLog__c/cwbtool__ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Stores all the exceptions thrown by code</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendEQAIBillingProjectCtrlTest.cls
@isTest
public class SendEQAIBillingProjectCtrlTest {

     private static testMethod void Test_SalesOrderMgmt() {
         
		Contact cont = new Contact();
		cont.FirstName = 'test';
		cont.LastName = 'test';
		cont.AccountId = TestDataUtil.customerAccountRecord.id;
		cont.Contact_Type__c = 'Billing';
		insert cont;
         
          Contract contractRecord = new Contract (
                Name = 'Test ContractRecord',
                AccountId = TestDataUtil.customerAccountRecord.id,
                StartDate = Date.today().addDays(-200),
                Subsidiary__c = '1-REPUBLIC SERVICES',
                Status = 'Draft'
        );
        insert contractRecord ;
         SendEQAIBillingProjectCtrl.sendBillingProjectToEQAI(contractRecord.Id);
     }
    
    private static testMethod void testContractServiceException(){
        
        Test.startTest();
        SendEQAIBillingProjectCtrl.insertErrorLog('TEST_ERROR','InvalidId_Erro',93,'prinstrace','Request');
        Test.stopTest(); //Test
        List<cwbtool__ErrorLog__c> errorlogs = [SELECT Id FROM cwbtool__ErrorLog__c];
        System.assertEquals(true,errorlogs.size()>0);
    }
}