objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Project_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Project_Coordinator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Project Manager)</relationshipLabel>
    <relationshipName>TMs1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM__c/fields/Site_City__c.field-meta.xml
<CustomField>
    <fullName>Site_City__c</fullName>
    <label>Site City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/TM__c/fields/Site_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Site_Email_Address__c</fullName>
    <label>Site Email Address</label>
    <type>Email</type>
</CustomField>

objects/TM__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/TM__c/fields/Site_State__c.field-meta.xml
<CustomField>
    <fullName>Site_State__c</fullName>
    <label>Site State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Site_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

objects/TM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Mobile Review</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fully Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <isActive>false</isActive>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
                <isActive>false</isActive>
                <label>Partially Invoiced</label>
            </value>
            <value>
                <fullName>Pro forma Review</fullName>
                <isActive>false</isActive>
                <label>Pro forma Review</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <isActive>false</isActive>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Received By Billing</fullName>
                <isActive>false</isActive>
                <label>Received By Billing</label>
            </value>
            <value>
                <fullName>Received By Dispatch</fullName>
                <isActive>false</isActive>
                <label>Received By Dispatch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/DailyRosterController.cls
public class DailyRosterController {
    /*
    @AuraEnabled

    public static String getWOData(string scheduledDate) {
        system.debug('scheduledDate ***' + scheduledDate);
        String strMsg = 'OK';
        List<TM__c> theWOList = new List<TM__c>();
        try {
            if (string.isNotEmpty(scheduledDate)) {
                system.debug('1***');
                theWOList = [
                        SELECT Id, Name, Status__c, Site_City__c, Site_State__c, Project_Coordinator__r.Name, Site_Name__c, Site_Email_Address__c, Scheduled_Date__c
                        FROM TM__c
                        WHERE Scheduled_Date__c = :date.valueOf(scheduledDate)
                ];
            } else {
                system.debug('2***');
                theWOList = [SELECT Id, Name, Status__c, Site_City__c, Site_State__c, Project_Coordinator__r.Name, Site_Name__c, Site_Email_Address__c, Scheduled_Date__c FROM TM__c];
            }
        } catch (dmlexception e) {
            strMsg = e.getMessage();
        }

        if (strMsg == 'OK') {
            return JSON.serialize(new ResponseWrapper(strMsg, JSON.serialize(theWOList)));
        } else {
            return JSON.serialize(new ResponseWrapper(strMsg, ''));
        }
    }

    public class ResponseWrapper {
        @AuraEnabled
        public String respMsg { get; set; }
        @AuraEnabled
        public String respJson { get; set; }

        public ResponseWrapper(string respMsg, string respJson) {
            this.respMsg = respMsg;
            this.respJson = respJson;
        }
    }
    */
}