objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Executive</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <formula>User__r.RSG_EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSG EIN #</label>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Salesperson__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Salespeople</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/User/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <description>Employee Workday Number</description>
    <label>RSG EIN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/UserController.cls
public with sharing class UserController {

    @future
    public static void LinkSalespeople(List<Id> uIds) {
        Map<Id, Salesperson__c> mUsers = new Map<Id, Salesperson__c>();
        for (User u : [SELECT Id, Name, FirstName, LastName, UserRole.Name FROM User WHERE Id IN :uIds]) {
            if (u.UserRole != null && (u.UserRole.Name.startsWithIgnoreCase('AE') || u.UserRole.Name.startsWithIgnoreCase('BD'))) {
                mUsers.put(u.Id, new Salesperson__c(Name = u.Name, First_Name__c = u.FirstName, Last_Name__c = u.LastName, Account_Executive__c = true, User__c =  u.Id, Status__c = 'Active'));
            }
            else if (u.UserRole != null && u.UserRole.Name.startsWithIgnoreCase('PC')) {
                mUsers.put(u.Id, new Salesperson__c(Name = u.Name, First_Name__c = u.FirstName, Last_Name__c = u.LastName, Account_Executive__c = false, User__c = u.Id, Status__c = 'Active'));
            }
            else {
                //mUsers.put(u.Id, new Salesperson__c(Name = U.Name, First_Name__c = u.FirstName, Last_Name__c = u.LastName, User__c = u.Id, Status__c = 'Inactive'));
            }
        }

        List<Salesperson__c> salespeople = new List<Salesperson__c>();
                    
        List<Salesperson__c> sps = [SELECT Id, Name, First_Name__c, Last_Name__c, Salesperson_Code__c, User__c, Account_Executive__c, Status__c FROM Salesperson__c];
        Set<String> codes = new Set<String>();
        for (Salesperson__c sp : sps) {
            if (mUsers.containsKey(sp.User__c)) { //check if users already have a salesperson record
                Salesperson__c salesperson = mUsers.get(sp.User__c);
                sp.Account_Executive__c = salesperson.Account_Executive__c;
                sp.Status__c = salesperson.Status__c;
                salespeople.add(sp);
                mUsers.remove(sp.User__c); //remove the existing salesperson record from the queue
            }
            codes.add(sp.Salesperson_Code__c);
        }
        
        //assign codes to the new salesperson records
        for (Salesperson__c sp : mUsers.values()) {            
            String code = (sp.First_Name__c != null ? sp.First_Name__c.left(1) : '') + sp.Last_Name__c;
            if (code.length() >= 3) {
                code = code.left(3);
            }
            Integer i = 0;                
            while (codes.contains(code)) {
                code = code + i;
            }
            sp.Salesperson_Code__c = code.toUpperCase();
            codes.add(sp.Salesperson_Code__c);
            salespeople.add(sp);
        }
        upsert(salespeople);
    }
    //US144300: Resource Sync : Salesforce : Labor : New/Termed Labor Resources sync from EQAI to Salesforce
    //To set IsActive as false based on the request receive from EQAI
    @future
    public static void InactivateUser(Set<String> employeeIds) {
        List<User> updateUserList = new List<User>();
                for(User userRecord : [SELECT Id,Name,IsActive,RSG_EIN__c FROM User WHERE RSG_EIN__c IN: employeeIds]){
                    userRecord.IsActive = False;
                    updateUserList.add(userRecord);
                }
                if(!updateUserList.isEmpty()){
                    Database.SaveResult[] results = Database.update(updateUserList, false);
                }
    }
    
}