objects/Timesheet_Line__c/Timesheet_Line__c.object-meta.xml
<CustomObject>
    <label>Timesheet Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Timesheet Line No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Timesheet_Line__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

classes/TimesheetLineWrapper.cls
/**
 * Created by Steven on 7/20/2018.
 */

global class TimesheetLineWrapper implements Comparable{

    public Timesheet_Line__c theTL;

    // Constructor
    public TimesheetLineWrapper(Timesheet_Line__c tl){
        theTL = tl;
    }

    // Compare timesheet line based on the date.
    global Integer compareTo(Object compareTo){
        // Cast argument to TimesheetLineWrapper
        TimesheetLineWrapper compareToTheTL = (TimesheetLineWrapper)compareTo;

        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if(theTL.Scheduled_Date__c > compareToTheTL.theTL.Scheduled_Date__c){
            returnValue = 1;
        } else if (theTL.Scheduled_Date__c < compareToTheTL.theTL.Scheduled_Date__c){
            returnValue = -1;
        } else {
            if(theTL.Start_Time__c < compareToTheTL.theTL.Start_Time__c){
                returnValue = -1;
            } else if(theTL.Start_Time__c > compareToTheTL.theTL.Start_Time__c){
                returnValue = 1;
            }
        }

        return returnValue;
    }
}