objects/Auto_Number__c/Auto_Number__c.object-meta.xml
<CustomObject>
    <label>Auto Number</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auto_Number__c/fields/Displaying_Format__c.field-meta.xml
<CustomField>
    <fullName>Displaying_Format__c</fullName>
    <label>Displaying Format</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Auto_Number__c/fields/Starting_Number__c.field-meta.xml
<CustomField>
    <fullName>Starting_Number__c</fullName>
    <label>Starting Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/AutoNumberController.cls
public with sharing class AutoNumberController {
    public static Boolean ValidateFormatString(String formatString) {
        Pattern pat = Pattern.compile('\\{([^}]*)\\}');
        Matcher mat = pat.matcher(formatString);
        if (!mat.find() || mat.groupCount() != 1) {
            return false;
        }
        return true;
    }
    
    public static String GetNextNumber(String name) {
        Auto_Number__c autoNumber = [SELECT Id, Displaying_Format__c, Starting_Number__c FROM Auto_Number__c WHERE Name = :name LIMIT 1 FOR UPDATE];
        String nextNoSeries = '';
        String formatString = autoNumber.Displaying_Format__c;
        Pattern pat = Pattern.compile('\\{([^}]*)\\}');
        Matcher mat = pat.matcher(formatString);
        if (mat.find()) {
            if (mat.groupCount() == 1) {
                autoNumber.Starting_Number__c += 1;
                nextNoSeries = String.valueOf(autoNumber.Starting_Number__c.intValue());
                nextNoSeries = formatString.replace(mat.group(), nextNoSeries.leftPad(mat.group().length() - 2, '0'));
                update autoNumber;
            }
        }
        return nextNoSeries;
    }
}