objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Signature__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request_Date__c</fullName>
    <formula>Signature_Request__r.Request_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signature Request Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature__c/fields/Signature_Request_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request_Email_Sent__c</fullName>
    <formula>Signature_Request__r.Request_Email_Sent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signature Request Email Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Signer_Role__c.field-meta.xml
<CustomField>
    <fullName>Signer_Role__c</fullName>
    <label>Signer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Customer A</fullName>
            </value>
            <value>
                <fullName>Customer B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/fields/Site_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Site_Access_Token__c</fullName>
    <formula>Signature_Request__r.Site_Access__r.Token__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Access Token</label>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Token_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Token_Expiration_Date__c</fullName>
    <formula>Signature_Request__r.Site_Access__r.Expiration_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Token Expiration Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature__c/fields/Void_Reason__c.field-meta.xml
<CustomField>
    <fullName>Void_Reason__c</fullName>
    <label>Void Reason</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Declined__c.field-meta.xml
<CustomField>
    <fullName>Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Declined</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Site_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Site_Access_Token__c</fullName>
    <formula>Site_Access__r.Token__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Access Token</label>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Token_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Token_Expiration_Date__c</fullName>
    <formula>Site_Access__r.Expiration_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Token Expiration Date</label>
    <type>DateTime</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

classes/SignaturesSelector.cls
public with sharing class SignaturesSelector extends fflib_SObjectSelector implements ISignaturesSelector {
    public static ISignaturesSelector newInstance() {
        return (ISignaturesSelector) Application.Selector.newInstance(Signature__c.SObjectType);
    }

    public SObjectType getSObjectType() {
        return Signature__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                Signature__c.TM__c,
                Signature__c.Id,
                Signature__c.Signer_Role__c,
                Signature__c.Name,
                Signature__c.Print_Name__c,
                Signature__c.Email__c,
                Signature__c.Accept_Terms_and_Conditions__c,
                Signature__c.Customer_Not_Available__c,
                Signature__c.Request_Signature__c,
                Signature__c.Signature_Request_Date__c,
                Signature__c.Signature_Request_Email_Sent__c,
                Signature__c.Signature_Request__c,
                Signature__c.Site_Access_Token__c,
                Signature__c.Token_Expiration_Date__c,
                Signature__c.Signed__c,
                Signature__c.Signature_Date__c,
                Signature__c.Email__c,
                Signature__c.Voided__c,
                Signature__c.Void_Reason__c,
                //ticket 21113 <<
                Signature__c.Related_To_Object_Name__c,
                Signature__c.Related_To_Id__c,
                Signature__c.Declined__c,
                Signature__c.Customer_PO_No__c,
                Signature__c.Customer_Comment__c
                //ticket 21113 >>
        };
    }

    public List<Signature__c> selectById(Set<Id> ids) {
        return Database.query(newQueryFactory(true)
                .selectField('TM__r.Name')
                .selectField('Signature_Request__r.Signed__c')
                .selectField('Signature_Request__r.Signature_Date__c')
                .setCondition('Id IN :ids').toSOQL());
    }

    public List<Signature__c> selectByTMId(Set<Id> tmIds) {
        List<String> filters = new List<String>();
        filters.add('TM__c IN :tmIds');
        filters.add('Voided__c != TRUE');
        String conditions = String.join(filters, ' AND ');

        return Database.query(newQueryFactory(true)
                .selectField('TM__r.Name')
                .selectField('Signature_Request__r.Signed__c')
                .selectField('Signature_Request__r.Signature_Date__c')
                .setCondition(conditions).toSOQL());
    }

    public List<Signature__c> selectByRoles(Set<Id> tmIds, List<String> roles) {
        List<String> filters = new List<String>();
        filters.add('TM__c IN :tmIds');
        filters.add('Voided__c != TRUE');
        filters.add('Signer_Role__c IN :roles');
        String conditions = String.join(filters, ' AND ');

        return Database.query(newQueryFactory(true)
                .selectField('TM__r.Name')
                .selectField('Signature_Request__r.Signed__c')
                .selectField('Signature_Request__r.Signature_Date__c')
                .setCondition(conditions).toSOQL());
    }

    public Signature__c selectCustomerSignatureBySiteAccessToken(String siteAccessToken) {
        List<Signature__c> signatures = Database.query(newQueryFactory(true)
                .selectField('TM__r.Name')
                .selectField('Signature_Request__r.Signed__c')
                .selectField('Signature_Request__r.Signature_Date__c')
                .setCondition('Site_Access_Token__c = :siteAccessToken').toSOQL());
        if (signatures.size() > 0) {
            return signatures[0];
        }
        return null;
    }
}