objects/Parent_Child_Resource__c/Parent_Child_Resource__c.object-meta.xml
<CustomObject>
    <label>Parent Child Resource (Import)</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Child Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Parent_Child_Resource__c/fields/Child_1_Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Child_1_Resource_Type__c</fullName>
    <label>Child 1 Resource Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Parent_Child_Resource__c/fields/Child_1_UOM__c.field-meta.xml
<CustomField>
    <fullName>Child_1_UOM__c</fullName>
    <label>Child 1 UOM</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Parent_Child_Resource__c/fields/Child_2_Resource__c.field-meta.xml
<CustomField>
    <fullName>Child_2_Resource__c</fullName>
    <label>Child 2 Resource</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Parent_Child_Resource__c/fields/Child_2_UOM__c.field-meta.xml
<CustomField>
    <fullName>Child_2_UOM__c</fullName>
    <label>Child 2 UOM</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Parent_Child_Resource__c/fields/Child_3_Resource__c.field-meta.xml
<CustomField>
    <fullName>Child_3_Resource__c</fullName>
    <label>Child 3 Resource</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Parent_Child_Resource__c/fields/Child_3_UOM__c.field-meta.xml
<CustomField>
    <fullName>Child_3_UOM__c</fullName>
    <label>Child 3 UOM</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Parent_Child_Resource__c/fields/Parent_Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Parent_Resource_Type__c</fullName>
    <label>Parent Resource Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource__c/recordTypes/Material.recordType-meta.xml
<RecordType>
    <fullName>Material</fullName>
    <active>true</active>
    <label>Material</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Per Diem</fullName>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_Type__c/Sales_Order_Type__c.object-meta.xml
<CustomObject>
    <label>Sales Order Type</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template (Import)</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Template__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Template__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Template__c/fields/Sales_Order_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Type_Id__c</fullName>
    <label>Sales Order Type Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Template__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/ParentChildResourceImportTest.cls
@isTest
private class ParentChildResourceImportTest {
    private static testMethod void test() {
        createTestData();
        ParentChildResourceImport.importParentChildResources();
        ParentChildResourceImport.importTemplate();
        ParentChildResourceImport.updateSalesOrderTypes();
        ParentChildResourceImport.updateParentChildLines();
        ParentChildResourceImport.checkAllowZeroUnitCostResources();
    }


    private static void createTestData() {
        Map<String, Resource_Type__c> mapResourceTypesByName = new Map<String, Resource_Type__c>();
        Map<String, Resource__c> mapResourcesByName = new Map<String, Resource__c>();

        Unit_of_Measure__c unitOfMeasure = new Unit_of_Measure__c();
        unitOfMeasure.Name = 'EA';
        insert unitOfMeasure;

        Resource_Type__c parentResourceType = new Resource_Type__c();
        parentResourceType.Category__c = 'Labor';
        parentResourceType.Name = 'Parent Labor';
        parentResourceType.Unit_of_Measure__c = unitOfMeasure.Id;
        mapResourceTypesByName.Put(parentResourceType.Name, parentResourceType);

        Resource_Type__c childResourceType = new Resource_Type__c();
        childResourceType.Category__c = 'Labor';
        childResourceType.Name = 'Child Labor';
        childResourceType.Unit_of_Measure__c = unitOfMeasure.Id;
        mapResourceTypesByName.Put(childResourceType.Name, childResourceType);

        insert mapResourceTypesByName.values();

        Id recordTypeId = Schema.SObjectType.Resource__c.getRecordTypeInfosByName().get('Material').getRecordTypeId();
        Resource__c childResource = new Resource__c();
        childResource.RecordTypeId = recordTypeId;
        childResource.Name = 'Child Material';
        childResource.Category__c = 'Materials';
        childResource.Unit_of_Measure__c = unitOfMeasure.Id;
        mapResourcesByName.put(childResource.Name, childResource);

        recordTypeId = Schema.SObjectType.Resource__c.getRecordTypeInfosByName().get('Waste Disposal').getRecordTypeId();
        Resource__c childDemurageResource = new Resource__c();
        childDemurageResource.RecordTypeId = recordTypeId;
        childDemurageResource.Name = 'Child Demurrage';
        childDemurageResource.Category__c = 'Demurrage';
        childDemurageResource.Unit_of_Measure__c = unitOfMeasure.Id;
        mapResourcesByName.put(childDemurageResource.Name, childDemurageResource);

        insert mapResourcesByName.values();


        List<Parent_Child_Resource__c> parentChildResources = new List<Parent_Child_Resource__c>();

        Parent_Child_Resource__c parentChildResource = new Parent_Child_Resource__c();
        parentChildResource.Parent_Resource_Type__c = parentResourceType.Id;
        parentChildResource.Child_1_Resource_Type__c = childResourceType.Id;
        parentChildResource.Child_1_UOM__c = unitOfMeasure.Id;
        parentChildResources.add(parentChildResource);

        parentChildResource = new Parent_Child_Resource__c();
        parentChildResource.Parent_Resource_Type__c = parentResourceType.Id;
        parentChildResource.Child_2_Resource__c = childResource.Id;
        parentChildResource.Child_2_UOM__c = unitOfMeasure.Id;
        parentChildResources.add(parentChildResource);

        parentChildResource = new Parent_Child_Resource__c();
        parentChildResource.Parent_Resource_Type__c = parentResourceType.Id;
        parentChildResource.Child_3_Resource__c = childResource.Id;
        parentChildResource.Child_3_UOM__c = unitOfMeasure.Id;
        parentChildResources.add(parentChildResource);

        insert parentChildResources;


        //sales order type
        Sales_Order_Type__c salesOrderType = new Sales_Order_Type__c();
        salesOrderType.Name = 'Field Services';
        salesOrderType.Description__c = 'Field Services';
        insert salesOrderType;

        //templates
        List<Template__c> templates = new List<Template__c>();

        Template__c template = new Template__c();
        template.Name = 'Field Services';
        template.Sales_Order_Type_Id__c = salesOrderType.Id;
        template.Resource_Type__c = parentResourceType.Id;
        template.Unit_of_Measure__c = unitOfMeasure.Id;
        templates.add(template);

        template = new Template__c();
        template.Name = 'Field Services';
        template.Sales_Order_Type_Id__c = salesOrderType.Id;
        template.Resource__c = childResource.Id;
        template.Unit_of_Measure__c = unitOfMeasure.Id;
        templates.add(template);

        template = new Template__c();
        template.Name = 'Field Services';
        template.Sales_Order_Type_Id__c = salesOrderType.Id;
        template.Resource_Type__c = childResourceType.Id;
        template.Unit_of_Measure__c = unitOfMeasure.Id;
        templates.add(template);

        insert templates;
    }
}