objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/Sales_Invoice_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/fields/Invoice_Format__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Format__c</fullName>
    <label>Invoice Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>By Date by Category</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Print_Order__c.field-meta.xml
<CustomField>
    <fullName>Print_Order__c</fullName>
    <label>Print Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Job Tasks</relationshipLabel>
    <relationshipName>Sales_Invoice_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Include_SO_in_EQAI_Invoice_Integration__c.field-meta.xml
<CustomField>
    <fullName>Include_SO_in_EQAI_Invoice_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include SO in EQAI Invoice Integration</label>
    <type>Checkbox</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

classes/PrintSalesInvoiceConfirmationController.cls
/*************************************************************************************************
* Name         :  PrintSalesInvoiceConfirmationController
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Prabhu Rathakrishnan      12-14-2023             Task75275: Salesforce - Remove or disable the below on the Sales Invoice Object
*************************************************************************************************/
public with sharing class PrintSalesInvoiceConfirmationController {
    private final ApexPages.StandardController controller;
    public Sales_Invoice__c salesInvoice { get; set; }
    public String selPrintCopy { get; set; }
    public String selInvoiceType { get; set; }
    public List<Sales_Invoice_Job_Task__c> jobTasks { get; set; }

    public PrintSalesInvoiceConfirmationController(ApexPages.StandardController controller) {
        this.controller = controller;
        Set<Id> salesInvoiceIds = new Set<Id>{ this.controller.getId() };
        List<Sales_Invoice__c> salesInvoices = SalesInvoicesSelector.newInstance().selectById(salesInvoiceIds);
        if (salesInvoices.size() > 0) {
            this.salesInvoice = salesInvoices[0];
            this.jobTasks = SalesInvoiceJobTasksSelector.newInstance().selectBySalesInvoiceId(salesInvoiceIds);
           // validatePrintDocumentEligibility();
            for (Sales_Invoice_Job_Task__c jobTask : this.jobTasks) {
                if (jobTask.Invoice_Format__c == null) {
                    jobTask.Invoice_Format__c = 'Detail';
                }
            }
        }
        else {
            this.salesInvoice = new Sales_Invoice__c();
            this.jobTasks = new List<Sales_Invoice_Job_Task__c>();
        }
    }
    public void validatePrintDocumentEligibility(){
       /* if(this.salesInvoice.Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The Print Document function has been disabled for this Service Center'));
        }*/
    }

    public PageReference PrintNewSalesInvoice() {
        CompanyMgmt.byPassTrigger = true;
        update this.jobTasks;
		checkPrintingOrder();

        //ticket 19631 <<
        //PageReference redirectPage = new PageReference('/apex/NewSalesInvoicePdf?id=' + this.controller.getId() + '&PrintCopy=' + selPrintCopy + '&InvoiceType=' + selInvoiceType);
        //ticket 19127 <<
        //PageReference redirectPage = new PageReference('/apex/NewSalesInvoicePdf?id=' + this.controller.getId() + '&PrintCopy=' + selPrintCopy + '&InvoiceType=' + selInvoiceType + '&nonbillable=' + this.printNonBillableLines);
        PageReference redirectPage = new PageReference('/apex/NewSalesInvoicePdf?id=' + this.controller.getId() + '&PrintCopy=' + selPrintCopy);
        //ticket 19127 >>
        //ticket 19631 >>
        redirectPage.setRedirect(true);
        return redirectPage;
    }
    
    public String title {
        get {
            if (this.controller.getId() == null) {
                return 'New Invoice';
            } else {
                return this.salesInvoice.Name;
            }
        }
    }

    /*
     *  Ticket#20402 check printing order - prevent duplicate printer order.
     */
    private void checkPrintingOrder(){
        Set<Decimal> printOrders = new Set<Decimal>();
        for(Sales_Invoice_Job_Task__c salesInvoiceJobTask : this.jobTasks){
            if(salesInvoiceJobTask.Print_Order__c != null) {
                if (printOrders.contains(salesInvoiceJobTask.Print_Order__c)) {
                    throw new DataException('ERROR: There are more than one job task assigned with Print Order ' + salesInvoiceJobTask.Print_Order__c + ', please update the print order to continue!');
                } else {
                    printOrders.add(salesInvoiceJobTask.Print_Order__c);
                }
            }
        }
    }
}