objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/Sales_Invoice_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/fields/Billing_Pct__c.field-meta.xml
<CustomField>
    <fullName>Billing_Pct__c</fullName>
    <label>Billing %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Task-Based</fullName>
                <isActive>false</isActive>
                <label>Task-Based</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Fixed_Price_Surcharge_Option__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Surcharge_Option__c</fullName>
    <label>Fixed Price Surcharge Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price Does Not Include Surcharge</fullName>
            </value>
            <value>
                <fullName>Fixed Price Includes Surcharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Invoice_Format__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Format__c</fullName>
    <label>Invoice Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detail</fullName>
            </value>
            <value>
                <fullName>Summary</fullName>
            </value>
            <value>
                <fullName>By Date by Category</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Print_Order__c.field-meta.xml
<CustomField>
    <fullName>Print_Order__c</fullName>
    <label>Print Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Job Tasks</relationshipLabel>
    <relationshipName>Sales_Invoice_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order Job Task</label>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Invoice Job Tasks</relationshipLabel>
    <relationshipName>Sales_Invoice_Job_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Task_No__c.field-meta.xml
<CustomField>
    <fullName>Task_No__c</fullName>
    <formula>IF(Sales_Order_Job_Task__c != null, Sales_Order_Job_Task__r.Task_No__c, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Task No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>Tax_Group__c</fullName>
    <label>Tax Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Tax_Pct__c.field-meta.xml
<CustomField>
    <fullName>Tax_Pct__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/fields/Voided__c.field-meta.xml
<CustomField>
    <fullName>Voided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Voided</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order_Job_Task__c/Sales_Order_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Order Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Order_Job_Task__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Task-Based</fullName>
                <isActive>false</isActive>
                <label>Task-Based</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Fixed_Price_Surcharge_Option__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Surcharge_Option__c</fullName>
    <label>Fixed Price Surcharge Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price Does Not Include Surcharge</fullName>
            </value>
            <value>
                <fullName>Fixed Price Includes Surcharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Task_No__c.field-meta.xml
<CustomField>
    <fullName>Task_No__c</fullName>
    <label>Task No.</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Order_Job_Task__c/fields/Tax_Group__c.field-meta.xml
<CustomField>
    <fullName>Tax_Group__c</fullName>
    <label>Tax Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SalesInvoiceJobTasksSelector.cls
public with sharing class SalesInvoiceJobTasksSelector extends fflib_SObjectSelector implements ISalesInvoiceJobTasksSelector {
    public static ISalesInvoiceJobTasksSelector newInstance() {
        return (ISalesInvoiceJobTasksSelector) Application.Selector.newInstance(Sales_Invoice_Job_Task__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType() {
        return Sales_Invoice_Job_Task__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Sales_Invoice_Job_Task__c.Id,
                Sales_Invoice_Job_Task__c.Name,
                Sales_Invoice_Job_Task__c.Line_No__c,
                Sales_Invoice_Job_Task__c.Task_No__c,
                Sales_Invoice_Job_Task__c.Print_Order__c, //Ticket#20402
                Sales_Invoice_Job_Task__c.Sales_Invoice__c,
                Sales_Invoice_Job_Task__c.Sales_Order_Job_Task__c,
                Sales_Invoice_Job_Task__c.Billing_Type__c,
                Sales_Invoice_Job_Task__c.Billing_Amount__c,
                Sales_Invoice_Job_Task__c.Tax__c,
                Sales_Invoice_Job_Task__c.Tax_Pct__c,
                Sales_Invoice_Job_Task__c.Tax_Group__c,
                Sales_Invoice_Job_Task__c.Billing_Pct__c,
                Sales_Invoice_Job_Task__c.Voided__c,
                //ticket 19127 <<
                Sales_Invoice_Job_Task__c.Invoice_Format__c,
                //ticket 19127 >>
                //ticket 19672 <<
                Sales_Invoice_Job_Task__c.Fixed_Price_Surcharge_Option__c
                //ticket 19672 >>
        };
    }

    public List<Sales_Invoice_Job_Task__c> selectById(Set<Id> idSet){
        return (List<Sales_Invoice_Job_Task__c>) Database.query(newQueryFactory()
                .selectField('Sales_Invoice__r.Name')
                .setCondition('Id IN :idSet')
                .setOrdering('Line_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }

    public List<Sales_Invoice_Job_Task__c> selectBySalesInvoiceId(Set<Id> idSet){
        return selectByJobTaskId(idSet, null);
    }

    public List<Sales_Invoice_Job_Task__c> selectByJobTaskId(Set<Id> salesInvoiceIds, Set<Id> jobTaskIds){
        List<String> filters = new List<String>();
        filters.add('Sales_Invoice__c IN :salesInvoiceIds');
        if (jobTaskIds != null && jobTaskIds.size() > 0) {
            filters.add('Id IN :jobTaskIds');
        }

        return (List<Sales_Invoice_Job_Task__c>) Database.query(newQueryFactory(true)
                .setCondition(String.join(filters, ' AND '))
                .setOrdering('Line_No__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }

    //Ticket#20402
    public List<Sales_Invoice_Job_Task__c> selectBySalesInvoiceIdForPrint(Set<Id> ids){
        return (List<Sales_Invoice_Job_Task__c>) Database.query(newQueryFactory()
                .setCondition('Sales_Invoice__c IN :ids')
                .setOrdering('Print_Order__c', fflib_QueryFactory.SortOrder.ASCENDING, true)
                .toSOQL());
    }
}