objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/Sales_Invoice_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Job Tasks</relationshipLabel>
    <relationshipName>Sales_Invoice_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Invoice__c</field>
            <operation>equals</operation>
            <valueField>Sales_Invoice_Job_Task__c.Sales_Invoice__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ACVSalesInvoiceLineController.cls
public with sharing class ACVSalesInvoiceLineController {


    @AuraEnabled
    public static String validateResourceType(String JSONSalesInvoice, String JSONJobTask, String JSONSalesInvoiceLine) {
        try {
            Sales_Invoice__c salesInvoice = JSONToSalesInvoice(JSONSalesInvoice);
            Sales_Invoice_Job_Task__c jobTask = JSONToJobTask(JSONJobTask);
            Sales_Invoice_Line__c salesInvoiceLine = JSONToSalesInvoiceLine(JSONSalesInvoiceLine);

            SalesInvoiceLinesService.initStaticVariables(salesInvoice, jobTask, salesInvoiceLine);
            SalesInvoiceLinesService.validateResourceType(salesInvoice, salesInvoiceLine);
            return JSON.serialize(salesInvoiceLine);
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String validateResource(String JSONSalesInvoice, String JSONJobTask, String JSONSalesInvoiceLine) {
        try {
            Sales_Invoice__c salesInvoice = JSONToSalesInvoice(JSONSalesInvoice);
            Sales_Invoice_Job_Task__c jobTask = JSONToJobTask(JSONJobTask);
            Sales_Invoice_Line__c salesInvoiceLine = JSONToSalesInvoiceLine(JSONSalesInvoiceLine);

            SalesInvoiceLinesService.initStaticVariables(salesInvoice, jobTask, salesInvoiceLine);
            SalesInvoiceLinesService.validateResource(salesInvoice, salesInvoiceLine);

            return JSON.serialize(salesInvoiceLine);
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String calculatePriceAndCost(String JSONSalesInvoice, String JSONJobTask, String JSONSalesInvoiceLine) {
        try {
            Sales_Invoice__c salesInvoice = JSONToSalesInvoice(JSONSalesInvoice);
            Sales_Invoice_Job_Task__c jobTask = JSONToJobTask(JSONJobTask);
            Sales_Invoice_Line__c salesInvoiceLine = JSONToSalesInvoiceLine(JSONSalesInvoiceLine);

            SalesInvoiceLinesService.initStaticVariables(salesInvoice, jobTask, salesInvoiceLine);
            SalesInvoiceLinesService.calculatePriceAndCost(salesInvoice, salesInvoiceLine); 
            return JSON.serialize(salesInvoiceLine);
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String calculateTaxPct(String JSONSalesInvoice, String JSONJobTask, String JSONSalesInvoiceLine) {
        try {
            Sales_Invoice__c salesInvoice = JSONToSalesInvoice(JSONSalesInvoice);
            Sales_Invoice_Job_Task__c jobTask = JSONToJobTask(JSONJobTask);
            Sales_Invoice_Line__c salesInvoiceLine = JSONToSalesInvoiceLine(JSONSalesInvoiceLine);

            SalesInvoiceLinesService.initStaticVariables(salesInvoice, jobTask, salesInvoiceLine);
            SalesInvoiceLinesService.assignTaxPercent(salesInvoice, salesInvoiceLine);
            return JSON.serialize(salesInvoiceLine);
        }
        catch(exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    private static Sales_Invoice__c JSONToSalesInvoice(String JSONSalesInvoice) {
        return (Sales_Invoice__c)JSON.deserialize(JSONSalesInvoice, Sales_Invoice__c.class);
    }

    private static Sales_Invoice_Job_Task__c JSONToJobTask(String JSONJobTask) {
        return (Sales_Invoice_Job_Task__c)JSON.deserialize(JSONJobTask, Sales_Invoice_Job_Task__c.class);
    }

    private static List<ACVSalesInvoiceJobTaskWrapper> JSONToJobTaskWrappers(String JSONJobTaskWrappers) {
        return (List<ACVSalesInvoiceJobTaskWrapper>)JSON.deserialize(JSONJobTaskWrappers, List<ACVSalesInvoiceJobTaskWrapper>.class);
    }

    private static ACVSalesInvoiceJobTaskWrapper JSONToJobTaskWrapper(String JSONJobTaskWrapper) {
        return (ACVSalesInvoiceJobTaskWrapper)JSON.deserialize(JSONJobTaskWrapper, ACVSalesInvoiceJobTaskWrapper.class);
    }

    private static Sales_Invoice_Line__c JSONToSalesInvoiceLine(String JSONSalesInvoiceLine) {
        return (Sales_Invoice_Line__c)JSON.deserialize(JSONSalesInvoiceLine, Sales_Invoice_Line__c.class);
    }
}