objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice__c/fields/Recall_Submitted_EQAI_BPR_clicked__c.field-meta.xml
<CustomField>
    <fullName>Recall_Submitted_EQAI_BPR_clicked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recall Submitted EQAI BPR clicked</label>
    <type>Checkbox</type>
</CustomField>

classes/RecallEQAIBillingPackageTest.cls
@isTest
public with sharing class RecallEQAIBillingPackageTest {
    
    @isTest
    public static void RecallEQAIBillingPackageCtrlTest() {
        //test data

        NewTestData.createTestData();

        Test.startTest();
        Sales_Invoice__c salesInvoice = NewTestData.mapSalesInvoicesByName.get('INVOICE01');
        salesInvoice.Document_Status__c = 'Sent to EQAI';
        salesInvoice.Recall_Submitted_EQAI_BPR_clicked__c = true;
        update salesInvoice;
        RecallEQAIBillingPackageCtrl.updateDocumentStatus(salesInvoice.Id);
        Test.stopTest();
    }

    @isTest
    public static void RecallSubmittedEQAIBillingPackageCtrlTest() {

        NewTestData.createTestData();

        Test.startTest();
        Sales_Invoice__c salesInvoice = NewTestData.mapSalesInvoicesByName.get('INVOICE01');
        salesInvoice.Document_Status__c = 'Sent to EQAI';
        salesInvoice.Recall_Submitted_EQAI_BPR_clicked__c = false;
        update salesInvoice;
        RecallSubmittedEQAIBillingPackageCtrl.createCaseRecord(salesInvoice.Id);
        Test.stopTest();
    }
}