objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Memo</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice__c/fields/Reversed_from_SI__c.field-meta.xml
<CustomField>
    <fullName>Reversed_from_SI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed from SI</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/TM_Line__c.field-meta.xml
<CustomField>
    <fullName>TM_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M Line</label>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Invoiced_Lines__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Lines__c</fullName>
    <label>Invoiced Lines</label>
    <summaryFilterItems>
        <field>TM_Line__c.Invoiced__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Mobile Review</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fully Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <isActive>false</isActive>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
                <isActive>false</isActive>
                <label>Partially Invoiced</label>
            </value>
            <value>
                <fullName>Pro forma Review</fullName>
                <isActive>false</isActive>
                <label>Pro forma Review</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <isActive>false</isActive>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Received By Billing</fullName>
                <isActive>false</isActive>
                <label>Received By Billing</label>
            </value>
            <value>
                <fullName>Received By Dispatch</fullName>
                <isActive>false</isActive>
                <label>Received By Dispatch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TM__c/fields/Total_Lines__c.field-meta.xml
<CustomField>
    <fullName>Total_Lines__c</fullName>
    <label>Total Lines</label>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/recordTypes/Open.recordType-meta.xml
<RecordType>
    <fullName>Open</fullName>
    <active>true</active>
    <label>Open</label>
    
    
</RecordType>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

objects/TM_Line__c/fields/Parent_Line__c.field-meta.xml
<CustomField>
    <fullName>Parent_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TM_Line__c.TM__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.TM__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Line</label>
    <referenceTo>Sales_Invoice_Line__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/UnpostSalesInvoiceController.cls
public with sharing class UnpostSalesInvoiceController {
    private final ApexPages.StandardController controller;
    public Sales_Invoice__c salesInvoice { get; set; }

    public UnpostSalesInvoiceController(ApexPages.StandardController controller) {
        this.controller = controller;
        Set<Id> salesInvoiceIds = new Set<Id>{ this.controller.getId() };
        this.salesInvoice = SalesInvoicesSelector.newInstance().selectById(salesInvoiceIds)[0];
    }

    public String docType {
        get {
            if (!this.salesInvoice.Credit_Memo__c) {
                return 'Sales Invoice';
            } else {
                return 'Credit Memo';
            }
        }
    }

    public Boolean posted {
        get {
            if (this.salesInvoice.Document_Status__c == 'Posted' || this.salesInvoice.Document_Status__c == 'Void') {
                return true;
            } else {
                return false;
            }
        }
    }

    public List<String> getMessages() {
        return new List<String>{
            'Document Status: ' + this.salesInvoice.Document_Status__c, '', ''
        };
    }

    public PageReference unpostSalesInvoice() {

        if (CompanyMgmt.checkUnpostPermission() == false && !Test.isRunningTest()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You are not allowed to unpost transactions.'));
        } else {

            List<String> errorList = new List<String>();
            errorList = SalesInvoiceMgmt.unpostCheck(this.salesInvoice);
            if (errorList.size() > 0 && !Test.isRunningTest()) {
                for (Integer i = 0; i < errorList.size(); i++){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorList[i]));
                }
                return null;
            }

            Savepoint sp = Database.setSavepoint();
            try {
                SalesInvoiceMgmt.unpostSI(this.salesInvoice);
                this.salesInvoice.Document_Status__c = 'Open';
                update this.salesInvoice;

                List<Sales_Invoice_Line__c> invoiceLines = SalesInvoiceLinesSelector.newInstance().selectByInvoiceId(this.controller.getId());

                Set<String> tmIds = new Set<String>();
                for (Sales_Invoice_Line__c invoiceLine : invoiceLines) {
                    if (invoiceLine.TM__c != null && !tmIds.contains(invoiceLine.TM__c)) {
                        tmIds.add(invoiceLine.TM__c);
                    }
                }
                
                List<TM__c> tms = new List<TM__c>();
                if (tmIds.size() > 0) {
                    tms = [SELECT Id, Name, Invoiced_Lines__c, Total_Lines__c , Status__c, Sales_Invoice__c,
                            Sales_Invoice__r.Name, (SELECT Id, Invoiced__c FROM TM_Lines__r)
                    FROM TM__c WHERE Id IN :tmIds];
                }

                tms = TMMgmt.updateTMStatus(tms);
                List<TM_Line__c> tmLinesToUpdate = new List<TM_Line__c>();
                if (tms != null && tms.size() > 0) {
                    for (TM__c TM : tms) {
                        if (this.salesInvoice.Credit_Memo__c) {
                            if(String.isBlank(TM.Sales_Invoice__c)){
                                TM.Sales_Invoice__c = this.salesInvoice.Reversed_from_SI__c;
                                TM.Status__c = 'Fully Invoiced';
                                List<TM_Line__c> tmLines = TM.TM_Lines__r;
                                for(TM_Line__c tml : tmLines){
                                    tml.Invoiced__c = true;
                                    tmLinesToUpdate.add(tml);
                                }
                            } else if (TM.Sales_Invoice__c != this.salesInvoice.Reversed_from_SI__c && String.isNotBlank(this.salesInvoice.Reversed_from_SI__c)){
                                throw new DataException('Cannot un-post this credit memo because T&M associated with the credit memo is already re-invoiced');
                            }
                        } else {
                            TM.Sales_Invoice__c = this.salesInvoice.Id;
                        }
                    }
                }
                update tms;
                if(tmLinesToUpdate.size() > 0) update tmLinesToUpdate;

                if (!this.salesInvoice.Credit_Memo__c) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You have successfully unposted Sales Invoice.'));
                } else {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You have successfully unposted Sales Credit Memo.'));
                }
            } catch (Exception e) {
                //Rollback
                Database.rollback(sp);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return null;
            }
        }
        return null;
    }
}