objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/ISalesInvoicesService.cls
public interface ISalesInvoicesService {
	Sales_Invoice__c createCreditMemo(Sales_Invoice__c recordToReverse, Id creditMemoWorksheetId);
	void submitForApproval(Id recordId);
    void submitForApproval(Id recordId, Boolean isInitialApprovalRequest);
    /*
     * Ticket#16912
     * add approval comment
     */
    void submitForApproval(Id recordId, Boolean isInitialApprovalRequest, String comment);
	Map<Id, String> getParentInvIdWithNextReversionInvNum(Set<Id> tmIds, Set<Id> tmlIds);
	Decimal calcSurchargeAmount(Sales_Invoice__c salesInvoice, List<Sales_Invoice_Line__c> salesInvoiceLines);
}