objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/Sales_Invoice_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Job Tasks</relationshipLabel>
    <relationshipName>Sales_Invoice_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Invoice__c</field>
            <operation>equals</operation>
            <valueField>Sales_Invoice_Job_Task__c.Sales_Invoice__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesInvoiceLinesService.cls
global with sharing class SalesInvoiceLinesService {
    private static ISalesInvoiceLinesService service() {
        return (ISalesInvoiceLinesService) Application.Service.newInstance(ISalesInvoiceLinesService.class);
    }

    global static void initStaticVariables(Sales_Invoice__c salesInvoice, List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers) {
        service().initStaticVariables(salesInvoice, jobTaskWrappers);
    }

    global static void initStaticVariables(Sales_Invoice__c salesInvoice, ACVSalesInvoiceJobTaskWrapper jobTaskWrapper) {
        List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers = new List<ACVSalesInvoiceJobTaskWrapper>{ jobTaskWrapper };
        service().initStaticVariables(salesInvoice, jobTaskWrappers);
    }

    global static void initStaticVariables(Sales_Invoice__c salesInvoice, Sales_Invoice_Job_Task__c jobTask, Sales_Invoice_Line__c salesInvoiceLine) {
        List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers = new List<ACVSalesInvoiceJobTaskWrapper>();
        ACVSalesInvoiceJobTaskWrapper jobTaskWrapper = new ACVSalesInvoiceJobTaskWrapper();
        jobTaskWrapper.JobTask = jobTask;
        jobTaskWrapper.SalesInvoiceLines.add(salesInvoiceLine);
        jobTaskWrappers.add(jobTaskWrapper);
        service().initStaticVariables(salesInvoice, jobTaskWrappers);
    }

    global static void validateResourceType(Sales_Invoice__c salesInvoice, Sales_Invoice_Line__c salesInvoiceLine) {
        service().assignDescription(salesInvoiceLine);
        if (salesInvoiceLine.Unit_of_Measure__c == null) {
            service().assignUnitOfMeasure(salesInvoiceLine);
        }
        service().assignResourceTypeUOM(salesInvoiceLine);
        service().calcUnitCost(salesInvoice, salesInvoiceLine);
        service().assignTaxPercent(salesInvoice, salesInvoiceLine);
        service().calculateLineTotals(salesInvoice, salesInvoiceLine);
    }

    global static void validateResource(Sales_Invoice__c salesInvoice, Sales_Invoice_Line__c salesInvoiceLine) {
        service().assignDescription(salesInvoiceLine);
        if (salesInvoiceLine.Unit_of_Measure__c == null) {
            service().assignUnitOfMeasure(salesInvoiceLine);
        }
        service().assignResourceUOM(salesInvoiceLine);
        service().calcUnitCost(salesInvoice, salesInvoiceLine);
        service().assignTaxPercent(salesInvoice, salesInvoiceLine);
        service().calculateLineTotals(salesInvoice, salesInvoiceLine);
    }

    global static void calculatePriceAndCost(Sales_Invoice__c salesInvoice, Sales_Invoice_Line__c salesInvoiceLine) {
        service().calcUnitCost(salesInvoice, salesInvoiceLine);
        service().calculateLineTotals(salesInvoice, salesInvoiceLine);
    }

    global static void assignTaxPercent(Sales_Invoice__c salesInvoice, Sales_Invoice_Line__c salesInvoiceLine) {
        service().assignTaxPercent(salesInvoice, salesInvoiceLine);
        service().calculateLineTotals(salesInvoice, salesInvoiceLine);
    }

    global static void calculateLineTotals(Sales_Invoice__c salesInvoice, List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers) {
        for (ACVSalesInvoiceJobTaskWrapper jobTaskWrapper : jobTaskWrappers) {
            for (Sales_Invoice_Line__c salesInvoiceLine : jobTaskWrapper.SalesInvoiceLines) {
                service().calculateLineTotals(salesInvoice, salesInvoiceLine);
            }
        }
    }
}