objects/Contract/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Account.Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract_Line__c/Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Contract Line</label>
    <nameField>
        <label>contract line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Line__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract_Line__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <label>Customer Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_Item_No__c</fullName>
    <label>Customer Item No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Overtime_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Overtime_Description__c</fullName>
    <label>Customer Overtime Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Overtime_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_Overtime_Item_No__c</fullName>
    <label>Customer Overtime Item No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Premium_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Premium_Description__c</fullName>
    <label>Customer Double Time Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Premium_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_Premium_Item_No__c</fullName>
    <label>Customer Double Time Item No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract_Line__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Min_Sell_Qty__c.field-meta.xml
<CustomField>
    <fullName>Min_Sell_Qty__c</fullName>
    <label>Min. Sell Qty.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Contract_Line__c/fields/Min_Sell_Qty_Container_Size__c.field-meta.xml
<CustomField>
    <fullName>Min_Sell_Qty_Container_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Min Sell Qty. Container Size</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Contract Lines (Min Sell Qty. Container Size)</relationshipLabel>
    <relationshipName>Contract_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Overtime_Rate__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Rate__c</fullName>
    <label>Overtime Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Contract_Line__c/fields/Premium_Rate__c.field-meta.xml
<CustomField>
    <fullName>Premium_Rate__c</fullName>
    <label>Double Time Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Contract_Line__c/fields/Regular_Rate__c.field-meta.xml
<CustomField>
    <fullName>Regular_Rate__c</fullName>
    <label>Regular Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Contract_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Resource_Category__c.field-meta.xml
<CustomField>
    <fullName>Resource_Category__c</fullName>
    <formula>TEXT(Resource__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Category</label>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Resource_Type_Category__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type_Category__c</fullName>
    <formula>TEXT(Resource_Type__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Type Category</label>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/T_M_Description__c.field-meta.xml
<CustomField>
    <fullName>T_M_Description__c</fullName>
    <label>T&amp;M Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field is used to prevent users from selecting a resource type if the date selected is prior the current date.  Otherwise it will allow billing to be completed for existing sales lines, TM lines, and billing worksheets.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Unit_of_Measure__c/fields/Hours_UOM__c.field-meta.xml
<CustomField>
    <fullName>Hours_UOM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hours UOM</label>
    <type>Checkbox</type>
</CustomField>

classes/ContractLinesSelector.cls
public class ContractLinesSelector extends fflib_SObjectSelector implements IContractLinesSelector{

    public static IContractLinesSelector newInstance() {
        return (IContractLinesSelector) Application.Selector.newInstance(Contract_Line__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType() {
        return Contract_Line__c.SObjectType;
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Contract_Line__c.Id,
                Contract_Line__c.Name,
                Contract_Line__c.Resource__c,
                Contract_Line__c.Resource_Type__c,
                Contract_Line__c.Contract__c,
                Contract_Line__c.Resource_Category__c,
                Contract_Line__c.Resource_Type_Category__c,
                Contract_Line__c.Unit_of_Measure__c,
                Contract_Line__c.Regular_Rate__c,
                Contract_Line__c.Overtime_Rate__c,
                Contract_Line__c.Premium_Rate__c,
                Contract_Line__c.Customer_Description__c,
                Contract_Line__c.Customer_Item_No__c,
                Contract_Line__c.Customer_Overtime_Description__c,
                Contract_Line__c.Customer_Overtime_Item_No__c,
                Contract_Line__c.Customer_Premium_Description__c,
                Contract_Line__c.Customer_Premium_Item_No__c,
                Contract_Line__c.Min_Sell_Qty__c,
                Contract_Line__c.Min_Sell_Qty_Container_Size__c,
                Contract_Line__c.Facility__c,
                Contract_Line__c.Default__c,
                Contract_Line__c.Blocked__c,
                Contract_Line__c.End_Date__c
        };
    }

    public Map<Id, Contract_Line__c> selectTMDescriptionById (Set<Id> idSet){
        return new Map<Id, Contract_Line__c>((List<Contract_Line__c>) System.Database.query(
                newQueryFactory().selectField(Contract_Line__c.T_M_Description__c).setCondition('Id IN :idSet').toSOQL()));
    }

    public List<Contract_Line__c> selectById(Set<Id> idSet){
        return (List<Contract_Line__c>) Database.query(newQueryFactory()
                .selectField('Unit_of_Measure__r.Id')
                .selectField('Unit_of_Measure__r.Name')
                .setCondition('Id IN :idSet').toSOQL());
    }

    public List<Contract_Line__c> selectLinesByContractId(Set<Id> idSet) {
        return (List<Contract_Line__c>) Database.query(newQueryFactory()
                .selectField('Unit_of_Measure__r.Id')
                .selectField('Unit_of_Measure__r.Name')
                //aura <<
                .selectField('Unit_of_Measure__r.Hours_UOM__c')
                //aura >>
                .selectField('Resource__r.Name')
                .selectField('Resource_Type__r.Name')
                .setCondition('Contract__c IN :idSet').toSOQL());
    }

    public List<Contract_Line__c> selectLinesByContractIdByWorkDate(Set<Id> idSet, Date workDate){
        return (List<Contract_Line__c>) Database.query(newQueryFactory()
                .selectField('Unit_of_Measure__r.Name')
                .selectField('Unit_of_Measure__r.Hours_UOM__c')
                .selectField('Resource__r.Name')
                .selectField('Resource_Type__r.Name')
                //job task <<
                .selectField('Contract__r.Name')
                .selectField('Contract__r.ContractNumber')
                //job task >>
                .setCondition('Contract__c IN :idSet AND (Blocked__c = false OR End_Date__c >= :workDate)')
                .setOrdering('End_Date__c', fflib_QueryFactory.SortOrder.ASCENDING, false)
                .addOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING)
                .toSOQL());
    }

    /*
        Key format ContractId:ResourceType:UOM
     */
    public Map<String, Contract_Line__c> selectLinesWithContractIdResTypeAndUOMByContractId(Set<Id> contractIdSet){
        List<Contract_Line__c> contractLines = selectLinesByContractId(contractIdSet);
        Map<String, Contract_Line__c> linesWithContractIdResTypeAndUOM = new Map<String, Contract_Line__c>();
        for (Contract_Line__c contractLine : contractLines) {
            if(contractLine.Resource_Type__c != null){
                String mapKey = contractLine.Contract__c + ':' + contractLine.Resource_Type__c + ':' + contractLine.Unit_of_Measure__c;
                linesWithContractIdResTypeAndUOM.put(mapKey, contractLine);
            }
        }

        System.debug('Info: selectLinesWithContractIdResTypeAndUOMByContractId ' + linesWithContractIdResTypeAndUOM);
        return linesWithContractIdResTypeAndUOM;
    }

    /*
        Key format ContractId:Resource:UOM
     */
    public Map<String, Contract_Line__c> selectLinesWithContractIdResAndUOMByContractId(Set<Id> contractIdSet){
        List<Contract_Line__c> contractLines = selectLinesByContractId(contractIdSet);
        Map<String, Contract_Line__c> linesWithContractIdResAndUOM = new Map<String, Contract_Line__c>();
        for (Contract_Line__c contractLine : contractLines) {
            if(contractLine.Resource__c != null){
                String mapKey = contractLine.Contract__c + ':' + contractLine.Resource__c + ':' + contractLine.Unit_of_Measure__c;
                linesWithContractIdResAndUOM.put(mapKey, contractLine);
            }
        }
        System.debug('Info: linesWithContractIdResAndUOM ' + linesWithContractIdResAndUOM);
        return linesWithContractIdResAndUOM;
    }

    public Map<String, Contract_Line__c> mapLineByContractResORResourceTypeAndUOM(Set<Id> contractIds){
        Map<String, Contract_Line__c> lineByContractByResORResTypeByUOM = new Map<String, Contract_Line__c>();
        for(Contract_Line__c contractLine :selectLinesByContractId(contractIds)){
            String mapKey = '';
            if(contractLine.Resource__c != null){
                mapKey = mapKey = contractLine.Contract__c + ':' + contractLine.Resource__c + ':' + contractLine.Unit_of_Measure__c;
            }

            if(contractLine.Resource_Type__c != null && contractLine.Resource__c == null){
                mapKey = contractLine.Contract__c + ':' + contractLine.Resource_Type__c + ':' + contractLine.Unit_of_Measure__c;
            }
            if(String.isNotBlank(mapKey)) lineByContractByResORResTypeByUOM.put(mapKey, contractLine);
        }

        return lineByContractByResORResTypeByUOM;
    }
}