objects/Contract/fields/Override_Remittance_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Override_Remittance_on_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Remittance on Invoice</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Override_Remittance_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Override_Remittance_on_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Remittance on Invoice</label>
    <type>Checkbox</type>
</CustomField>

classes/SalesInvoicePDFControllerTest.cls
@isTest
private class SalesInvoicePDFControllerTest {
    private static testMethod void test() {
        NewTestData.createTestData();
        Test.startTest();
        Sales_Invoice__c salesInvoice = NewTestData.mapSalesInvoicesByName.get('INVOICE01');
        PageReference pdfPage = Page.NewSalesInvoicePDF;
        Test.setCurrentPage(pdfPage);
        ApexPages.currentPage().getParameters().put('id', salesInvoice.Id);

        ApexPages.currentPage().getParameters().put('InvoiceType', 'TM by Date by Category');
        SalesInvoicePDFController salesInvoicePDFController = new SalesInvoicePDFController();

        Test.stopTest();
    }
    private static testMethod void test1() {
        NewTestData.createTestData();
        Test.startTest();
		List<Contract> contractList = [SELECT ID, Name,Override_Remittance_on_Invoice__c FROM Contract];

        for(Contract updContract : contractList){
            updContract.Override_Remittance_on_Invoice__c = false;
        }
        update contractList;
        Sales_Invoice__c salesInvoice = NewTestData.mapSalesInvoicesByName.get('INVOICE01');

        PageReference pdfPage = Page.NewSalesInvoicePDF;
        Test.setCurrentPage(pdfPage);
        ApexPages.currentPage().getParameters().put('id', salesInvoice.Id);

        ApexPages.currentPage().getParameters().put('InvoiceType', 'TM by Date by Category');
        SalesInvoicePDFController salesInvoicePDFController = new SalesInvoicePDFController();

        Test.stopTest();
    }    
    private static testMethod void test2() {
        NewTestData.createTestData();
        Test.startTest();
        List<Service_Center__c> serviceCenterList = [SELECT Id, Name,Override_Remittance_on_Invoice__c FROM Service_Center__c];
        for(Service_Center__c srvCent: serviceCenterList){
            srvCent.Override_Remittance_on_Invoice__c = true;
        }
        update serviceCenterList;
        
        List<Contract> contractList = [SELECT ID, Name,Override_Remittance_on_Invoice__c FROM Contract];
        for(Contract updContract : contractList){
            updContract.Override_Remittance_on_Invoice__c = false;
        }
        update contractList;

        Sales_Invoice__c salesInvoice = NewTestData.mapSalesInvoicesByName.get('INVOICE01');

        PageReference pdfPage = Page.NewSalesInvoicePDF;
        Test.setCurrentPage(pdfPage);
        ApexPages.currentPage().getParameters().put('id', salesInvoice.Id);

        ApexPages.currentPage().getParameters().put('InvoiceType', 'TM by Date by Category');
        SalesInvoicePDFController salesInvoicePDFController = new SalesInvoicePDFController();

        Test.stopTest();
    }
}