objects/Approval_Tree__c/Approval_Tree__c.object-meta.xml
<CustomObject>
    <label>Approval Tree</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Trees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Approval_Tree__c/fields/Approval_Margin_Pct__c.field-meta.xml
<CustomField>
    <fullName>Approval_Margin_Pct__c</fullName>
    <label>Approval Margin %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Approval_Tree__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Trees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Approval_Tree__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales_Order</fullName>
            </value>
            <value>
                <fullName>Sales_Quote</fullName>
            </value>
            <value>
                <fullName>Sales_Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Approval_Tree__c/fields/Sales_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order_Type__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order_Type__c</referenceTo>
    <relationshipLabel>Approval Trees</relationshipLabel>
    <relationshipName>Approval_Trees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Approval_Tree__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Approval Trees</relationshipLabel>
    <relationshipName>Approval_Trees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_Type__c/Sales_Order_Type__c.object-meta.xml
<CustomObject>
    <label>Sales Order Type</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ApprovalTreesSelector.cls
public class ApprovalTreesSelector extends fflib_SObjectSelector{

    public static ApprovalTreesSelector newInstance(){
        return (ApprovalTreesSelector) Application.Selector.newInstance(Approval_Tree__c.SObjectType);
    }

    public List<SObjectField> getSObjectFieldList(){
        return new List<SObjectField>{
                Approval_Tree__c.Id,
                Approval_Tree__c.Name,
                Approval_Tree__c.Service_Center__c,
                Approval_Tree__c.Sales_Order_Type__c,
                Approval_Tree__c.Document_Type__c,
                Approval_Tree__c.Approver__c,
                Approval_Tree__c.Level__c,
                Approval_Tree__c.Approval_Margin_Pct__c
        };
    }

    public SObjectType getSObjectType(){
        return Approval_Tree__c.SObjectType;
    }

    public override String getOrderBy(){
        return 'Document_Type__c, Service_Center__r.Name, Sales_Order_Type__r.Name, Level__c';
    }

    public List<Approval_Tree__c> selectApprovalTreesByDocType(String docType){
        String queryString = newQueryFactory().selectField('Approver__r.Name')
                .setCondition('Document_Type__c = :docType')
                .addOrdering('Level__c', fflib_QueryFactory.SortOrder.ASCENDING)
                .addOrdering('Service_Center__r.Name', fflib_QueryFactory.SortOrder.ASCENDING)
                .addOrdering('Sales_Order_Type__r.Name', fflib_QueryFactory.SortOrder.ASCENDING)
                .toSOQL();

        return (List<Approval_Tree__c>) Database.query(queryString);
    }

    public Map<String, List<Approval_Tree__c>> selectByDocTypeWithApprovalTreesByDocTypeScvCtrSOType(String docType){
        Map<String, List<Approval_Tree__c>>  approvalTreesByDocTypeScvCtrSOType = new Map<String, List<Approval_Tree__c>>();
        for(Approval_Tree__c approvalTree:selectApprovalTreesByDocType(docType)){

            String keyStr = approvalTree.Document_Type__c.toUpperCase() + ':' + approvalTree.Service_Center__c + ':' + approvalTree.Sales_Order_Type__c;
            if(approvalTreesByDocTypeScvCtrSOType.containsKey(keyStr)){
                List<Approval_Tree__c> approvalTrees = approvalTreesByDocTypeScvCtrSOType.get(keyStr);
                approvalTrees.add(approvalTree);
                approvalTreesByDocTypeScvCtrSOType.put(keyStr, approvalTrees);
            } else {
                approvalTreesByDocTypeScvCtrSOType.put(keyStr, new List<Approval_Tree__c>{approvalTree});
            }
        }

        return approvalTreesByDocTypeScvCtrSOType;
    }

    public List<Approval_Tree__c> getApprovalTreeByDocTypeBySrvCtrByOrderType(String docType, Id srvCtr, Id orderType) {
        Map<String, List<Approval_Tree__c>> approvalTreesByDocTypeSvcCtrSOType =
                ApprovalTreesSelector.newInstance().selectByDocTypeWithApprovalTreesByDocTypeScvCtrSOType(docType);

        //System.debug('Info: approvalTreesByDocTypeSvcCtrSOType ' + approvalTreesByDocTypeSvcCtrSOType);
        List<Approval_Tree__c> approvalTrees = new List<Approval_Tree__c>();
        String keyString = docType + ':' + srvCtr + ':' + orderType;

        //System.debug('Info: keyString 1' + keyString);
        if(!approvalTreesByDocTypeSvcCtrSOType.containsKey(keyString)){
            keyString = docType + ':' + 'null:' + orderType;
            //System.debug('Info: keyString 2' + keyString);
            if(!approvalTreesByDocTypeSvcCtrSOType.containsKey(keyString)){
                keyString = docType + ':' + srvCtr + ':null';
                //System.debug('Info: keyString 3' + keyString);
                if(approvalTreesByDocTypeSvcCtrSOType.containsKey(keyString)){
                    approvalTrees = approvalTreesByDocTypeSvcCtrSOType.get(keyString);
                    //System.debug('Info: approvalTrees 3 ' + approvalTrees);
                }
            } else {
                approvalTrees = approvalTreesByDocTypeSvcCtrSOType.get(keyString);
                //System.debug('Info: approvalTrees 2 ' + approvalTrees);
            }
        } else {
            approvalTrees = approvalTreesByDocTypeSvcCtrSOType.get(keyString);
            //System.debug('Info: approvalTrees 1 ' + approvalTrees);
        }
        return approvalTrees;
    }
}