objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility__c/fields/Third_Party_Facility__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Facility__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party Facility</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Account_Executives__c.field-meta.xml
<CustomField>
    <fullName>Account_Executives__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Quotes/Orders (Account Executive)</relationshipLabel>
    <relationshipName>Sales_Orders_AE</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Estimated_Job_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Job_Start_Date__c</fullName>
    <label>Estimated Job Start Date</label>
    <type>Date</type>
</CustomField>

objects/Sales_Order__c/fields/Name_of_Worker_Responsible__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Worker_Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of Worker Responsible</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Quotes/Orders</relationshipLabel>
    <relationshipName>Quotes_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/SO_sent_to_EQAI__c.field-meta.xml
<CustomField>
    <fullName>SO_sent_to_EQAI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SO sent to EQAI</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/SO_Submitted_to_EQAI__c.field-meta.xml
<CustomField>
    <fullName>SO_Submitted_to_EQAI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SO Submitted to EQAI</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Worker_Responsible__c.field-meta.xml
<CustomField>
    <fullName>Worker_Responsible__c</fullName>
    <label>Worker Responsible</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Executive</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Include_SO_in_EQAI_Invoice_Integration__c.field-meta.xml
<CustomField>
    <fullName>Include_SO_in_EQAI_Invoice_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include SO in EQAI Invoice Integration</label>
    <type>Checkbox</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SendSalesOrderToEqaiController.cls
/******************************************************************************************************
* Class Name: SendSalesOrderToEqaiController
* Description: It will send Sales Order and Sales Lines to EQAI when user submit [Send Sales Order to EQAI]
* 			   button on Sales Order.
* ***************************************************************************************************
* Owner		        Task #			Date		Description
* Andrew Simons                     2/12        Updated component to lightning component instead of vf page. 
* Andrew Simons     Task #71766     2/15        The SO_sent_to_EQAI__c is now set to true, regardless if integration is successful or failure. 
                                                This is to allow user to continue sales process (create T&M's) even if integration fails.
* Vennila P			78904		    2/19        Commented line #35 to 38 
  Shahwaz Khan      78352          02-20-2024  Salesforce - When Choosing Facility on SQ vs SO
  Shahwaz Khan      Bug80870       03-11-2024   3rd Party Restriction Impact on Group B Service Centers
* ******************************************************************************************************/

 public class SendSalesOrderToEqaiController {
     
  
    @AuraEnabled
    public static string sendSalesOrderToEQAI(Id recordId) {
        CompanyMgmt.systemCall = true;
        try { 
            List<Sales_Order__c> salesOrder = [SELECT ID, SO_sent_to_EQAI__c,Account_Executives__c,
                                               Account_Executives__r.Account_Executive__c,
                                               SO_Submitted_to_EQAI__c, Service_Center__c,  
                                               Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c,
                                               Name_of_Worker_Responsible__c, Worker_Responsible__c, 
                                               Estimated_Job_Start_Date__c  from Sales_Order__c 
                                               where Id=:recordId order by createddate DESC limit 1];
            User currUser = [SELECT profile.name FROM User WHERE id = :userinfo.getUserId() limit 1];
            String profileName = currUser.profile.name;
            //Bug#80870
            List<Sales_Line__c> salesLines=New List<Sales_Line__c>();
            Date thrdPartyValDate = Date.valueOf(label.SO_3rd_Party_Facility_Check);
            salesLines = [Select Id from Sales_Line__c Where Sales_Order__c=:recordId AND Facility__r.Third_Party_Facility__c = true 
                          AND Sales_Order__r.Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c=true 
                          AND CreatedDate >= :thrdPartyValDate ];
            System.debug('salesLines++++++++++++' + salesLines);
            System.debug('thrdPartyValDate++++++++++' +thrdPartyValDate);
            if(salesOrder[0].Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c == false){
                return 'Service Center Disabled';
            }
            else if(salesOrder.size()>0 && salesOrder[0].Id != Null && salesOrder[0].SO_sent_to_EQAI__c == true)
            {
                return 'Sent to EQAI';
            }
            else if(salesOrder.size()>0 && salesOrder[0].Id != Null && salesOrder[0].SO_Submitted_to_EQAI__c == true && profileName != 'System Administrator')
            {
                return 'Sent to EQAI';
            }
            else if(salesOrder[0].Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c == true && (salesOrder[0].Worker_Responsible__c == null || salesOrder[0].Name_of_Worker_Responsible__c == null || salesOrder[0].Estimated_Job_Start_Date__c == null)) {
                return 'Missing Fields Required';
            }
            //Task#78352
            else if(salesLines.size()>0)
            {
                System.debug('3rdPartyFacility');
                return '3rdPartyFacility';
            }
            else if(salesOrder[0].Account_Executives__c != null && salesOrder[0].Account_Executives__r.Account_Executive__c != True)
            {
                return 'Salesperson is not AE';
            }
            else 
            {
                String response = workOrderQuoteService.workOrderQuoteHeaderInfo(recordId);
                //78904 
               /* Sales_Order__c so = salesOrder[0];
                so.SO_Submitted_to_EQAI__c = true;
                update so;*/
                return response;
            }
        }
        catch(exception ex) {
            System.Debug('Error::'+ex.getMessage());
            System.Debug('Error::'+ex.getLineNumber());            
            throw ex;
        }
    }
}