objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ResourceUOMAssociation__c/ResourceUOMAssociation__c.object-meta.xml
<CustomObject>
    <label>Resource Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Unit of Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceUOMAssociation__c/fields/Container_Size__c.field-meta.xml
<CustomField>
    <fullName>Container_Size__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Container Size</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_of_Measure__c.Container_Size__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipName>ResourceUOMAssociations1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ResourceUOMAssociation__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Facility__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Facility__c</referenceTo>
    <relationshipName>ResourceUOMAssociations</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/ResourceUOMAssociation__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipName>ResourceUOMAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/ResourceUOMAssociation__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit_of_Measure__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Unit of Measures (Unit of Measure)</relationshipLabel>
    <relationshipName>ResourceUOMAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Unit_of_Measure__c/fields/Container_Size__c.field-meta.xml
<CustomField>
    <fullName>Container_Size__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Container Size</label>
    <type>Checkbox</type>
</CustomField>

objects/Unit_of_Measure__c/fields/Hours_UOM__c.field-meta.xml
<CustomField>
    <fullName>Hours_UOM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hours UOM</label>
    <type>Checkbox</type>
</CustomField>

classes/ResourceUnitOfMeasuresSelector.cls
public with sharing class ResourceUnitOfMeasuresSelector extends fflib_SObjectSelector implements IResourceUnitOfMeasuresSelector{

    public static IResourceUnitOfMeasuresSelector newInstance(){
        return (IResourceUnitOfMeasuresSelector) Application.Selector.newInstance(ResourceUOMAssociation__c.SObjectType);
    }


    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                ResourceUOMAssociation__c.Id,
                ResourceUOMAssociation__c.Name,
                ResourceUOMAssociation__c.Resource__c,
                ResourceUOMAssociation__c.Unit_of_Measure__c,
                ResourceUOMAssociation__c.Unit_Cost__c,
                ResourceUOMAssociation__c.Unit_Price__c,
                ResourceUOMAssociation__c.Min_Sell_Qty__c,
                ResourceUOMAssociation__c.Facility__c,
                ResourceUOMAssociation__c.Container_Size__c,
                ResourceUOMAssociation__c.ER_Unit_Price__c
        };
    }

    public Schema.SObjectType getSObjectType(){
        return ResourceUOMAssociation__c.SObjectType;
    }

    public List<ResourceUOMAssociation__c> selectById(Set<Id> ids){
        return (List<ResourceUOMAssociation__c>) super.selectSObjectsById(ids);
    }

    public List<ResourceUOMAssociation__c> selectByResId(Set<Id> resIds){
        fflib_QueryFactory resourceUOMAssociationQueryFactory = newQueryFactory();


        //job task <<
        //return Database.query(resourceUOMAssociationQueryFactory.setCondition('Resource__c IN :resIds').toSOQL());
        return Database.query(resourceUOMAssociationQueryFactory
                .selectField('Unit_of_Measure__r.Name')
                .setCondition('Resource__c IN :resIds').toSOQL());
        //job task >>
    }

    public List<ResourceUOMAssociation__c> selectByResByUOM(Id resId, Id uomId){
        fflib_QueryFactory resourceUOMAssociationQueryFactory = newQueryFactory();
        return Database.query(resourceUOMAssociationQueryFactory
                .selectField('Unit_of_Measure__r.Name')
                //aura <<
                .selectField('Unit_of_Measure__r.Hours_UOM__c')
                //aura >>
                .setCondition('Resource__c = :resId AND Unit_of_Measure__c = :uomId').toSOQL());
    }
}