objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Rule__c/fields/Holidays_Bill_in_DT_Rate__c.field-meta.xml
<CustomField>
    <fullName>Holidays_Bill_in_DT_Rate__c</fullName>
    <label>Holidays Bill in DT Rate</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Holiday_List</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule__c/fields/Holidays_Bill_in_OT_Rate__c.field-meta.xml
<CustomField>
    <fullName>Holidays_Bill_in_OT_Rate__c</fullName>
    <label>Holidays Bill in OT Rate</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Holiday_List</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule__c/fields/Saturday_Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Rate_Code__c</fullName>
    <label>Saturday Rate Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeRateCode</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule__c/fields/Sunday_Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Rate_Code__c</fullName>
    <label>Sunday Rate Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeRateCode</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule_Line__c/Billing_Rule_Line__c.object-meta.xml
<CustomObject>
    <label>Billing Rule Line</label>
    <nameField>
        <displayFormat>BRL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Rule Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billing_Rule_Line__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Billing Rule Lines</relationshipLabel>
    <relationshipName>Billing_Rule_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Billing_Rule_Line__c/fields/Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Type__c</fullName>
    <label>Calculation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Time_Based</fullName>
            </value>
            <value>
                <fullName>Hour_Based</fullName>
            </value>
            <value>
                <fullName>Day_Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billing_Rule_Line__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Billing_Rule_Line__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

objects/Billing_Rule_Line__c/fields/Hours_After_Number_of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours_After_Number_of_Hours__c</fullName>
    <label>Hours After Number of Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Billing_Rule_Line__c/fields/Number_of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hours__c</fullName>
    <label>Number of Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Billing_Rule_Line__c/fields/Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code__c</fullName>
    <label>Rate Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeRateCode</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule_Line__c/fields/Rate_Code_After_Number_of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code_After_Number_of_Hours__c</fullName>
    <label>Rate Code After Number of Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeRateCode</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule_Line__c/fields/Rate_Code_for_Remaining_Hours__c.field-meta.xml
<CustomField>
    <fullName>Rate_Code_for_Remaining_Hours__c</fullName>
    <label>Rate Code for Remaining Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeRateCode</valueSetName>
    </valueSet>
</CustomField>

objects/Billing_Rule_Line__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

globalValueSets/Holiday_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Christmas Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>CDPWO</fullName>
        <label>Christmas Day PW  Observed</label>
    </customValue>
    <customValue>
        <fullName>Christmas Eve Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Eve Company</fullName>
    </customValue>
    <customValue>
        <fullName>Columbus Day</fullName>
    </customValue>
    <customValue>
        <fullName>Day After Thanksgiving</fullName>
    </customValue>
    <customValue>
        <fullName>Easter</fullName>
    </customValue>
    <customValue>
        <fullName>Election Day</fullName>
    </customValue>
    <customValue>
        <fullName>Good Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Inauguration Day</fullName>
    </customValue>
    <customValue>
        <fullName>Independence Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Independence Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>IDPWO</fullName>
        <label>Independence Day PW Observed</label>
    </customValue>
    <customValue>
        <fullName>Juneteenth Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Juneteenth PW Observed</fullName>
    </customValue>
    <customValue>
        <fullName>Labor Day</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln&apos;s Birthday Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln&apos;s Birthday PW Observed</fullName>
    </customValue>
    <customValue>
        <fullName>Martin Luther King Day</fullName>
    </customValue>
    <customValue>
        <fullName>Memorial Day</fullName>
    </customValue>
    <customValue>
        <fullName>New Year&apos;s Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>New Year&apos;s Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>NYDPWO</fullName>
        <label>New Year&apos;s Day PW Observed</label>
    </customValue>
    <customValue>
        <fullName>Patriots Day</fullName>
    </customValue>
    <customValue>
        <fullName>Presidential Election Day</fullName>
    </customValue>
    <customValue>
        <fullName>Presidents Day</fullName>
    </customValue>
    <customValue>
        <fullName>Thanksgiving</fullName>
    </customValue>
    <customValue>
        <fullName>Veteran&apos;s Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>VDPWO</fullName>
        <label>Veteran&apos;s Day PW Observed</label>
    </customValue>
    <masterLabel>Holiday List</masterLabel>
</GlobalValueSet>

globalValueSets/TimeRateCode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>REG</fullName>
        <label>Regular</label>
    </customValue>
    <customValue>
        <fullName>OT</fullName>
        <label>Overtime</label>
    </customValue>
    <customValue>
        <fullName>DT</fullName>
        <label>Double Time</label>
    </customValue>
    <masterLabel>TimeRateCode</masterLabel>
</GlobalValueSet>

classes/BillingRuleTest.cls
@IsTest
private class BillingRuleTest {
    @IsTest
    static void testBehavior() {
        Billing_Rule__c br = new Billing_Rule__c(
                Name = 'test',
                Holidays_Bill_in_DT_Rate__c = 'Christmas Day Company',
                Holidays_Bill_in_OT_Rate__c = 'Thanksgiving',
                Sunday_Rate_Code__c = EnumUtil.TimeRateCode.DT.name(),
                Saturday_Rate_Code__c = EnumUtil.TimeRateCode.OT.name()
        );
        insert br;

        List<Billing_Rule_Line__c> billingRuleLines = new List<Billing_Rule_Line__c>();

        Billing_Rule_Line__c billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Monday';
        billingRuleLine.Rate_Code__c = 'OT';
        billingRuleLine.Start_Time__c = Time.newInstance(0,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(7,30,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Monday';
        billingRuleLine.Rate_Code__c = 'REG';
        billingRuleLine.Start_Time__c = Time.newInstance(7,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(15,30,0,0);
        billingRuleLine.Hours_After_Number_of_Hours__c = 8;
        billingRuleLine.Rate_Code_After_Number_of_Hours__c = 'OT';
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Monday';
        billingRuleLine.Rate_Code__c = 'OT';
        billingRuleLine.Start_Time__c = Time.newInstance(15,30,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(0,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Hour_Based';
        billingRuleLine.Day__c = 'Tuesday';
        billingRuleLine.Number_of_Hours__c = 8;
        billingRuleLine.Rate_Code__c = 'REG';
        billingRuleLine.Rate_Code_for_Remaining_Hours__c = 'OT';
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Wednesday';
        billingRuleLine.Rate_Code__c = 'REG';
        billingRuleLine.Start_Time__c = Time.newInstance(7,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(15,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Wednesday';
        billingRuleLine.Rate_Code__c = 'DT';
        billingRuleLine.Start_Time__c = Time.newInstance(0,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(7,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Wednesday';
        billingRuleLine.Rate_Code__c = 'DT';
        billingRuleLine.Start_Time__c = Time.newInstance(15,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(0,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Thursday';
        billingRuleLine.Rate_Code__c = 'REG';
        billingRuleLine.Start_Time__c = Time.newInstance(7,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(15,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Thursday';
        billingRuleLine.Rate_Code__c = 'DT';
        billingRuleLine.Start_Time__c = Time.newInstance(0,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(7,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Time_Based';
        billingRuleLine.Day__c = 'Thursday';
        billingRuleLine.Rate_Code__c = 'DT';
        billingRuleLine.Start_Time__c = Time.newInstance(15,0,0,0);
        billingRuleLine.End_Time__c = Time.newInstance(0,0,0,0);
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Hour_Based';
        billingRuleLine.Day__c = 'Friday';
        billingRuleLine.Number_of_Hours__c = 8;
        billingRuleLine.Rate_Code__c = 'REG';
        billingRuleLine.Hours_After_Number_of_Hours__c = 3;
        billingRuleLine.Rate_Code_After_Number_of_Hours__c = 'OT';
        billingRuleLine.Rate_Code_for_Remaining_Hours__c = 'DT';
        billingRuleLines.add(billingRuleLine);

        billingRuleLine = new Billing_Rule_Line__c();
        billingRuleLine.Billing_Rule__c = br.Id;
        billingRuleLine.Calculation_Type__c = 'Day_Based';
        billingRuleLine.Day__c = 'Saturday';
        billingRuleLine.Rate_Code__c = 'OT';
        billingRuleLines.add(billingRuleLine);

        if(billingRuleLines.size() > 0){
            insert billingRuleLines;
        }


        Billing_Rule__c brRecord = BillingRulesSelector.newInstance().selectByIdsWithLines(new Set<Id>{br.Id})[0];

        BillingRule billingRule = new BillingRule(brRecord);
        String dtHoliday = 'Christmas Day Company';
        String otHoliday = 'Thanksgiving';

        System.assertEquals(true, billingRule.isDoubleTimePayHolidays(dtHoliday));
        System.assertEquals(false, billingRule.isOverTimePayHolidays(dtHoliday));
        System.assertEquals(true, billingRule.isOverTimePayHolidays(otHoliday));
        System.assertEquals(false, billingRule.isOverTimePayHolidays(dtHoliday));

        System.assertEquals('OT', billingRule.getSaturdayPayCode());
        System.assertEquals('DT', billingRule.getSundayPayCode());

        Date workDate = Date.newInstance(2019, 10, 14);
        Time startTime = Time.newInstance(7,30,0,0);
        Time endTime = Time.newInstance(16,0,0,0);
        Time lunchStartTime = Time.newInstance(12,0,0,0);
        Time lunchEndTime = Time.newInstance(12,30,0,0);
        billingRule.getHoursWithRateCodes(workDate, startTime, endTime, lunchStartTime, lunchEndTime, true);
        billingRule.getHoursWithRateCodes(workDate, startTime, endTime, lunchStartTime, lunchEndTime, false);

        workDate = Date.newInstance(2019,10,15);
        billingRule.calcHoursWithRateCodes(workDate, startTime, endTime);

        workDate = Date.newInstance(2019, 10, 16);
        startTime = Time.newInstance(6,0,0,0);
        endTime = Time.newInstance(7,0,0,0);
        billingRule.getHoursWithRateCodes(workDate, startTime, endTime, lunchStartTime, lunchEndTime, true);

        workDate = Date.newInstance(2019, 10, 18);
        startTime = Time.newInstance(0,0,0,0);
        endTime = Time.newInstance(0,0,0,0);
        billingRule.calcHoursWithRateCodes(workDate, startTime, endTime);

        workDate = Date.newInstance(2019,10,19);
        startTime = Time.newInstance(7,0,0,0);
        endTime = Time.newInstance(15,0,0,0);
        billingRule.calcHoursWithRateCodes(workDate, startTime, endTime);
    }
}