objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Rule__c/fields/Quote_Order_Assumption__c.field-meta.xml
<CustomField>
    <fullName>Quote_Order_Assumption__c</fullName>
    <label>Quote/Order Assumption</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PortalBasis</fullName>
            </value>
            <value>
                <fullName>OvertimeRate</fullName>
            </value>
            <value>
                <fullName>DailyRate</fullName>
            </value>
            <value>
                <fullName>LumpSum</fullName>
            </value>
            <value>
                <fullName>PortalBasisAdv</fullName>
            </value>
            <value>
                <fullName>DefaultBillingRule2023</fullName>
            </value>
            <value>
                <fullName>LumpSum2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Daily_Rate__c.field-meta.xml
<CustomField>
    <fullName>Daily_Rate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Daily Rate</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Default_Billing_Rule_2023__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing_Rule_2023__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default_Billing_Rule_2023</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Lump_Sum__c.field-meta.xml
<CustomField>
    <fullName>Lump_Sum__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lump Sum</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Overtime_Rate__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Rate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overtime Rate</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Portal_Basis__c.field-meta.xml
<CustomField>
    <fullName>Portal_Basis__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Portal Basis</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Portal_Basis_Adv__c.field-meta.xml
<CustomField>
    <fullName>Portal_Basis_Adv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Basis Adv</label>
    <type>Checkbox</type>
</CustomField>

classes/BillingRuleService.cls
public with sharing class BillingRuleService {
    public static Map<String, Billing_Rule__c> billingRulesByAssumptions = new Map<String, Billing_Rule__c>();

    public static void setBillingRulesByAssumptions() {
        for (Billing_Rule__c billingRule : BillingRulesSelector.newInstance().selectByAssumptions()) {
            if (billingRule.Quote_Order_Assumption__c != null) {
                //Quote_Order_Assumption__c is a multi picklist
                for (String assumption : billingRule.Quote_Order_Assumption__c.split(';')) {
                    billingRulesByAssumptions.put(assumption, billingRule);
                }
            }
        }
    }

    public static Billing_Rule__c getBillingRuleIdForSalesOrderAssumption(Sales_Order__c salesOrder){
        if(billingRulesByAssumptions.size() == 0){
            setBillingRulesByAssumptions();
        }

        String assumption = '';
        if (salesOrder.Portal_Basis__c == true) {
            assumption = 'PortalBasis';
        } else if (salesOrder.Overtime_Rate__c == true) {
            assumption = 'OvertimeRate';
        } else if (salesOrder.Daily_Rate__c == true) {
            assumption = 'DailyRate';
        } else if (salesOrder.Lump_Sum__c == true) {
            if(salesOrder.CreatedDate < CompanySettingUtil.acvSetting.X2023_Billing_Rule_Start_Date__c) {
                assumption = 'LumpSum';
            } else {
                assumption = 'LumpSum2023';
            }
        } else if (salesOrder.Portal_Basis_Adv__c == true) {
            assumption = 'PortalBasisAdv';
        } else if (salesOrder.Default_Billing_Rule_2023__c == true) {
            assumption = 'DefaultBillingRule2023';
        }

        System.debug('Info: assumption --> ' + assumption);
        if (billingRulesByAssumptions.containsKey(assumption)) {
            return billingRulesByAssumptions.get(assumption);
        } else {
            throw new DataException('Order assumption ' + assumption + ' is not mapped to a billing rule. Please contact admin to set up the mapping for the assumption.');
        }
    }
}