objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Setting__mdt/Company_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Company Setting</label>
    <pluralLabel>Company Settings</pluralLabel>
</CustomObject>

objects/Company_Setting__mdt/fields/API2PDF_Key__c.field-meta.xml
<CustomField>
    <fullName>API2PDF_Key__c</fullName>
    <label>API2PDF Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Default_Resource_Type_for_FA__c.field-meta.xml
<CustomField>
    <fullName>Default_Resource_Type_for_FA__c</fullName>
    <label>Default Resource Type for FA</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Default_Retainage_Resource_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Retainage_Resource_Id__c</fullName>
    <label>Default Retainage Resource Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Fixed_Price_Job_Resource__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Job_Resource__c</fullName>
    <label>Fixed Price Job Resource</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Mobile_TM_Version_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_TM_Version_No__c</fullName>
    <label>Mobile T&amp;M Version No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Company_Setting__mdt/fields/Payroll_Blockout_End_Minute__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Blockout_End_Minute__c</fullName>
    <label>Payroll Blockout End Minute</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Company_Setting__mdt/fields/Payroll_Blockout_Start_Hour__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Blockout_Start_Hour__c</fullName>
    <label>Payroll Blockout Start Hour</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Company_Setting__mdt/fields/Payroll_Blockout_Start_Minute__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Blockout_Start_Minute__c</fullName>
    <label>Payroll Blockout Start Minute</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Company_Setting__mdt/fields/Quote_Signature_Token_Expiration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Quote_Signature_Token_Expiration_Hours__c</fullName>
    <label>Quote Signature Token Expiration Hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Company_Setting__mdt/fields/Retainage_Receivable_GL_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Retainage_Receivable_GL_Account_Id__c</fullName>
    <label>Retainage Receivable GL Account Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Rinse_Out_Fee_Resource_Id__c.field-meta.xml
<CustomField>
    <fullName>Rinse_Out_Fee_Resource_Id__c</fullName>
    <label>Rinse Out Fee Resource Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Sandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sandbox</label>
    <type>Checkbox</type>
</CustomField>

objects/Company_Setting__mdt/fields/Sandbox_Email_Recipients__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Email_Recipients__c</fullName>
    <label>Sandbox Email Recipients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/TM_Signature_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>TM_Signature_Site_URL__c</fullName>
    <label>T&amp;M Signature Site URL</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Company_Setting__mdt/fields/TM_Signature_Token_Expiration_Hours__c.field-meta.xml
<CustomField>
    <fullName>TM_Signature_Token_Expiration_Hours__c</fullName>
    <label>T&amp;M Signature Token Expiration Hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Company_Setting__mdt/fields/X2023_Billing_Rule_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>X2023_Billing_Rule_Start_Date__c</fullName>
    <label>2023_Billing_Rule_Start_Date</label>
    <type>Date</type>
</CustomField>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Company__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Subsidiary Companies</relationshipLabel>
    <relationshipName>Subsidiary_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/fields/Disable_Customer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Disable_Customer_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Customer Portal</label>
    <type>Checkbox</type>
</CustomField>

objects/Subsidiary_Company__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Subsidiary_Company__c/fields/EEC_Surcharge_Cost_Pct__c.field-meta.xml
<CustomField>
    <fullName>EEC_Surcharge_Cost_Pct__c</fullName>
    <label>EEC Surcharge Cost %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Subsidiary_Company__c/fields/ESIC_Surcharge_Cost_Pct__c.field-meta.xml
<CustomField>
    <fullName>ESIC_Surcharge_Cost_Pct__c</fullName>
    <label>ESIC Surcharge Cost %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Subsidiary_Company__c/fields/Fuel_Surcharge_Cost_Pct__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Surcharge_Cost_Pct__c</fullName>
    <label>Fuel Surcharge Cost %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Subsidiary_Company__c/fields/QtC_Enabled__c.field-meta.xml
<CustomField>
    <fullName>QtC_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QtC Enabled?</label>
    <type>Checkbox</type>
</CustomField>

objects/Subsidiary_Company__c/fields/Watermark__c.field-meta.xml
<CustomField>
    <fullName>Watermark__c</fullName>
    <label>Watermark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/CompanySettingUtil.cls
/*************************************************************************************************
* Name         :  CompanySettingUtil
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Prabhu Rathakrishnan      10-13-2024             US127188 - Salesforce - Modifications to allow ESIC Surcharge Type 
*************************************************************************************************/
public with sharing class CompanySettingUtil {    
    /*
     *  Ticket#24469 - add Payroll blockout time related fields: Payroll_Blockout_Start_Hour__c, Payroll_Blockout_Start_Minute__c, Payroll_Blockout_End_Minute__c
     *  Ticket#24559 add 2023 Billing Rule Start Date to acv setting query
     */
    public static Company_Setting__mdt acvSetting{
        get{
            if(acvSetting == null){
                acvSetting = [
                        SELECT Id, Name__c, Retainage_Receivable_GL_Account_Id__c,Default_Retainage_Resource_Id__c,Rinse_Out_Fee_Resource_Id__c,
                                API2PDF_Key__c, Default_Resource_Type_for_FA__c, Fixed_Price_Job_Resource__c, Mobile_TM_Version_No__c, Sandbox__c,
                                Sandbox_Email_Recipients__c, X2023_Billing_Rule_Start_Date__c, TM_Signature_Site_URL__c, Payroll_Blockout_Start_Hour__c, Payroll_Blockout_Start_Minute__c, Payroll_Blockout_End_Minute__c,
                                Quote_Signature_Token_Expiration_Hours__c, TM_Signature_Token_Expiration_Hours__c
                        FROM Company_Setting__mdt
                        WHERE Label = 'ACV'
                        LIMIT 1];
            }
            return acvSetting;
        }
        private set;
    }

    public static Company_Setup__c defaultCompanySetup {
        get{
            if (defaultCompanySetup == null) {
                defaultCompanySetup = CompanyMgmt.getCompanySetup();
            }
            return defaultCompanySetup;
        }
        private set;
    }

    public static Boolean isSandbox(){
        return acvSetting.Sandbox__c;
    }

    public static List<String> getSandboxEmailRecipients(){
        List<String> emails = new List<String>();
        if(String.isNotBlank(acvSetting.Sandbox_Email_Recipients__c)){
            emails = acvSetting.Sandbox_Email_Recipients__c.split(';');
        }
        return emails;
    }

    //Ticket#21883 - add Surcharge_Cost_Pct__c
    public static Subsidiary_Company__c getSubsidiaryCompanySetup(Id subsidiaryCompanyId){
        return [SELECT Id, Name, Disable_Customer_Portal__c, Display_Name__c, QtC_Enabled__c,
                Watermark__c, Billing_Rule__c, Fuel_Surcharge_Cost_Pct__c, EEC_Surcharge_Cost_Pct__c,ESIC_Surcharge_Cost_Pct__c
                    FROM Subsidiary_Company__c WHERE Id = :subsidiaryCompanyId LIMIT 1];
    }
}