objects/Company_Setting__mdt/Company_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Company Setting</label>
    <pluralLabel>Company Settings</pluralLabel>
</CustomObject>

objects/Company_Setting__mdt/fields/Default_Resource_Type_for_FA__c.field-meta.xml
<CustomField>
    <fullName>Default_Resource_Type_for_FA__c</fullName>
    <label>Default Resource Type for FA</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Field_Activity_Log__c/Field_Activity_Log__c.object-meta.xml
<CustomObject>
    <label>Field Activity Log</label>
    <nameField>
        <displayFormat>FAL-{000000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Activity Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Field_Activity_Log__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Field Activity Log</relationshipLabel>
    <relationshipName>Field_Activity_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Field_Activity_Log__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Field_Activity_Log__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Field Activity Log</relationshipLabel>
    <relationshipName>Field_Activity_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Field_Activity_Log__c/fields/T_M_Line__c.field-meta.xml
<CustomField>
    <fullName>T_M_Line__c</fullName>
    <label>T&amp;M Line</label>
    <referenceTo>TM_Line__c</referenceTo>
    <relationshipLabel>Field Activity Log</relationshipLabel>
    <relationshipName>Field_Activity_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Equipment</label>
    <type>Checkbox</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Service</fullName>
                <label>OOS-On Lot</label>
            </value>
            <value>
                <fullName>OOS-Pending</fullName>
                <label>OOS-Pending Sale</label>
            </value>
            <value>
                <fullName>Gone</fullName>
            </value>
            <value>
                <fullName>Junked</fullName>
                <isActive>false</isActive>
                <label>Junked</label>
            </value>
            <value>
                <fullName>OOS-Under Repair</fullName>
                <isActive>false</isActive>
                <label>OOS-Under Repair</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Stolen</fullName>
                <isActive>false</isActive>
                <label>Stolen</label>
            </value>
            <value>
                <fullName>Under Repair</fullName>
                <isActive>false</isActive>
                <label>Under Repair</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

objects/TM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Mobile Review</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fully Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <isActive>false</isActive>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Partially Invoiced</fullName>
                <isActive>false</isActive>
                <label>Partially Invoiced</label>
            </value>
            <value>
                <fullName>Pro forma Review</fullName>
                <isActive>false</isActive>
                <label>Pro forma Review</label>
            </value>
            <value>
                <fullName>Ready to Bill</fullName>
                <isActive>false</isActive>
                <label>Ready to Bill</label>
            </value>
            <value>
                <fullName>Received By Billing</fullName>
                <isActive>false</isActive>
                <label>Received By Billing</label>
            </value>
            <value>
                <fullName>Received By Dispatch</fullName>
                <isActive>false</isActive>
                <label>Received By Dispatch</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Line_No__c.field-meta.xml
<CustomField>
    <fullName>Line_No__c</fullName>
    <label>Line No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/FieldLogActivityController.cls
global with sharing class FieldLogActivityController {
    public final ApexPages.StandardController theController;
    public List<Field_Activity_Log__c> fieldActivityLogs {get; set;}
    public String tmId {get; set;}
    public String tmLineId {get; set;}
    public TM_Line__c laborLine {get; set;}
    public Boolean viewMode {get; set;}

    public static Company_Setting__mdt defaultCompanySetting {
        get {
            defaultCompanySetting = CompanySettingUtil.acvSetting;
            return defaultCompanySetting;
        }
        set;
    }

    public FieldLogActivityController(ApexPages.StandardController controller){
        viewMode = false;
        tmLineId = ApexPages.currentPage().getParameters().get('tmlId');
        tmId = ApexPages.currentPage().getParameters().get('tmId');
        fieldActivityLogs = [
                SELECT
                        End_Time__c,
                        Equipment__c,
                        Equipment__r.Name,
                        Id,
                        Resource_Type__c,
                        Resource_Type__r.Name,
                        Start_Time__c,
                        T_M_Line__c,
                        Line_No__c
                FROM Field_Activity_Log__c WHERE T_M_Line__c = :tmLineId ORDER BY Start_Time__c ASC ];

        laborLine = new TM_Line__c();
        List<TM_Line__c> tmLines = [SELECT Id, TM__c, TM__r.Status__c, Resource__c, Resource__r.Name FROM TM_Line__c WHERE Id = :tmLineId];

        if(tmLines.size() > 0){
            laborLine = tmLines[0];
            if(laborLine.TM__r.Status__c != TMsService.OPEN_STATUS &&
                    laborLine.TM__r.Status__c != TMsService.MOBILE_REVIEW_STATUS &&
                    laborLine.TM__r.Status__c != TMsService.SCHEDULED_STATUS){
                viewMode = true;
            }
        }
    }

    public PageReference addLine(){
        Decimal nextLineNo = 0;
        for(Field_Activity_Log__c fieldActivityLog : fieldActivityLogs){
            if(nextLineNo < fieldActivityLog.Line_No__c){
                nextLineNo = fieldActivityLog.Line_No__c;
            }
        }
        nextLineNo += 1;

        fieldActivityLogs.add(
                new Field_Activity_Log__c(
                        T_M_Line__c = tmLineId,
                        Equipment__c = null,
                        Resource_Type__c = defaultCompanySetting.Default_Resource_Type_for_FA__c,
                        Line_No__c = nextLineNo
                )
        );

        System.debug('Info: add Line');
        System.debug('Info: tmLineId ' + tmLineId);
        System.debug('Info: fieldActivityLogs ' + fieldActivityLogs.size());
        return null;
    }

    public PageReference returnToTM(){
        if(String.isNotBlank(tmId)){
            PageReference tmPage = new PageReference('/apex/TM?id=' + tmId);
            tmPage.setRedirect(true);
            return tmPage;
        }
        return null;
    }

    public PageReference deleteLine(){
        String displayId = ApexPages.currentPage().getParameters().get('displayId');
        if (displayId == '') {
            displayId = '0';
        }

        for (Integer i = 0; i < fieldActivityLogs.size(); i++) {

            if (fieldActivityLogs[i].Line_No__c == Decimal.valueOf(displayId)) {
                fieldActivityLogs.remove(i);
                break;
            }
        }

        return null;
    }

    public PageReference save() {
        if(fieldActivityLogs == null) {
            return null;
        }

        List<Field_Activity_Log__c> fieldActivityLogsBackUp = fieldActivityLogs.deepClone(true, true, true);
        Savepoint savepoint = Database.setSavepoint();
        try{
            List<Field_Activity_Log__c> deletedRecords = new List<Field_Activity_Log__c>();
            for(Field_Activity_Log__c fieldActivityLog : [SELECT Id FROM Field_Activity_Log__c WHERE T_M_Line__c = :tmLineId]){
                Boolean lineFound = false;
                for(Field_Activity_Log__c fieldActivityLog2 : fieldActivityLogs){
                    if(fieldActivityLog.Id == fieldActivityLog2.Id){
                        lineFound = true;
                    }
                }

                if(lineFound == false){
                    deletedRecords.add(fieldActivityLog);
                }
            }
            if(deletedRecords.size() > 0){
                delete deletedRecords;
            }

            for(Field_Activity_Log__c fieldActivityLog:fieldActivityLogs){
                if(String.isBlank(fieldActivityLog.Equipment__c)){
                    throw new DataException('Equipment field must not be blank!');
                }
                if(fieldActivityLog.Start_Time__c == null || fieldActivityLog.End_Time__c == null){
                    throw new DataException('Times field must not be blank!');
                }
            }

            upsert fieldActivityLogs;
            return null;
        } catch (Exception e){
            System.debug('Error: ' + e.getStackTraceString());
            Database.rollback(savepoint);
            fieldActivityLogs = fieldActivityLogsBackUp;
            return null;
        }
    }

    public PageReference validateField() {
        String fieldName = ApexPages.currentPage().getParameters().get('fieldName');
        Integer i = Integer.valueOf(ApexPages.currentPage().getParameters().get('indexNo'));
        String newFieldValue = ApexPages.currentPage().getParameters().get('newFieldValue');
        if(fieldName == 'theEquipment'){
            if(String.isBlank(newFieldValue)){
                fieldActivityLogs[i].Equipment__c = null;
            } else {
                fieldActivityLogs[i].Equipment__c = newFieldValue;
                List<Resource__c> equipmentRes = [SELECT Id, Name FROM Resource__c WHERE Id = :newFieldValue];
                fieldActivityLogs[i].Equipment__r = equipmentRes[0];
            }
        } else if(fieldName == 'startTime' || fieldName == 'endTime'){
            List<String> theTime = new List<String>();
            Integer hrs;
            Integer min;
            try {
                if (String.isEmpty(newFieldValue)) {
                    hrs = 0;
                    min = 0;
                } else {
                    if (newFieldValue.contains(':')) {
                        theTime = newFieldValue.split(':');
                        hrs = Integer.valueOf(theTime[0]);
                        min = Integer.valueOf(theTime[1]);
                    } else {
                        hrs = Integer.valueOf(newFieldValue);
                        min = 0;
                    }
                }

                Time enteredTime = Time.newInstance(hrs, min, 0, 0);
                if(fieldName == 'startTime'){
                    fieldActivityLogs[i].Start_Time__c = enteredTime;
                }

                if(fieldName == 'endTime'){
                    fieldActivityLogs[i].End_Time__c = enteredTime;
                }

            } catch (Exception e) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return null;
            }
        } else if (fieldName == 'resourceType'){
            if(String.isBlank(newFieldValue)){
                fieldActivityLogs[i].Resource_Type__c = null;
            } else {
                List<Resource_Type__c> resourceTypes = [SELECT Id, Name FROM Resource_Type__c WHERE Id = :newFieldValue];
                fieldActivityLogs[i].Resource_Type__c = resourceTypes[0].Id;
                fieldActivityLogs[i].Resource_Type__r = resourceTypes[0];
            }
        }
        return null;
    }
}