objects/Account/fields/Account_Executive_ids__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive_ids__c</fullName>
    <description>To store Account Executive id's to create a hyper link</description>
    <label>Account Executive ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Account_Executives__c.field-meta.xml
<CustomField>
    <fullName>Account_Executives__c</fullName>
    <description>To show selected Account executives as a hyper link</description>
    <label>Additional Account Executives</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AddAccountExecutiveController.cls
/*************************************************************************************************
* Name         :  AddAccountExecutiveController 
* Description  :  Apex Class for addAccountExecutive aura component
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Pavithra P				08-21-2024             US124701 : [Continued] [Continued] [Unplanned] - Update - Salesforce Assign Multiple Salespeople to an Account and Sales Orders
*************************************************************************************************/
public class AddAccountExecutiveController {
    
    @AuraEnabled
    public static void addMultipleAccountExecutives(string AccountId, string AccountExecutiveIds){
        
        list<Id> setOfSalesPersonIds = new list<Id>();
        if(AccountExecutiveIds !=  null){            
            setOfSalesPersonIds.addall(AccountExecutiveIds.split(','));            
        }else{            
            Account updateAccount = new Account();
            updateAccount.Id = AccountId;
            updateAccount.Account_Executives__c = null;
            updateAccount.Account_Executive_ids__c = null;
            update updateAccount;
            
        }
         
        String hyperlinks = '';
        integer count = 0;
        integer totalSalesPersons = setOfSalesPersonIds.size();
        
        if(!setOfSalesPersonIds.isEmpty()){
            Map<Id, Salesperson__c> AccountExecutiveMap = new Map<Id, Salesperson__c>([SELECT Id, Name FROM Salesperson__c WHERE Id IN :setOfSalesPersonIds]);
            String baseUrl = URL.getOrgDomainURL().toExternalForm();
            for (String salesPersonId : setOfSalesPersonIds) {
                Salesperson__c salesPerson = AccountExecutiveMap.get(salesPersonId);
                if (salesPerson != null) {
                    String recordUrl = baseUrl + '/' + salesPerson.Id;
                    String hyperlink = '<a href="' + recordUrl + '">' + salesPerson.Name + '</a>';
                    hyperlinks += hyperlink;
                    // Append a comma if it's not the last record
                    if (count < totalSalesPersons - 1) {
                        hyperlinks += ', ';
                    }
                }
                count++;
            }                
        }
        Account updateAccount = new Account();
        updateAccount.Id = AccountId;
        updateAccount.Account_Executives__c = hyperlinks;
        updateAccount.Account_Executive_ids__c = AccountExecutiveIds;
        update updateAccount;        
    }
    
    @AuraEnabled
    public static List<SalesPerson__c> getAccountExecutives(String accountId){
        List<Salesperson__c> accountExecutivesList = new List<Salesperson__c>();
        if(accountId != null){
            Account accRecord = [SELECT Id,Name,Account_Executive_ids__c FROM Account WHERE Id =: accountId];
            if(accRecord.Account_Executive_ids__c != null){
                List<Id> relatedIds = accRecord.Account_Executive_ids__c.split(',');
                accountExecutivesList = [SELECT Id,Name FROM Salesperson__c WHERE Id IN: relatedIds];
            }  
        }
        return accountExecutivesList;
    }
}