objects/Account/fields/Account_Executive_ids__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive_ids__c</fullName>
    <description>To store Account Executive id's to create a hyper link</description>
    <label>Account Executive ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Account_Executives__c.field-meta.xml
<CustomField>
    <fullName>Account_Executives__c</fullName>
    <description>To show selected Account executives as a hyper link</description>
    <label>Additional Account Executives</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Salesperson__r.Salesperson_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AddAccountExecutiveControllerTest.cls
/*************************************************************************************************
* Name         :  AddAccountExecutiveControllerTest 
* Description  :  Test Class for AddAccountExecutiveController
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Pavithra P				08-21-2024             US124701 : [Continued] [Continued] [Unplanned] - Update - Salesforce Assign Multiple Salespeople to an Account and Sales Orders
*************************************************************************************************/

@isTest
public class AddAccountExecutiveControllerTest {
    // Test setup method to create test data
    @testSetup
    static void setupData() {
        List<Salesperson__c> salespersons = new List<Salesperson__c>();
        for (Integer i = 0; i < 3; i++) {
            // Generate a single character for Salesperson code
            String salespersonCode = String.fromCharArray(new List<Integer>{65 + i});
            salespersons.add(new Salesperson__c(Name = 'Salesperson ' + i,Salesperson_Code__c = salespersonCode ,Status__c='Active'));
        }
        insert salespersons;
        
        Account acc = new Account(Name = 'Test Account');
        insert acc;
    }
    
    // Test method to verify adding multiple Account Executives
    @isTest
    static void testAddMultipleAccountExecutives() {
        // Fetch the test Account and Salespersons created in testsetup
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        List<Salesperson__c> salespersons = [SELECT Id FROM Salesperson__c];
        
        // Prepare a string of salesperson IDs
        String salesPersonIds = String.join(new List<String> { salespersons[0].Id, salespersons[1].Id }, ',');
        Test.startTest();
        AddAccountExecutiveController.addMultipleAccountExecutives(testAccount.Id, salesPersonIds);
        Test.stopTest();
             
        Account updatedAccount = [SELECT Id, Account_Executives__c, Account_Executive_ids__c FROM Account WHERE Id = :testAccount.Id];
        System.assertNotEquals(null, updatedAccount.Account_Executives__c, 'Account Executives field should not be null');
        System.assertEquals(salesPersonIds, updatedAccount.Account_Executive_ids__c, 'Account Executive Ids should match the input');
    }
    
    // Test Method to verify when null value is provided for Account Executives
    @isTest
    static void testAddMultipleAccountExecutivesWithNull() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        AddAccountExecutiveController.addMultipleAccountExecutives(testAccount.Id, null);
        Test.stopTest();
        
        Account updatedAccount = [SELECT Id, Account_Executives__c, Account_Executive_ids__c FROM Account WHERE Id = :testAccount.Id];
        System.assertEquals(null, updatedAccount.Account_Executives__c, 'Account Executives field should be null');
        System.assertEquals(null, updatedAccount.Account_Executive_ids__c, 'Account Executive Ids should be null');
    }
    
    // Test Method to verify retrieving Account Executives
    @isTest
    static void testGetAccountExecutives() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        List<Salesperson__c> salespersons = [SELECT Id FROM Salesperson__c];
        
        // Set Account Executive IDs to the Account
        String salesPersonIds = String.join(new List<String> { salespersons[0].Id, salespersons[1].Id }, ',');
        testAccount.Account_Executive_ids__c = salesPersonIds;
        update testAccount;
        
        Test.startTest();
        List<Salesperson__c> accountExecutives = AddAccountExecutiveController.getAccountExecutives(testAccount.Id);
        Test.stopTest();
        
        System.assertEquals(2, accountExecutives.size(), 'There should be 2 Account Executives');
    }
    
    // Test method to verify when there are no Account Executives
    @isTest
    static void testGetAccountExecutivesWithNoExecutives() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        List<Salesperson__c> accountExecutives = AddAccountExecutiveController.getAccountExecutives(testAccount.Id);
        Test.stopTest();
        
        System.assertEquals(0, accountExecutives.size(), 'There should be no Account Executives');
    }
}