objects/Account/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts (Account Executive)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Account_Executive_ids__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive_ids__c</fullName>
    <description>To store Account Executive id's to create a hyper link</description>
    <label>Account Executive ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Contact_Type_Filter__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type_Filter__c</fullName>
    <label>Contact Type Filter</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Customer_Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Instructions__c</fullName>
    <label>Customer Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <defaultValue>"Active"</defaultValue>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency?</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Inter_co_Account__c.field-meta.xml
<CustomField>
    <fullName>Inter_co_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Accounts are not tax liable.</inlineHelpText>
    <label>Intra-Co</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/InterCo__c.field-meta.xml
<CustomField>
    <fullName>InterCo__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Republic Customer Accounts</inlineHelpText>
    <label>Inter-Co</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Invoice_Backup_Documents__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Backup_Documents__c</fullName>
    <label>Invoice Backup Documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVOICE</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>MANIFEST_WEIGHT_TICKET</fullName>
                <label>Disposal Manifest/Weight Ticket</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>T&amp;M</label>
            </value>
            <value>
                <fullName>CERTIFIED_PAYROLL</fullName>
                <label>Certified Payroll</label>
            </value>
            <value>
                <fullName>SPILL_REPORT_WITH_PICTURES</fullName>
                <label>Spill Report w/ Pictures</label>
            </value>
            <value>
                <fullName>MARK_UP_VENDOR_INVOICE_OR_RECEIPT</fullName>
                <label>Mark-Up Vendor Invoice/Receipt</label>
            </value>
            <value>
                <fullName>CUSTOMER_SPECIFIC_DOCUMENTATION</fullName>
                <label>Customer Specific Documentation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Invoice_Email_Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email_Contact_Types__c</fullName>
    <label>Invoice Email Contact Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BILLING</fullName>
                <label>Billing</label>
            </value>
            <value>
                <fullName>SITE</fullName>
                <label>Site</label>
            </value>
            <value>
                <fullName>EXECUTIVE</fullName>
                <label>Executive</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <label>Sales</label>
            </value>
            <value>
                <fullName>QUOTE</fullName>
                <label>Quote</label>
            </value>
            <value>
                <fullName>PURCHASE</fullName>
                <label>Purchase</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Invoice_Portal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Portal__c</fullName>
    <label>Invoice Portal</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoice_Submission_Channels__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Submission_Channels__c</fullName>
    <label>Invoice Submission Channels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>INVOICE_PORTAL</fullName>
                <label>Invoice Portal</label>
            </value>
            <value>
                <fullName>HARD_COPY_SUBMITTAL</fullName>
                <label>Hard Copy Submittal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/NAV_ID__c.field-meta.xml
<CustomField>
    <fullName>NAV_ID__c</fullName>
    <externalId>true</externalId>
    <label>NAV ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Phone_Ext__c.field-meta.xml
<CustomField>
    <fullName>Phone_Ext__c</fullName>
    <label>Phone Ext.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/PO_Required__c.field-meta.xml
<CustomField>
    <fullName>PO_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Required</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Pricing_Group__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Group__c</fullName>
    <label>Pricing Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Area__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Executive</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Include_SO_in_EQAI_Invoice_Integration__c.field-meta.xml
<CustomField>
    <fullName>Include_SO_in_EQAI_Invoice_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include SO in EQAI Invoice Integration</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Company__c/fields/QtC_Enabled__c.field-meta.xml
<CustomField>
    <fullName>QtC_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QtC Enabled?</label>
    <type>Checkbox</type>
</CustomField>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/Tax_Area__c/Tax_Area__c.object-meta.xml
<CustomObject>
    <label>Tax Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountsSelector.cls
public class AccountsSelector extends fflib_SObjectSelector
        implements IAccountsSelector
{
    public static IAccountsSelector newInstance()
    {
        return (IAccountsSelector) Application.Selector.newInstance(Account.SObjectType);
    }
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                Account.AccountNumber,
                Account.Id,
                Account.ParentId,
                Account.Name,
                Account.NAV_ID__c,
                Account.Service_Center__c,
                Account.BillingStreet,
                Account.BillingCity,
                Account.BillingStateCode,
                Account.BillingPostalCode,
                Account.BillingCountryCode,
                Account.Fax,
                Account.Phone,
                Account.Phone_Ext__c,
                Account.Tax_Area__c,
                Account.Tax_Liable__c,
                Account.Inter_co_Account__c,
                Account.Pricing_Group__c,
                Account.Type,
                Account.Subsidiary_Company__c,
                Account.Emergency__c,
                Account.Payment_Term__c,
                Account.Internal_Comments__c,
                Account.Billing_Instructions__c,
                Account.Salesperson__c,
                Account.Account_Executive__c,
                Account.Customer_Status__c,
                Account.PO_Number_Type__c,
                Account.PO_Required__c, //US141334
                Account.Invoice_Email_Contact_Types__c,
                Account.Invoice_Submission_Channels__c,
                Account.Invoice_Portal__c,
                Account.Invoice_Backup_Documents__c,
                Account.Contact_Type_Filter__c,
                Account.Customer_Billing_Instructions__c,
                Account.InterCo__c, //Ticket#21211
                Account.Sage_Customer_No__c, //Task#78375
                Account.Service_Center__c  //Task#81352    
        };
    }

    public Schema.SObjectType getSObjectType(){
        return Account.SObjectType;
    }

    public List<Account> selectById(Set<Id> idSet){
        return (List<Account>)Database.query(newQueryFactory().
                selectField('Tax_Area__r.Name').
                selectField('Subsidiary_Company__r.Name').
                selectField('Payment_Term__r.Name').
                selectField('Account_Executive__r.Name').
                selectField('Salesperson__r.Name').
                selectField('Owner.Name').
                selectField('Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c').  //Task#81352  
                selectField('Account_Executive_ids__c').
                setCondition('Id IN :idSet').toSOQL());
    }

    public List<Account> selectBillingInstructionsById(Set<Id> idSet){
        return (List<Account>) Database.query(
                newQueryFactory(false).
                        selectField(Account.Id).
                        selectField(Account.Billing_Instructions__c).
                        selectField(Account.Internal_Comments__c).
                        setCondition('Id IN :idSet').toSOQL());
    }

    public List<Account> selectTaxAreaNameById(Set<Id> idSet){
        return (List<Account>) Database.query(newQueryFactory().
                selectField('Tax_Area__r.Name').
                selectField(Account.ParentId).
                selectField(Account.Subsidiary_Company__c).
                selectField(Account.Account_Executive__c).
                selectField(Account.Salesperson__c).
                selectField('Subsidiary_Company__r.Name').
                selectField(Account.Billing_Instructions__c).
                selectField(Account.Internal_Comments__c).
                selectField(Account.ParentId).
                selectField(Account.Payment_Term__c).
                //aura <<
                selectField('Payment_Term__r.Name').
                selectField('Account_Executive__r.Name').
                selectField('Salesperson__r.Name').
                selectField('Owner.Name').
                //aura >>
                setCondition('Id IN :idSet').toSOQL());
    }

    public List<Account> selectSubsidiaryCompInfoById(Set<Id> idSet){
        return (List<Account>) Database.query(newQueryFactory().
                selectField('Subsidiary_Company__r.Name').
                selectField('Subsidiary_Company__r.QtC_Enabled__c').
                selectField(Account.Emergency__c).
                setCondition('Id IN :idSet').toSOQL());
    }

    public List<Account> selectParentAccountById(Set<Id> idSet){
        return (List<Account>) Database.query(newQueryFactory(false).
                selectField('Id').
                selectField('Name').
                selectField('ParentId').
                selectField('Subsidiary_Company__c').
                selectField('Subsidiary_Company__r.Name').
                setCondition('Id In :idSet').
                toSOQL());
    }

    public List<Account> selectBySubsidiaryCompanyAndType(Id subCompanyId){
        return (List<Account>) Database.query(newQueryFactory().
                setCondition('Subsidiary_Company__c =: subCompanyId AND ' +
                '(Type =\'Customer\' OR Type = \'Prospect\')').toSOQL());
    }
}