objects/Account/fields/Account_Executives__c.field-meta.xml
<CustomField>
    <fullName>Account_Executives__c</fullName>
    <description>To show selected Account executives as a hyper link</description>
    <label>Additional Account Executives</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

objects/Account/fields/Invoice_Backup_Documents__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Backup_Documents__c</fullName>
    <label>Invoice Backup Documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVOICE</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>MANIFEST_WEIGHT_TICKET</fullName>
                <label>Disposal Manifest/Weight Ticket</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>T&amp;M</label>
            </value>
            <value>
                <fullName>CERTIFIED_PAYROLL</fullName>
                <label>Certified Payroll</label>
            </value>
            <value>
                <fullName>SPILL_REPORT_WITH_PICTURES</fullName>
                <label>Spill Report w/ Pictures</label>
            </value>
            <value>
                <fullName>MARK_UP_VENDOR_INVOICE_OR_RECEIPT</fullName>
                <label>Mark-Up Vendor Invoice/Receipt</label>
            </value>
            <value>
                <fullName>CUSTOMER_SPECIFIC_DOCUMENTATION</fullName>
                <label>Customer Specific Documentation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Invoice_Portal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Portal__c</fullName>
    <label>Invoice Portal</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoice_Submission_Channels__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Submission_Channels__c</fullName>
    <label>Invoice Submission Channels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>INVOICE_PORTAL</fullName>
                <label>Invoice Portal</label>
            </value>
            <value>
                <fullName>HARD_COPY_SUBMITTAL</fullName>
                <label>Hard Copy Submittal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/PO_Required__c.field-meta.xml
<CustomField>
    <fullName>PO_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PO Required</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Contact/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Service Center</description>
    <inlineHelpText>Choose the Employee Service Center</inlineHelpText>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/fields/EQAI_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Terms_Code__c</fullName>
    <label>EQAI Terms Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Account_Executives__c.field-meta.xml
<CustomField>
    <fullName>Account_Executives__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Quotes/Orders (Account Executive)</relationshipLabel>
    <relationshipName>Sales_Orders_AE</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Bill_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-to Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Bill_to_Customer_No__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Contact_Type_Filter__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes/Orders (Bill-to Contact)</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>To track sales order close date</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Internal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Internal_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Contact</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <formula>User__r.RSG_EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSG EIN #</label>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/fields/Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Territory_Code__c</fullName>
    <label>Territory Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <label>Billing</label>
</RecordType>

objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

classes/SFJobBillingProjectJSON.cls
/*
* Class Name: SFJobBillingProjectJSON
* Summary  : Details format send to EQAI

* Modification Log :
* Developer                 Date                   Description
--------------------------------------------------------------------------------------------------------------               
Sanjana Ravichandran           15/04/2024         76997: new billing project within EQAI from Salesforce "Job Billing Project"
Sanjana Ravichandran		   26/04/2024		  Update the JSON based on new mapping sheet
Sanjana Ravichandran 		   05-15-2024 		  Added Invoice Backup Document field in the JSON
Vennila Paramasivam			05/20/2024				 Task 88134: Added 'SF Job Level - ' infront of sales order name.
Sathish Rosekumar			05/21/2024			  Made the default value as '99' if territory code for account executive is null
Vennila Paramasivam			05/24/2024			  Added Role.
Pavithra Periyasamy			02/24/2025           US142143: Salesforce : Replace PO_Number_Type__c with PO_Required__c Field
*************************************************************************************************************/
public class SFJobBillingProjectJSON {
    Public String  D365CustomerId;
    Public DateTime  DateAdded;
    Public DateTime  DateModified;
    Public String EmployeeId;
    Public String SalesforceJobBillingProjectCsid;
    Public DateTime SalesforceSalesOrderCloseDate;
    Public String ReopenFlag;
    Public String contact_ID;
    Public String MailToBillToAddressFlag;
    Public String TermsCode;
    Public String ProjectName;
    Public String InvoiceComment1;
    Public String InvoiceComment2;
    Public String InvoiceComment3;
    Public String InvoiceComment4;
    Public String InvoiceComment5;
    Public String added_by;
    Public String modified_by;
    Public String InvoicePackageContent;
    Public String PORequiredFlag;
    Public String DistributionMethod;
    Public String EManifestFeeOption;
    Public String AllFacilitiesFlag;
    Public String PrintWosWithStartDateFlag;
    Public String InsuranceSurchargeFlag;
    Public Integer RegionId;
    Public String CustBillXContDistributionMethod;
    Public String CustBillXContInvoicePackageContent;
    Public String CustomerBillingTerritoryStatus;
    Public String CustomerBillingTerritoryType;
    Public Integer BusinessSegmentUid1;
    Public Integer BusinessSegmentUid2;
    Public String CustomerBillingTerritoryCode;
    Public String CusBilXContactEmail;
    //Public String CusBilXContactName;
    Public String RsgEin;
    Public String InvoiceFlag;
    Public String EManifestFlag;
    Public String RecordType;
    Public String SalesforceInvoiceCSID;
    Public String InvoiceBackupDocument;
    Public String BreakCode1;
    Public String BreakCode2;
    Public String BreakCode3;
    Public String EbillingFlag;
    Public Integer CompanyId;
    Public Integer ProfitCenterId;
    Public String Role;
    Public String SalesforceSoQuoteId;
    
    
    public SFJobBillingProjectJSON(Sales_order__c salesOrderRec, String employeeId, Boolean isReOpen,String salesInvoiceCSID, map<String,String>  company_Id_EQIMap, map<String,String> profit_Ctr_Id_EQIMap){
        this.SalesforceInvoiceCSID = salesInvoiceCSID;
        this.D365CustomerId= (salesOrderRec.Bill_to_Customer_No__c!=null && salesOrderRec.Bill_to_Customer_No__r.Sage_Customer_No__c!=null)? salesOrderRec.Bill_to_Customer_No__r.Sage_Customer_No__c:null;
                 
        this.DateAdded = salesOrderRec.CreatedDate;
        this.DateModified = salesOrderRec.LastModifiedDate;
        this.EmployeeId = employeeId;
        this.SalesforceJobBillingProjectCsid = salesOrderRec.CSID__c;
        this.ReopenFlag = isReOpen?'T': salesOrderRec.Document_Status__c == 'Closed' ? 'F':null;
        this.SalesforceSalesOrderCloseDate = this.ReopenFlag == 'F'?salesOrderRec.Close_Date__c:null;
        this.contact_ID = salesOrderRec.Bill_to_Contact__r.Name +'-'+ salesOrderRec.Bill_to_Contact__r.Email ;
        if(salesOrderRec.Bill_to_Customer_No__c!=null && salesOrderRec.Bill_to_Customer_No__r.Invoice_Submission_Channels__c!=null){
            if(salesOrderRec.Bill_to_Customer_No__r.Invoice_Submission_Channels__c == 'EMAIL'){
                this.MailToBillToAddressFlag ='F';
            }
            else 
                if(salesOrderRec.Bill_to_Customer_No__r.Invoice_Submission_Channels__c=='HARD_COPY_SUBMITTAL'){
                    this.MailToBillToAddressFlag ='T';
                }
            else
                if(salesOrderRec.Bill_to_Customer_No__r.Invoice_Submission_Channels__c=='INVOICE_PORTAL'){
                    this.MailToBillToAddressFlag = null;
                }
        }
        if(salesOrderRec.Service_Center__c != null && salesOrderRec.Service_Center__r.Name != null && company_Id_EQIMap !=null && company_Id_EQIMap.containskey(salesOrderRec.Service_Center__r.Name)) CompanyId = Integer.valueOf(company_Id_EQIMap.get(salesOrderRec.Service_Center__r.Name));
        if(salesOrderRec.Service_Center__c != null && salesOrderRec.Service_Center__r.Name != null && profit_Ctr_Id_EQIMap !=null && profit_Ctr_Id_EQIMap.containskey(salesOrderRec.Service_Center__r.Name)) ProfitCenterId = Integer.valueOf(profit_Ctr_Id_EQIMap.get(salesOrderRec.Service_Center__r.Name));
        
        this.TermsCode=(salesOrderRec.Payment_Term__c!=null && salesOrderRec.Payment_Term__r.EQAI_Terms_Code__c != null)?salesOrderRec.Payment_Term__r.EQAI_Terms_Code__c:null;
        if(
            salesOrderRec.Bill_to_Customer_No__c!=null &&
            salesOrderRec.Bill_to_Customer_No__r.Payment_Term__c != null
            && salesOrderRec.Bill_to_Customer_No__r.Payment_Term__r.EQAI_Terms_Code__c != null && 
            salesOrderRec.Payment_Term__c!=null && 
            salesOrderRec.Payment_Term__r.EQAI_Terms_Code__c != null
        ){
            if(salesOrderRec.Bill_to_Customer_No__r.Payment_Term__r.EQAI_Terms_Code__c != salesOrderRec.Payment_Term__r.EQAI_Terms_Code__c){
                this.TermsCode = salesOrderRec.Payment_Term__r.EQAI_Terms_Code__c;
            }else{
                this.TermsCode = null;
            }
        }else{
            this.TermsCode = null;
        }
        
        this.ProjectName = salesOrderRec.Name != null? 'SF Job Level - '+salesOrderRec.Name:null;
        if (salesOrderRec.Internal_Comments__c != null) {
            List<String> commentSegments = splitComments(salesOrderRec.Internal_Comments__c);
            for (Integer i = 0; i < Math.min(commentSegments.size(), 5); i++) {
                String fieldName = 'InvoiceComment' + (i + 1);
                if (i == 0) {
                    this.InvoiceComment1 = commentSegments[i];
                } else if (i == 1) {
                    this.InvoiceComment2 = commentSegments[i];
                } else if (i == 2) {
                    this.InvoiceComment3 = commentSegments[i];
                } else if (i == 3) {
                    this.InvoiceComment4 = commentSegments[i];
                } else if (i == 4) {
                    this.InvoiceComment5 = commentSegments[i];
                }
            }
        }
        this.modified_by =salesOrderRec.LastModifiedBy.Name;
        this.added_by = salesOrderRec.CreatedBy.Name;
        this.CustomerBillingTerritoryCode = salesOrderRec.Account_Executives__c != null?
            salesOrderRec.Account_Executives__r.Territory_Code__c != null?salesOrderRec.Account_Executives__r.Territory_Code__c:'99':null;
        
        this.RsgEin = (salesOrderRec.Account_Executives__c != null && salesOrderRec.Account_Executives__r.Internal_Contact__c)
            ?salesOrderRec.Account_Executives__r.RSG_EIN__c
            : null; 
        
        //this.CusBilXContactName = salesOrderRec.Bill_to_Contact__r.Name;
        this.CusBilXContactEmail = salesOrderRec.Bill_to_Contact__r.Email;
        this.InvoicePackageContent = 'C';
        this.DistributionMethod = 'M';
        this.EManifestFeeOption = 'C';
        this.AllFacilitiesFlag = 'T';
        this.PrintWosWithStartDateFlag = 'T';
        this.InsuranceSurchargeFlag = 'T';
        this.RegionId = 2;
        //88092
        this.CustBillXContDistributionMethod = 'A';
        //88092
        this.CustBillXContInvoicePackageContent ='C';
        this.CustomerBillingTerritoryStatus = 'A';
        this.CustomerBillingTerritoryType = 'T';
        this.BusinessSegmentUid1 = 1;
        this.BusinessSegmentUid2 = 2;
        this.InvoiceFlag ='S';
        this.RecordType = 'B';
        this.EManifestFlag = 'T'; 
        this.InvoiceBackupDocument = salesOrderRec.Bill_to_Customer_No__r.Invoice_Backup_Documents__c;
       // this.InvoiceBackupDocument = 'Invoice';        
        if(salesOrderRec.Bill_to_Customer_No__r!=null && (salesOrderRec.Bill_to_Customer_No__r.PO_Number_Type__c!=null || salesOrderRec.Bill_to_Customer_No__r.PO_Required__c)){
            //if(salesOrderRec.Bill_to_Customer_No__r.PO_Number_Type__c == 'ALPHANUMERICAL' ||salesOrderRec.Bill_to_Customer_No__r.PO_Number_Type__c=='NUMERICAL' || salesOrderRec.Bill_to_Customer_No__r.PO_Number_Type__c=='NAME_OF_CONTACT'){
                this.PORequiredFlag ='T'; 
                this.BreakCode1 = 'B';
                this.BreakCode2 = 'P';
                this.BreakCode3 = 'I';
            //}
        }else{
            	this.PORequiredFlag ='F';
                this.BreakCode1 = 'B';
                this.BreakCode2 = 'I';
                this.BreakCode3 = 'N';  
            }
        this.EbillingFlag = (salesOrderRec.Bill_to_Customer_No__c!=null && salesOrderRec.Bill_to_Customer_No__r.Invoice_Portal__c!=null)? 'T':'F';
 		this.SalesforceSoQuoteId = salesOrderRec.Name;
        //88158
        this.Role = (salesOrderRec.Bill_to_Contact__c != null)?salesOrderRec.Bill_to_Contact__r.Title:null; 
   
    }
    
    private static List<String> splitComments(String comments) {
        List<String> segments = new List<String>();
        while (comments.length() > 80) {
            segments.add(comments.substring(0, 80));
            comments = comments.substring(80);
        }
        segments.add(comments);
        return segments;
    }
}