objects/Account/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts (Account Executive)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Invoice_Portal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Portal__c</fullName>
    <label>Invoice Portal</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoice_Submission_Channels__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Submission_Channels__c</fullName>
    <label>Invoice Submission Channels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>INVOICE_PORTAL</fullName>
                <label>Invoice Portal</label>
            </value>
            <value>
                <fullName>HARD_COPY_SUBMITTAL</fullName>
                <label>Hard Copy Submittal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

objects/Contract/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Contract/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-REPUBLIC SERVICES</fullName>
            </value>
            <value>
                <fullName>5-RS-ES Gulf Coast</fullName>
            </value>
            <value>
                <fullName>1-ACV ENVIRO</fullName>
                <isActive>false</isActive>
                <label>1-ACV ENVIRO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contract/fields/Surcharge_Type__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Type__c</fullName>
    <label>Surcharge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>EEC Fee</fullName>
            </value>
            <value>
                <fullName>Fuel Surcharge</fullName>
            </value>
            <value>
                <fullName>ESIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/cwbtool__ErrorLog__c/cwbtool__ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Stores all the exceptions thrown by code</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/fields/EQAI_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Terms_Code__c</fullName>
    <label>EQAI Terms Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Executive</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/Internal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Internal_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Contact</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <formula>User__r.RSG_EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSG EIN #</label>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/fields/Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Territory_Code__c</fullName>
    <label>Territory Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Company__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

classes/ContractBillingProjectTest.cls
@IsTest
public class ContractBillingProjectTest {
   
    @IsTest
    private static void testContractService1(){
        Subsidiary_Company__c subC = new Subsidiary_Company__c(
            Name = '1-ACV ENVIRO',
            Display_Name__c = '081223'
        );
        insert subC;
        Account corporate = TestDataUtil.corporateAccountRecord;
        corporate.Subsidiary_Company__c = subC.Id;
        corporate.Invoice_Submission_Channels__c ='EMAIL';
        update corporate;
        Contract contract = new Contract();
        contract.AccountId = corporate.Id;
        contract.Status = 'Draft';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Subsidiary__c = '1-ACV ENVIRO';
        insert contract;
        contract.Surcharge_Type__c = 'EEC Fee';
        contract.Status ='Activated';
        Test.startTest();
          Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
         try{
         update contract;   
        }
        catch(Exception e){
            
        }
         
        Test.stopTest();
    }
      @IsTest
    private static void testContractService2(){
        Subsidiary_Company__c subC = new Subsidiary_Company__c(
            Name = '1-ACV ENVIRO',
            Display_Name__c = '081223'
        );
        insert subC;
        Account corporate = TestDataUtil.corporateAccountRecord;
        corporate.Subsidiary_Company__c = subC.Id;
        corporate.Invoice_Submission_Channels__c ='HARD_COPY_SUBMITTAL';
        corporate.PO_Number_Type__c = 'ALPHANUMERICAL';
        update corporate;
        Contract contract = new Contract();
        contract.AccountId = corporate.Id;
        contract.Status = 'Draft';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Subsidiary__c = '1-ACV ENVIRO';
        insert contract;
        contract.Surcharge_Type__c = 'EEC Fee';
        contract.Status ='Activated';
        Test.startTest();
          Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
         try{
         update contract;   
        }
        catch(Exception e){
            
        }
         
        Test.stopTest();
    }
     @IsTest
    private static void testContractService5(){
        Subsidiary_Company__c subC = new Subsidiary_Company__c(
            Name = '1-ACV ENVIRO',
            Display_Name__c = '081223'
        );
        insert subC;
        Account corporate = TestDataUtil.corporateAccountRecord;
        corporate.Subsidiary_Company__c = subC.Id;
        corporate.Invoice_Submission_Channels__c ='INVOICE_PORTAL';
        update corporate;
        Contract contract = new Contract();
        contract.AccountId = corporate.Id;
        contract.Status = 'Draft';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Subsidiary__c = '1-ACV ENVIRO';
        insert contract;
        contract.Surcharge_Type__c = 'EEC Fee';
        contract.Status ='Activated';
        Test.startTest();
          Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
         try{
         update contract;   
        }
        catch(Exception e){
            
        }
         
        Test.stopTest();
    }
    @IsTest
    private static void testContractServiceException(){
        
        Test.startTest();
        ContractBillingProjectServiceQueueable.insertErrorLog('TEST_ERROR','InvalidId_Erro',93,'prinstrace','Request');
        Test.stopTest();
        List<cwbtool__ErrorLog__c> errorlogs = [SELECT Id FROM cwbtool__ErrorLog__c];
        System.assertEquals(true,errorlogs.size()>0);//assertion
    }
    
    @IsTest
    private static void testCreateCaseWithParentId(){  
         Subsidiary_Company__c subC = new Subsidiary_Company__c(
            Name = '1-ACV ENVIRO',
            Display_Name__c = '081223'
        );
        insert subC;
        Account corporate = TestDataUtil.corporateAccountRecord;
        corporate.Subsidiary_Company__c = subC.Id;
        corporate.Invoice_Submission_Channels__c ='INVOICE_PORTAL';
        corporate.PO_Number_Type__c = 'ALPHANUMERICAL';
        update corporate;
        Contact testContact = TestDataUtil.Contact2Record;
        testContact.AccountId = corporate.Id;
        update testContact;
        Contract contract = new Contract();
        contract.AccountId = corporate.Id;
        contract.Status = 'Draft';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Subsidiary__c = '1-ACV ENVIRO';
        contract.Internal_Comments__c = 'During UAT for billing project creation,several fields were found to be errors and also new requirements needed.';
        insert contract;
        
        Test.StartTest();
        Contract cotractRec = [SELECT Id,Name,Account.Invoice_Submission_Channels__c,Payment_Term__c,Payment_Term__r.EQAI_Terms_Code__c,Account.Sage_Customer_No__c,ContractNumber,CreatedDate,LastModifiedDate,Account.PO_Number_Type__c,Account.Account_Executive__c,Internal_Comments__c,Account.Salesperson__r.Territory_Code__c,
                               CreatedBy.Name,LastModifiedBy.Name,Account.Account_Executive__r.Internal_Contact__c,Account.Account_Executive__r.RSG_EIN__c,Account.Invoice_Portal__c FROM  Contract WHERE Id = :contract.Id];
        ContractBillingProjectJSON contractBillingJson = new ContractBillingProjectJSON(cotractRec,'12345678',testContact);
        ContractBillingProjectServiceQueueable.createCaseWithParentId(contract.Id,'Error','check','Request');
        ContractBillingProjectServiceQueueable.splitSuccessMessage('Error1;Error2');
        Test.StopTest();
    
    }
}