objects/Account/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts (Account Executive)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGR</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE</fullName>
            </value>
            <value>
                <fullName>CHEMICAL</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION</fullName>
            </value>
            <value>
                <fullName>CONSULTANT-ENGINEER</fullName>
            </value>
            <value>
                <fullName>CONTRACTOR</fullName>
            </value>
            <value>
                <fullName>GOVERNMENT</fullName>
            </value>
            <value>
                <fullName>GSA</fullName>
            </value>
            <value>
                <fullName>HOSPITAL</fullName>
            </value>
            <value>
                <fullName>I/C</fullName>
            </value>
            <value>
                <fullName>INSURANCE</fullName>
            </value>
            <value>
                <fullName>LAB</fullName>
            </value>
            <value>
                <fullName>MANU</fullName>
            </value>
            <value>
                <fullName>MARINE</fullName>
            </value>
            <value>
                <fullName>OIL &amp; GAS</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>PETROLEUM</fullName>
            </value>
            <value>
                <fullName>PHARMACEUTICAL</fullName>
            </value>
            <value>
                <fullName>PROPERTY</fullName>
            </value>
            <value>
                <fullName>REFINERY</fullName>
            </value>
            <value>
                <fullName>REMEDIATION</fullName>
            </value>
            <value>
                <fullName>RESIDENCE</fullName>
            </value>
            <value>
                <fullName>SCHOOLS</fullName>
            </value>
            <value>
                <fullName>STEEL</fullName>
            </value>
            <value>
                <fullName>TRANS</fullName>
            </value>
            <value>
                <fullName>UTILITIES</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>OIL AND GAS</fullName>
            </value>
            <value>
                <fullName>ASBESTOS</fullName>
                <isActive>false</isActive>
                <label>ASBESTOS</label>
            </value>
            <value>
                <fullName>AUTOMBILE</fullName>
                <isActive>false</isActive>
                <label>AUTOMBILE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Salesperson__r.Salesperson_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Area__c.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/GL_Account__c/GL_Account__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GL_Account__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/fields/Discount_Date_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Discount_Date_Calculation__c</fullName>
    <label>Discount Date Calculation</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Payment_Term__c/fields/Discount_Pct__c.field-meta.xml
<CustomField>
    <fullName>Discount_Pct__c</fullName>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Payment_Term__c/fields/Due_Date_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Calculation__c</fullName>
    <label>Due Date Calculation</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tax_Area__c.Blocked__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Quotes/Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Executive</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Tax_Area__c/Tax_Area__c.object-meta.xml
<CustomObject>
    <label>Tax Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Area__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Tax_Area__c/fields/Sales_Tax_Account__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Tax Account</label>
    <referenceTo>GL_Account__c</referenceTo>
    <relationshipLabel>Tax Areas</relationshipLabel>
    <relationshipName>Tax_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/rsgTriggerStrategyTest.cls
/************************************************************************************************************
* Name         :  rsgTriggerStrategyTest
* Description  :  rsgTriggerStrategyTest
*
* Modification Log :
* Developer                    Date            Description
* ---------------------------------------------------------------------------- 
Harika Madapathi         07/22/2023             68128 - Tech Debt: Update Trigger Framework for SalesOrder object
*************************************************************************************************************/
@IsTest
private class rsgTriggerStrategyTest {
    
    @testSetup
    private static void setup() {
        
        SalesPerson__c sp =  new SalesPerson__c(Name = 'London Postmaster',Salesperson_Code__c = 'HOU',Status__c = 'Active');
        insert sp;
        Subsidiary_Company__c sco = TestDataUtil.SubsidiaryCompanyRecord;
        Service_Center__c sc = new Service_Center__c (Name = 'Test',
                                                      Description__c = 'SC01 Elizabeth, NJ Ops', Code__c = '01', Subsidiary_Company__c = sco.Id);//TestDataUtil.ServiceCenterRecord;
        insert sc;
        
        Payment_Term__c pt = new Payment_Term__c(
            Name = '14 DAYS',
            Discount_Pct__c = 0,
            Discount_Date_Calculation__c = 0,
            Due_Date_Calculation__c = 0
        );
        insert pt;
        GL_Account__c glAccount = new GL_Account__c(
            Name = 'GLAccountRecordTest',
            Description__c = 'Test GL Account'
        );
        insert glAccount;
        Tax_Area__c ta = new Tax_Area__c(
            Name = 'NJ',
            Sales_Tax_Account__c = glAccount.Id
        );
        insert ta;
        
        Account account = new Account();
        account.Name = 'Cannon Group';
        account.AccountNumber = '01-00000001';
        account.Payment_Term__c = pt.Id;
        account.Tax_Area__c = ta.Id;
        account.BillingStreet = 'test Street';
        account.BillingCity = 'test City';
        account.BillingState = 'Colorado';
        account.BillingStateCode = 'CO';
        account.BillingCountryCode = 'US';
        account.BillingPostalCode = 'test postalcode';
        account.Customer_Type__c = 'UTILITIES';
        account.Account_Executive__c = sp.Id;
        account.Salesperson__c = sp.Id;
        System.debug('sco.Id======>'+sco.Id);
        account.Subsidiary_Company__c = sco.Id;
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        insert account;
        
    }
    
    @IsTest
    static void executeTriggerHandler(){
        
        SalesPerson__c sp = [Select Id from SalesPerson__c LIMIT 1];
        Service_Center__c sc= [Select Id from Service_Center__c LIMIT 1];
        Account acc = [Select Id from Account LIMIT 1];
        Subsidiary_Company__c sco = [Select Id from Subsidiary_Company__c LIMIT 1];
        
        test.startTest();
        Sales_Order__c so = new Sales_Order__c(Name = 'NJ57506-01-2083',
                                               Surcharge_Type__c = 'N/A',Service_Center__c =  sc.id,
                                               Site_Name__c = 'Test SIte Name xx', Project_Coordinator__c = sp.id);
        so.Bill_to_Customer_No__c = acc.Id;
        so.Subsidiary_Company__c = sco.Id;
        insert so;
        test.stopTest();
        
        System.assert(true, 'This is a code coverage'); 
    }
    
    @IsTest
    static void executeTriggerHandler_with2updates(){
        SalesPerson__c sp = [Select Id from SalesPerson__c LIMIT 1];
        Service_Center__c sc= [Select Id from Service_Center__c LIMIT 1];
        Account acc = [Select Id from Account LIMIT 1];
        Subsidiary_Company__c sco = [Select Id from Subsidiary_Company__c LIMIT 1];
        
        Sales_Order__c so = new Sales_Order__c(Name = 'NJ57506-01-2083',
                                               Surcharge_Type__c = 'N/A',Service_Center__c =  sc.id,
                                               Site_Name__c = 'Test SIte Name xx', Project_Coordinator__c = sp.id);
        so.Bill_to_Customer_No__c = acc.Id;
        so.Subsidiary_Company__c = sco.Id;
        insert so;
        
        test.startTest();
        
        so.Billing_Type__c = 'T&M';
        update so;
        
        test.stopTest();
        
    }
    
    @IsTest
    static void getHandlerNameFromTriggerConfigurationSettings(){
        test.startTest();
        rsgTrigger_Configuration_Setting__mdt rsgTriggerConfigurationSetting = rsgTriggerStrategy.getHandlerNameFromTriggerConfigurationSettings('Sales_Order__c', 'insert', 'after');
        test.stopTest();
        
        System.assert(rsgTriggerConfigurationSetting != null, 'Expected the class to be initialized');
        System.assertEquals('SalesOrder_AfterInsertTriggerHandler', rsgTriggerConfigurationSetting.Trigger_Handler_Name__c, 'The Handler Name Should match.');
    }
}