objects/Account/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts (Account Executive)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Invoice_Portal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Portal__c</fullName>
    <label>Invoice Portal</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoice_Submission_Channels__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Submission_Channels__c</fullName>
    <label>Invoice Submission Channels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>INVOICE_PORTAL</fullName>
                <label>Invoice Portal</label>
            </value>
            <value>
                <fullName>HARD_COPY_SUBMITTAL</fullName>
                <label>Hard Copy Submittal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Case/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Case/fields/Http_Request__c.field-meta.xml
<CustomField>
    <fullName>Http_Request__c</fullName>
    <label>Http Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Case/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Case/recordTypes/Case_Record.recordType-meta.xml
<RecordType>
    <fullName>Case_Record</fullName>
    <active>true</active>
    <businessProcess>Cases</businessProcess>
    <label>Salesforce Support</label>
</RecordType>

objects/Contract/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Account.Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract/fields/Contract_Billing_Project_created_in_EQAI__c.field-meta.xml
<CustomField>
    <fullName>Contract_Billing_Project_created_in_EQAI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Billing Project created in EQAI</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Contract/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/cwbtool__ErrorLog__c/cwbtool__ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Stores all the exceptions thrown by code</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/cwbtool__ErrorLog__c/fields/cwbtool__LineNumber__c.field-meta.xml
<CustomField>
    <fullName>cwbtool__LineNumber__c</fullName>
    <description>Line Number from where the exception was thrown.</description>
    <inlineHelpText>Line Number from where the exception was thrown.</inlineHelpText>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/cwbtool__ErrorLog__c/fields/cwbtool__StackTrace__c.field-meta.xml
<CustomField>
    <fullName>cwbtool__StackTrace__c</fullName>
    <description>Detailed stack trace showing additional error information</description>
    <inlineHelpText>Detailed stack trace showing additional error information</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/cwbtool__ErrorLog__c/fields/Http_Request__c.field-meta.xml
<CustomField>
    <fullName>Http_Request__c</fullName>
    <label>Http Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/cwbtool__ErrorLog__c/fields/Http_Response__c.field-meta.xml
<CustomField>
    <fullName>Http_Response__c</fullName>
    <label>Http Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/cwbtool__ErrorLog__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/cwbtool__ErrorLog__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/EQAI_API_URL_Extensions__mdt.object-meta.xml
<CustomObject>
    <description>URL Extensions for EQAI API Endpoints</description>
    <label>EQAI API URL Extensions</label>
    <pluralLabel>EQAI API URL Extensions</pluralLabel>
</CustomObject>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Extension__c.field-meta.xml
<CustomField>
    <fullName>API_Extension__c</fullName>
    <label>API Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/fields/EQAI_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Terms_Code__c</fullName>
    <label>EQAI Terms Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Sales Invoices (Account Executive)</relationshipLabel>
    <relationshipName>Sales_Invoices_AE</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Invoices (Sell-to Contact)</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Invoice__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Reversed_from_SI__c.field-meta.xml
<CustomField>
    <fullName>Reversed_from_SI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed from SI</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Account Executive</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/Internal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Internal_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Contact</label>
    <type>Checkbox</type>
</CustomField>

objects/Salesperson__c/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <formula>User__r.RSG_EIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSG EIN #</label>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/fields/Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Territory_Code__c</fullName>
    <label>Territory Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/User/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <description>Employee Workday Number</description>
    <label>RSG EIN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/SendEQAIBillingProjectCtrl.cls
public class SendEQAIBillingProjectCtrl {
    @AuraEnabled
    public static String sendBillingProjectToEQAI(Id contractId) {
        CompanyMgmt.systemCall = true;
        
        String requestJSON ='';
        try{ 
            String employeeId = [SELECT RSG_EIN__c from User WHERE Id =: userinfo.getUserId() limit 1].RSG_EIN__c;
            EQAI_API_URL_Extensions__mdt getWOHeaderInfo = [select API_Extension__c, API_Key__c, API_Token__c, DeveloperName from EQAI_API_URL_Extensions__mdt where DeveloperName='getContractBillingInfo'];
            Contract contractRec = [SELECT Id, Name, AccountId, Account.Invoice_Submission_Channels__c, Payment_Term__c, 
                                    Payment_Term__r.EQAI_Terms_Code__c, Account.Sage_Customer_No__c, ContractNumber, CreatedDate, 
                                    LastModifiedDate,Contract_Billing_Project_created_in_EQAI__c, Account.PO_Number_Type__c,CreatedBy.Name,LastModifiedBy.Name,
                                    Internal_Comments__c,Account.Account_Executive__r.Territory_Code__c,
                                    Account.Account_Executive__r.Internal_Contact__c,Account.Account_Executive__r.RSG_EIN__c,Account.Invoice_Portal__c,
                                    (SELECT Contact__r.Name, Contact__r.Email FROM Sales_Invoices__r LIMIT 1) FROM Contract WHERE Id = :contractId];
            Contact billToContact = [SELECT Id, Name, Email FROM Contact WHERE AccountId = :contractRec.AccountId ORDER BY LastActivityDate DESC LIMIT 1];
            ContractBillingProjectJSON contractBillingJson = new ContractBillingProjectJSON(contractRec,employeeId,billToContact);
            requestJSON = String.valueOf(contractBillingJson);
            System.debug('contractBillingJson++'+System.Json.serialize(getWOHeaderInfo));
            String response = WorkOrderQuoteService.getPostCalloutResponseContents(getWOHeaderInfo.API_Extension__c, System.Json.serialize(contractBillingJson),'POST',getWOHeaderInfo.API_Key__c,getWOHeaderInfo.API_Token__c);
            System.debug('response ++'+response);
            if(response == '200'){
                contractRec.Status = 'Activated';
                contractRec.Contract_Billing_Project_created_in_EQAI__c = true;
                update contractRec;  
            }else{
                createCaseWithParentId(contractRec.Id,'Error in Contract Billing Project',splitSuccessMessage(response),Json.serialize(contractBillingJson));               
            }
            return response;
            
        }
        
        Catch(Exception e){
            System.Debug('Error at  - '+e.getLineNumber()+' Message - '+e.getMessage()+' cause '+e.getCause());            
            insertErrorLog(contractId,string.valueOf(e.getMessage()),e.getLineNumber(),string.valueOf(e.getCause()),requestJSON); 
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    public static void insertErrorLog(
        String contractId,String errorMessage,Integer lineNumber,
        String strackTrace,String request
    ){
        cwbtool__ErrorLog__c errorlog = new cwbtool__ErrorLog__c(Object_Name__c = 'Contract Billing Project', Record_Id__c = contractId, 
                                                                 Http_Response__c = errorMessage, cwbtool__LineNumber__c = decimal.valueOf(lineNumber),
                                                                 cwbtool__StackTrace__c = strackTrace, Http_Request__c = request);
        insert errorlog;
    }
    
    
    public static void createCaseWithParentId(Id parentId,String subject,String caseDescription,String httpRequest) {
        try{
            Group newCaseQueue = [SELECT Id FROM Group WHERE Type = 'Queue' and Name = 'Case Owners'];
            Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Case_Record').getRecordTypeId();
            Case newCase = new Case();
            newCase.Subject = subject;
            newCase.RecordTypeId = recordTypeId;
            newCase.Description = caseDescription;
            newCase.Http_Request__c = httpRequest;
            newCase.Contract__c = parentId; 
            newCase.Reason = 'EQAI-Contract Error'; 
            newCase.Priority = 'Medium';    
            newCase.OwnerId = newCaseQueue.Id; 
            insert newCase;
            System.debug('Case created successfully with Id: ' + newCase.Id);
        }Catch(Exception ex)
        {
            System.Debug('Error::'+ex.getMessage());
        }
    }    
    
    public Static string splitSuccessMessage(String message){
        List<String> messages = message.split(';');
        String generalErrorMessage = messages.remove(0);
        String finalErrorMessage = generalErrorMessage + '\n';
        for(Integer i = 0; i < messages.size(); i++) {
            finalErrorMessage += '('+(i+1)+')' + '.' + messages[i];
            if(i < messages.size() - 1) {
                finalErrorMessage += '\n';
            }
        } 
        System.debug(finalErrorMessage);
        return finalErrorMessage; 
    }
    
}