objects/Account/fields/Auto_Create_Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Catalog_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Create Catalog Item</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

objects/Purchase_Price__c/Purchase_Price__c.object-meta.xml
<CustomObject>
    <label>Product Catalog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchase_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Prices</relationshipLabel>
    <relationshipName>Purchase_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Purchase_Price__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountTriggersMgmt.cls
/**
 * Created by Steven on 2/27/2018.
 */

public with sharing class AccountTriggersMgmt {
    public static void accountInsertUpdate(List<Account> acctList, Map<Id, Account> oldAcctMap, Boolean isInsert){
        Set<Id> acctIds = new Set<Id>();
        Map<Id, Account> acctMap = new Map<Id, Account>();
        for (Account acct: acctList) {
            acctIds.add(acct.Id);
            acctMap.put(acct.Id, acct);
        }

        Map<Id, Purchase_Price__c> accountPurchasePriceMap = new Map<Id, Purchase_Price__c>();
        List<Purchase_Price__c> ppInsertLst = new List<Purchase_Price__c>();
        List<Purchase_Price__c> ppDeleteLst = new List<Purchase_Price__c>();
        for(Purchase_Price__c pp : [SELECT Id, Name, Account__c FROM Purchase_Price__c WHERE Account__c IN :acctIds AND Name = 'NEW']){
            accountPurchasePriceMap.put(pp.Account__c, pp);
        }

        for(Id acctId : acctMap.keySet()){
            Account acct = acctMap.get(acctId);
            if(acct.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId() &&
                    !accountPurchasePriceMap.containsKey(acctId) &&
                    acct.Auto_Create_Catalog_Item__c == true) {
                Purchase_Price__c pp = new Purchase_Price__c();
                pp.Account__c = acct.Id;
                pp.Name = 'NEW';
                pp.Status__c = 'Approved';
                ppInsertLst.add(pp);
            }

            if(acct.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId() &&
                    accountPurchasePriceMap.containsKey(acctId) &&
                    acct.Auto_Create_Catalog_Item__c == false) {
                ppDeleteLst.add(accountPurchasePriceMap.get(acctId));
            }
        }

        if(ppInsertLst.size() > 0){
            insert ppInsertLst;
        }

        if(ppDeleteLst.size() > 0){
            delete ppDeleteLst;
        }
        /*
        for (Account acct: acctList){
            if(acct.RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId()){
                List<Purchase_Price__c> ppList = [SELECT Id, Name, Account__c FROM Purchase_Price__c WHERE Account__c =: acct.Id AND Name = 'NEW'];
                if(acct.Auto_Create_Catalog_Item__c){
                    if(ppList.size() == 0){
                        Purchase_Price__c pp = new Purchase_Price__c();
                        pp.Account__c = acct.Id;
                        pp.Name = 'NEW';
                        pp.Status__c = 'Approved';
                        insert pp;
                    }
                } else {
                    if(ppList.size() != 0){
                        delete ppList;
                    }
                }
            }
        }
        */
    }

    public static String updateAccountExecutives(String accountExecutiveIds, Map<Id, Salesperson__c> salesPersonRecords){
        String hyperlinks = '';
        integer count = 0;
        
        if(!String.isEmpty(accountExecutiveIds)){      
            integer totalSalesPersons = accountExecutiveIds.split(',').size();     
            String baseUrl = URL.getOrgDomainURL().toExternalForm();
            for (String salesPersonId : accountExecutiveIds.split(',')) {
                Salesperson__c salesPerson = salesPersonRecords.get(salesPersonId);
                if (salesPerson != null) {
                    String recordUrl = baseUrl + '/' + salesPerson.Id;
                    String hyperlink = '<a href="' + recordUrl + '">' + salesPerson.Name + '</a>';
                    hyperlinks += hyperlink;
                    // Append a comma if it's not the last record
                    if (count < totalSalesPersons - 1) {
                        hyperlinks += ', ';
                    }
                }
                count++;
            }                
        }        
        return hyperlinks;
    }
}