objects/Account/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Customer_Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Instructions__c</fullName>
    <label>Customer Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency?</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Inter_co_Account__c.field-meta.xml
<CustomField>
    <fullName>Inter_co_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Accounts are not tax liable.</inlineHelpText>
    <label>Intra-Co</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>Sales_Line__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/UOM_Qty__c.field-meta.xml
<CustomField>
    <fullName>UOM_Qty__c</fullName>
    <label>UOM Qty.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/D365_Project_ID__c.field-meta.xml
<CustomField>
    <fullName>D365_Project_ID__c</fullName>
    <label>D365 Project ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Include_Weekend__c.field-meta.xml
<CustomField>
    <fullName>Include_Weekend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Weekend</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Is_New_D365_Project__c.field-meta.xml
<CustomField>
    <fullName>Is_New_D365_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is New D365 Project</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Tax_Liable__c.field-meta.xml
<CustomField>
    <fullName>Tax_Liable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Tax Liable</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Sales_Order_No_Series__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_No_Series__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order No. Series</label>
    <referenceTo>Numbering_Series__c</referenceTo>
    <relationshipLabel>Service Centers (Job Numbering Series)</relationshipLabel>
    <relationshipName>Service_Centers_Job_Numbering_Series</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesOrderTriggersMgtTest.cls
@isTest
public class SalesOrderTriggersMgtTest {
    
    public static Map<String, Numbering_Series__c> mapNumberSeries = new Map<String, Numbering_Series__c>();
    public static Numbering_Series__c theNumberingSeries;
    @testSetup static void SetupData() {
        //Setup Data
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
        List<Company_Setup__c> theCSList = [SELECT Id From Company_Setup__c WHERE Id = : companySetup.Id];
        System.assertEquals(theCSList.size(), 1);
    }
    
    private static testMethod void Test_SalesOrderTriggersMgt() {
        
        Sales_Order__c SalesOrderRecord=TestDataUtil.SalesOrderRecord;
        Account testAccount= New Account();//TestDataUtil.AccountRecord;
        List<Sales_Order__c>SalesOrderList=New List<Sales_Order__c>();
        testAccount.Id = SalesOrderRecord.Bill_to_Customer_No__c;
        testAccount.Inter_co_Account__c = true;
        testAccount.Tax_Liable__c = false;
        testAccount.Emergency__c = false;
        testAccount.AccountNumber = '123456';
        testAccount.Customer_Billing_Instructions__c = 'Some Billing Instructions';
        testAccount.Billing_Instructions__c = 'Some Billing Instructions';
        update testAccount;
        update SalesOrderRecord;
        SalesOrderList.add(SalesOrderRecord);
        Map<Id,Sales_Order__c>SalesOrderMap=New Map<Id,Sales_Order__c>();
        SalesOrderMap.put(SalesOrderRecord.Id,SalesOrderRecord);
        test.startTest();
        SalesOrderTriggersMgt.SOInsertUpdate(SalesOrderList,SalesOrderMap,True);
        test.stopTest();
        
    }
    private static testMethod void Test_SalesLine() {
        
        Sales_Line__c SalesLineRecord=TestDataUtil.SalesLineRecord;
        SalesLineRecord.Quote_Line__c = SalesLineRecord.Id;
        List<Sales_Line__c>SalesLineList=New List<Sales_Line__c>();
        SalesLineList.add(SalesLineRecord);
        Map<Id,Sales_Line__c>SalesOrderMap=New Map<Id,Sales_Line__c>();
        SalesOrderMap.put(SalesLineRecord.Id,SalesLineRecord);
        CompanyMgmt.byPassTrigger = false;
        SalesOrderTriggersMgt.SLInsertUpdate(SalesLineList,SalesOrderMap);
        
    }  
    private static testMethod void Test_SalesLine1() {
        Sales_Line__c SalesLineRecord = TestDataUtil.SalesEquipmentLineRecord;
        
        //Sales_Line__c SalesLineRecord=TestDataUtil.SalesLineRecord;
        SalesLineRecord.Quote_Line__c = SalesLineRecord.Id;
        List<Sales_Line__c>SalesLineList=New List<Sales_Line__c>();
        SalesLineList.add(SalesLineRecord);
        Map<Id,Sales_Line__c>SalesOrderMap=New Map<Id,Sales_Line__c>();
        SalesOrderMap.put(SalesLineRecord.Id,SalesLineRecord);
        CompanyMgmt.byPassTrigger = false;
        SalesOrderTriggersMgt.SLInsertUpdate(SalesLineList,SalesOrderMap);
        
    }  
    private static testMethod void Test_SalesLine2() {
        Sales_Line__c SalesLineRecord = TestDataUtil.SalesWasteLineRecord;
        
        //Sales_Line__c SalesLineRecord=TestDataUtil.SalesLineRecord;
        SalesLineRecord.Quote_Line__c = SalesLineRecord.Id;
        List<Sales_Line__c>SalesLineList=New List<Sales_Line__c>();
        SalesLineList.add(SalesLineRecord);
        Map<Id,Sales_Line__c>SalesOrderMap=New Map<Id,Sales_Line__c>();
        SalesOrderMap.put(SalesLineRecord.Id,SalesLineRecord);
        CompanyMgmt.byPassTrigger = false;
        SalesOrderTriggersMgt.SLInsertUpdate(SalesLineList,SalesOrderMap);
        
    }  
    
    private static testMethod void Test_SalesOrderTriggersMgt1() {
        
        Test.startTest();
        Sales_Order__c SalesOrderRecord=TestDataUtil.SalesOrderRecord;
        SalesOrderRecord.Name = null;
        Service_Center__c serviceCenter = new Service_Center__c();
        serviceCenter.Id = SalesOrderRecord.Service_Center__c;
        SalesOrderRecord.Service_Center__c = null;
        SalesOrderRecord.Include_Weekend__c = true;
        List<Sales_Order__c>SalesOrderList=New List<Sales_Order__c>();
        SalesOrderList.add(SalesOrderRecord);
        Map<Id,Sales_Order__c>SalesOrderMap=New Map<Id,Sales_Order__c>();
        SalesOrderMap.put(SalesOrderRecord.Id,SalesOrderRecord);
        try{
            SalesOrderTriggersMgt.SOInsertUpdate(SalesOrderList,SalesOrderMap,True);
            
        }catch(Exception e){
            
        }
        serviceCenter.Blocked__c = true;
        update serviceCenter;
        SalesOrderRecord.Service_Center__c = serviceCenter.Id;
        try{
            SalesOrderTriggersMgt.SOInsertUpdate(SalesOrderList,SalesOrderMap,True);
            
        }catch(Exception e){
            
        }
        serviceCenter.Blocked__c = false;
        //serviceCenter.Sales_Order_No_Series__c = null;
        update serviceCenter;
        try{
            SalesOrderTriggersMgt.SOInsertUpdate(SalesOrderList,SalesOrderMap,True);
            
        }catch(Exception e){
            
        }
        Test.stoptest();
    }
    private static testMethod void Test_SalesLineUOMQuantity() {
        Sales_Order__c obj=New Sales_Order__c(); 
        Sales_Line__c SalesLineRecord = TestDataUtil.SalesEquipmentLineRecord;
        obj.Id = SalesLineRecord.Sales_Order__c;
        obj.Document_Type__c = 'Sales Quote';
        obj.Is_New_D365_Project__c = false;
        update obj;
        obj.D365_Project_ID__c = 'P302.56112';
        update obj;
        SalesLineRecord.Quote_Line__c = SalesLineRecord.Id;
        SalesLineRecord.UOM_Qty__c = null;
        SalesLineRecord.Quantity__c = 0;
        SalesLineRecord.Unit_of_Measure__c = null;
        List<Sales_Line__c>SalesLineList=New List<Sales_Line__c>();
        SalesLineList.add(SalesLineRecord);
        Map<Id,Sales_Line__c>SalesOrderMap=New Map<Id,Sales_Line__c>();
        SalesOrderMap.put(SalesLineRecord.Id,SalesLineRecord);
        CompanyMgmt.byPassTrigger = false;
        SalesOrderTriggersMgt.SLInsertUpdate(SalesLineList,SalesOrderMap);
        try{
            delete obj; 
        }Catch(Exception e){}
    }
}