objects/Account/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Customer_Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Instructions__c</fullName>
    <label>Customer Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Customer_Specific_Documentation__c.field-meta.xml
<CustomField>
    <fullName>Customer_Specific_Documentation__c</fullName>
    <label>Customer Specific Documentation</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoice_Backup_Documents__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Backup_Documents__c</fullName>
    <label>Invoice Backup Documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INVOICE</fullName>
                <label>Invoice</label>
            </value>
            <value>
                <fullName>MANIFEST_WEIGHT_TICKET</fullName>
                <label>Disposal Manifest/Weight Ticket</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>T&amp;M</label>
            </value>
            <value>
                <fullName>CERTIFIED_PAYROLL</fullName>
                <label>Certified Payroll</label>
            </value>
            <value>
                <fullName>SPILL_REPORT_WITH_PICTURES</fullName>
                <label>Spill Report w/ Pictures</label>
            </value>
            <value>
                <fullName>MARK_UP_VENDOR_INVOICE_OR_RECEIPT</fullName>
                <label>Mark-Up Vendor Invoice/Receipt</label>
            </value>
            <value>
                <fullName>CUSTOMER_SPECIFIC_DOCUMENTATION</fullName>
                <label>Customer Specific Documentation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Invoice_Email_Contact_Types__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email_Contact_Types__c</fullName>
    <label>Invoice Email Contact Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BILLING</fullName>
                <label>Billing</label>
            </value>
            <value>
                <fullName>SITE</fullName>
                <label>Site</label>
            </value>
            <value>
                <fullName>EXECUTIVE</fullName>
                <label>Executive</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <label>Sales</label>
            </value>
            <value>
                <fullName>QUOTE</fullName>
                <label>Quote</label>
            </value>
            <value>
                <fullName>PURCHASE</fullName>
                <label>Purchase</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Invoice_Portal__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Portal__c</fullName>
    <label>Invoice Portal</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Invoice_Submission_Channels__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Submission_Channels__c</fullName>
    <label>Invoice Submission Channels</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>INVOICE_PORTAL</fullName>
                <label>Invoice Portal</label>
            </value>
            <value>
                <fullName>HARD_COPY_SUBMITTAL</fullName>
                <label>Hard Copy Submittal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

classes/AccountsTest.cls
@IsTest
private class AccountsTest {

    @IsTest
    private static void test(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IAccounts domainAccountMock = new Mocks.Accounts(mocks);
        Account a = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'Test'
        );
        IAccounts domainAccount = Accounts.newInstance(new List<Account>{a});
    }

    @IsTest
    private static void testSelectors(){
        Account customerAccount = TestDataUtil.customerAccountRecord;
        List<Account> accounts = AccountsSelector.newInstance().selectTaxAreaNameById(new Set<Id>{customerAccount.Id});
        accounts = AccountsSelector.newInstance().selectSubsidiaryCompInfoById(new Set<Id>{customerAccount.Id});
        accounts = AccountsSelector.newInstance().selectParentAccountById(new Set<Id>{customerAccount.Id});
        accounts = AccountsSelector.newInstance().selectById(new Set<Id>{customerAccount.Id});
        accounts = AccountsSelector.newInstance().selectBillingInstructionsById(new Set<Id>{customerAccount.Id});
    }

    @IsTest
    private static void testAccountService(){
        Account customerAccount = TestDataUtil.customerAccountRecord;
        customerAccount.PO_Number_Type__c = AccountsService.PO_FORMAT_ALPHANUMERICAL;
        customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_INVOICE;
        customerAccount.Invoice_Email_Contact_Types__c = AccountsService.INVOICE_EMAIL_CONTACT_TYPE_AP;
        customerAccount.Invoice_Email_Contact_Types__c = AccountsService.INVOICE_EMAIL_CONTACT_TYPE_EXECUTIVE;
        customerAccount.Invoice_Email_Contact_Types__c = AccountsService.INVOICE_EMAIL_CONTACT_TYPE_PURCHASE;
        customerAccount.Invoice_Email_Contact_Types__c = AccountsService.INVOICE_EMAIL_CONTACT_TYPE_QUOTE;
        customerAccount.Invoice_Email_Contact_Types__c = AccountsService.INVOICE_EMAIL_CONTACT_TYPE_SALES;
        customerAccount.Invoice_Email_Contact_Types__c = AccountsService.INVOICE_EMAIL_CONTACT_TYPE_SITE;
        customerAccount.Invoice_Submission_Channels__c = AccountsService.INVOICE_SUBMISSION_CHANNEL_EMAIL;
        update customerAccount;

        String poNumber = 'ABC1234';
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }

        poNumber = 'ABC';
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }

        poNumber = 'ABCDEFGHI ';
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }

        customerAccount.PO_Number_Type__c = AccountsService.PO_FORMAT_NUMERICAL;
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }
        //test
        poNumber = '123-123';
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }

        customerAccount.PO_Number_Type__c = AccountsService.PO_FORMAT_NAME_OF_CONTACT;
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }

        poNumber = 'Test Name';
        try{
            AccountsService.validatePONumberFormat(customerAccount, poNumber);
        } catch (Exception e){

        }

        customerAccount.Invoice_Submission_Channels__c = AccountsService.INVOICE_SUBMISSION_CHANNEL_MAIL;
        customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_CERTIFIED_PAYROLL;
        customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_MANIFEST_WEIGHT_TICKET;
        customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_MARK_UP_VENDOR_INVOICE_OR_RECEIPT;
        customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_SPILL_REPORT_WITH_PICTURES;
        //customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_TM;
        update customerAccount;
        customerAccount.Invoice_Submission_Channels__c = AccountsService.INVOICE_SUBMISSION_CHANNEL_INVOICE_PORTAL;
        customerAccount.Invoice_Portal__c = 'www.test.com';
        customerAccount.Invoice_Backup_Documents__c = AccountsService.INVOICE_BACKUP_TYPE_CUSTOMER_SPECIFIC_DOCUMENTATION;
        customerAccount.Customer_Specific_Documentation__c = 'Test Backup Type';
        String tempBillingDescription = AccountsService.generateCustomerBillingVerbose(
                customerAccount.PO_Number_Type__c,
                customerAccount.Invoice_Email_Contact_Types__c,
                customerAccount.Invoice_Submission_Channels__c,
                customerAccount.Invoice_Portal__c,
                customerAccount.Invoice_Backup_Documents__c,
                customerAccount.Customer_Specific_Documentation__c
        );

        customerAccount.Customer_Billing_Instructions__c = 'test customer billing instruction!';
        customerAccount.Billing_Instructions__c = 'test billing instruction!';
        String customerDescription = AccountsService.generateCustomerBillingInstructions(customerAccount);
        
        Account pros = new Account(Name = 'CORP', Type = 'Vendor');
        insert pros;
        
        Account prosp = new Account(Name = 'CORP', Type = 'Prospect');
        insert prosp;
        //test123
        Account cust = new Account(Name = 'CORP', Type = 'Customer', BillingStreet = 'Test Billing Street', Customer_Specific_Documentation__c = 'Test CSD',Billing_Instructions__c='Test BI');
        insert cust;
         
    }
    //test
}