objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts_Billing_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/E_Mail__c.field-meta.xml
<CustomField>
    <fullName>E_Mail__c</fullName>
    <label>E-Mail</label>
    <type>Email</type>
</CustomField>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Order No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchasing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Buy_from_Vendor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Buy_from_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Buy_from_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Buy-from Vendor)</relationshipLabel>
    <relationshipName>Purchase_Orders_BF</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Fully Received</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>All Received</fullName>
                <isActive>false</isActive>
                <label>All Received</label>
            </value>
            <value>
                <fullName>Back Order</fullName>
                <isActive>false</isActive>
                <label>Back Order</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Receipt Created</fullName>
                <isActive>false</isActive>
                <label>Receipt Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PurchaseOrderEmailing.cls
public class PurchaseOrderEmailing {

    private final ApexPages.StandardController theController;
    public final Purchase_Order__c thePO{get; set;}
    public final Contact[] theContactList{get; set;}
    public final Company_setup__c theCompanySetup {get;set;}
    public static String theToAddresses{get;set;}
    public static String theCcAddresses{get;set;}
    public static String theBody{get;set;}
    public static String theSubject{get;set;}
    private String POId;
    public boolean showEmail{get;set;}
    public Boolean isTest{get; set;}
    public Attachment file {
        get {
            if (file == null) file = new Attachment();
            return file;
        }
        set;
    }

    public  PurchaseOrderEmailing(ApexPages.StandardController controller) {
        theController = controller;
        POId = ApexPages.CurrentPage().getParameters().get('id');
        thePO = [SELECT Id, Name, Document_Status__c, E_Mail__c, Billing_Contact__c, Billing_Contact__r.Name,
                    Buy_from_Vendor__c, Buy_from_Vendor__r.Name
                    FROM Purchase_Order__c WHERE Id =: POId];
        theContactList = [SELECT Id, Name, Email FROM Contact WHERE Id =: thePO.Billing_Contact__c];

        showEmail = true;

        if(theContactList.size() == 0){
            showEmail = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Purchasing Contact cannot be blank for purchase order ' + thePO.Name));
        }

        if((thePO.Document_Status__c == 'Open') || thePO.Document_Status__c =='Pending Approval') {
            showEmail = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Document Status must be approved'));
        }

        if(showEmail){
            
            theToAddresses = theContactList[0].Email;
            theSubject = 'Purchase Order ' + thePO.Name + '---' + thePO.Buy_from_Vendor__r.Name;
            theBody = 'Attached please find PO No. ' + thePO.Name + '. Let me know if you have any question. Otherwise, please confirm receipt.';
        }
    }

    public String title {
        get {
            if (POId == null) {
                return 'New Invoice';
            } else {
                return thePO.Name;
            }
        }
    }

    public PageReference EmailPO() {

        Messaging.SingleEmailMessage theEmail = new Messaging.SingleEmailMessage();
        PageReference pdf =  Page.PurchaseOrderPDF;
        pdf.getParameters().put('id',(String)thePO.Id);
        pdf.setRedirect(true);
        Blob b;
        if (Test.isRunningTest())
        {
            b = Blob.valueOf('UNIT.TEST');
        }
        else {
            b = pdf.getContent();
        }

        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();

        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName(thePO.Name+'.pdf');
        efa.setBody(b);
        attachments.add(efa);

        if(file.Body != null){
            Messaging.EmailFileAttachment efa2 = new Messaging.EmailFileAttachment();
            efa2.setFileName(file.Name);
            efa2.setBody(file.Body);
            attachments.add(efa2);
        }

        if (Test.isRunningTest()) {
            theToAddresses = 'test@test.com;abc@abc.com';
        }
        /*else if (UserInfo.getOrganizationId() != '00Df40000000Ns9EAE') {
            theToAddresses = 'rvandra@acvenviro.com;dscerbo@acvenviro.com;jmarcotte@acvenviro.com';
        }*/

        //fix null error <<
        //String[] toAddressesNew = theToAddresses.split(';');
        String[] toAddressesNew = new String[]{};
        if (theToAddresses != null) {
            toAddressesNew = theToAddresses.split(';');
        }
        //fix null error >>

        for(Integer i = 0; i < toAddressesNew.size(); i++){
            if(String.isEmpty(toAddressesNew[i])){
                toAddressesNew.remove(i);
            }
        }

        if (Test.isRunningTest()) {
            theCcAddresses = 'test@test.com;abc@abc.com';
        }

        //fix null error <<
        //String[] ccNew = theCcAddresses.split(';');
        String[] ccNew = new String[]{};
        if (theCcAddresses != null) {
            ccNew = theCcAddresses.split(';');
        }
        //fix null error >>

        for(Integer i = 0; i < ccNew.size(); i++){
            if(String.isEmpty(ccNew[i])){
                ccNew.remove(i);
            }
        }

        if(CompanySettingUtil.isSandbox() == true){
            //toAddressesNew = CompanySettingUtil.getSandboxEmailRecipients();
            toAddressesNew = new List<String>{UserInfo.getUserEmail()};
        }

        theEmail.setSubject(theSubject);
        theEmail.setToAddresses(toAddressesNew);
        theEmail.setCcAddresses(ccNew);
        theEmail.setPlainTextBody(theBody);
        theEmail.setSenderDisplayName(UserInfo.getName());
        if(isTest != true && CompanySettingUtil.isSandbox() != true) {
            theEmail.setTargetObjectId(theContactList[0].Id);
            theEmail.setWhatId(thePO.Id);
            theEmail.setSaveAsActivity(true);
        }

        //theEmail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        theEmail.setFileAttachments(attachments);

        try {
            Messaging.SendEmailResult [] r =
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] {theEmail});
        } catch(Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
        return theController.view();
    }

    public PageReference returnBack() {
        return theController.view();
    }
}