objects/Account/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account_Contract_Association__c/Account_Contract_Association__c.object-meta.xml
<CustomObject>
    <label>Account Contract Association</label>
    <nameField>
        <displayFormat>ACA-{00000000}</displayFormat>
        <label>Entry No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contract Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Contract_Association__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contracts cannot be associated to Customer Accounts that have not yet been issued a customer account number.</errorMessage>
        <filterItems>
            <field>Account.AccountNumber</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Contract</relationshipLabel>
    <relationshipName>Associated_Contract</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Account_Contract_Association__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Associated Account</relationshipLabel>
    <relationshipName>Associated_Account</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Rule__c/fields/Enable_Weekly_Total_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Weekly_Total_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Weekly Total Calculation</label>
    <type>Checkbox</type>
</CustomField>

objects/Billing_Rule__c/fields/Quote_Order_Assumption__c.field-meta.xml
<CustomField>
    <fullName>Quote_Order_Assumption__c</fullName>
    <label>Quote/Order Assumption</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PortalBasis</fullName>
            </value>
            <value>
                <fullName>OvertimeRate</fullName>
            </value>
            <value>
                <fullName>DailyRate</fullName>
            </value>
            <value>
                <fullName>LumpSum</fullName>
            </value>
            <value>
                <fullName>PortalBasisAdv</fullName>
            </value>
            <value>
                <fullName>DefaultBillingRule2023</fullName>
            </value>
            <value>
                <fullName>LumpSum2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contract/fields/Allow_Lunch_Time_on_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Lunch_Time_on_Equipment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Lunch Time on Equipment</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Contract/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract/fields/Checking_Account_1__c.field-meta.xml
<CustomField>
    <fullName>Checking_Account_1__c</fullName>
    <label>Checking Account 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/Checking_Account_2__c.field-meta.xml
<CustomField>
    <fullName>Checking_Account_2__c</fullName>
    <label>Checking Account 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Account.Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract/fields/EFT_Address_1__c.field-meta.xml
<CustomField>
    <fullName>EFT_Address_1__c</fullName>
    <label>EFT Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/EFT_Address_2__c.field-meta.xml
<CustomField>
    <fullName>EFT_Address_2__c</fullName>
    <label>EFT Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/EFT_To_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>EFT_To_Bank_Name__c</fullName>
    <label>EFT To Bank Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/Energy_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Energy_Insurance__c</fullName>
    <label>Energy Insurance</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Contract/fields/Fuel_Surcharge_Pct__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Surcharge_Pct__c</fullName>
    <label>Fuel Surcharge %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Contract/fields/Has_Lump_Sum_Lines__c.field-meta.xml
<CustomField>
    <fullName>Has_Lump_Sum_Lines__c</fullName>
    <label>Has Bundled Lines</label>
    <summaryFilterItems>
        <field>Contract_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Lump Sum</value>
    </summaryFilterItems>
    <summaryForeignKey>Contract_Line__c.Contract__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Contract/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Contract/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

objects/Contract/fields/Override_Remittance_on_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Override_Remittance_on_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Remittance on Invoice</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract/fields/Remittance_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Remittance_Address_1__c</fullName>
    <label>Remittance Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/Remittance_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Remittance_Address_2__c</fullName>
    <label>Remittance Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/Remittance_Name__c.field-meta.xml
<CustomField>
    <fullName>Remittance_Name__c</fullName>
    <label>Remittance Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract/fields/Remittance_Phone__c.field-meta.xml
<CustomField>
    <fullName>Remittance_Phone__c</fullName>
    <label>Remittance Phone</label>
    <type>Phone</type>
</CustomField>

objects/Contract/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <label>Subsidiary</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-REPUBLIC SERVICES</fullName>
            </value>
            <value>
                <fullName>5-RS-ES Gulf Coast</fullName>
            </value>
            <value>
                <fullName>1-ACV ENVIRO</fullName>
                <isActive>false</isActive>
                <label>1-ACV ENVIRO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contract/fields/Surcharge_Pct__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Pct__c</fullName>
    <label>Surcharge %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

objects/Contract/fields/Surcharge_Type__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Type__c</fullName>
    <label>Surcharge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>EEC Fee</fullName>
            </value>
            <value>
                <fullName>Fuel Surcharge</fullName>
            </value>
            <value>
                <fullName>ESIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractsSelector.cls
/*
    Ticket#20079 - new field Payment_Term__c
 */
public class ContractsSelector extends fflib_SObjectSelector implements IContractsSelector{

    public static IContractsSelector newInstance(){
        return (IContractsSelector) Application.Selector.newInstance(Contract.SObjectType);
    }

    public SObjectType getSObjectType() {
        return Contract.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                Contract.Id,
                Contract.Name,
                Contract.ContractNumber,
                Contract.Status,
                Contract.AccountId,
                Contract.StartDate,
                Contract.EndDate,
                Contract.ContractTerm,
                Contract.Fuel_Surcharge_Pct__c,
                Contract.Energy_Insurance__c,
                Contract.Billing_Rule__c,
                Contract.Allow_Lunch_Time_on_Equipment__c,
                Contract.Billing_Instructions__c,
                Contract.Internal_Comments__c,
                Contract.Has_Lump_Sum_Lines__c,
                Contract.Surcharge_Type__c,
                Contract.Surcharge_Pct__c,
                Contract.Override_Remittance_on_Invoice__c,
                Contract.Remittance_Name__c,
                Contract.Remittance_Address_1__c,
                Contract.Remittance_Address_2__c,
                Contract.EFT_To_Bank_Name__c,
                Contract.EFT_Address_1__c,
                Contract.EFT_Address_2__c,
                Contract.Checking_Account_1__c,
                Contract.Checking_Account_2__c,
                Contract.Remittance_Phone__c,
                Contract.Logo__c,
                Contract.Payment_Term__c,
                Contract.Subsidiary__c, //Ticket#20977
                Contract.Description, //Ticket#28846
                Contract.SpecialTerms //Ticket#28846
        };
    }

    public List<Contract> selectById(Set<Id> idSet){
        return (List<Contract>) Database.query(newQueryFactory()
                .selectField('Billing_Rule__r.Name')
                .selectField('Billing_Rule__r.Quote_Order_Assumption__c')
                .selectField('Billing_Rule__r.Enable_Weekly_Total_Calculation__c') //Ticket#20496
                .selectField('Payment_Term__r.Name')
                .setCondition('Id IN :idSet').toSOQL());
    }

    /*
        Ticket#17949 Account Contract Association
    */
    public List<Contract> selectActivatedContractsByIds(Set<Id> contractIds){
        return (List<Contract>) Database.query(newQueryFactory()
                .selectField('Billing_Rule__r.Name')
                .selectField('Billing_Rule__r.Quote_Order_Assumption__c')
                .selectField('Payment_Term__r.Name')
                .selectField('Billing_Rule__r.Enable_Weekly_Total_Calculation__c') //Ticket#20496                
                .setCondition('Id IN :contractIds AND Status = \'Activated\'').toSOQL());
    }

    public List<Contract> selectByIdsWithLines(Set<Id> ids){
        fflib_QueryFactory contractQueryFactory = newQueryFactory();
        new ContractLinesSelector().addQueryFactorySubselect(contractQueryFactory);
        String strQuery = contractQueryFactory.setCondition('Id IN :ids').toSOQL();
        return Database.query(strQuery);
    }

    public List<Contract> selectByIdWithBillingRule(Set<Id> contractIds){
        fflib_QueryFactory contractQueryFactory = newQueryFactory()
                .selectField('Billing_Rule__r.Name')
                .selectField('Billing_Rule__r.Enable_Weekly_Total_Calculation__c'); //Ticket#20496

        new BillingRulesSelector().configureQueryFactoryFields(
                contractQueryFactory,
                Contract.Billing_Rule__c.getDescribe().getRelationshipName());

        return Database.query(
                contractQueryFactory.setCondition('Id IN :contractIds').toSOQL());
    }

    public List<Contract> selectBillingInstructionsById(Set<Id> idSet){
        return (List<Contract>) Database.query(
                newQueryFactory(true).
                        selectField(Contract.Id).
                        selectField(Contract.Billing_Instructions__c).
                        selectField(Contract.Internal_Comments__c).
                        setCondition(' Id IN :idSet').
                        toSOQL());
    }

    /*
        Ticket#17949 Account Contract Association
     */
    public List<Contract> selectByAccountId(Set<Id> accountIds) {
        Set<Id> contractIds = getAssociatedContractIdByAccountId(accountIds);
        return selectActivatedContractsByIds(contractIds);
    }

    /*
        Ticket#17949 Account Contract Association
    */
    public List<Account_Contract_Association__c> selectAccountContractAssociationByAccountId(Set<Id> accountIds){
        List<Account_Contract_Association__c> accountContractAssociations = new List<Account_Contract_Association__c>();
        accountContractAssociations = [SELECT Id, Contract__c, Account__c FROM Account_Contract_Association__c WHERE Account__c IN :accountIds];
        return accountContractAssociations;
    }

    /*
        Ticket#17949 Account Contract Association
    */
    public Set<Id> getAssociatedContractIdByAccountId(Set<Id> accountIds){
        Set<Id> contractIds = new Set<Id>();
        for(Account_Contract_Association__c accountContractAssociation : selectAccountContractAssociationByAccountId(accountIds)){
            contractIds.add(accountContractAssociation.Contract__c);
        }
        return contractIds;
    }

    /*
        Ticket#17949 Account Contract Association
     */
    public List<Account_Contract_Association__c> selectAccountContractAssociationByAcctIdAndConttractId(Id accountId, Id contractId){
        List<Account_Contract_Association__c> accountContractAssociations = new List<Account_Contract_Association__c>();
        accountContractAssociations = [SELECT Id, Contract__c, Account__c FROM Account_Contract_Association__c WHERE Account__c =:accountId AND Contract__c = :contractId];
        return accountContractAssociations;
    }
}