objects/Account/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <defaultValue>"Active"</defaultValue>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Inter_co_Account__c.field-meta.xml
<CustomField>
    <fullName>Inter_co_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Accounts are not tax liable.</inlineHelpText>
    <label>Intra-Co</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Setup__c/fields/Quote_Default_Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Quote_Default_Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Default Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Company Setup</relationshipLabel>
    <relationshipName>Company_Setup</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contact/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Service Center</description>
    <inlineHelpText>Choose the Employee Service Center</inlineHelpText>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

objects/Contract/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Contract/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Account.Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

objects/Contract/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Contract/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract/fields/Surcharge_Type__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Type__c</fullName>
    <label>Surcharge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>EEC Fee</fullName>
            </value>
            <value>
                <fullName>Fuel Surcharge</fullName>
            </value>
            <value>
                <fullName>ESIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rate_Sheet__c/Rate_Sheet__c.object-meta.xml
<CustomObject>
    <label>Rate Sheet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>Sales_Line__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <label>Additional Billing Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contract.Status</field>
            <operation>equals</operation>
            <value>Activated</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Rate_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Rate_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Sheet</label>
    <referenceTo>Rate_Sheet__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Surcharge_Type__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Type__c</fullName>
    <label>Surcharge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Fuel Surcharge</fullName>
            </value>
            <value>
                <fullName>EEC Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Pending_Approval</fullName>
        <label>Pending Approval</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

classes/SalesOrdersServiceTest.cls
@IsTest
private class SalesOrdersServiceTest {
    @IsTest
    private static void testUpdateSalesLinesForBillAsLumpSumAllAction(){
        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ISalesLines domainMock = new Mocks.SalesLines(mocks);
        ISalesOrdersSelector selectorMock= new Mocks.SalesOrdersSelector(mocks);
        
        // Given
        mocks.startStubbing();
        Sales_Order__c theSO = new Sales_Order__c(
            Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType)
        );
        Sales_Line__c salesLine1 = new Sales_Line__c(
            Id = fflib_IDGenerator.generate(Sales_Line__c.SObjectType),
            Sales_Order__c = theSO.Id
        );
        Sales_Line__c salesLine2 = new Sales_Line__c(
            Id = fflib_IDGenerator.generate(Sales_Line__c.SObjectType),
            Sales_Order__c = theSO.Id
        );
        List<Sales_Line__c> theSLList = new List<Sales_Line__c>{salesLine1, salesLine2};
            mocks.when(domainMock.sObjectType()).thenReturn(Sales_Line__c.SObjectType);
        mocks.when(selectorMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorMock.selectById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.stopStubbing();
        Application.Domain.setMock(domainMock);
        Application.Selector.setMock(selectorMock);
        
        // When
        SalesOrdersService.updateSalesLinesForBillAsLumpSumAllAction(theSLList);
        
    }
    
    /*
@IsTest
private static void testCloneSalesOrder() {
// Create mocks
fflib_ApexMocks mocks = new fflib_ApexMocks();
fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
ISalesOrdersSelector selectorMock= new Mocks.SalesOrdersSelector(mocks);

// Given
mocks.startStubbing();
Account billToCust = TestDataUtil.customerAccountRecord;
Id theSOId = fflib_IDGenerator.generate(Sales_Order__c.SObjectType);
Id theSLId = fflib_IDGenerator.generate(Sales_Line__c.SObjectType);

String jsonStr = '{"Id" : "' + theSOId + '", "Approval_Status__c" : "Approved", "Sales_Lines__r" : {"totalSize" : 1, "done" : true, "records" : [{"Id" : "'+  theSLId +'", "Sales_Order__c" : "'+ theSOId +'"}]}}';
Sales_Order__c theSO  = (Sales_Order__c) JSON.deserialize(jsonStr, Sales_Order__c.class);
mocks.when(selectorMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
mocks.when(selectorMock.selectByIdWithLinesForClone(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
mocks.stopStubbing();
Application.UnitOfWork.setMock(uowMock);
Application.Selector.setMock(selectorMock);

// When
SalesOrdersService.cloneSalesOrder(new Set<Id>{theSO.Id}, 'Quote', fflib_IDGenerator.generate(Service_Center__c.SObjectType), billToCust.Id, billToCust.Id);
SalesOrdersService.cloneSalesOrder(new Set<Id>{theSO.Id}, 'Order', fflib_IDGenerator.generate(Service_Center__c.SObjectType), billToCust.Id, billToCust.Id);
}
*/
    
    @IsTest
    private static void testCloneSalesQuote() {
        // Create mocks
        /*
Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;
Subsidiary_Company__c theSubsidiaryCompany = TestDataUtil.SubsidiaryCompanyRecord;
Service_Center__c theServiceCenter = TestDataUtil.ServiceCenterRecord;
Sales_Order__c theSO  = TestDataUtil.SalesOrderRecord;
SalesOrdersService.cloneSalesOrder(new Set<Id>{theSO.Id}, 'Quote', theServiceCenter.Id, theSO.Bill_to_Customer_No__c, theSO.Bill_to_Customer_No__c, 'job description', 'ABC12123');
SalesOrdersService.cloneSalesOrder(new Set<Id>{theSO.Id}, 'Order', theServiceCenter.Id, theSO.Bill_to_Customer_No__c, theSO.Bill_to_Customer_No__c, 'job description','ABV123123');
*/
        NewTestData.createTestData();
        
        Test.startTest();
        Account customer = NewTestData.mapAccountWrappersByName.get('Customer 2').Account;
        Service_Center__c theServiceCenter = TestDataUtil.ServiceCenterRecord;
        Sales_Order__c salesOrder = NewTestData.mapSalesOrdersByName.get('SQ1');
        salesOrder.Contract__c = null;
        salesOrder.Approval_Status__c = EnumUtil.ApprovalStatus.APPROVED.name();
        CompanyMgmt.byPassTrigger = true;
        update salesOrder;
        SalesOrdersService.cloneSalesOrder(new Set<Id>{salesOrder.Id}, 'Quote', theServiceCenter.Id, customer.Id, customer.Id, 'job description', '12123');
        Test.stopTest();
    }
    @IsTest
    private static void testCloneSalesOrder() {
        NewTestData.createTestData();
        
        Test.startTest();
        Service_Center__c theServiceCenter = TestDataUtil.ServiceCenterRecord;
        Sales_Order__c salesOrder = NewTestData.mapSalesOrdersByName.get(NewTestData.TEST_SO_NAME_01);
        salesOrder.Approval_Status__c = EnumUtil.ApprovalStatus.APPROVED.name();
        CompanyMgmt.byPassTrigger = true;
        update salesOrder;
        try{
            SalesOrdersService.cloneSalesOrder(new Set<Id>{salesOrder.Id}, 'Order', theServiceCenter.Id, salesOrder.Bill_to_Customer_No__c, salesOrder.Bill_to_Customer_No__c, 'job description','123123');   
        }
        catch(Exception ex){}
        Test.stopTest();
    }
    
    
    @IsTest
    private static void testCreateNewSalesQuoteOrSalesOrderWithSalesOrderParam(){
        NewTestData.createTestData();
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IContractsSelector selectorContractMock = new Mocks.ContractsSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        
        mocks.startStubbing();
        String documentType = 'Sales Order';
        String billToCustomer = fflib_IDGenerator.generate(Account.SObjectType);
        Account parentAcct = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Billing_Instructions__c = 'Test',
            Internal_Comments__c = 'test'
        );
        Account acct = new Account(
            Id = billToCustomer,
            Type = 'Prospect',
            ParentId = parentAcct.Id
        );
        String serviceCenter = '01';
        Service_Center__c theSC = new Service_Center__c(
            Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
            Name = serviceCenter
        );
        String contrac = fflib_IDGenerator.generate(Contract.SObjectType);
        Contract contra = new Contract(
            Id = contrac
        );
        String quote = fflib_IDGenerator.generate(Account.SObjectType);
        Company_Setup__c theCompanySetup = new Company_Setup__c(
            Quote_Default_Payment_Term__c = fflib_IDGenerator.generate(Payment_Term__c.SObjectType)
        );
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorContractMock.sObjectType()).thenReturn(Contract.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorSCMock.selectByName('01')).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorContractMock.selectByIdWithBillingRule(new Set<Id>{contrac})).thenReturn(new List<Contract>{contra});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCustomer})).thenReturn(new List<Account>{acct});
        mocks.when(selectorAccountMock.selectBillingInstructionsById(new Set<Id>{acct.ParentId})).thenReturn(new List<Account>{parentAcct});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorContractMock);
        
        SalesOrdersServiceImpl.theCompanySetupValue = theCompanySetup;
        SalesOrdersService.createNewSalesQuoteOrSalesOrder(documentType, billToCustomer, serviceCenter, contrac, quote);
        
    }
    @IsTest
    private static void testCreateNewSalesQuoteOrSalesOrderWithSalesQuoteParam(){
        NewTestData.createTestData();
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IContractsSelector selectorContractMock = new Mocks.ContractsSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        
        mocks.startStubbing();
        String documentType = 'Sales Quote';
        String billToCustomer = fflib_IDGenerator.generate(Account.SObjectType);
        Account parentAcct = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Billing_Instructions__c = 'Test',
            Internal_Comments__c = 'test'
        );
        Account acct = new Account(
            Id = billToCustomer,
            Type = 'Customer',
            ParentId = parentAcct.Id,
            Inter_co_Account__c = true
        );
        
        String serviceCenter = '01';
        Service_Center__c theSC = new Service_Center__c(
            Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
            Name = serviceCenter
        );
        String contrac = fflib_IDGenerator.generate(Contract.SObjectType);
        Contract contra = new Contract(
            Id = contrac
        );
        String quote = fflib_IDGenerator.generate(Account.SObjectType);
        Company_Setup__c theCompanySetup = new Company_Setup__c(
            Quote_Default_Payment_Term__c = fflib_IDGenerator.generate(Payment_Term__c.SObjectType)
        );
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorContractMock.sObjectType()).thenReturn(Contract.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorSCMock.selectByName('01')).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorContractMock.selectByIdWithBillingRule(new Set<Id>{contrac})).thenReturn(new List<Contract>{contra});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCustomer})).thenReturn(new List<Account>{acct});
        mocks.when(selectorAccountMock.selectBillingInstructionsById(new Set<Id>{acct.ParentId})).thenReturn(new List<Account>{parentAcct});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorContractMock);
        
        SalesOrdersServiceImpl.theCompanySetupValue = theCompanySetup;
        SalesOrdersService.createNewSalesQuoteOrSalesOrder(documentType, billToCustomer, serviceCenter, contrac, quote);
    }
    
    @IsTest
    private static void testSetSurchargePct() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IContractsSelector selectorContractMock = new Mocks.ContractsSelector(mocks);
        
        mocks.startStubbing();
        Contract contra = new Contract(
            Id = fflib_IDGenerator.generate(Contract.SObjectType)
        );
        Sales_Order__c theSO = new Sales_Order__c(
            Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
            Contract__c = contra.Id,
            Surcharge_Type__c = 'EEC Fee'
        );
        mocks.when(selectorContractMock.sObjectType()).thenReturn(Contract.SObjectType);
        mocks.when(selectorContractMock.selectById(new Set<Id>{contra.Id})).thenReturn(new List<Contract>{contra});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorContractMock);
        
        SalesOrdersService.setSurchargePct(theSO);
    }
    
    @IsTest
    private static void testConvertQuoteToOrder(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ISalesOrdersSelector selectorMock= new Mocks.SalesOrdersSelector(mocks);
    }
    
    @IsTest
    private static void testSalesOrderService(){
        NewTestData.createTestData();
        Test.startTest();
        Id salesOrderId = NewTestData.mapSalesOrdersByName.get(NewTestData.TEST_SO_NAME_01).Id;
        SalesOrdersService.addManifestLineToRelatedRecords(new Set<Id>{salesOrderId});
        //SalesOrdersService.deleteManifestLineFromRelatedRecords(new Set<Id>{salesOrderId});
        
        Sales_Order__c salesOrder = SalesOrdersSelector.newInstance().selectById(new Set<Id>{salesOrderId})[0];
        SalesOrdersService.validatePayRule(salesOrder);
        Id salesQuoteId = NewTestData.mapSalesOrdersByName.get('SQ1').Id;
        SalesOrdersService.updateSQWhenNewSOCreated(salesQuoteId);
        Test.stopTest();
    }
    
    @IsTest
    private static void testdeleteManifestLineFromRelatedRecords(){
        NewTestData.createTestData();
        Test.startTest();
        Id salesOrderId = NewTestData.mapSalesOrdersByName.get(NewTestData.TEST_SO_NAME_01).Id;
        //SalesOrdersService.addManifestLineToRelatedRecords(new Set<Id>{salesOrderId});
        SalesOrdersService.deleteManifestLineFromRelatedRecords(new Set<Id>{salesOrderId});
        SalesOrdersService.reopenKronosProcessedTMLinesBySalesOrderId(salesOrderId);
        Test.stopTest();
    }
    
    // @IsTest
    // private static void testIsValidCustomer() {
    //     NewTestData.createTestData();
        
    //     Test.startTest();
    //     Account customer = NewTestData.mapAccountWrappersByName.get('Customer 2').Account;
    //     customer.Type = 'Prospect';
    //     customer.Customer_Status__c = 'Active';
    //     customer.BillingStreet = 'Test Street';
    //     customer.BillingCity = 'Test City';
    //     customer.BillingStateCode ='AZ';
    //     customer.BillingPostalCode ='85244';
    //     update customer;
    //     Service_Center__c theServiceCenter = TestDataUtil.ServiceCenterRecord;
    //     Sales_Order__c salesOrder = NewTestData.mapSalesOrdersByName.get('SQ1');
    //     salesOrder.Contract__c = null;
    //     salesOrder.Approval_Status__c = EnumUtil.ApprovalStatus.APPROVED.name();
    //     List<Contact> contacts = new List<Contact>();
        
    //     Contact customerContact = new Contact();
    //     customerContact.AccountId = customer.Id;
    //     customerContact.Account = customer;
    //     customerContact.FirstName = 'John';
    //     customerContact.LastName = 'Smith';
    //     customerContact.MailingStreet = '123 ABC Ave' + '\n' + 'Suite 123';
    //     customerContact.MailingStateCode = 'NY';
    //     customerContact.MailingState = 'New York';
    //     customerContact.MailingCity = 'New York';
    //     customerContact.MailingCountry = 'United States';
    //     customerContact.MailingCountryCode = 'US';
    //     customerContact.MailingPostalCode = '10002';
    //     customerContact.Contact_Type__c = 'Site;Quote;Billing;Purchase;Executive;Sales';
    //     contacts.add(customerContact);
        
    //     insert contacts;
        
    //     CompanyMgmt.byPassTrigger = true;
    //     update salesOrder;
    //     SalesOrdersService.isValidCustomer(customer.Id);
    //     Test.stopTest();
    // }
    private static testMethod void testValidateRateSheet() {
        NewTestData.createTestData();
        Sales_Order__c salesOrder = NewTestData.mapSalesOrdersByName.get('SO1');
        Rate_Sheet__c objRate = New Rate_Sheet__c();
        objRate.Name = 'test';
        insert objRate; 
        Test.startTest();
        String JSONSalesOrderWrapper = ACVSalesOrderController.getSalesOrder(salesOrder.Id);
        ACVSalesOrderWrapper salesOrderWrapper = (ACVSalesOrderWrapper)JSON.deserialize(JSONSalesOrderWrapper, ACVSalesOrderWrapper.class);
        List<ACVSalesOrderJobTaskWrapper> jobTaskWrappers = salesOrderWrapper.JobTaskWrappers;
        SalesOrdersService.validateRateSheet(salesOrder,jobTaskWrappers,objRate.Id);
        SalesOrdersService.cloneJobTask(salesOrder,jobTaskWrappers[0],jobTaskWrappers[0],1);
        Test.stopTest();  
    }
    //test1
}