objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts_Billing_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <defaultValue>"Active"</defaultValue>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Contact/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contact/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Service Center</description>
    <inlineHelpText>Choose the Employee Service Center</inlineHelpText>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/CMR_Description__c.field-meta.xml
<CustomField>
    <fullName>CMR_Description__c</fullName>
    <label>Job Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Prevent_New_and_Cloned_Sales_Orders__c.field-meta.xml
<CustomField>
    <fullName>Prevent_New_and_Cloned_Sales_Orders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prevent New and Cloned Sales Orders</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Company__c/fields/QtC_Enabled__c.field-meta.xml
<CustomField>
    <fullName>QtC_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QtC Enabled?</label>
    <type>Checkbox</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
            <value>
                <fullName>01</fullName>
                <isActive>false</isActive>
                <label>SC01 Elizabeth, NJ Ops</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/CloneSalesOrderControllerTest.cls
@IsTest
private class CloneSalesOrderControllerTest {

    @IsTest
    private static void testCloneSO(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        IUsersSelector selectorUserMock = new Mocks.UsersSelector(mocks);

        // Given taskf
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01',
            	Description__c = 'Test',
            	Prevent_New_and_Cloned_Sales_Orders__c = false
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV'
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Prospect'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id,
            	CMR_Description__c = 'Test'
        );
        User usertest = new User(
                Id = fflib_IDGenerator.generate(User.SObjectType),
                Service_Center__c = theSC.Name
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorUserMock.sObjectType()).thenReturn(User.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});
        mocks.when(selectorUserMock.selectById(new Set<Id>{Id.valueOf(UserInfo.getUserId())})).thenReturn(new List<User>{usertest});
        mocks.when(selectorSCMock.selectByName(usertest.Service_Center__c)).thenReturn(new List<Service_Center__c>{theSC});
        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorUserMock);

        // When
        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        List<SelectOption> selectOptions = controller.lstConvertTo;
        //String sc = controller.selServiceCenter;;
        controller.selConvertTo = 'Order';
        controller.poNumber = 'TestPO';
        controller.selectedServiceCenterId = theSC.Id;
        controller.cloneSO();

    }

    @IsTest
    private static void testCloneSOWithException(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        IUsersSelector selectorUserMock = new Mocks.UsersSelector(mocks);


        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01'
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV'
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id
        );
        User usertest = new User(
                Id = fflib_IDGenerator.generate(User.SObjectType),
                Service_Center__c = theSC.Name
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorUserMock.sObjectType()).thenReturn(User.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});
        mocks.when(selectorUserMock.selectById(new Set<Id>{Id.valueOf(UserInfo.getUserId())})).thenReturn(new List<User>{usertest});
        mocks.when(selectorSCMock.selectByName(usertest.Service_Center__c)).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(serviceSOMock.cloneSalesOrder(new Set<Id>{ theSO.Id},'Order', theSC.Id, billToCust.Id, billToCust.Id, 'job description','ACV12343')).thenThrow(new MyException('lala'));
        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorUserMock);

        // When
        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        controller.selConvertTo = 'Order';
        
        controller.cloneSO();

    }

    @IsTest
    private static void testValidateBillToCust(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);

        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01'
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV'
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Prospect'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});

        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);

        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        System.currentPageReference().getParameters().put('billToCustId', billToCust.Id);
        controller.validateBillToCust();
    }
    @IsTest
    private static void testValidateBillToCustWithNullBillToCust(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);

        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01'
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV',
            QtC_Enabled__c = true
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Prospect'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturnMulti(new List<List<Account>>{new List<Account>{billToCust}, new List<Account>()});

        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);

        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        //System.currentPageReference().getParameters().put('billToCustId', billToCust.Id);
        controller.validateBillToCust();
    }
    
	 @IsTest
    private static void testValidateBillToCustwithParam(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);

        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01'
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV'
        );
        Contact contact = new Contact(
            Id = fflib_IDGenerator.generate(Contact.SObjectType),
            Contact_Type__c = 'Billing',
            Blocked__c = False
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Customer',
            Customer_Status__c = 'Active',
            BillingStreet = 'Test Street',
            BillingCity = 'Test City',
            BillingStateCode = 'Test State',
             BillingPostalCode = '85249',
            Billing_Contact__c = contact.Id
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});

        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);

        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        System.currentPageReference().getParameters().put('billToCustId', billToCust.Id);
        controller.validateBillToCust();
        CloneSalesOrderController.validateBillToCust(billToCust.Id);
    }
    @IsTest
    private static void testCloneSOwithParam(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);

        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01',
            Prevent_New_and_Cloned_Sales_Orders__c = false
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV',QtC_Enabled__c = True
        );
        Contact contact = new Contact(
            Id = fflib_IDGenerator.generate(Contact.SObjectType),
            Contact_Type__c = 'Billing',
            Blocked__c = False
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Customer'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});
		mocks.stopStubbing();
        
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
		CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        System.currentPageReference().getParameters().put('billToCustId', billToCust.Id);
        System.currentPageReference().getParameters().put('selectedSCId', theSC.Id);
        
        controller.populatedSelectedServiceCenterId();
        //controller.selServiceCenter();
        CloneSalesOrderController.cloneSalesOrder( theSO.Id,'Order', theSC.Id, billToCust.Id, billToCust.Id, 'job description','ACV12343');
        
    }
    
    @IsTest
    private static void testselServiceCenter(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        IUsersSelector selectorUserMock = new Mocks.UsersSelector(mocks);

        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01',
            	Description__c = 'Test',
            	Prevent_New_and_Cloned_Sales_Orders__c = false
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV'
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Prospect'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id,
            	CMR_Description__c = 'Test'
        );
        User usertest = new User(
                Id = fflib_IDGenerator.generate(User.SObjectType),
                Service_Center__c = theSC.Name
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorUserMock.sObjectType()).thenReturn(User.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});
        mocks.when(selectorUserMock.selectById(new Set<Id>{Id.valueOf(UserInfo.getUserId())})).thenReturn(new List<User>{usertest});
        mocks.when(selectorSCMock.selectByName(usertest.Service_Center__c)).thenReturn(new List<Service_Center__c>{theSC});
        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorUserMock);

        // When
        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        List<SelectOption> selectOptions = controller.lstConvertTo;
        
        controller.selConvertTo = 'Quote';
        controller.poNumber = 'TestPO';
        System.currentPageReference().getParameters().put('poNumber', 'PO1234');
        controller.cloneSO();
        String sc = controller.selServiceCenter;

    }
    
    @IsTest
    private static void testgetData(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        IServiceCentersSelector selectorSCMock = new Mocks.ServiceCentersSelector(mocks);
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        IUsersSelector selectorUserMock = new Mocks.UsersSelector(mocks);

        // Given
        mocks.startStubbing();
        Service_Center__c theSC = new Service_Center__c(
                Id = fflib_IDGenerator.generate(Service_Center__c.SObjectType),
                Name = '01',
            	Description__c = 'Test',
            	Prevent_New_and_Cloned_Sales_Orders__c = false
        );
        Subsidiary_Company__c subCom = new Subsidiary_Company__c(
                Id = fflib_IDGenerator.generate(Subsidiary_Company__c.SObjectType),
                Name= '1-ACV'
        );
        Account billToCust = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Name = 'CON EDISON',
            	Type = 'Prospect'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                //Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Service_Center__c = theSC.Id,
                Subsidiary_Company__c = subCom.Id,
                Bill_to_Customer_No__c = billToCust.Id,
            	CMR_Description__c = 'Test'
        );
    // insert theSO;
        
        NewTestData.createTestData();
        //Test.startTest();
        Sales_Order__c salesOrder = NewTestData.mapSalesOrdersByName.get(NewTestData.TEST_SO_NAME_01);
        
        User usertest = new User(
                Id = fflib_IDGenerator.generate(User.SObjectType),
                Service_Center__c = theSC.Name
        );

        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSCMock.sObjectType()).thenReturn(Service_Center__c.SObjectType);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorUserMock.sObjectType()).thenReturn(User.SObjectType);
        mocks.when(selectorSOMock.selectServiceCenterAndSubCompanyById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorSCMock.selectAll()).thenReturn(new List<Service_Center__c>{theSC});
        mocks.when(selectorAccountMock.selectById(new Set<Id>{billToCust.Id})).thenReturn(new List<Account>{billToCust});
        mocks.when(selectorUserMock.selectById(new Set<Id>{Id.valueOf(UserInfo.getUserId())})).thenReturn(new List<User>{usertest});
        mocks.when(selectorSCMock.selectByName(usertest.Service_Center__c)).thenReturn(new List<Service_Center__c>{theSC});
        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        Application.Selector.setMock(selectorSCMock);
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorUserMock);

        // When
        CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
        List<SelectOption> selectOptions = controller.lstConvertTo;
        //String sc = controller.selServiceCenter;
        CloneSalesOrderController.getData(salesOrder.Id);

    }

    private class MyException extends Exception {
    }
    //test1
}