objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency?</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Salesperson__r.Salesperson_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Allow_Convert__c.field-meta.xml
<CustomField>
    <fullName>Allow_Convert__c</fullName>
    <formula>IF((Convert_Count__c &gt; 0 &amp;&amp; ISPICKVAL(Quote_Type__c, 'One_Time'))||(TODAY() &gt; Expiration_Date__c &amp;&amp; ISPICKVAL(Quote_Type__c, 'Recurrence')) || ISBLANK(TEXT( Quote_Type__c )) , false, true)</formula>
    <label>Allow Convert</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Is_New_D365_Project__c.field-meta.xml
<CustomField>
    <fullName>Is_New_D365_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is New D365 Project</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Project_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Project_Coordinator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Name</field>
            <operation>notEqual</operation>
            <value>HOU</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Quotes/Orders (Project Manager)</relationshipLabel>
    <relationshipName>Sales_Orders_PC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Surcharge_Type__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Type__c</fullName>
    <label>Surcharge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Fuel Surcharge</fullName>
            </value>
            <value>
                <fullName>EEC Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Service_Center__c/fields/Include_SO_in_EQAI_Invoice_Integration__c.field-meta.xml
<CustomField>
    <fullName>Include_SO_in_EQAI_Invoice_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include SO in EQAI Invoice Integration</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConvertSQToSOControllerTest.cls
@IsTest
private class ConvertSQToSOControllerTest {
    
    @IsTest
    private static void test(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        
        mocks.startStubbing();
        Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL');
        Insert acc;
        Sales_Order__c theSO = new Sales_Order__c(
            Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
            Document_Type__c = 'Sales Order',Bill_to_Customer_No__c = acc.Id,Customer_PO_No__c ='a23453'
        );
        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSOMock.selectConvertRelatedFieldsById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(serviceSOMock.convertQuoteToOrder(new Set<Id>{theSO.Id})).thenReturn(theSO.Id);
        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        //test
        CovertSalesQuoteToSalesOrderController controller = new CovertSalesQuoteToSalesOrderController(standardController);
        Test.setMock(HttpCalloutMock.class, new workOrderQuoteServiceTest());
        controller.convertQuoteToOrder();
        controller.getConvertMessages();
        Boolean bool = controller.allowConvertToOrder;
    }
    
    @IsTest
    private static void testExceptionAndErrors(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Mocks.SalesOrdersService serviceSOMock = new Mocks.SalesOrdersService(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);
        
        mocks.startStubbing();
        Id soId= fflib_IDGenerator.generate(Sales_Order__c.SObjectType);
        Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
        insert subsidiaryCompany;
        Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id);
        insert serviceCenter;
        Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
        insert salesPerson;
        Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
        insert acc;
        String prospectId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        String jsonStr = '{ "Id" : "' + soId + '" , "Bill_to_Customer_No__r" : {"RecordTYpeId" : "' + prospectId + '","id":"'+ acc.id +'"}, "Allow_Convert__c" : false, "Document_Type__c" : "Sales Quote", "Customer_PO_No__c":"a1234","Blocked__c": true}';
        Sales_Order__c theSO = (Sales_Order__c) JSON.deserialize(jsonStr, Sales_Order__c.class);
        theSO.Bill_to_Customer_No__c = acc.id;
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(theSO);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorSOMock.selectConvertRelatedFieldsById(new Set<Id>{theSO.Id})).thenReturn(new List<Sales_Order__c>{theSO});
        //mocks.when(serviceSOMock.convertQuoteToOrder(new Set<Id>{theSO.Id})).thenThrow(new MyException('heh'));
        mocks.stopStubbing();
        Application.Service.setMock(ISalesOrdersService.class, serviceSOMock);
        Application.Selector.setMock(selectorSOMock);
        
        CovertSalesQuoteToSalesOrderController controller = new CovertSalesQuoteToSalesOrderController(standardController);
        Test.setMock(HttpCalloutMock.class, new workOrderQuoteServiceTest());
        controller.convertQuoteToOrder();
        controller.getConvertMessages();
    }
    
    
    @isTest
    static void testPerformWorkOrderQuoteHeaderInfoCallout() {
        Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
        insert subsidiaryCompany;
        Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id);
        insert serviceCenter;
        Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
        insert salesPerson;
        Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
        insert acc;
        
        Sales_Order__c salesQuote = new Sales_Order__c(Name='Test1');
        salesQuote.Subsidiary_Company__c = subsidiaryCompany.id;
        salesQuote.Bill_to_Customer_No__c = acc.id;
        salesQuote.Project_Coordinator__c = salesPerson.id;
        salesQuote.Service_Center__c = serviceCenter.id;
        salesQuote.Surcharge_Type__c = 'EEC Fee';
        salesQuote.Customer_PO_No__c = '123456';
        insert salesQuote;
        
        Test.startTest();
        CovertSalesQuoteToSalesOrderController.performWorkOrderQuoteHeaderInfoCallout(salesQuote.id);
        Test.stopTest();
    }
    
    @isTest
    static void testConvertQuoteToOrder() {
        Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
        insert subsidiaryCompany;
        Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id);
        insert serviceCenter;
        Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
        insert salesPerson;
        Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
        insert acc;
        
        Sales_Order__c salesQuote = new Sales_Order__c(Name='Quote-Test1');
        salesQuote.Subsidiary_Company__c = subsidiaryCompany.id;
        salesQuote.Bill_to_Customer_No__c = acc.id;
        salesQuote.Project_Coordinator__c = salesPerson.id;
        salesQuote.Service_Center__c = serviceCenter.id;
        salesQuote.Surcharge_Type__c = 'EEC Fee';
        salesQuote.Customer_PO_No__c = '123421321';
        insert salesQuote;
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(salesQuote);
        CovertSalesQuoteToSalesOrderController controller = new CovertSalesQuoteToSalesOrderController(standardController);
        
        Test.startTest();
        controller.convertQuoteToOrder();
        Test.stopTest();
    }
    
    @IsTest
    private static void testWithEmergencySO(){
        
        Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
        insert subsidiaryCompany;
        Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id,Include_SO_in_EQAI_Invoice_Integration__c =true);
        insert serviceCenter;
        Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
        insert salesPerson;
        Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id,Emergency__c = true);
        insert acc;
        
        Sales_Order__c salesQuote = new Sales_Order__c(Name='Quote-Test1');
        salesQuote.Subsidiary_Company__c = subsidiaryCompany.id;
        salesQuote.Bill_to_Customer_No__c = acc.id;
        salesQuote.Project_Coordinator__c = salesPerson.id;
        salesQuote.Service_Center__c = serviceCenter.id;
        salesQuote.Surcharge_Type__c = 'EEC Fee';
        salesQuote.Customer_PO_No__c = '123421321';
        insert salesQuote;
        system.debug('salesQuote'+salesQuote);
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(salesQuote);
        CovertSalesQuoteToSalesOrderController controller = new CovertSalesQuoteToSalesOrderController(standardController);
        
        Test.startTest();
        controller.convertQuoteToOrder();
        salesQuote.Is_New_D365_Project__c = false;
        update salesQuote;
        acc.Sage_Customer_No__c = '12345';
        update acc;
        controller.convertQuoteToOrder();
        controller.getConvertMessages();
        Test.stopTest();
    }
    //test1
    
    class MyException extends Exception{}
}