objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Contact/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/Contact_Sync_d_with_EQAI__c.field-meta.xml
<CustomField>
    <fullName>Contact_Sync_d_with_EQAI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Sync'd with EQAI</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contact/fields/COR2_Portal_Contact__c.field-meta.xml
<CustomField>
    <fullName>COR2_Portal_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>COR2 Portal Contact</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/EQAI_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Contact_Id__c</fullName>
    <label>EQAI Contact Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Contact/recordTypes/Contacts.recordType-meta.xml
<RecordType>
    <fullName>Contacts</fullName>
    <active>true</active>
    <label>Contacts</label>
</RecordType>

objects/EQAI_API_URL_Extensions__mdt/EQAI_API_URL_Extensions__mdt.object-meta.xml
<CustomObject>
    <description>URL Extensions for EQAI API Endpoints</description>
    <label>EQAI API URL Extensions</label>
    <pluralLabel>EQAI API URL Extensions</pluralLabel>
</CustomObject>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Extension__c.field-meta.xml
<CustomField>
    <fullName>API_Extension__c</fullName>
    <label>API Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/Sales_Order_EQAI_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data Mapping of Sales Order Field Values to EQAI Field Values</description>
    <label>Sales Order EQAI Mapping</label>
    <pluralLabel>Sales Order EQAI Mapping</pluralLabel>
</CustomObject>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Name__c</fullName>
    <label>EQAI Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>company_id</fullName>
                <default>true</default>
                <label>company_id</label>
            </value>
            <value>
                <fullName>profit_ctr_id</fullName>
            </value>
            <value>
                <fullName>project_code</fullName>
            </value>
            <value>
                <fullName>country_code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Value__c</fullName>
    <label>EQAI Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service_Center__r.Name</fullName>
                <default>true</default>
                <label>Service_Center__r.Name</label>
            </value>
            <value>
                <fullName>Payment_Term__r.Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Value__c</fullName>
    <label>Salesforce Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/User/fields/RSG_EIN__c.field-meta.xml
<CustomField>
    <fullName>RSG_EIN__c</fullName>
    <description>Employee Workday Number</description>
    <label>RSG EIN #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/ContactEQAIService.cls
/*************************************************************************************************
* Name         :  ContactEQAIService 
* Description  :  Apex Class for API call out of the work order Quote Service
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Vennila Paramasivam		07/08/2024				Whenever a Contact insert/update it will sync to EQAI
* Shahwaz Khan              16/12/2024              Salesforce - Incl. web_access_flag field in contact sync integration (SF -> EQAI).
****************************************************************************************************************************************/
public class ContactEQAIService {
    
    @future(callout=true)
    Public static void sendContacttoEQAI(Id conId, String event)
    {
        ContactEQAIServiceJson.countryCodeMap = new Map<String,string>();
        ApplicationLog.ApplicationlogInformation logData = new ApplicationLog.ApplicationlogInformation();
		logData.className = 'ContactEQAIService';
		logData.methodName = 'sendContacttoEQAI';
        logData.recordId = conId;

        Contact contactRec = [SELECT Id, Name,account.accountNumber, account.Name, FirstName,LastName, Email, Phone, MobilePhone,
                              Contact_Type__c, Title, MailingStreet, MailingCity, MailingState,MailingStateCode, Fax, Salutation, MiddleName, Suffix,
                              account.Sage_Customer_No__c,
                              MailingPostalCode,MailingCountry,MailingCountryCode,
                              Contact_Sync_d_with_EQAI__c,Blocked__c,EQAI_Contact_Id__c,COR2_Portal_Contact__c
                              FROM Contact WHERE Id =: conId and RecordType.Developername = 'Contacts'];
                            
        if(contactRec.MailingCountry != null){            
            Sales_Order_EQAI_Mapping__mdt[] salesOrderEQIMappingRecord = [SELECT Id,EQAI_Field_Name__c,EQAI_Field_Value__c,Salesforce_Field_API_Name__c,Salesforce_Field_Value__c FROM Sales_Order_EQAI_Mapping__mdt WHERE EQAI_Field_Name__c = 'Country_Code' AND Salesforce_Field_Value__c =: contactRec.MailingCountry.toUpperCase()]; 
            if(salesOrderEQIMappingRecord.size()>0){
                
                ContactEQAIServiceJson.countryCodeMap.put(contactRec.MailingCountry,salesOrderEQIMappingRecord[0].EQAI_Field_Value__c);
                
            }
            
            
        }
        
        
        //Sales_Order_EQAI_Mapping__mdt salesOrderEQIMappingRecord = [SELECT Id,EQAI_Field_Name__c,EQAI_Field_Value__c,,Salesforce_Field_API_Name__c,Salesforce_Field_Value__c FROM Sales_Order_EQAI_Mapping__mdt WHERE EQAI_Field_Name__c = 'Country_Code' AND 
        User currUser = [SELECT Id, RSG_EIN__c FROM USER WHERE Id =:userinfo.getUserId()];
        try
        {
            if(contactRec != Null)
           	{
               String metadataName;
               String methodType;
               if(event == 'Insert')
               {
                   metadataName = 'getContactInsert'; 
                   methodType = 'POST';
               }
               else
               {
                   metadataName = 'getContactUpdate';  
                   methodType = 'PUT';
               }
                 
              
               EQAI_API_URL_Extensions__mdt contactAPIs = [SELECT API_Extension__c, API_Key__c, API_Token__c, DeveloperName 
                                                           FROM EQAI_API_URL_Extensions__mdt 
                                                           WHERE DeveloperName=:metadataName];
               JSONGenerator jsonGen = JSON.createGenerator(true); 
               ContactEQAIServiceJson contactJSON = new ContactEQAIServiceJson(contactRec,currUser.RSG_EIN__c,event);
               System.debug('body: '+ System.Json.serialize(contactJSON));
               String contactResponse = workOrderQuoteService.getPostCalloutResponseContents(contactAPIs.API_Extension__c, System.Json.serialize(contactJSON),methodType,contactAPIs.API_Key__c,contactAPIs.API_Token__c);
               System.debug('contactResponse+++++++++++'+contactResponse);
               logData.serviceRequest = 'contactRequest>>'+System.Json.serialize(contactJSON);
			   logData.serviceResponse = 'contactResponse>>'+contactResponse;
               if(contactResponse.contains('Integration Successful') || contactResponse == '200')
               {
                   ContactEQAIServiceJson.isSkipValidation = true;
                   String contactId;
                   if(contactResponse.contains('Contact Id'))
                   {
                        contactId = contactResponse.remove('Integration Successful;Contact Id:');
                        contactRec.Eqai_Contact_Id__c = contactId;
                   }
                   contactRec.Contact_Sync_d_with_EQAI__c = true;                   
                   update contactRec;
               }
               else
               {
                  workOrderQuoteService.createCaseWithParentId(conId,'Error in Contact Insert',workOrderQuoteService.splitSuccessMessage(contactResponse),Json.serialize(contactJSON));  
               }
       		}
            ApplicationLog.startLog(JSON.serialize(logData));
        }
        Catch(Exception e)
        {  
            logData.message = e.getMessage();
			ApplicationLog.startLog(JSON.serialize(logData));
            System.Debug('Error at  - '+e.getLineNumber()+' Message - '+e.getMessage()+' cause '+e.getCause());
            workOrderQuoteService.createCaseWithParentId(conId,'Error in apex class','Error at  - '+e.getLineNumber()+' Message - '+e.getMessage()+' cause '+e.getCause(),null); 
        }
    }
}