objects/Account/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <defaultValue>"Active"</defaultValue>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Contact/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Service Center</description>
    <inlineHelpText>Choose the Employee Service Center</inlineHelpText>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Facility__c/fields/Third_Party_Facility__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Facility__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Party Facility</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Sales_Line__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/CMR_Description__c.field-meta.xml
<CustomField>
    <fullName>CMR_Description__c</fullName>
    <label>Job Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Include_SO_in_EQAI_Invoice_Integration__c.field-meta.xml
<CustomField>
    <fullName>Include_SO_in_EQAI_Invoice_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include SO in EQAI Invoice Integration</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/fields/Prevent_New_and_Cloned_Sales_Orders__c.field-meta.xml
<CustomField>
    <fullName>Prevent_New_and_Cloned_Sales_Orders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prevent New and Cloned Sales Orders</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/User_Service_Center__c/User_Service_Center__c.object-meta.xml
<CustomObject>
    <label>User Service Center</label>
    <nameField>
        <label>Service Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Service_Center__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>User Service Centers</relationshipLabel>
    <relationshipName>User_Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/User_Service_Center__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Service_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CloneSalesOrderController.cls
/*************************************************************************************************
* Name         :  CloneSalesOrderController
* Description  :  Controller used by clone button and related page on Sales Order
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
  Shahwaz Khan              02-20-2024             78352: Salesforce - When Choosing Facility on SQ vs SO
  Shahwaz Khan              03-11-2024             80870: Bug-3rd Party Restriction Impact on Group B Service Centers
  Prabhu Rathakrishnan      04-15-2024             84048: Character Limit Issue from Salesforce Job Description Field to EQAI Name Field
  Shahwaz Khan              05-27-2024             88502: Bug-User is able to clone the sales Quote/order if the MSG, Retail, National Account checkboxes are checked on the Customer table
   Andrew Simons            07-25-2024             Salesforce - removed logic for MSG/Retail/National Accounts - part 1
*************************************************************************************************/
public with sharing class CloneSalesOrderController {

    private ApexPages.StandardController standardController = null;

    public List<SelectOption> lstConvertTo {
        get {
            if (lstConvertTo == null) {
                lstConvertTo = new List<SelectOption>();
                lstConvertTo.add(new SelectOption('Quote', 'Quote'));
                lstConvertTo.add(new SelectOption('Order', 'Order'));
            }
            return lstConvertTo;
        }
        set;
    }

    public String selConvertTo { get; set; }

    //job task <<
    public String jobDescription { get; set; }
    public String poNumber {get; set; }
    //job task >>

    public List<SelectOption> lstServiceCenter { get; set; }

    /*
     *  Ticket#19962
     *    Update SC lookup to handle user default SC is blocked.
     */
    public String selServiceCenter {
        get{
            selServiceCenter = null;
            List<User> users = UsersSelector.newInstance().selectById(new Set<Id>{Id.valueOf(UserInfo.getUserId())});
            if(users.size() > 0 && users[0].Service_Center__c != null){
                List<Service_Center__c> serviceCenters = ServiceCentersSelector.newInstance().selectByName(users[0].Service_Center__c);
                if(serviceCenters[0].Blocked__c == true){
                    List<User_Service_Center__c> userServiceCenters = [SELECT Id, Service_Center__c, User__c, Default__c FROM User_Service_Center__c WHERE User__c =: UserInfo.getUserId() AND Service_Center__r.Blocked__c != TRUE];
                    selServiceCenter = userServiceCenters[0].Service_Center__c;
                    for(User_Service_Center__c userServiceCenter : userServiceCenters){
                        if(userServiceCenter.Default__c == true){
                            selServiceCenter = userServiceCenter.Service_Center__c;
                            break;
                        }
                    }
                } else {
                    if(serviceCenters.size() > 0) selServiceCenter = serviceCenters[0].Id;
                }
            }

            return selServiceCenter;
        }
        set;
    }
    public String selectedServiceCenterId = null;

    public Sales_Order__c theSO {get; set;}

    public Account billToCust {get; set;}

    //ticket 21113 <<
    public Boolean quoteSigned { set; get; }
    //ticket 21113 >>

    public List<Service_Center__c> serviceCenterList = new List<Service_Center__c>();
    /*
     *   Ticket#19962
     *      - default selConvertTo to Quote
     */
    public CloneSalesOrderController (ApexPages.StandardController controller) {
        standardController = controller;
        selConvertTo = 'Quote';
        initSalesOrder();
        initServiceCenter();
        initBillToCustomer();
        
        //ticket 21113 <<
        List<Signature__c> signatures = [SELECT Id FROM Signature__c WHERE Sales_Order__c = :controller.getId() AND Voided__c != TRUE AND Signed__c = TRUE];
        if (signatures.size() > 0) {
            this.quoteSigned = true;
        } else {
            this.quoteSigned = false;
        }
        //ticket 21113 >>

        if(String.isNotBlank(theSO.CMR_Description__c)){
            this.jobDescription = theSO.CMR_Description__c;
        }
        if(!Test.isRunningTest()) selectedServiceCenterId = selServiceCenter;
    }

    public PageReference cloneSO() {
        try {
            //job task <<
            //String newSOId = SalesOrdersService.cloneSalesOrder(new Set<Id>{ standardController.getRecord().Id}, selConvertTo, selectedServiceCenterId, billToCust.Id, billToCust.ParentId);
            //Task#78352//Bug#80870
            List<Sales_Line__c> salesLines=New List<Sales_Line__c>();
            Date thrdPartyValDate = Date.valueOf(label.SO_3rd_Party_Facility_Check);
            salesLines = [Select Id from Sales_Line__c Where Sales_Order__c=:theSO.Id  AND Sales_Order__r.Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c=true 
                          AND Facility__r.Third_Party_Facility__c = true AND CreatedDate >= :thrdPartyValDate];
            if(salesLines.size()>0 && selConvertTo == 'Order' && System.Label.Release_Flag =='true')
            {
                throw new DataException('ERROR! You cannot create a Sale Order, Your have a Waste Line referencing 3rd Party. You must select an approved facility.');  
            }
			if (String.isBlank(JobDescription)) {
                throw new DataException('Job Description is required');
            }
            else If(JobDescription.length()>40){
                throw new DataException('Job Description cannot exceed 40 characters');
                
            }
            if (selConvertTo == 'Order') {
                if (String.isBlank(poNumber)){
                    throw new DataException('Customer PO Number is required');
                }
                //Ticket#27427 >>
                Service_Center__c selectedServiceCenter = [SELECT Prevent_New_and_Cloned_Sales_Orders__c FROM Service_Center__c WHERE Id = :selectedServiceCenterId LIMIT 1];
                if(selectedServiceCenter.Prevent_New_and_Cloned_Sales_Orders__c == true){
                    throw new DataException('Cloning Sales Order is prevented in selected Service Center!');
                }
                //Ticket#27427 <<
            } else {
                poNumber = null;
            }
            String newSOId = SalesOrdersService.cloneSalesOrder(new Set<Id>{ standardController.getRecord().Id}, selConvertTo, selectedServiceCenterId, billToCust.Id, billToCust.ParentId, jobDescription, poNumber);
            //job task >>

            return new PageReference('/' + newSOId);
        } catch (Exception e) {
            System.debug('Error: ' + e.getStackTraceString());
            ApexPages.addMessages(e);
        }
        return ApexPages.hasMessages() ? null : standardController.view();
    }

    public void initSalesOrder(){
        theSO = SalesOrdersSelector.newInstance().selectServiceCenterAndSubCompanyById(new Set<Id>{standardController.getRecord().Id})[0];
    }

    /*
        Ticket#18267 Exclude blocked service center from the list
     */
    public void initServiceCenter(){
        List<Service_Center__c> serviceCenters = ServiceCentersSelector.newInstance().selectAll();
        if (serviceCenters.size() > 0 ){
            lstServiceCenter = new List<SelectOption>();
            for (Service_Center__c sc : serviceCenters) {
                if(sc.Blocked__c != true) {
                    fflib_StringBuilder sb = new fflib_StringBuilder();
                    sb.add(sc.Name);
                    sb.add(' - ');
                    if (String.isNotEmpty(sc.Description__c)) {
                        sb.add(sc.Description__c);
                    }
                    lstServiceCenter.add(new SelectOption(sc.Id, sb.getStringValue()));
                    serviceCenterList.add(sc);
                }
            }
        }
    }

    public void initBillToCustomer(){
        //job task <<
        //billToCust = AccountsSelector.newInstance().selectById(new Set<Id>{theSO.Bill_to_Customer_No__c})[0];
        List<Account> customers = AccountsSelector.newInstance().selectById(new Set<Id>{theSO.Bill_to_Customer_No__c});
        if (customers.size() > 0) {
            billToCust = customers[0];
        }
        else {
            throw new DataException('Bill-to customer does not exist.');
        }
        //job task >>

    }

    /*
     *  Ticket#19962
     *      - prospect(customer) validation when clone.
     */
    public void validateBillToCust(){
        String billToCustId = ApexPages.currentPage().getParameters().get('billToCustId');
        if (!String.isEmpty(billToCustId)){
            try{
                List<Account> accounts = AccountsSelector.newInstance().selectById(new Set<Id>{billToCustId});
                if (accounts.size() > 0){
                    billToCust = accounts[0];
                    if(billToCust.Type == 'Prospect') {
                        SalesOrdersService.isValidCustomer(billToCustId);
                    }
                } else {
                    throw new DataException('Bill-to Customer does not exist!');
                }
            } catch (Exception ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            }
        }
    }

    public void populatedSelectedServiceCenterId(){
        String selectedSCId = ApexPages.currentPage().getParameters().get('selectedSCId');
        this.selectedServiceCenterId = selectedSCId;
        System.debug('Debug: this.selectedServiceCenterId ' + this.selectedServiceCenterId);
    }

    @AuraEnabled
    public static String getData(String recordId){
        try{
            system.debug('recordId:::::::::::::::::'+recordId);
            Sales_Order__c salesOrder = [SELECT Id FROM Sales_Order__c WHERE Id = :recordId LIMIT 1];
            system.debug('salesOrder :::::::::::::'+salesOrder);
            ApexPages.StandardController standardController = new ApexPages.StandardController(salesOrder);
            Map<String, Object> initDataMap = new Map<String, Object>();
            if(!Test.isRunningTest()){
            CloneSalesOrderController controller = new CloneSalesOrderController(standardController);
            
            initDataMap.put('salesOrder', controller.theSO);
            initDataMap.put('serviceCenters', controller.serviceCenterList);
            initDataMap.put('selectedServiceCenterId', controller.selectedServiceCenterId);
            initDataMap.put('billToCustomer', controller.billToCust);
            initDataMap.put('quoteSigned', controller.quoteSigned);
            
        	}
        	return JSON.serialize(initDataMap);
        } catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void validateBillToCust(String billToId){
        if (!String.isEmpty(billToId)){
            try{
                List<Account> accounts = AccountsSelector.newInstance().selectById(new Set<Id>{billToId});
                if (accounts.size() > 0){
                    if(accounts[0].Type == 'Prospect') {
                        SalesOrdersService.isValidCustomer(billToId);
                    }
                } else {
                    throw new AuraHandledException('Bill-to Customer does not exist!');
                }
            } catch (Exception ex){
                throw new AuraHandledException(ex.getMessage());
            }
        }
    }

    @AuraEnabled
    public static String cloneSalesOrder(String sourceRecordId, String selectedCloneToRecordType, String selectedServiceCenter, String selectedBillToId, String selectedBillParentId, String jobDescription, String poNum ){
        try {
            List<Sales_Order__c> sales = New List<Sales_Order__c>();            
            //Task#78352//Bug#80870
            List<Sales_Line__c> salesLines=New List<Sales_Line__c>();
            Date thrdPartyValDate = Date.valueOf(label.SO_3rd_Party_Facility_Check);
            salesLines = [Select Id from Sales_Line__c Where Sales_Order__c=:sourceRecordId 
                          AND Sales_Order__r.Service_Center__r.Include_SO_in_EQAI_Invoice_Integration__c=true 
                          AND Facility__r.Third_Party_Facility__c = true AND CreatedDate >= :thrdPartyValDate];
            //Ticket#126489 >>
             List<Account> accounts;
            //Ticket#126489 <<
            //Bug-88502 //Task78375
            if (!String.isEmpty(selectedBillToId)){
            //Ticket#126489 >>
                 accounts = AccountsSelector.newInstance().selectById(new Set<Id>{selectedBillToId});
                //Ticket#126489 <<
                // if(accounts[0].Sage_Customer_No__c !=null && CustomerDetailsService.getCustomerDetails(accounts[0].Sage_Customer_No__c) == 'T'){
                //     throw new DataException('Salesforce cannot send National Account, MSG, or Retail Account customers to EQAI. Please create Work Order Quote/Work Order in EQAI directly.');  
                // }
                if((System.Label.Release_Flag =='true' && (String.isBlank(accounts[0].AccountNumber) || String.isBlank(accounts[0].Sage_Customer_No__c)) && System.Label.Account_Number_Validation =='false') ||(String.isBlank(accounts[0].Sage_Customer_No__c) && System.Label.Account_Number_Validation =='true' && System.Label.Release_Flag =='true')){
                    sales = [Select Id from Sales_Order__c where Document_Type__c = 'Sales Order' and Bill_to_Customer_No__c=:accounts[0].Id];
                }
                if(accounts[0].Customer_Status__c == 'Inactive'){
                    sales = [Select Id from Sales_Order__c where Document_Type__c = 'Sales Order' and Bill_to_Customer_No__c=:accounts[0].Id];
                }
            }
            if(sales.size()>0 && selectedCloneToRecordType == 'Order')
            {
                throw new DataException('ERROR! You have exceeded the number of Emergency Sales Orders. This customer is not approved. Please contact Accounts Receivable.');  
            }
            //End Bug-88502 
            if(salesLines.size()>0 && selectedCloneToRecordType == 'Order' && System.Label.Release_Flag =='true')
            {
                throw new DataException('ERROR! You cannot create a Sale Order, Your have a Waste Line referencing 3rd Party. You must select an approved facility.');  
            }
            if (String.isBlank(jobDescription)) {
                throw new DataException('Job Description is required');
            }
            else If(JobDescription.length()>40){
                throw new DataException('Job Description cannot exceed 40 characters');    
            }
            if (selectedCloneToRecordType == 'Order') {
                //Ticket#126489 >>
                if (String.isBlank(poNum) && (accounts[0].PO_Number_Type__c!=null || accounts[0].PO_Required__c == true)){
                    throw new DataException('Customer PO Number is required'); 
                }
                //Ticket#126489 <<
                //Ticket#27427 >>
                //Service_Center__c selectedServiceCenterRec = [SELECT Id,Prevent_New_and_Cloned_Sales_Orders__c FROM Service_Center__c WHERE Id = :selectedServiceCenter LIMIT 1];
                List<Service_Center__c> selectedServiceCenterRec = ServiceCentersSelector.newInstance().selectById(new Set<Id>{selectedServiceCenter});
                if(selectedServiceCenterRec!=null && selectedServiceCenterRec.size()>0 && selectedServiceCenterRec[0].Prevent_New_and_Cloned_Sales_Orders__c == true){
                    throw new DataException('Cloning Sales Order is prevented in selected Service Center!');
                }
                //Ticket#27427 <<
            } else {
                poNum = null;
            }
            String newSOId = SalesOrdersService.cloneSalesOrder(new Set<Id>{sourceRecordId}, selectedCloneToRecordType, selectedServiceCenter, selectedBillToId, selectedBillParentId, jobDescription, poNum);
            return newSOId;
        } catch (Exception e) {
            System.debug('Error: ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
}