objects/Account/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>Today()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Rental_Order__c/Rental_Order__c.object-meta.xml
<CustomObject>
    <label>Rental Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rental Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rental_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

objects/Rental_Order__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipment No.</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Rental Orders</relationshipLabel>
    <relationshipName>Rental_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Rental_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Rental Orders</relationshipLabel>
    <relationshipName>Rental_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Rental_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Rental Orders</relationshipLabel>
    <relationshipName>Rental_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/Resource_Off__c.object-meta.xml
<CustomObject>
    <label>Resource Off</label>
    <nameField>
        <displayFormat>Off-{0000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Off</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Off__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

objects/Resource_Off__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Offs</relationshipLabel>
    <relationshipName>Resource_Offs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Off__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>Service_Center__r.Shop_Time_Sales_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/Resource_Off__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resource Off</relationshipLabel>
    <relationshipName>Resource_Off</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

objects/TM__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Roll up field - Labor line count</inlineHelpText>
    <label>Labor Resource Count</label>
    <summaryFilterItems>
        <field>TM_Line__c.Category__c</field>
        <operation>equals</operation>
        <value>Labor</value>
    </summaryFilterItems>
    <summaryForeignKey>TM_Line__c.TM__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Confirmed.recordType-meta.xml
<RecordType>
    <fullName>Confirmed</fullName>
    <active>true</active>
    <label>Confirmed</label>
    
    
</RecordType>

objects/TM__c/recordTypes/Scheduled.recordType-meta.xml
<RecordType>
    <fullName>Scheduled</fullName>
    <active>true</active>
    <label>Scheduled</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Billing Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>TM__r.Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <formula>TM__r.Scheduled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

objects/TM_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/ResourceMgmt.cls
public with sharing class ResourceMgmt {
    /*
    public static Map<string, List<TM_Line__c>> mapAllTML = new Map<string, List<TM_Line__c>>();
    public static Map<string, List<TM_Line__c>> mapRentalTML = new Map<string, List<TM_Line__c>>();
    public static Map<string, List<Resource_Off__c>> mapAllResourceOff = new Map<string, List<Resource_Off__c>>();
    public static Map<string, List<Rental_Order__c>> mapAllRentalOrders = new Map<string, List<Rental_Order__c>>();
    */
    public static Resource__c validateServiceCenter(Resource__c theResource) {        
        if (String.isEmpty(theResource.Service_Center__c)) {
            return theResource;
        } else {
            Service_Center__c sc = [SELECT Id, Name FROM Service_Center__c WHERE Id = : theResource.Service_Center__c];
            theResource.Service_Center__r = new Service_Center__c(Id = sc.Id, Name = sc.Name);
        }

        return theResource;
    }
    
    public static List<TM_Line__c> selectAllTML(string scheduledDateValue,Set<Date> scheduledDatesSet) {
        Date scheduledDate;
        List<TM_Line__c> theAllTMLList = new List<TM_Line__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.TM_Line__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ', Resource__r.Name, TM__r.Scheduled_Date__c,Resource__r.Description__c,TM__r.Sales_Order__r.Name, TM__r.Name, Resource_Type__r.Name, TM__r.Service_Center__r.Name';
        strQuery += ' FROM TM_Line__c ';

        if (string.isNotEmpty(scheduledDateValue)) {
            scheduledDate = date.parse(scheduledDateValue);
            strQuery += ' WHERE TM__r.Scheduled_Date__c =: scheduledDate LIMIT 1000';
        }
        else if (scheduledDatesSet != null) {
            strQuery += ' WHERE TM__r.Scheduled_Date__c =: scheduledDatesSet LIMIT 1000';
        } 
        else {
            strQuery += ' LIMIT 1000';
        }
        
        system.debug('**strQuery' + strQuery);

        theAllTMLList = Database.query(strQuery);
        
        return theAllTMLList;
    }

    public static List<TM_Line__c> selectRentalTML(string scheduledDateValue,Set<Date> scheduledDatesSet) {
        Date scheduledDate;
        set<String> setStatus = new set<string>();
        setStatus.add('Scheduled');
        setStatus.add('Confirmed');
        setStatus.add('Received By Billing');
        setStatus.add('Ready to Bill');

        List<TM_Line__c> theRentalTMLList = new List<TM_Line__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.TM_Line__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ', Resource__r.Name, TM__r.Scheduled_Date__c,Resource__r.Description__c,TM__r.Sales_Order__r.Name, TM__r.Sales_Order__c, TM__r.Name, Resource_Type__r.Name, TM__r.Service_Center__r.Name';
        strQuery += ' FROM TM_Line__c WHERE TM__r.Status__c IN :setStatus AND Drop_Off_Rental__c = true AND Drop_Off_R_O__c = null ';

        if (string.isNotEmpty(scheduledDateValue)) {
            scheduledDate = date.parse(scheduledDateValue);
            strQuery += ' AND TM__r.Scheduled_Date__c <=: scheduledDate LIMIT 1000';
        } 
        else if (scheduledDatesSet != null) {
            strQuery += ' AND TM__r.Scheduled_Date__c <=: scheduledDatesSet LIMIT 1000';
        }
        else {
            strQuery += ' LIMIT 1000';
        }
        System.debug('scheduledDatesSet' + scheduledDatesSet);
        System.debug('theQuery' + strQuery);
        theRentalTMLList = Database.query(strQuery);
        
        return theRentalTMLList;
    }

    public static List<Resource_Off__c> selectAllResourceOff(string scheduledDateValue,Set<Date> scheduledDatesSet) {
        Date scheduledDate;
        List<Resource_Off__c> theAllResourceOffList = new List<Resource_Off__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.Resource_Off__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ', Off_Type__r.Name,Resource__r.Name, Service_Center__r.Name, Resource_Service_Center__r.Name';
        strQuery += ' FROM Resource_Off__c ';

        if (string.isNotEmpty(scheduledDateValue)) {
            scheduledDate = date.parse(scheduledDateValue);
            strQuery += ' WHERE Resource_Off__c.Date__c =: scheduledDate LIMIT 1000';
        } 
        else if (scheduledDatesSet != null) {
             strQuery += ' WHERE Resource_Off__c.Date__c =: scheduledDatesSet LIMIT 1000';
        }
        else {
            strQuery += ' LIMIT 1000';
        }

        theAllResourceOffList = Database.query(strQuery);
        
        return theAllResourceOffList;
    }
    
    public static List<Rental_Order__c> selectAllRentalOrders(string scheduledDateValue,Set<Date> scheduledDatesSet) {
        Date scheduledDate;
        List<Rental_Order__c> theAllRentalOrdersList = new List<Rental_Order__c>();
        //mapRentalOrders = new Map<String, Rental_Order__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.Rental_Order__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ', Bill_to_Customer__r.Name, Sales_Order__r.Name, Service_Center__r.Name,Resource__r.Name ';
        strQuery += ' FROM Rental_Order__c ';

        if (string.isNotEmpty(scheduledDateValue)) {
            scheduledDate = date.parse(scheduledDateValue);
            strQuery += ' WHERE Drop_Off_Date__c <=: scheduledDate AND (Pick_Up_Date__c >=: scheduledDate OR Pick_Up_Date__c = null) LIMIT 1000';
        } 
            // This may not make sense if there are multiple dates in the set
        else if (scheduledDatesSet != null) {
            strQuery += ' WHERE Drop_Off_Date__c <=: scheduledDatesSet AND (Pick_Up_Date__c >=: scheduledDatesSet OR Pick_Up_Date__c = null) LIMIT 1000';
        }
        else {
            strQuery += ' LIMIT 1000';
        }

        theAllRentalOrdersList = Database.query(strQuery);
        
        return theAllRentalOrdersList;
    }

    //Ticket#13910
    public static List<TM_Line__c> getAllTMLinesByResIdSetAndDate(Set<Id> resIdSet, String fromDate){
        Date scheduledDate;
        List<TM_Line__c> theAllTMLList = new List<TM_Line__c>();
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.TM_Line__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ', Resource__r.Name, TM__r.Scheduled_Date__c,Resource__r.Description__c,TM__r.Sales_Order__r.Name, TM__r.Name, Resource_Type__r.Name, TM__r.Service_Center__r.Name';
        strQuery += ' FROM TM_Line__c ';

        if (String.isNotEmpty(fromDate)) {
            scheduledDate = date.parse(fromDate);
            strQuery += ' WHERE TM__r.Scheduled_Date__c =: scheduledDate AND Resource__c IN :resIdSet';
        }

        theAllTMLList = Database.query(strQuery);

        return theAllTMLList;
    }
}