objects/Account/fields/EQAI_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Customer_ID__c</fullName>
    <label>EQAI Customer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term</label>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Salesperson__r.Salesperson_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Term__c/fields/EQAI_Terms_Code__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Terms_Code__c</fullName>
    <label>EQAI Terms Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Salesperson__c/fields/Territory_Code__c.field-meta.xml
<CustomField>
    <fullName>Territory_Code__c</fullName>
    <label>Territory Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomerServiceTest.cls
/*************************************************************************************************
* Name         :  CustomerServiceTest
* Description  :  Test class for CustomerService
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Sanjana Ravichandran     02-07-2025             US140550: Salesforce: Create New Customer in SF from EQAI
* Sanjana Ravichandran     02-18-2025 			  US140555: Salesforce: Process update to Customer record received from EQAI
***********************************************************************************************************/
@isTest
private class CustomerServiceTest {
    @testSetup
    static void setupTestData() {
        Subsidiary_Company__c subsidiary = new Subsidiary_Company__c(Name = '1-REPUBLIC SERVICES');
        insert subsidiary;

        Payment_Term__c paymentTerm = new Payment_Term__c(EQAI_Terms_Code__c = 'NET30');
        insert paymentTerm;

        Salesperson__c salesperson = new Salesperson__c(
            Territory_Code__c = 'TX01', 
            Salesperson_Code__c = 'SP01', 
            Status__c = 'Active' 
        );
        insert salesperson;

        Account existingAccount = new Account(
            Name = 'Test Customer',
            Sage_Customer_No__c = 'D365-001',
            EQAI_Customer_ID__c = 'EQAI-123',
            Subsidiary_Company__c = subsidiary.Id
        );
        insert existingAccount;
    }

    @isTest
    static void testCreateOrUpdateCustomers() {
        Test.startTest();

        String jsonRequest = '[{"cust_name":"New Customer","Salesforce_Account_CSID":"","customer_ID":"EQAI-456","ax_customer_id":"D365-002","cust_website":"www.newcustomer.com","cust_phone":"1234567890","cust_fax":"0987654321","bill_to_addr1":"123 Billing St","bill_to_city":"Dallas","bill_to_state":"TX","bill_to_zip_code":"75001","bill_to_country":"USA","cust_addr1":"456 Shipping St","cust_city":"Houston","cust_state":"TX","cust_zip_code":"77001","cust_country":"USA","terms_code":"NET30","CustomerBilling":[{"territory_code":"TX01","PO_required_flag":"T"}]}]';

        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueOf(jsonRequest);
        req.httpMethod = 'PUT';
        req.requestURI = '/services/apexrest/CustomerService/';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;

        CustomerService.createOrUpdateCustomers();

        Test.stopTest();

        Account newAccount = [SELECT Name, Sage_Customer_No__c, EQAI_Customer_ID__c, Payment_Term__c FROM Account WHERE EQAI_Customer_ID__c = 'EQAI-456' LIMIT 1];
        System.assertEquals('NEW CUSTOMER', newAccount.Name);
        System.assertEquals('D365-002', newAccount.Sage_Customer_No__c);
        System.assertNotEquals(null, newAccount.Payment_Term__c);
    }

    @isTest
    static void testUpdateExistingCustomer() {
        Test.startTest();

        String jsonRequest = '[{"cust_name":"Updated Customer","customer_ID":"EQAI-123","ax_customer_id":"D365-001","bill_to_city":"Austin","cust_city":"San Antonio"}]';

        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueOf(jsonRequest);
        req.httpMethod = 'PUT';
        req.requestURI = '/services/apexrest/CustomerService/';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;

        CustomerService.createOrUpdateCustomers();

        Test.stopTest();

        Account updatedAccount = [SELECT Name, BillingCity, ShippingCity FROM Account WHERE EQAI_Customer_ID__c = 'EQAI-123' LIMIT 1];
        System.assertEquals('TEST CUSTOMER', updatedAccount.Name);
    }

    @isTest
    static void testErrorHandling() {
        Test.startTest();

        String jsonRequest = '[{"cust_name": "Invalid Customer"}]';

        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueOf(jsonRequest);
        req.httpMethod = 'PUT';
        req.requestURI = '/services/apexrest/CustomerService/';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;

        try {
            CustomerService.createOrUpdateCustomers();
            System.assert(true);
        } catch (Exception ex) {
            System.assert(false, 'Method should handle errors gracefully.');
        }

        Test.stopTest();
    }
}