objects/Account/fields/PO_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Number_Type__c</fullName>
    <label>PO Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALPHANUMERICAL</fullName>
                <label>Alphanumerical</label>
            </value>
            <value>
                <fullName>NUMERICAL</fullName>
                <label>Numerical</label>
            </value>
            <value>
                <fullName>NAME_OF_CONTACT</fullName>
                <label>Name of Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Salesperson__r.Salesperson_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Service</fullName>
                <label>OOS-On Lot</label>
            </value>
            <value>
                <fullName>OOS-Pending</fullName>
                <label>OOS-Pending Sale</label>
            </value>
            <value>
                <fullName>Gone</fullName>
            </value>
            <value>
                <fullName>Junked</fullName>
                <isActive>false</isActive>
                <label>Junked</label>
            </value>
            <value>
                <fullName>OOS-Under Repair</fullName>
                <isActive>false</isActive>
                <label>OOS-Under Repair</label>
            </value>
            <value>
                <fullName>Retired</fullName>
                <isActive>false</isActive>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
            <value>
                <fullName>Stolen</fullName>
                <isActive>false</isActive>
                <label>Stolen</label>
            </value>
            <value>
                <fullName>Under Repair</fullName>
                <isActive>false</isActive>
                <label>Under Repair</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Estimated_Job_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Job_Start_Date__c</fullName>
    <label>Estimated Job Start Date</label>
    <type>Date</type>
</CustomField>

objects/Sales_Order__c/fields/Name_of_Worker_Responsible__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Worker_Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of Worker Responsible</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Quotes/Orders</relationshipLabel>
    <relationshipName>Quotes_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Project_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Project_Coordinator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Name</field>
            <operation>notEqual</operation>
            <value>HOU</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Quotes/Orders (Project Manager)</relationshipLabel>
    <relationshipName>Sales_Orders_PC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/SO_sent_to_EQAI__c.field-meta.xml
<CustomField>
    <fullName>SO_sent_to_EQAI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SO sent to EQAI</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Surcharge_Type__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_Type__c</fullName>
    <label>Surcharge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Fuel Surcharge</fullName>
            </value>
            <value>
                <fullName>EEC Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Worker_Responsible__c.field-meta.xml
<CustomField>
    <fullName>Worker_Responsible__c</fullName>
    <label>Worker Responsible</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Service_Center__c/fields/Include_SO_in_EQAI_Invoice_Integration__c.field-meta.xml
<CustomField>
    <fullName>Include_SO_in_EQAI_Invoice_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include SO in EQAI Invoice Integration</label>
    <type>Checkbox</type>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendSalesOrderToEqaiControllerTest.cls
@isTest
private class SendSalesOrderToEqaiControllerTest  {
  

    @isTest
    static void testSendSalesOrderToEqai() {
            // Create a test Service Center with Include_SO_in_EQAI_Invoice_Integration__c set to true
            Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
            insert subsidiaryCompany;
            Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id, Include_SO_in_EQAI_Invoice_Integration__c = true);
            insert serviceCenter;
            Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
            insert salesPerson;
            Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
            insert acc;
            Resource__c resource = new Resource__c(Name='TEST Resource');
            insert resource;
    
            Sales_Order__c salesOrder = new Sales_Order__c(Name='Test1');
            salesOrder.Subsidiary_Company__c = subsidiaryCompany.id;
            salesOrder.Bill_to_Customer_No__c = acc.id;
            salesOrder.Project_Coordinator__c = salesPerson.id;
            salesOrder.Service_Center__c = serviceCenter.id;
            salesOrder.Surcharge_Type__c = 'EEC Fee';
            salesOrder.SO_sent_to_EQAI__c = false;
            salesOrder.Worker_Responsible__c = '456456456';
            salesOrder.Name_of_Worker_Responsible__c = resource.id;
            salesOrder.Estimated_Job_Start_Date__c = Date.newInstance(2024, 03, 09);
            insert salesOrder;

            String result = SendSalesOrderToEqaiController.sendSalesOrderToEQAI(salesOrder.Id);
    
        }

    @isTest
    static void testSendSalesOrderToEqaiSCfalse() {
            // Create a test Service Center with Include_SO_in_EQAI_Invoice_Integration__c set to false
            Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
            insert subsidiaryCompany;
            Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id, Include_SO_in_EQAI_Invoice_Integration__c = false);
            insert serviceCenter;
            Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
            insert salesPerson;
            Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
            insert acc;
    
            Sales_Order__c salesOrder = new Sales_Order__c(Name='Test1');
            salesOrder.Subsidiary_Company__c = subsidiaryCompany.id;
            salesOrder.Bill_to_Customer_No__c = acc.id;
            salesOrder.Project_Coordinator__c = salesPerson.id;
            salesOrder.Service_Center__c = serviceCenter.id;
            salesOrder.Surcharge_Type__c = 'EEC Fee';
            insert salesOrder;
    
            Test.startTest();
            String result = SendSalesOrderToEqaiController.sendSalesOrderToEQAI(salesOrder.Id);
            Test.stopTest();
    
        }

     @isTest
    static void testSendSalesOrderToEqaiSOsentToEqaiTrue() {
            // Create a test Service Center with Include_SO_in_EQAI_Invoice_Integration__c set to true and SO_sent_to_EQAI__c = true
            Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
            insert subsidiaryCompany;
            Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id, Include_SO_in_EQAI_Invoice_Integration__c = true);
            insert serviceCenter;
            Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
            insert salesPerson;
            Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
            insert acc;

            Sales_Order__c salesOrder = new Sales_Order__c(Name='Test1');
            salesOrder.Subsidiary_Company__c = subsidiaryCompany.id;
            salesOrder.Bill_to_Customer_No__c = acc.id;
            salesOrder.Project_Coordinator__c = salesPerson.id;
            salesOrder.Service_Center__c = serviceCenter.id;
            salesOrder.Surcharge_Type__c = 'EEC Fee';
            salesOrder.SO_sent_to_EQAI__c = true;
            insert salesOrder;

            Test.startTest();
            String result = SendSalesOrderToEqaiController.sendSalesOrderToEQAI(salesOrder.Id);
            Test.stopTest(); //test

        }

        @isTest
        static void testSendSalesOrderToEqaiRequiredFieldsAreNull() {
            // Create a test Service Center with Include_SO_in_EQAI_Invoice_Integration__c set to true and Worker Responsible is null
            Subsidiary_Company__c subsidiaryCompany = new Subsidiary_Company__c(Name='Subsidiary Company1');
            insert subsidiaryCompany;
            Service_Center__c serviceCenter = new Service_Center__c(Name='12', Code__c='12345', Subsidiary_Company__c=subsidiaryCompany.id, Include_SO_in_EQAI_Invoice_Integration__c = true);
            insert serviceCenter;
            Salesperson__c salesPerson = new SalesPerson__c(Name='Salesperson1', Salesperson_Code__c='1', Status__c='Active');
            insert salesPerson;
            Account acc = new Account(name ='Test Account',PO_Number_Type__c ='NUMERICAL', AccountNumber='123dfsa', Subsidiary_Company__c=subsidiaryCompany.id);
            insert acc;

            Sales_Order__c salesOrder = new Sales_Order__c(Name='Test1');
            salesOrder.Subsidiary_Company__c = subsidiaryCompany.id;
            salesOrder.Bill_to_Customer_No__c = acc.id;
            salesOrder.Project_Coordinator__c = salesPerson.id;
            salesOrder.Service_Center__c = serviceCenter.id;
            salesOrder.Surcharge_Type__c = 'EEC Fee';
            SalesOrder.Worker_Responsible__c = null;
            insert salesOrder;

            Test.startTest();
            String result = SendSalesOrderToEqaiController.sendSalesOrderToEQAI(salesOrder.Id);
            Test.stopTest();
    
            }

     
}