objects/Account/fields/Pricing_Group__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Group__c</fullName>
    <label>Pricing Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silver</fullName>
                <default>true</default>
                <label>Silver</label>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Contract_Line__c/Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Contract Line</label>
    <nameField>
        <label>contract line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure1__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure1</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure1)</relationshipLabel>
    <relationshipName>Resources1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure2__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure2</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure2)</relationshipLabel>
    <relationshipName>Resources2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure3__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure3</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure3)</relationshipLabel>
    <relationshipName>Resources3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure4__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure4</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources (Unit of Measure4)</relationshipLabel>
    <relationshipName>Resources4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

objects/Resource__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Unit_of_Measure1__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure1</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure1)</relationshipLabel>
    <relationshipName>Resource_Types1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure2__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure2</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure2)</relationshipLabel>
    <relationshipName>Resource_Types2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure3__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure3</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure3)</relationshipLabel>
    <relationshipName>Resource_Types3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure4__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure4</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types (Unit of Measure4)</relationshipLabel>
    <relationshipName>Resource_Types4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Emergency_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Sales_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Sales Order</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Pricing_Group__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Group__c</fullName>
    <formula>TEXT(Bill_to_Customer_No__r.Pricing_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Group</label>
    <type>Text</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Resource_Type__c.Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>TM__r.Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>Service_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/TMLinesTest.cls
@IsTest
private class TMLinesTest {
    @IsTest
    private static void testUpdateTMLinesWhenResourceTypeChanged (){
        // Create mocks test
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

        // Given
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Account account = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                Pricing_Group__c = 'Silver'
        );
        Sales_Order__c theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Emergency_Sales_Order__c = false
        );
        TM__c theTM = new TM__c(
                Id = fflib_IDGenerator.generate(TM__c.SObjectType),
                Sales_Order__c = theSO.Id
        );
        Unit_of_Measure__c uom = new Unit_of_Measure__c(
                Id = fflib_IDGenerator.generate(Unit_of_Measure__c.SObjectType)
        );
        Unit_of_Measure__c uom1 = new Unit_of_Measure__c(
                Id = fflib_IDGenerator.generate(Unit_of_Measure__c.SObjectType)
        );
        Unit_of_Measure__c uom2 = new Unit_of_Measure__c(
                Id = fflib_IDGenerator.generate(Unit_of_Measure__c.SObjectType)
        );
        Unit_of_Measure__c uom3 = new Unit_of_Measure__c(
                Id = fflib_IDGenerator.generate(Unit_of_Measure__c.SObjectType)
        );
        Unit_of_Measure__c uom4 = new Unit_of_Measure__c(
                Id = fflib_IDGenerator.generate(Unit_of_Measure__c.SObjectType)
        );
        Resource_Type__c rt1 = new Resource_Type__c(
                Id = fflib_IDGenerator.generate(Resource_Type__c.SObjectType),
                Unit_of_Measure__c = uom.Id,
                Unit_of_Measure1__c = uom1.Id,
                Unit_of_Measure2__c = uom2.Id,
                Unit_of_Measure3__c = uom3.Id,
                Unit_of_Measure4__c = uom4.Id
        );
        TM_Line__c theTML = new TM_Line__c(
                Id = fflib_IDGenerator.generate(TM_Line__c.SObjectType),
                TM__c = theTM.Id,
                Category__c = 'Labor',
                Unit_of_Measure__c = uom.Id,
                Resource_Type__c = rt1.Id
        );
        Company_Setup__c theCompanySetup = new Company_Setup__c(
                Id = fflib_IDGenerator.generate(Company_Setup__c.SObjectType),
                T_M_Overtime_Multiplier__c = 1.5,
                T_M_Premium_Multiplier__c = 2
        );
        theTML.TM__r = new TM__c(Id = theTM.Id, Sales_Order__c = theSO.Id, Bill_to_Customer__c = account.Id);
        List<TM_Line__c> theTMLList = new List<TM_Line__c>();
        theTMLList.add(theTML);
        Application.UnitOfWork.setMock(uowMock);

        //When
        TMLines.mapSalesOrders.put(theSO.Id, theSO);
        TMLines.mapAccounts.put(account.Id, account);
        TMLines.mapResourceTypes.put(rt1.Id, rt1);
        TMLines.theCompanySetupValue = theCompanySetup;
        ITMLines TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom1.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom2.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom3.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom4.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theSO.Emergency_Sales_Order__c = true;
        TMLines.mapSalesOrders.put(theSO.Id, theSO);
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom3.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom2.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom1.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Category__c = 'Equipment';
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom1.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom2.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom3.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom4.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theSO.Emergency_Sales_Order__c = false;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom3.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom2.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom1.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Category__c = 'Materials';
        Resource__c r = new Resource__c (
                Id = fflib_IDGenerator.generate(Resource__c.SObjectType),
                Unit_of_Measure__c = uom.Id,
                Unit_of_Measure1__c = uom1.Id,
                Unit_of_Measure2__c = uom2.Id,
                Unit_of_Measure3__c = uom3.Id,
                Unit_of_Measure4__c = uom4.Id
        );
        theTML.Resource__c = r.Id;
        TMLines.mapResources.put(r.Id, r);
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom1.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom2.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom3.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom4.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theSO.Emergency_Sales_Order__c = true;
        theTML.Unit_of_Measure__c = uom4.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom3.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom2.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom1.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Unit_of_Measure__c = uom.Id;
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        Contract_Line__c cl = new Contract_Line__c(
                Id = fflib_IDGenerator.generate(Contract_Line__c.SObjectType),
                Regular_Rate__c = 1
        );
        theTML.Contract_Line__c = cl.Id;
        TMLines.mapContractLines.put(cl.Id, cl);
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Category__c = 'Equipment';
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        theTML.Category__c = 'Labor';
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

        Sales_Line__c theSL = new Sales_Line__c(
                Id = fflib_IDGenerator.generate(Sales_Line__c.SObjectType),
                Unit_Price__c = 998,
                Unit_of_Measure__c = uom.Id
        );
        theTML.Sales_Line__c = theSL.Id;
        TMLines.mapSalesLines.put(theSL.Id, theSL);
        TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenResourceTypeChanged();

    }

    @IsTest
    private static void testUpdateTMLinesWhenUnitOfMeasureChanged (){
        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        TM_Line__c theTML = new TM_Line__c(
                Id = fflib_IDGenerator.generate(TM_Line__c.SObjectType)
        );
        List<TM_Line__c> theTMLList = new List<TM_Line__c>();
        ITMLines TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesWhenUnitOfMeasureChanged();
    }

    @IsTest
    private static void testUpdateTMLinesRestOfFields (){
        
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);
        Company_Setup__c theCompanySetup = TestDataUtil.CompanySetupRecord;

        Unit_of_Measure__c uom = new Unit_of_Measure__c(
                Id = fflib_IDGenerator.generate(Unit_of_Measure__c.SObjectType),
                Hours_UOM__c = true
        );
        Resource_Type__c rt = new Resource_Type__c(
                Id = fflib_IDGenerator.generate(Resource_Type__c.SObjectType),
                Unit_of_Measure__c = uom.Id
        );
        Resource__c r = new Resource__c(
                Id = fflib_IDGenerator.generate(Resource__c.SObjectType),
                Unit_of_Measure__c = uom.Id
        );
        TM_Line__c theTML = new TM_Line__c(
                Id = fflib_IDGenerator.generate(TM_Line__c.SObjectType),
                Hour__c = 1,
                Bill_Site_Time__c = true,
                Category__c = 'Labor',
                Resource_Type__c = rt.Id,
                Unit_of_Measure__c = uom.Id,
                Resource__c = r.Id,
                Bill_as_Lump_Sum__c = true
        );
        TM_Line__c theTML2 = new TM_Line__c(
                Id = fflib_IDGenerator.generate(TM_Line__c.SObjectType),
                Hour__c = 1,
                Bill_Site_Time__c = false,
                Category__c = 'Materials',
                Resource_Type__c = rt.Id,
                Unit_of_Measure__c = uom.Id,
                Resource__c = r.Id,
                Bill_as_Lump_Sum__c = true
        );
        List<TM_Line__c> theTMLList = new List<TM_Line__c>();
        theTMLList.add(theTML);
        theTMLList.add(theTML2);
        TMLines.mapResourceTypes.put(rt.Id, rt);
        TMLines.mapResources.put(r.Id, r);
        TMLines.mapUnitOfMeasures.put(uom.Id, uom);
        ITMLines TMLDomain = TMLines.newInstance(theTMLList);
        TMLDomain.updateTMLinesRestOfFields();
    }

    @IsTest
    private static void testPopulateLinesInfo(){
        NewTestData.createTestData();
        Test.startTest();
        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        List<TM_Line__c> tmLines = new List<TM_Line__c>();
        TM_Line__c tmLine = NewTestData.mapTMLinesByTMIdByCategory.get(tm.Id).get(ResourceService.WASTE_DISPOSAL_CATEGORY);
        tmLines.add(tmLine);
        TM_Line__c laborLine = NewTestData.mapTMLinesByTMIdByCategory.get(tm.Id).get(ResourceService.LABOR_CATEGORY);
        tmLines.add(laborLine);
        Map<TM__c, List<TM_Line__c>> tmLinesByTm = new Map<TM__c, List<TM_Line__c>>();
        tmLinesByTm.put(tm, tmLines);
        TMLLinesService.populateLinesInfo(tmLinesByTm);
        TMLLinesService.isCalcBaseOnResType(laborLine.Category__c);
        TMLLinesService.validateResourceType(tm, laborLine, false);
        TMLLinesService.validateContractLine(tm, laborLine);
        laborLine.Resource_Type__c = null;
        TMLLinesService.validateContractLine(tm, laborLine);
        TMLLinesService.validateContractLine(tm, tmLine);
        tmLine.Resource__c = null;
        TMLLinesService.validateContractLine(tm, tmLine);
        Test.stopTest();
    }

    @IsTest
    private static void testPopulateLinesInfo2(){
        NewTestData.createTestData();
        Test.startTest();
        TM__c tm = NewTestData.mapTMsByName.get(NewTestData.TEST_TM_NAME_01);
        List<TM_Line__c> tmLines = new List<TM_Line__c>();
        TM_Line__c tmLine = NewTestData.mapTMLinesByTMIdByCategory.get(tm.Id).get(ResourceService.WASTE_DISPOSAL_CATEGORY);
        tmLines.add(tmLine);
        TM_Line__c laborLine = NewTestData.mapTMLinesByTMIdByCategory.get(tm.Id).get(ResourceService.LABOR_CATEGORY);
        tmLines.add(laborLine);
        System.debug('Info: tmLines size: ' + tmLines.size());
        System.debug('Info: tmLines: ' + tmLines);
        Map<TM__c, List<TM_Line__c>> tmLinesByTm = new Map<TM__c, List<TM_Line__c>>();
        tmLinesByTm.put(tm, tmLines);
        TMLLinesService.initStaticVariables(tmLinesByTm);
        TMLLinesService.calcLineCost(tmLinesByTm);
        TMLLinesService.calcTotals(tmLinesByTm);
        TMLLinesService.validateResourceType(tm, laborLine, false);
        TMLLinesService.calcUnitCost(tm, laborLine);
        TMLLinesService.calcUnitPrice(tm,laborLine);
        Test.stopTest();
    }
    //test
}