objects/Account/fields/Sage_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Customer_No__c</fullName>
    <label>D365 Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/EQAI_API_URL_Extensions__mdt.object-meta.xml
<CustomObject>
    <description>URL Extensions for EQAI API Endpoints</description>
    <label>EQAI API URL Extensions</label>
    <pluralLabel>EQAI API URL Extensions</pluralLabel>
</CustomObject>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Extension__c.field-meta.xml
<CustomField>
    <fullName>API_Extension__c</fullName>
    <label>API Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/EQAI_API_URL_Extensions__mdt/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Facility__c/Facility__c.object-meta.xml
<CustomObject>
    <label>Facility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility__c/fields/TSDF_Code__c.field-meta.xml
<CustomField>
    <fullName>TSDF_Code__c</fullName>
    <label>TSDF Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Alternate_Site_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Site_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Address__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer_No__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Address__c</referenceTo>
    <relationshipLabel>Quotes/Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/EqaiGeneratorId__c.field-meta.xml
<CustomField>
    <fullName>EqaiGeneratorId__c</fullName>
    <label>EqaiGeneratorId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/Sales_Order_EQAI_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Data Mapping of Sales Order Field Values to EQAI Field Values</description>
    <label>Sales Order EQAI Mapping</label>
    <pluralLabel>Sales Order EQAI Mapping</pluralLabel>
</CustomObject>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Name__c</fullName>
    <label>EQAI Field Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>company_id</fullName>
                <default>true</default>
                <label>company_id</label>
            </value>
            <value>
                <fullName>profit_ctr_id</fullName>
            </value>
            <value>
                <fullName>project_code</fullName>
            </value>
            <value>
                <fullName>country_code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Field_Value__c</fullName>
    <label>EQAI Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/EQAI_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>EQAI_Table_Name__c</fullName>
    <label>EQAI Table Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WorkOrderQuoteHeader</fullName>
                <default>true</default>
                <label>WorkOrderQuoteHeader</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service_Center__r.Name</fullName>
                <default>true</default>
                <label>Service_Center__r.Name</label>
            </value>
            <value>
                <fullName>Payment_Term__r.Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order_EQAI_Mapping__mdt/fields/Salesforce_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Value__c</fullName>
    <label>Salesforce Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site_Address__c/Site_Address__c.object-meta.xml
<CustomObject>
    <label>Site Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Alternate_Site_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Site_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site Address Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Site_Address__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site_Address__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>T&amp;Ms (Service Center)</relationshipLabel>
    <relationshipName>T_Ms</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ProfileApprovalService.cls
/*************************************************************************************************
* Name         :  ProfileApprovalService
* Description  :  
*
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Shahwaz Khan             15-08-2024             US117942:  Add a Waste profile approval lookup in Salesforce T&M
*************************************************************************************************/
public class ProfileApprovalService {
    Public static httpResponse approvalJsonfromEQAI(String tmId,String description,string facilityId,string genId, String scId){
        map<String,String> company_Id_EQIMap = new map<String,String>();
        map<String,String> profit_Ctr_Id_EQIMap = new map<String,String>();
        try
        {
            for(Sales_Order_EQAI_Mapping__mdt salesOrderEQIMappingRecord :[select Id,EQAI_Field_Name__c,EQAI_Field_Value__c,EQAI_Table_Name__c,Salesforce_Field_API_Name__c,Salesforce_Field_Value__c from Sales_Order_EQAI_Mapping__mdt]){
                if(salesOrderEQIMappingRecord.EQAI_Field_Name__c =='company_id'){
                    company_Id_EQIMap.put(salesOrderEQIMappingRecord.Salesforce_Field_Value__c,salesOrderEQIMappingRecord.EQAI_Field_Value__c);
                }
                else if(salesOrderEQIMappingRecord.EQAI_Field_Name__c=='profit_ctr_id'){
                    profit_Ctr_Id_EQIMap.put(salesOrderEQIMappingRecord.Salesforce_Field_Value__c,salesOrderEQIMappingRecord.EQAI_Field_Value__c);
                }
            }
            HTTPResponse res = new HttpResponse();
            List<Facility__c> facility = [SELECT Id,TSDF_Code__c FROM Facility__c WHERE id=:facilityId LIMIT 1];
            String tsdfCode= (facility.size()>0 && String.isNotBlank(facility[0].TSDF_Code__c)) ? facility[0].TSDF_Code__c : '';
            System.debug('tmId++++++++++'+tmId);
            System.debug('genId++++++++++'+genId);
            System.debug('scId++++++++++'+scId);
            Integer companyId;
            Integer profitCenId;
            String gneratorId;            
            Boolean tmFlag = false;
            
            if(tmId != null)
            {
                if(tmId.startsWith('a1X'))
                {
                    tmflag = true;
                }
            }
            
                if(tmflag)
                {
                    TM__c tm = [Select Id,Sales_Order__r.Alternate_Site_Address__r.Id,
                                     Sales_Order__r.EqaiGeneratorId__c,
                                     Sales_Order__r.Bill_to_Customer_No__r.Sage_Customer_No__c,
                                     Sales_Order__r.Service_Center__r.Name
                                     FROM TM__c where Id=:tmId limit 1];
                    if(tm.Sales_Order__r.Service_Center__r.Name != null && company_Id_EQIMap !=null && company_Id_EQIMap.containskey(tm.Sales_Order__r.Service_Center__r.Name)) 
                        companyId = Integer.valueOf(company_Id_EQIMap.get(tm.Sales_Order__r.Service_Center__r.Name));
                    if(tm.Sales_Order__r.Service_Center__r.Name != null && profit_Ctr_Id_EQIMap !=null && profit_Ctr_Id_EQIMap.containskey(tm.Sales_Order__r.Service_Center__r.Name)) 
                        profitCenId = Integer.valueOf(profit_Ctr_Id_EQIMap.get(tm.Sales_Order__r.Service_Center__r.Name)); 
                     gneratorId = String.ValueOf(tm.Sales_Order__r.EqaiGeneratorId__c) != null ? String.ValueOf(tm.Sales_Order__r.EqaiGeneratorId__c) : '';
                     res = getApprovedProfiles(tm,null,companyId,profitCenId,description,tsdfCode,gneratorId);
                }
                else
                {
                   List<Sales_Order__c> salesOrder = [SELECT Id,Alternate_Site_Address__r.Id,
                                              EqaiGeneratorId__c,
                                 			  Bill_to_Customer_No__r.Sage_Customer_No__c,
                                   			  Service_Center__r.Name
                                 			  FROM Sales_Order__c WHERE Id=:tmId limit 1];
                   Service_Center__c sc = [SELECT Name FROM Service_Center__c WHERE Id = :scId];
                   if(company_Id_EQIMap.containskey(sc.Name)) 
                        companyId = Integer.valueOf(company_Id_EQIMap.get(sc.Name));
                  if( profit_Ctr_Id_EQIMap.containskey(sc.Name)) 
                        profitCenId = Integer.valueOf(profit_Ctr_Id_EQIMap.get(sc.Name));
                  gneratorId = genId;
                 
                  res = getApprovedProfiles(null,salesOrder,companyId,profitCenId,description,tsdfCode,gneratorId);  
               }
          
           return res;
        } catch (Exception e) {
            System.debug('Error in sendContactToEQAI: ' + e.getMessage());
            System.debug('line::'+e.getLineNumber());
            return null; 
        }
    }
    Public static httpResponse getApprovedProfiles(TM__c tmRecord ,List<Sales_Order__c> salesOrderList, Integer companyId, Integer prId,String description,String tsdfCode, String genId){
        ApplicationLog.ApplicationlogInformation logData = new ApplicationLog.ApplicationlogInformation();
        logData.className = 'ProfileApprovalService';
        logData.methodName = 'getApprovedProfiles'; 
        Integer company_id;
        Integer profit_ctr_id;
        String GeneratorId; 
        String SalesforceSiteCsid;
        String D365CustomerId; 
        
        company_id = companyId;
        profit_ctr_id = prId;
        GeneratorId= genId;
        
        try
        {
           
            EQAI_API_URL_Extensions__mdt CustomerDetails = [select API_Extension__c, API_Key__c, API_Token__c, DeveloperName from EQAI_API_URL_Extensions__mdt where DeveloperName='GetProfileApprovalDetails'];
            String endpoint = CustomerDetails.API_Extension__c;
           	if(tmRecord!=null)
            {
               D365CustomerId = tmRecord.Sales_Order__r.Bill_to_Customer_No__r.Sage_Customer_No__c != null ? tmRecord.Sales_Order__r.Bill_to_Customer_No__r.Sage_Customer_No__c : null;
               SalesforceSiteCsid = (tmRecord.Sales_Order__r.Alternate_Site_Address__r.Id != null ? tmRecord.Sales_Order__r.Alternate_Site_Address__r.Id : null);

            }
            else if(!salesOrderList.isEmpty())
            {
               Sales_Order__c salesOrderRecord = salesOrderList[0];
               SalesforceSiteCsid = (salesOrderRecord.Alternate_Site_Address__r.Id != null ? salesOrderRecord.Alternate_Site_Address__r.Id : null);
           	   D365CustomerId =  salesOrderRecord.Bill_to_Customer_No__r.Sage_Customer_No__c != null ? salesOrderRecord.Bill_to_Customer_No__r.Sage_Customer_No__c : null;
            }
                
            //company_id = 21;
            //profit_ctr_id = 0;
           // D365CustomerId = 'C322006';
            endpoint += 'TsdfCode=' + EncodingUtil.urlEncode(tsdfCode, 'UTF-8');
            endpoint += '&SalesforceSiteCsid=' + SalesforceSiteCsid;
            endpoint += '&D365CustomerId=' + D365CustomerId;
            endpoint += '&CompanyId=' + company_id;
            endpoint += '&ProfitCenterId=' + profit_ctr_id;
            endpoint += '&Description=' + (description != null ? description : '');
            endpoint += '&GeneratorId=' + GeneratorId;
            system.debug('callout:EQAI_Base_URL'+endpoint);
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:EQAI_Base_URL'+endpoint);
            req.setHeader('Content-Type','application/json');
            req.setHeader('x-api-key',CustomerDetails.API_Key__c);
            req.setHeader('x-secret-token',CustomerDetails.API_Token__c);
            req.setMethod('GET');
            req.setTimeout(20000);
            Http http = new Http();
            HTTPResponse res = http.send(req);
            String response = res.getBody();
            logData.serviceRequest = 'ProfileApprovalReq>>' + 'callout:EQAI_Base_URL'+endpoint;
            logData.serviceResponse = 'ProfileApprovalRes>>' + res.getBody();
            ApplicationLog.startLog(JSON.serialize(logData));
            if (res.getStatusCode() == 200) {
                return res;
            } else {
                System.debug('Error in API response: ' + res.getStatusCode() + ' - ' + res.getBody());
                return res;
            }
            
        } catch (Exception e) {
            System.debug('Error in getApprovedProfiles: ' + e.getMessage());
            return null;
        }
    }
}