objects/Account/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Depreciated No longer needed.  Ticket#20704</description>
    <inlineHelpText>Depreciated No longer needed. Ticket#20704</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <formula>Salesperson__r.Salesperson_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesperson Code</label>
    <type>Text</type>
</CustomField>

objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Accounting_Period__c/fields/Fiscal_year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_year__c</fullName>
    <label>Fiscal Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Accounting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Ledger_Entry__c/Customer_Ledger_Entry__c.object-meta.xml
<CustomObject>
    <label>Customer Ledger Entry</label>
    <nameField>
        <label>Entry No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Ledger Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Ledger_Entry__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

objects/Customer_Ledger_Entry__c/fields/Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Date__c</fullName>
    <label>Posting Date</label>
    <type>Date</type>
</CustomField>

objects/Customer_Ledger_Entry__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Customer Ledger Entries</relationshipLabel>
    <relationshipName>Customer_Ledger_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Ledger_Entry__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Customer_Ledger_Entry__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Customer Ledger Entries</relationshipLabel>
    <relationshipName>Customer_Ledger_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Customer_Ledger_Entry__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Customer Ledger Entries</relationshipLabel>
    <relationshipName>Customer_Ledger_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrganizationConfigurations__c/OrganizationConfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Organization Configurations</label>
</CustomObject>

objects/Sales_Order_Type__c/Sales_Order_Type__c.object-meta.xml
<CustomObject>
    <label>Sales Order Type</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesperson__c/fields/Salesperson_Code__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_Code__c</fullName>
    <label>Salesperson Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Salesperson__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountControllerTest.cls
@isTest
public with sharing class AccountControllerTest {
    
    @testSetup static void SetupData() {
        //Setup Data//83014
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c testNumberSeriesRecord = TestDataUtil.NumberingSeriesRecord;
        User testUser = TestDataUtil.UserRecord;
        Account testAccRecord = TestDataUtil.AccountRecord;
        Account testAccRecord3 = TestDataUtil.customerAccountRecord;
        Subsidiary_Company__c testSubsidiaryCompRecord = TestDataUtil.SubsidiaryCompanyRecord;
        Service_Center__c testServiceCenRecord = TestDataUtil.ServiceCenterRecord;
        OrganizationConfigurations__c testOrgConfigRecord = TestDataUtil.OrganizationConfigurationsRecord;
        Salesperson__c testSalesperRecord = TestDataUtil.SalespersonRecord;
        if ([SELECT Id FROM Group WHERE Name = 'Data Admin'].size() == 0) {
        	Group testGroupRecord = TestDataUtil.GroupRecord;
        	GroupMember testGroupMemberRecord = TestDataUtil.GroupMemberRecord;
        }
        List<Accounting_Period__c> testAccountingPerRecords = TestDataUtil.AccountingPeriodRecords;
        Sales_Order_Type__c testSalesOrdtypeRecord = TestDataUtil.SalesOrdertypeRecord;
        List<Customer_Ledger_Entry__c> testCustomerLedgerEntryRecords = TestDataUtil.CustomerLedgerEntryRecords;
    }

    public static testMethod void test() {
		Account testAccRecord = [SELECT Id FROM Account WHERE Name LIKE :'%Cannon%' Limit 1];
        PageReference pageRef = Page.AccountConversion;
        ApexPages.StandardController sc = new ApexPages.standardController(testAccRecord);
        AccountController controller = new AccountController(sc);
                
        test.startTest();
        try {
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('id', testAccRecord.id);
            testAccRecord.Type = 'Customer';
            controller.ConvertToCustomer();
            User theUser = [SELECT Id, FirstName, LastName, Phone, Service_Center__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
            theUser.Service_Center__c='SC01 Elizabeth, NJ Ops';
            update theUser ;
            
        } catch (exception ex) {
        }
        
        Subsidiary_Company__c subsidiaryCompany = [SELECT Id FROM Subsidiary_Company__c Limit 1];
        Service_Center__c serviceCenter = [SELECT Id FROM Service_Center__c Limit 1];
        
        testAccRecord.Type = 'Account';
        testAccRecord.Subsidiary_Company__c = subsidiaryCompany.Id;
        testAccRecord.Service_Center__c = serviceCenter.Id;
        update testAccRecord;        
        sc = new ApexPages.standardController(testAccRecord);
        controller = new AccountController(sc);
        
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id', testAccRecord.id);
        controller.ValidateServiceCenter();
        controller.SalesOrderTypeId =TestDataUtil.SalesOrdertypeRecord.id;
        controller.ownerId = UserInfo.getUserId();
        controller.CreateSO();

        controller.CreateSQ();       
        controller.CreateMiscCreditMemo();
        controller.SetSalesOrderType();
        controller.getMessages();
        System.debug('Info: ' + controller.getMessages());
        controller.returnBack();

        controller.getItems();
        controller.setSurchargeType('E&I Surcharge');
        test.stopTest();     
    }
    
    private static testMethod void testRollup() {
        Subsidiary_Company__c subsidiaryCompany = [Select Id From Subsidiary_Company__c Limit 1];
        Service_Center__c serviceCenter = [Select Id From Service_Center__c Limit 1];

        Accounting_Period__c testAccPer = [SELECT Id, Start_Date__c, End_Date__c FROM Accounting_Period__c LIMIT 1];
        testAccPer.Start_Date__c = System.today() -1;
        testAccPer.End_Date__c = System.today() +1;
        testAccPer.Fiscal_year__c = System.today().year();
        update testAccPer; 
        
        Salesperson__c testSalesperson = [SELECT Id, Name,Salesperson_Code__c, Status__c FROM Salesperson__c];
        testSalesperson.Name = 'Smith'; 
        testSalesperson.Salesperson_Code__c = 'S001'; 
        testSalesperson.Status__c='Active';
        update testSalesperson;
        
        List<Customer_Ledger_Entry__c> customerLedgerEntries = [SELECT Id, Due_Date__c, Posting_Date__c FROM Customer_Ledger_Entry__c];
        for(Customer_Ledger_Entry__c customerLedgerEntry : customerLedgerEntries) {
            customerLedgerEntry.Due_Date__c = System.today();
            customerLedgerEntry.Posting_Date__c = System.today();
        }
        update customerLedgerEntries;
        
        Test.startTest();        
        Database.executeBatch(new RollupCustomerARBatchable());  
        Database.executeBatch(new RollupCustomerRevenueBatchable());
        Database.executeBatch(new RollupCorporateARBatchable());
        Database.executeBatch(new RollupCustomerRevenueBatch());
        Test.stopTest();
    }

    static testMethod void testValidateField(){
		Subsidiary_Company__c subsidiaryCompany = [Select Id From Subsidiary_Company__c Limit 1];
        Service_Center__c serviceCenter = [Select Id From Service_Center__c Limit 1];
		Salesperson__c testSalesperson = [SELECT Id FROM Salesperson__c];
		Subsidiary_Company__c testComp = [SELECT Id FROM Subsidiary_Company__c];
        Sales_Order_Type__c testSalOrdType = [SELECT Id FROM Sales_Order_Type__c Limit 1];

        Account testAcc = [SELECT Id FROM Account WHERE Type = 'Customer' Limit 1];
        PageReference pref = Page.CreateSQFromAccountConfirmation;
        PageReference pageRef = Page.AccountConversion;

        ApexPages.StandardController sc = new ApexPages.standardController(testAcc);
        AccountController controller = new AccountController(sc);
        Test.startTest();

        Test.setCurrentPage(pref);
        pref.getParameters().put('id', testAcc.id);

        pref.getParameters().put('fieldName', 'targetNameWH');
        pref.getParameters().put('newFieldValue','awefawe');
        controller.validateField();
        pref.getParameters().put('fieldName', 'ja;efj');
        pref.getParameters().put('newFieldValue','awefawe');
        controller.validateField();
        pref.getParameters().put('fieldName', 'targetNameWH');
        pref.getParameters().put('newFieldValue',testSalOrdType.Id);
        controller.validateField();
        
        pref.getParameters().put('fieldName', 'targetOwner');
        pref.getParameters().put('newFieldValue', 'awefa');
        controller.validateField();

        Test.setCurrentPage(pageRef);
        pref.getParameters().put('id', testAcc.id);
        testAcc.Type = 'Customer';
        controller.ConvertToCustomer();
        Test.stopTest();

    }
    //test
}