objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Numbering_Series__c/Numbering_Series__c.object-meta.xml
<CustomObject>
    <label>Numbering Series</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Numbering Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Order No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Purchase_Order__c/fields/Buy_from_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Buy_from_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Buy-from Vendor)</relationshipLabel>
    <relationshipName>Purchase_Orders_BF</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Coupa_Id__c.field-meta.xml
<CustomField>
    <fullName>Coupa_Id__c</fullName>
    <externalId>true</externalId>
    <label>Coupa Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Purchase_Order__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Purchase_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Approval Routing</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>CapEx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Purchase_Order__c/fields/Pay_to_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Pay_to_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay-to Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/PO_Requestor__c.field-meta.xml
<CustomField>
    <fullName>PO_Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Purchase_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Vendor__c/Subsidiary_Vendor__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Vendor</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subsidiary_Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_and_Vendor_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Subsidiary_Vendor__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Subsidiary_Vendor__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Center__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Subsidiary Vendors</relationshipLabel>
    <relationshipName>Subsidiary_Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Vendor__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Account_and_Vendor_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CmpApprovalURLTest.cls
/**
 * Created by Steven on 5/4/2018.
 */

@IsTest
private class CmpApprovalURLTest {
    @IsTest
    static void testBehavior() {

        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Numbering_Series__c NumberingSeries = TestDataUtil.NumberingSeriesRecord;

        Subsidiary_Company__c subCompany = new Subsidiary_Company__c(Name = 'ACV Test');
        insert subCompany;

        Account ac = new Account( Name = 'MDN',
                        Type = 'Vendor',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId()
        );
        insert ac;
        System.debug('ac==>'+ac);
        /*
        Service_Center__c sc = new Service_Center__c(
                Name = '01',
                Subsidiary_Company__c = subCompany.Id,
                Code__c = '01'
        );
        insert sc;
        */
        Subsidiary_Vendor__c subVend = new Subsidiary_Vendor__c(Name = 'ACV0001', Subsidiary_Company__c = subCompany.Id, Account__c = ac.Id);
        insert subVend;
        Purchase_Order__c thePO;
        System.debug('ac==>'+ac.RecordTypeId);
        String reordtye=[Select Recordtype.Name from Account where Id=:ac.id].Recordtype.Name;
        System.debug('reordtye==>'+reordtye);
        try{
            thePO = new Purchase_Order__c(
                Name = '01-00000001',
                Buy_from_Vendor__c = ac.Id,
                Pay_to_Vendor__c = ac.Id,
                Service_Center__c = TestDataUtil.ServiceCenterRecord.Id,
                OwnerId = UserInfo.getUserId(),
                PO_Requestor__c = UserInfo.getUserId(),
                Order_Type__c = 'Regular',
                Note__c = 'Test PO',
                Coupa_Id__c = '1123'
            );
            insert thePO;
        } catch (Exception e){

        }

        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval');
        req1.setObjectId(thePO.Id);
        req1.setProcessDefinitionNameOrId('SC15_REG');
        req1.setSkipEntryCriteria(true);
        req1.setNextApproverIds(new Id[] {UserInfo.getUserId()});

        Approval.ProcessResult result = Approval.process(req1);

        System.assert(result.isSuccess());

        System.assertEquals(
                'Pending', result.getInstanceStatus(),
                'Instance Status' + result.getInstanceStatus());

        List<Id> newWorkItemIds = result.getNewWorkitemIds();

        CmpApprovalURL appURL = new CmpApprovalURL();
        appURL.recId = thePO.Id;

        String hostStr = System.URL.getSalesforceBaseUrl().getHost();
        String url = '';
        List<String> strList = hostStr.split('\\.');
        if(strList.size() > 0) {
            String customDomain = hostStr.split('\\.')[0];
            if (customDomain.endsWith('--c')) {
                customDomain = customDomain.removeEnd('--c');
            }
            url = 'https://' + customDomain + '.lightning.force.com/lightning/r/ProcessInstanceWorkitem/' + newWorkItemIds[0] + '/view';
        }

        System.assertEquals(appURL.urlStr, url);

    }
}