objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountCreateSQSOControllerTest.cls
@IsTest
private class AccountCreateSQSOControllerTest {

    @IsTest
    private static void test(){
        //Create Mock
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IAccountsSelector selectorAccountMock = new Mocks.AccountsSelector(mocks);
        IContractsSelector selectorContractMock = new Mocks.ContractsSelector(mocks);
        IUsersSelector selectorUserMock = new Mocks.UsersSelector(mocks);
        ISalesOrdersSelector selectorSOMock = new Mocks.SalesOrdersSelector(mocks);

        mocks.startStubbing();
        Account parentAcct = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType)
        );
        Account acct = new Account(
                Id = fflib_IDGenerator.generate(Account.SObjectType),
                ParentId = parentAcct.Id
        );

        Id contractId = fflib_IDGenerator.generate(Contract.SObjectType);
        String jsonStr = '{"Id" : "' + contractId + '", "Name" : "Test Contract", "ContractNumber" : "998"}';
        Contract contra = (Contract) JSON.deserialize(jsonStr, Contract.class);
        User u = new User(
                Service_Center__c = fflib_IDGenerator.generate(Service_Center__c.SObjectType)
        );
        Sales_Order__c  theSO = new Sales_Order__c(
                Id = fflib_IDGenerator.generate(Sales_Order__c.SObjectType),
                Name = 'test sales order'
        );
        ApexPages.StandardController standardController = new ApexPages.StandardController(acct);
        mocks.when(selectorAccountMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(selectorContractMock.sObjectType()).thenReturn(Contract.SObjectType);
        mocks.when(selectorUserMock.sObjectType()).thenReturn(User.SObjectType);
        mocks.when(selectorSOMock.sObjectType()).thenReturn(Sales_Order__c.SObjectType);
        mocks.when(selectorAccountMock.selectParentAccountById(new Set<Id>{acct.Id})).thenReturn(new List<Account>{acct});
        mocks.when(selectorContractMock.selectByAccountId(new Set<Id>{acct.Id, parentAcct.Id})).thenReturnMulti(new List<List<Contract>>{new List<Contract>{contra}, new List<Contract>()});
        mocks.when(selectorSOMock.selectQuotesByBillToCustomer(acct.Id)).thenReturn(new List<Sales_Order__c>{theSO});
        mocks.when(selectorUserMock.selectById(new Set<Id>{UserInfo.getUserId()})).thenReturn(new List<User>{u});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorAccountMock);
        Application.Selector.setMock(selectorContractMock);
        Application.Selector.setMock(selectorUserMock);
        Application.Selector.setMock(selectorSOMock);

        AccountCreateSalesQuoteOrOrderController controller = new AccountCreateSalesQuoteOrOrderController(standardController);
        controller.checkAccountContractBeforeRenderPage();
        AccountCreateSalesQuoteOrOrderController controller2 = new AccountCreateSalesQuoteOrOrderController(standardController);
        controller2.checkAccountContractBeforeRenderPage();
    }

}