objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subsidiary_Vendor__c/Subsidiary_Vendor__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Vendor</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Vendors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Subsidiary_Vendor__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Center__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Subsidiary Vendors</relationshipLabel>
    <relationshipName>Subsidiary_Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Vendor__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Account_and_Vendor_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/Vendor_Ledger_Entry__c.object-meta.xml
<CustomObject>
    <label>Vendor Ledger Entry</label>
    <nameField>
        <label>Vendor Ledger Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Ledger Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vendor_Ledger_Entry__c/fields/Amount_LCY__c.field-meta.xml
<CustomField>
    <fullName>Amount_LCY__c</fullName>
    <label>Amount ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/Document_No__c.field-meta.xml
<CustomField>
    <fullName>Document_No__c</fullName>
    <label>Document No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/NAV_Vendor_No__c.field-meta.xml
<CustomField>
    <fullName>NAV_Vendor_No__c</fullName>
    <label>NAV Vendor No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/Purchase_LCY__c.field-meta.xml
<CustomField>
    <fullName>Purchase_LCY__c</fullName>
    <label>Purchase ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Vendor Ledger Entries</relationshipLabel>
    <relationshipName>Vendor_Ledger_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Vendor Ledger Entries</relationshipLabel>
    <relationshipName>Vendor_Ledger_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Vendor_Ledger_Entry__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Ledger Entries</relationshipLabel>
    <relationshipName>Vendor_Ledger_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/RollupVendorAPBatchableTest.cls
@IsTest
private class RollupVendorAPBatchableTest {
    @IsTest
    static void testBehavior() {
        Company_Setup__c companySetup = TestDataUtil.CompanySetupRecord;
        Subsidiary_Vendor__c subsidiaryVendor = TestDataUtil.SubsidiaryRecord;
        Subsidiary_Company__c subsidiaryCompany = TestDataUtil.SubsidiaryCompanyRecord;
        Account vendor = TestDataUtil.VendorAccount;
        Service_Center__c serviceCenter = TestDataUtil.ServiceCenterRecord;
        Vendor_Ledger_Entry__c vendorLedgerEntry = new Vendor_Ledger_Entry__c();
        vendorLedgerEntry.Subsidiary_Company__c = subsidiaryCompany.Id;
        vendorLedgerEntry.Vendor__c = vendor.Id;
        vendorLedgerEntry.Name = '1';
        vendorLedgerEntry.Service_Center__c = serviceCenter.Id;
        vendorLedgerEntry.Document_Type__c = 'Sales Invoice';
        vendorLedgerEntry.Document_No__c = 'SI-00001';
        vendorLedgerEntry.Posting_Date__c = Date.today();
        vendorLedgerEntry.Due_Date__c = Date.today();
        vendorLedgerEntry.Amount__c = 1000;
        vendorLedgerEntry.Amount_LCY__c = 1000;
        vendorLedgerEntry.Purchase_LCY__c = 1000;
        vendorLedgerEntry.NAV_Vendor_No__c = subsidiaryVendor.Name;
        insert vendorLedgerEntry;
    }
}