objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Company_Setup__c/Company_Setup__c.object-meta.xml
<CustomObject>
    <label>Company Setup</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Setup__c/fields/Default_Lump_Sum_Resource__c.field-meta.xml
<CustomField>
    <fullName>Default_Lump_Sum_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Bundled Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Company Setup (Default_Lump_Sum_Resource)</relationshipLabel>
    <relationshipName>Company_Setup_LS</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ResourceCategory</valueSetName>
    </valueSet>
</CustomField>

objects/Resource__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Billing Package</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Invoice__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Invoice__c/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Invoices (Bill-to Customer)</relationshipLabel>
    <relationshipName>Sales_Invoices1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Memo</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/Sales_Invoice__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Sent to EQAI</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Invoice__c/fields/Misc_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Misc_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Misc. Invoice</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice__c/fields/Reversed_from_SI__c.field-meta.xml
<CustomField>
    <fullName>Reversed_from_SI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed from SI</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Job_Task__c/Sales_Invoice_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoice Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Job_Task__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Sales Invoice Job Tasks</relationshipLabel>
    <relationshipName>Sales_Invoice_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/Sales_Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Line</label>
    <nameField>
        <displayFormat>SIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Invoice_Line__c/fields/Print_Line__c.field-meta.xml
<CustomField>
    <fullName>Print_Line__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Print Line</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Billing Package Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Sales_Invoice_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Invoice__c</field>
            <operation>equals</operation>
            <valueField>Sales_Invoice_Job_Task__c.Sales_Invoice__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Invoice_Line__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Sales Invoice Lines</relationshipLabel>
    <relationshipName>Sales_Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/User/fields/Super_User__c.field-meta.xml
<CustomField>
    <fullName>Super_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Super User</label>
    <type>Checkbox</type>
</CustomField>

globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Pending_Approval</fullName>
        <label>Pending Approval</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

globalValueSets/ResourceCategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Subcontractors</fullName>
        <label>Cost Plus Materials, Equipment and Services</label>
    </customValue>
    <customValue>
        <fullName>Waste Disposal</fullName>
    </customValue>
    <customValue>
        <fullName>Demurrage</fullName>
        <label>Transportation, Demurrage and Fees</label>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Misc. Charges And Taxes</fullName>
    </customValue>
    <customValue>
        <fullName>Field Remediation</fullName>
        <isActive>false</isActive>
        <label>Field Remediation</label>
    </customValue>
    <masterLabel>ResourceCategory</masterLabel>
</GlobalValueSet>

classes/ACVSalesInvoiceController.cls
public with sharing class ACVSalesInvoiceController {


    @AuraEnabled
    public static String testStackCall() {
        return String.valueOf(Datetime.now());
    }

    @AuraEnabled
    public static String getSetupData() {
        try {
            SalesInvoiceSetupData setupData = new SalesInvoiceSetupData();
            User user = [SELECT Id, Name, Username, Super_User__c, Service_Center__c, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
            setupData.CompanySetup = CompanyMgmt.getCompanySetup();
            setupData.User = user;

            return JSON.serialize(setupData);
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String getSalesInvoice(Id salesInvoiceId) {
        try {
            Set<Id> salesInvoiceIds = new Set<Id>{ salesInvoiceId };
            List<Sales_Invoice__c> salesInvoices = SalesInvoicesSelector.newInstance().selectById(salesInvoiceIds);
            List<Sales_Invoice_Job_Task__c> salesInvoiceJobTasks = SalesInvoiceJobTasksSelector.newInstance().selectBySalesInvoiceId(salesInvoiceIds);
            List<Sales_Invoice_Line__c> salesInvoiceLines = SalesInvoiceLinesSelector.newInstance().selectByInvoiceId(salesInvoiceId);

            ACVSalesInvoiceWrapper salesInvoiceWrapper = new ACVSalesInvoiceWrapper(salesInvoices[0], salesInvoiceJobTasks, salesInvoiceLines);
            return JSON.serialize(salesInvoiceWrapper);
        }
        catch(Exception ex) {
            System.debug('Error: ' + ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void saveSalesInvoice(String JSONSalesInvoice, String JSONJobTaskWrappers) {
        try {
            Sales_Invoice__c salesInvoice = (Sales_Invoice__c)JSON.deserialize(JSONSalesInvoice, Sales_Invoice__c.class);
            List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers = (List<ACVSalesInvoiceJobTaskWrapper>)JSON.deserialize(JSONJobTaskWrappers, List<ACVSalesInvoiceJobTaskWrapper>.class);
            saveSalesInvoice(salesInvoice, jobTaskWrappers);
        }
        catch(Exception ex) {
                        system.debug('ex'+ex.getMessage());
		String errorMessage = ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')? ex.getMessage().substring( ex.getMessage().indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION,') + 'FIELD_CUSTOM_VALIDATION_EXCEPTION,'.length()): ex.getMessage();
		throw new AuraHandledException(errorMessage);        }
    }

    @AuraEnabled
    public static void postSalesInvoice(String JSONSalesInvoice, String JSONJobTaskWrappers) {
        try {
            Sales_Invoice__c salesInvoice = (Sales_Invoice__c)JSON.deserialize(JSONSalesInvoice, Sales_Invoice__c.class);
            List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers = (List<ACVSalesInvoiceJobTaskWrapper>)JSON.deserialize(JSONJobTaskWrappers, List<ACVSalesInvoiceJobTaskWrapper>.class);

            saveSalesInvoice(salesInvoice, jobTaskWrappers);

        }
        catch(Exception ex) {
            throw new DataException(ex.getMessage());
        }
    }

    private static void saveSalesInvoice(Sales_Invoice__c salesInvoice, List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers) {
        Company_Setup__c defaultCompanySetup = CompanySettingUtil.defaultCompanySetup;
        if(salesInvoice.Misc_Invoice__c == true) {
            CompanyMgmt.systemCall = true;
        }
        Savepoint sp = Database.setSavepoint();
        try {

            //Ticket#22853 >>
            if(salesInvoice.Id != null){
                List<Sales_Invoice__c> salesInvoices = [SELECT Id, Document_Status__c, LastModifiedDate FROM Sales_Invoice__c WHERE Id = :salesInvoice.Id];
                if(salesInvoices.size() > 0 && salesInvoices[0].Document_Status__c != salesInvoice.Document_Status__c){
                    throw new DataException('There is a newer version of the invoice in the database.  Please refresh the page to retrieve the updated invoice record!');
                }

                if(salesInvoice.LastModifiedDate < salesInvoices[0].LastModifiedDate) {
                    throw new DataException('Sales Invoice have been modified after you retrieved the data. Please refresh page and try again.');
                }

                Map<Id, Datetime> invoiceLineModifiedDatesByIds = new Map<Id, Datetime>();
                for (ACVSalesInvoiceJobTaskWrapper jobTaskWrapper : jobTaskWrappers) {
                    for (Sales_Invoice_Line__c salesInvoiceLine : jobTaskWrapper.SalesInvoiceLines) {
                        invoiceLineModifiedDatesByIds.put(salesInvoice.Id, salesInvoiceLine.LastModifiedDate);
                    }
                }
                List<Sales_Invoice_Line__c> existingInvoiceLines = [SELECT Id, LastModifiedDate FROM Sales_Invoice_Line__c WHERE Id IN :invoiceLineModifiedDatesByIds.keySet()];
                for(Sales_Invoice_Line__c salesInvoiceLine : existingInvoiceLines){
                    if(invoiceLineModifiedDatesByIds.containsKey(salesInvoiceLine.Id) &&
                            invoiceLineModifiedDatesByIds.get(salesInvoiceLine.Id) < salesInvoiceLine.LastModifiedDate){
                        throw new DataException('Sales Invoice lines have been modified after you retrieved the data. Please refresh page and try again.');
                    }
                }
            }
            //Ticket#22853 <<

            if (salesInvoice.Document_Status__c == 'Posted') {
                //Save Invoice header information after document is posted.
                //AR Collection purpose fields: SPO No. Expected Payment Date and Corrected Customer PO No.
                update salesInvoice;

                //ticket 19631 <<
                List<Sales_Invoice_Line__c> salesInvoiceLinesToUpdate = new List<Sales_Invoice_Line__c>();
                for (ACVSalesInvoiceJobTaskWrapper jobTaskWrapper : jobTaskWrappers) {
                    for (Sales_Invoice_Line__c salesInvoiceLine : jobTaskWrapper.SalesInvoiceLines) {
                        Sales_Invoice_Line__c salesInvoiceLineToUpdate = new Sales_Invoice_Line__c();
                        salesInvoiceLineToUpdate.Id = salesInvoiceLine.Id;
                        salesInvoiceLineToUpdate.Print_Line__c = salesInvoiceLine.Print_Line__c;
                        salesInvoiceLinesToUpdate.add(salesInvoiceLineToUpdate);
                    }
                }
                CompanyMgmt.byPassTrigger = true;
                update salesInvoiceLinesToUpdate;
                //ticket 19631 >>
            } else {

                //Ticket#20293 >>
                if(salesInvoice.Id != null) {
                    List<Sales_Invoice__c> salesInvoices = [SELECT Id, Document_Status__c FROM Sales_Invoice__c WHERE Id = :salesInvoice.Id];
                    if(salesInvoices.size() > 0 && salesInvoices[0].Document_Status__c != salesInvoice.Document_Status__c){
                        throw new DataException('There is a newer version of the invoice in the database.  Please refresh the page to retrieve the updated invoice record!');
                    }
                }
                //Ticket#20293 <<

                //Credit Memo created from Sales Order AKA Partial credit memo
                if (salesInvoice.Credit_Memo__c == true && salesInvoice.Misc_Invoice__c == true) {
                    if (String.isBlank(salesInvoice.Reversed_from_SI__c)) {
                        throw new DataException('Applies-to Invoice No. must not be blank for partial invoice!');
                    }
                }

                if (String.isNotBlank(salesInvoice.Bill_to_Customer__c)) {
                    List<Account> billToCusts = AccountsSelector.newInstance().selectById(new Set<Id>{
                            salesInvoice.Bill_to_Customer__c
                    });
                    if (billToCusts.size() > 0) {
                        if (String.isNotBlank(salesInvoice.Customer_PO_No__c)) {
                            AccountsService.validatePONumberFormat(billToCusts[0], salesInvoice.Customer_PO_No__c);
                        }
                    }
                }

                if (salesInvoice.Approval_Status__c == EnumUtil.ApprovalStatus.PENDING_APPROVAL.name()) {
                    throw new DataException('Invoice record cannot be modify, it is pending for approval!');
                }

                update salesInvoice;

                List<Sales_Invoice_Job_Task__c> salesInvoiceJobTasks = new List<Sales_Invoice_Job_Task__c>();
                List<Sales_Invoice_Line__c> salesInvoiceLines = new List<Sales_Invoice_Line__c>();

                //handle removed lines
                Set<Id> salesInvoiceLineIds = new Set<Id>();
                for (Sales_Invoice_Line__c salesInvoiceLine : [SELECT Id FROM Sales_Invoice_Line__c WHERE Sales_Invoice__c = :salesInvoice.Id]) {
                    salesInvoiceLineIds.add(salesInvoiceLine.Id);
                }

                for (ACVSalesInvoiceJobTaskWrapper jobTaskWrapper : jobTaskWrappers) {
                    for (Sales_Invoice_Line__c salesInvoiceLine : jobTaskWrapper.SalesInvoiceLines) {
                        if (salesInvoiceLine.Sales_Invoice_Job_Task__c == null) {
                            throw new DataException('Sales lines must be associated with a job task.');
                        }
                        if (salesInvoiceLine.Id != null && salesInvoiceLineIds.contains(salesInvoiceLine.Id)) {
                            salesInvoiceLineIds.remove(salesInvoiceLine.Id);
                        }
                    }
                }

                if (salesInvoiceLineIds.size() > 0) {
                    delete [SELECT Id FROM Sales_Invoice_Line__c WHERE Id IN :salesInvoiceLineIds];
                }

                for (ACVSalesInvoiceJobTaskWrapper jobTaskWrapper : jobTaskWrappers) {
                    salesInvoiceJobTasks.add(jobTaskWrapper.JobTask);
                    for (Sales_Invoice_Line__c salesInvoiceLine : jobTaskWrapper.SalesInvoiceLines) {
                        //assign default resource to lump sum line if line's resource is blank
                        if(salesInvoiceLine.Category__c == ResourceService.LUMP_SUM_CATEGORY && String.isBlank(salesInvoiceLine.Resource__c)){
                            salesInvoiceLine.Resource__c = defaultCompanySetup.Default_Lump_Sum_Resource__c;
                        }

                        if(salesInvoiceLine.Category__c == ResourceService.SUBCONTRACTORS_CATEGORY && String.isBlank(salesInvoiceLine.Resource__c)){
                            salesInvoiceLine.Resource__c = defaultCompanySetup.Default_Subcontractor_Resource__c;
                        }
                        
                        salesInvoiceLines.add(salesInvoiceLine);
                    }
                }

                update salesInvoiceJobTasks;
                upsert salesInvoiceLines;

                if (salesInvoice.Misc_Invoice__c == true) {
                    Decimal appliedToBalance = 0;
                    Decimal creditAmountInclTax = 0;
                    List<Sales_Invoice__c> appliesToInvoices = new List<Sales_Invoice__c>();
                    if (String.isNotBlank(salesInvoice.Reversed_from_SI__c)) {
                        appliesToInvoices = [SELECT Id, Name, Balance__c FROM Sales_Invoice__c WHERE Id = :salesInvoice.Reversed_from_SI__c];
                        if (appliesToInvoices.size() > 0) {
                            appliedToBalance = appliesToInvoices[0].Balance__c;

                            for (Sales_Invoice_Line__c salesInvoiceLine : salesInvoiceLines) {
                                creditAmountInclTax = creditAmountInclTax + CompanyMgmt.zeroIfNull(salesInvoiceLine.Line_Amt_Incl_Tax__c);
                            }

                            creditAmountInclTax = Math.abs(creditAmountInclTax);
                            if (creditAmountInclTax > appliedToBalance) {
                                String message = 'Credit Memo amount: ' + creditAmountInclTax + ' is larger than remaining balance ' + appliedToBalance + ' on applies-to invoice# ' + appliesToInvoices[0].Name;
                                throw new DataException(message);
                            }
                        }
                    }
                }
            }
        } catch(Exception ex) {
            Database.rollback(sp);
            throw ex;
        }
    }

    @AuraEnabled
    public static String validateAppliesToDoc(String JSONSalesInvoice, String JSONJobTaskWrappers){
        try {
            Sales_Invoice__c salesInvoice = (Sales_Invoice__c)JSON.deserialize(JSONSalesInvoice, Sales_Invoice__c.class);
            List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers = (List<ACVSalesInvoiceJobTaskWrapper>)JSON.deserialize(JSONJobTaskWrappers, List<ACVSalesInvoiceJobTaskWrapper>.class);

            if(salesInvoice.Credit_Memo_Reason_Code__c == 'Customer is tax exempt') {
                String appliedToDocId = salesInvoice.Reversed_from_SI__c;
                List<Sales_Invoice__c> salesInvoices = [SELECT Id, Tax_Area__c, Invoice_Tax__c FROM Sales_Invoice__c WHERE Id = :appliedToDocId];
                if (salesInvoices.size() == 0) {
                    throw new DataException('The applies-to invoice is not found.');
                }

                Sales_Invoice__c appliesToInvoice = salesInvoices[0];
                SalesInvoicesService.reverseTaxAmount(appliesToInvoice, salesInvoice, jobTaskWrappers);
            }

            return JSON.serialize(jobTaskWrappers);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String validatePaymentTerm(String JSONSalesInvoice){
        try {
            Sales_Invoice__c salesInvoice = (Sales_Invoice__c)JSON.deserialize(JSONSalesInvoice, Sales_Invoice__c.class);
            SalesInvoicesService.validatePaymentTerm(salesInvoice);
            return JSON.serialize(salesInvoice);
        } catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static String calculateSalesInvoice(String JSONSalesInvoice, String JSONJobTaskWrappers) {
        try {
            Sales_Invoice__c salesInvoice = (Sales_Invoice__c)JSON.deserialize(JSONSalesInvoice, Sales_Invoice__c.class);
            List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers = (List<ACVSalesInvoiceJobTaskWrapper>)JSON.deserialize(JSONJobTaskWrappers, List<ACVSalesInvoiceJobTaskWrapper>.class);

            SalesInvoiceLinesService.calculateLineTotals(salesInvoice, jobTaskWrappers);
            return JSON.serialize(jobTaskWrappers);
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    private static void calculateSalesInvoice(Sales_Invoice__c salesInvoice, List<ACVSalesInvoiceJobTaskWrapper> jobTaskWrappers) {
        SalesInvoiceLinesService.calculateLineTotals(salesInvoice, jobTaskWrappers);
    }
}