objects/Account/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Order_Description__c.field-meta.xml
<CustomField>
    <fullName>Order_Description__c</fullName>
    <label>Order Description</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Service_Center__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Service_Center__c/Service_Center__c.object-meta.xml
<CustomObject>
    <label>Service Center</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Center__c/fields/Subsidiary_Company__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Subsidiary Company</label>
    <referenceTo>Subsidiary_Company__c</referenceTo>
    <relationshipLabel>Service Centers</relationshipLabel>
    <relationshipName>Service_Centers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Subsidiary_Company__c/Subsidiary_Company__c.object-meta.xml
<CustomObject>
    <label>Subsidiary Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subsidiary Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User/fields/Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Service_Center__c</fullName>
    <label>Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>SC02 Republic Services – Clayton</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>SC04 Republic Services – Baltimore</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>SC07 Republic Services – Norfolk</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>SC15 Republic Services – Avenel</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>SC16 Republic Services – Skowhegan</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>SC17 Republic Services – Middletown New York</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>SC19 Republic Services – Windsor Locks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>SC20 Republic Services - Nashua</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>SC21 Republic Services – Bridgeport</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>SC22 Republic Services – Griffith</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>SC24 Republic Services – Pulaski</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>SC25 Republic Services – Lewisberry</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>SC27 Republic Services – Albany</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>SC28 Republic Services - Essex Junction</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>SC29 Republic Services - Hopewell Junction</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>SC30 Republic Services - Imperial</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>SC31 Republic Services – Rahway</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>SC32 Republic Services – Brooklyn</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>SC33 Republic Services – Aston</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>SC40 Republic Services -Rensselaer</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>SC41 Republic Services - Hydro, PA and NJ</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>SC64 Republic Services – Greensboro</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>SC65 Republic Services – Lexington</label>
            </value>
            <value>
                <fullName>66</fullName>
                <label>SC66 Republic Services – Americus</label>
            </value>
            <value>
                <fullName>73</fullName>
                <label>SC73 Republic Services - Metro Lab Pack</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>SC74 Republic Services - Baltimore Lab Pack</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>SC75 Republic Services - Pennsylvania Lab Pack</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>SC77 Republic Services – Woonsocket Lab Pack</label>
            </value>
            <value>
                <fullName>96</fullName>
                <label>SC96 Republic Services - National Services</label>
            </value>
            <value>
                <fullName>98</fullName>
                <label>SC98 Republic Services - ER Events</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountCreateSalesQuoteOrOrderController.cls
/**
 * Controller shared by Create Sales Quote and Create Sales Order Custom Buttons (and related pages) on the Account
 */
public with sharing class AccountCreateSalesQuoteOrOrderController {

    private ApexPages.StandardController standardController = null;

    private ApexPages.StandardSetController standardSetController = null;

    public Account account {get; set;}

    public User user {get; set;}

    public List<SelectOption> contractOptions {get; set;}

    public String chosenContract {get; set;}

    public List<SelectOption> quoteOptions {get; set;}

    public String chosenQuote {get; set;}

    public Boolean isPlain {get;set;}

    public Boolean isAllowedToCreateSalesRecord{get; set;}

    public AccountCreateSalesQuoteOrOrderController(ApexPages.StandardController controller){
        standardController = controller;
        contractOptions = new List<SelectOption>();
        quoteOptions = new List<SelectOption>();
        initAccount();
        initUser();
        isPlain = true;
        isAllowedToCreateSalesRecord = true;
    }

    public AccountCreateSalesQuoteOrOrderController(ApexPages.StandardSetController controller) {
        standardSetController = controller;
    }

    public PageReference redirectToSalesOrderPage() {
        try {
            PageReference pageReference = Page.SalesOrder;
            pageReference.getParameters().put('billToCustomer', account.Id);
            pageReference.getParameters().put('serviceCenter', user.Service_Center__c);
            pageReference.getParameters().put('contract', chosenContract);
            pageReference.getParameters().put('quote', chosenQuote);
            if (CompanyMgmt.getVFPageName() == 'AccountCreateSalesQuote') {
                pageReference.getParameters().put('documentType', 'Sales Quote');
            } else {
                pageReference.getParameters().put('documentType', 'Sales Order');
            }
            return pageReference;
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }

    public void initAccount(){
        List<Account> accounts = AccountsSelector.newInstance().selectParentAccountById(new Set<Id>{ ((Account)standardController.getRecord()).Id});
        account = accounts[0];
        Set<Id> accountIds = new Set<Id>();
        accountIds.add(account.Id);
        if (String.isNotEmpty(account.ParentId)) accountIds.add(account.ParentId);
        List<Contract> contracts = ContractsSelector.newInstance().selectByAccountId(accountIds);
        if (contracts.size() > 0){
            for (Contract contract : contracts) {
                contractOptions.add(new SelectOption(contract.Id, contract.Name + ' - ' + contract.ContractNumber));
            }
        }
        if (CompanyMgmt.getVFPageName() == 'AccountCreateSalesOrder' || Test.isRunningTest()){
            List<Sales_Order__c> salesQuotes = SalesOrdersSelector.newInstance().selectQuotesByBillToCustomer(account.Id);
            if (salesQuotes.size() > 0){
                for (Sales_Order__c so : salesQuotes){
                    quoteOptions.add(new SelectOption(so.Id, so.Order_Description__c + ' - ' + so.Name));
                }
            }
        }
    }

    public void initUser(){
        List<User> users = UsersSelector.newInstance().selectById(new Set<Id>{UserInfo.getUserId()});
        user = users[0];
    }

    public PageReference checkAccountContractBeforeRenderPage(){
        String docType = '';
        if (CompanyMgmt.getVFPageName() == 'AccountCreateSalesQuote') docType = 'Sales Quote';
        else docType = 'Sales Order';

        if(account.Subsidiary_Company__r.Name != '1-ACV ENVIRO'){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                    String.format('You can only create {0} from ACV Enviro customer!', new String[]{docType})));
            isAllowedToCreateSalesRecord = false;
            return null;
        }
        if (CompanyMgmt.getVFPageName() == 'AccountCreateSalesOrder'){
            if (contractOptions.size() == 0 && quoteOptions.size() == 0) return redirectToSalesOrderPage();
        } else {
            if (contractOptions.size() == 0 ) return redirectToSalesOrderPage();
        }
        return null;
    }
}