objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

objects/OrganizationConfigurations__c/OrganizationConfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Organization Configurations</label>
</CustomObject>

objects/OrganizationConfigurations__c/fields/Data_Admin_Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Data_Admin_Public_Group__c</fullName>
    <label>Data Admin Public Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

classes/RollupCorporateARBatchable.cls
global class RollupCorporateARBatchable implements Database.Batchable<Account> {
    global List<Account> start(Database.BatchableContext bc) {
        return [SELECT Id FROM Account WHERE Type = 'Corporate'];
    }

    global void execute(Database.BatchableContext bc, list<Account> accts) {
        List<Id> acctIds = new List<Id>();
        for (Account acct : accts) {
            acctIds.add(acct.Id);
        }
        try {
            AccountController.RollupCorporateAR(acctIds);
        }
        catch(exception ex) {
            OrganizationConfigurations__c config = OrganizationConfigurations__c.getOrgDefaults();
            Helper.EmailGroupUsers(config.Data_Admin_Public_Group__c, 'Corporate AR Rollup Error ' + System.today(), ex.getMessage());
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}