objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Bill_to_Customer__c/Bill_to_Customer__c.object-meta.xml
<CustomObject>
    <label>Bill-to Customer xx</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill-to Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Bill_to_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Bill_to_Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Bill_to_Customer__c/fields/Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_No__c</fullName>
    <externalId>true</externalId>
    <label>Customer No.</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/User/fields/Allow_Deleting_Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Allow_Deleting_Bill_to_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Deleting Bill-to Customer</label>
    <type>Checkbox</type>
</CustomField>

classes/BillToCustomerTriggerTest.cls
@isTest
public class BillToCustomerTriggerTest {
    public testMethod static void test() {
        Account acct = new Account(Name = 'account');
        insert acct;
        
        Bill_to_Customer__c cust = new Bill_to_Customer__c(Name = 'Test', Account__c = acct.Id, Customer_No__c = '00-000001');
        insert cust;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];        
        User u = new User(Alias = 'user', Email = 'test@testorg.com', EmailEncodingKey = 'UTF-8', LastName = 'user', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'test@steinway.com', Allow_Deleting_Bill_to_Customer__c = true);
        insert u;
        
        System.runAs(u) {
            try {
                delete cust;
            }
            catch(exception ex) {
            
            }
        }
    }
}