objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Portal_Login__c/Portal_Login__c.object-meta.xml
<CustomObject>
    <label>Portal Login</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staging_Contact__c/Staging_Contact__c.object-meta.xml
<CustomObject>
    <label>Staging Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Staging_Contact__c/fields/Is_Updated__c.field-meta.xml
<CustomField>
    <fullName>Is_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Updated</label>
    <type>Checkbox</type>
</CustomField>

objects/Staging_Contact__c/fields/Last_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Updated By</label>
    <referenceTo>Portal_Login__c</referenceTo>
    <relationshipLabel>Staging Contacts</relationshipLabel>
    <relationshipName>Staging_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Staging_Contact__c/fields/Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated_Date__c</fullName>
    <label>Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

objects/Staging_Contact__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

classes/StagingContactControllerTest.cls
@IsTest
private class StagingContactControllerTest {
    private static testMethod void test() {
        SiteTestData.createData();
    
        Account acct = [SELECT Id FROM Account LIMIT 1];
        Contact cont = [SELECT Id FROM Contact LIMIT 1];
        Portal_Login__c login = [SELECT Id, Name FROM Portal_Login__c LIMIT 1];
        
        StagingContactController.StageContact(cont.Id);
        
        Staging_Contact__c sa = [SELECT Id FROM Staging_Contact__c LIMIT 1];
        sa.Is_Updated__c = true;
        sa.Last_Updated_By__c = login.Id;
        sa.Last_Updated_Date__c = system.today();
        sa.Notes__c = 'test note';
        update sa;
        
        String jsonString = JSON.serialize(sa);
        try {
            StagingContactController.validateBillingAddress(jsonString);
        }
        catch(exception ex) {
        }
        
        StagingContactController.saveStagingContact(jsonString);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(sa);  
        StagingContactController controller = new StagingContactController(sc);        
        controller.copyFirstName();
        controller.copyMiddleName();
        controller.copyLastName();
        controller.copyStreet();
        controller.copyCity();
        controller.copyState();
        controller.copyPostalCode();
        controller.copyCountry();
        controller.copyPhone();
        controller.copyEmail();
        controller.copyMobilePhone();
        controller.copyTitle();
        controller.copyAll();
        controller.SyncContact();
    }
    
    private static testMethod void testBatch() {
        SiteTestData.createData();
        
        List<Staging_Contact__c> sas = new List<Staging_Contact__c>();
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(sas);  
        StagingContactController controller = new StagingContactController(sc);
        controller.ResetUpdateRequestEmailSentFlag = true;
        controller.ImportContacts();
        
        controller.ImportContacts(); ///upate
        sas = [SELECT Id FROM Staging_Contact__c];
                
        controller.SendContactUpdateRequestEmails();
    }
}