objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

objects/Auto_Number__c/Auto_Number__c.object-meta.xml
<CustomObject>
    <label>Auto Number</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auto Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Auto_Number__c/fields/Displaying_Format__c.field-meta.xml
<CustomField>
    <fullName>Displaying_Format__c</fullName>
    <label>Displaying Format</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Auto_Number__c/fields/Starting_Number__c.field-meta.xml
<CustomField>
    <fullName>Starting_Number__c</fullName>
    <label>Starting Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/AutoNumberControllerTest.cls
@isTest
private class AutoNumberControllerTest {
    private static testMethod void test() {
        Auto_Number__c an = new Auto_Number__c(Name = 'Corporate No. Series', Displaying_Format__c = 'CORP-{00000}', Starting_Number__c = 1);
        insert an;

        AutoNumberController.ValidateFormatString('CORP-{00000}');
        Account corp = new Account(Name = 'Test', Type = 'Corporate');
        insert corp;
    }
}