objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Site</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Portal_Login__c/Portal_Login__c.object-meta.xml
<CustomObject>
    <label>Portal Login</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Portal_Login__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Portal Logins</relationshipLabel>
    <relationshipName>Portal_Logins</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Portal_Login__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal Logins</relationshipLabel>
    <relationshipName>Portal_Logins</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Portal_Login__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

objects/Portal_Login__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

objects/Portal_Login__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/SiteTestData.cls
@isTest
public class SiteTestData {

    public static void createData() {
        List<Account> accts = new List<Account>();
        Account acct = new Account();
        acct.Type = 'Customer';
        acct.Name = 'Site Customer';
        acct.BillingStreet = '123 ABC Ave';
        acct.BillingCity = 'New York';
        acct.BillingState = 'New York';
        acct.BillingPostalCode = '10002';
        acct.BillingCountry = 'United States';
        acct.Phone = '1234567890';
        acct.Fax = '1234567890';
        
        accts.add(acct);
        
        insert accts;
        
        List<Contact> conts = new List<Contact>();
        Contact cont = new Contact();
        cont.AccountId = acct.Id;
        cont.Contact_Type__c = 'Billing';
        cont.LastName = 'Smith';
        cont.FirstName = 'John';
        cont.Phone = '1234567890';
        cont.Email = 'kchen@micro-datanet.com';
        cont.MailingStreet = '123 ABC Ave';
        cont.MailingCity = 'New York';
        cont.MailingState = 'New York';
        cont.MailingPostalCode = '12345';
        cont.MailingCountry = 'United States';
        
        conts.add(cont);
        insert conts;
        
        Portal_Login__c login = new Portal_Login__c();
        login.Account__c = acct.Id;
        login.Contact__c = cont.Id;
        login.Username__c = 'kchen@micro-datanet.com';
        login.Password__c = 'password';
        login.Email__c = 'kchen@micro-datanet.com';
        insert login;
        
    }
}