objects/Tax_Area__c/Tax_Area__c.object-meta.xml
<CustomObject>
    <label>Tax Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Detail__c/Tax_Detail__c.object-meta.xml
<CustomObject>
    <label>Tax Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Detail__c/fields/Tax_Area__c.field-meta.xml
<CustomField>
    <fullName>Tax_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Area</label>
    <referenceTo>Tax_Area__c</referenceTo>
    <relationshipLabel>Tax Details</relationshipLabel>
    <relationshipName>Tax_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Tax_Detail__c/fields/Tax_Pct__c.field-meta.xml
<CustomField>
    <fullName>Tax_Pct__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

classes/TaxService.cls
public class TaxService {
    public static Map<Id, Map<String, Decimal>> taxPctByTaxGroupByTaxAreaId = new Map<Id, Map<String, Decimal>>();

    public static void setTaxPctByTaxGroupByTaxAreaIdMap(Set<Id> taxAreaIds){
        List<Tax_Detail__c> taxDetails = [SELECT Id, Tax_Area__c, Tax_Group__c, Tax_Pct__c FROM Tax_Detail__c WHERE Tax_Area__c IN :taxAreaIds];
        for(Tax_Detail__c taxDetail : taxDetails){
            Map<String, Decimal> taxPctByTaxGroup = new Map<String, Decimal>();
            if(taxPctByTaxGroupByTaxAreaId.containsKey(taxDetail.Tax_Area__c)){
                taxPctByTaxGroup = taxPctByTaxGroupByTaxAreaId.get(taxDetail.Tax_Area__c);
            }
            taxPctByTaxGroup.put(taxDetail.Tax_Group__c, taxDetail.Tax_Pct__c);
            taxPctByTaxGroupByTaxAreaId.put(taxDetail.Tax_Area__c, taxPctByTaxGroup);
        }
    }

    public static Decimal getTaxPct(Id taxAreaId, String taxGroup){
        Decimal taxPct = 0;
        if(taxPctByTaxGroupByTaxAreaId.containsKey(taxAreaId)){
            Map<String, Decimal> taxPctByTaxGroup = taxPctByTaxGroupByTaxAreaId.get(taxAreaId);
            if(taxPctByTaxGroup.containsKey(taxGroup)){
                taxPct = taxPctByTaxGroup.get(taxGroup);
            }
        }
        return taxPct;
    }

}