objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Convert_Count__c.field-meta.xml
<CustomField>
    <fullName>Convert_Count__c</fullName>
    <label>Convert Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>IF(TEXT(Document_Type__c) == 'Sales Order', false,
IF(Expiration_Date__c == NULL, false,
IF(Expiration_Date__c &lt; TODAY(), true, false)))</formula>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Pending_Approval</fullName>
        <label>Pending Approval</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

classes/AutoLostSalesQuoteJob.cls
/************************************************************************
 Class Name   : AutoLostSalesQuoteJob
 Created Date : 10/13/2023
 Description  :
 Author       : Steven
 Contributors  :
 ***************************** Update Logs *****************************
 ***********************************************************************
 */
public with sharing class AutoLostSalesQuoteJob implements Database.Batchable<SObject>, Schedulable {
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new AutoLostSalesQuoteJob(), 1000);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Quote_Status__c, Approval_Status__c FROM Sales_Order__c WHERE Document_Type__c = \'Sales Quote\' AND Expired__c = TRUE AND Quote_Status__c = \'Pending\' AND (Convert_Count__c = 0 OR Convert_Count__c = NULL)');
    }

    public void execute(Database.BatchableContext bc, List<Sales_Order__c> expiredSalesQuotes) {
        for(Sales_Order__c salesQuote : expiredSalesQuotes){
            if(salesQuote.Approval_Status__c == 'Approved') {
                salesQuote.Quote_Status__c = 'Lost';
            } else {
                salesQuote.Quote_Status__c = 'Canceled';
            }
        }
        CompanyMgmt.byPassTrigger = true;
        CompanyMgmt.byPassLineTrigger = true;
        Database.update(expiredSalesQuotes, false);
    }

    public void finish(Database.BatchableContext bc){

    }
}