objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Signature__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request_Email_Sent__c</fullName>
    <formula>Signature_Request__r.Request_Email_Sent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signature Request Email Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Signer_Role__c.field-meta.xml
<CustomField>
    <fullName>Signer_Role__c</fullName>
    <label>Signer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Customer A</fullName>
            </value>
            <value>
                <fullName>Customer B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/fields/Site_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Site_Access_Token__c</fullName>
    <formula>Signature_Request__r.Site_Access__r.Token__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Access Token</label>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Declined__c.field-meta.xml
<CustomField>
    <fullName>Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Declined</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Site_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Site_Access_Token__c</fullName>
    <formula>Site_Access__r.Token__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Access Token</label>
    <type>Text</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SignatureWrapper.cls
public with sharing class SignatureWrapper {

    @AuraEnabled
    public Id SignatureId { set; get; }
    @AuraEnabled
    public String Name { set; get; }
    @AuraEnabled
    public String PrintName { set; get; }
    @AuraEnabled
    public Boolean AcceptTerms { set; get; }
    @AuraEnabled
    public DateTime SignatureDate { set; get; }
    @AuraEnabled
    public Boolean NotAvailable { set; get; }
    @AuraEnabled
    public String Email { set; get; }
    @AuraEnabled
    public String SignatureData { set; get; }
    @AuraEnabled
    public Boolean Signed { set; get; }
    @AuraEnabled
    public Boolean RequestSignature { set; get; }
    @AuraEnabled
    public Id SignatureRequestId { set; get; }
    @AuraEnabled
    public Boolean SignatureRequestEmailSent { set; get; }
    @AuraEnabled
    public Id TMId { set; get; }
    //ticket 21113 <<
    @AuraEnabled
    public String RelatedToObjectName { set; get; }
    @AuraEnabled
    public String RelatedToId { set; get; }
    @AuraEnabled
    public String CustomerPONo { set; get; }
    @AuraEnabled
    public String CustomerComment { set; get; }
    @AuraEnabled
    public Boolean Declined { set; get; }
    //ticket 21113 >>
    @AuraEnabled
    public String SiteAccessToken { set; get; }
    @AuraEnabled
    public String IPAddress { set; get; }
    @AuraEnabled
    public String SignerRole { set; get; }

    //ticket 21770 <<
    @AuraEnabled
    public String TermsAndConditions { set; get; }
    //ticket 21770 >>

    public SignatureWrapper() {
    }

    public SignatureWrapper(Signature__c signature) {
        this.SignatureId = signature.Id;
        this.Name = signature.Name;
        this.PrintName = signature.Print_Name__c;
        this.AcceptTerms = signature.Accept_Terms_and_Conditions__c;
        this.SignatureDate = signature.Signature_Date__c;
        this.NotAvailable = signature.Customer_Not_Available__c;
        this.Email = signature.Email__c;
        this.Signed = signature.Signed__c;
        this.TMId = signature.TM__c;
        //ticket 21113 <<
        this.RelatedToObjectName = signature.Related_To_Object_Name__c;
        if (signature.Related_To_Object_Name__c == 'Sales_Order__c') {
            this.RelatedToId = signature.Sales_Order__c;
        }
        else {
            this.RelatedToId = signature.TM__c;
        }
        this.Declined = signature.Declined__c;
        this.CustomerPONo = signature.Customer_PO_No__c;
        this.CustomerComment = signature.Customer_Comment__c;
        //ticket 21113 >>
        this.RequestSignature = signature.Request_Signature__c;
        this.SignatureRequestEmailSent = signature.Signature_Request_Email_Sent__c;
        this.SignatureRequestId = signature.Signature_Request__c;
        this.SiteAccessToken = signature.Site_Access_Token__c;
        this.SignerRole = signature.Signer_Role__c;
    }

    public Signature__c toRecord() { 
        if (this.TMId == null) {
            throw new DataException('TM Id is required.');
        }
        Signature__c signature = new Signature__c();
        signature.Id = this.SignatureId;
        signature.Name = this.Name;
        signature.Print_Name__c = this.PrintName;
        signature.Accept_Terms_and_Conditions__c = (this.AcceptTerms == true);
        signature.Signature_Date__c = this.SignatureDate;
        signature.Customer_Not_Available__c = (this.NotAvailable == true);
        signature.Email__c = this.Email;
        if (this.SignatureId == null) {
            signature.TM__c = this.TMId;
        }
        signature.Request_Signature__c = (this.RequestSignature == true);
        signature.Signature_Request__c = this.SignatureRequestId;
        signature.Signed__c = (this.SignatureData != null);
        signature.Signer_Role__c = this.SignerRole;
        //ticket 21113 <<
        signature.Related_To_Object_Name__c = 'TM__c';
        signature.Related_To_Id__c = this.TMId;
        signature.Declined__c = (this.Declined == true);
        signature.Customer_PO_No__c = this.CustomerPONo;
        signature.Customer_Comment__c = this.CustomerComment;
        //ticket 21113 >>
        return signature;
    }
}