objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Signature_Request_Pending__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature Request Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Signature_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request_Status__c</fullName>
    <label>Signature Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Acceptance</fullName>
            </value>
            <value>
                <fullName>Customer Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Fail to Respond</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Signature__c/Signature__c.object-meta.xml
<CustomObject>
    <label>Signature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Customer_Comment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comment__c</fullName>
    <label>Customer Comment</label>
    <type>TextArea</type>
</CustomField>

objects/Signature__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature__c/fields/Request_Signature__c.field-meta.xml
<CustomField>
    <fullName>Request_Signature__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Signature</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/Signature_Request__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Request</label>
    <referenceTo>Signature_Request__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>Signatures</relationshipLabel>
    <relationshipName>Signatures</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Signature_Request__c/Signature_Request__c.object-meta.xml
<CustomObject>
    <label>Signature Request</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signature_Request__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Declined__c.field-meta.xml
<CustomField>
    <fullName>Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Declined</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/PDF_Email_Pending__c.field-meta.xml
<CustomField>
    <fullName>PDF_Email_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PDF Email Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Print_Name__c.field-meta.xml
<CustomField>
    <fullName>Print_Name__c</fullName>
    <label>Print Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Related_To_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object_Name__c</fullName>
    <label>Related To Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Signature_Request__c/fields/Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Reminder_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Sent_Date__c</fullName>
    <label>Reminder Sent Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Request_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Request_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request Email Sent</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>DateTime</type>
</CustomField>

objects/Signature_Request__c/fields/Signature_Pending__c.field-meta.xml
<CustomField>
    <fullName>Signature_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/Signature_Request__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signed</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/fields/Accept_Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accept_Terms_and_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Terms and Conditions</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>Customer_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Not Available</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/fields/Customer_PO_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_No__c</fullName>
    <label>Customer PO No.</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

objects/TM__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Order__c.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Service_Center__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Center__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Order__c.Document_Type__c</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>T&amp;Ms</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TM__c/fields/Signature_Request_Pending__c.field-meta.xml
<CustomField>
    <fullName>Signature_Request_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature Request Pending</label>
    <type>Checkbox</type>
</CustomField>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

classes/SignatureProcessController.cls
public with sharing class SignatureProcessController {
    public Id sourceRecordId;
    public List<Signature_Request__c> signatureRequests { set; get; }

    //ticket 21113 <<
    public SignatureProcessController() {
        this.sourceRecordId = (Id)ApexPages.currentPage().getParameters().get('id');
        this.signatureRequests = getUnprocessedSignatureRequests(this.sourceRecordId);
    }

    public PageReference processSignatures() {
        try {
            List<Signature_Request__c> signatureRequests = getUnprocessedSignatureRequests(this.sourceRecordId);
            processCustomerSignaturesByDocument(signatureRequests);
            processEmailByDocument(this.sourceRecordId);
            return new PageReference('/' + this.sourceRecordId).setRedirect(true);
        }
        catch (Exception ex) {
            ApexPages.addMessages(ex);
            return null;
        }
    }

    public PageReference cancel() {
        return new PageReference('/' + this.sourceRecordId);
    }

    public static List<Signature_Request__c> getUnansweredSignatureRequests(String relatedToId) {
        Integer days = 2;

        List<String> filters = new List<String>();
        filters.add('Voided__c != TRUE');
        filters.add('Signed__c != TRUE');
        filters.add('Declined__c != TRUE');
        filters.add('Processed__c != TRUE');
        filters.add('Request_Email_Sent__c = TRUE');
        filters.add('Reminder_Sent__c != TRUE');
        filters.add('Request_Date__c < LAST_N_DAYS:' + days); //last days

        filters.add('Related_To_Object_Name__c = \'Sales_Order__c\'');//quote only
        if (relatedToId != null) {
            filters.add('Related_To_Id__c = :relatedToId');
        }
        filters.add('CreatedDate >= 2023-02-24T12:00:00.000Z');
        String queryString = 'SELECT Id, Email__c, Print_Name__c, Signature_Date__c, Request_Date__c, Reminder_Sent__c, Accept_Terms_and_Conditions__c, Related_To_Object_Name__c, Related_To_Id__c, Signed__c, Declined__c, Customer_PO_No__c, Customer_Comment__c, Processed__c '
                + ' FROM Signature_Request__c'
                + ' WHERE ' + String.join(filters, ' AND ');
        List<Signature_Request__c> signatureRequests = Database.query(queryString);
        return signatureRequests;
    }

    public static List<Signature_Request__c> getUnprocessedSignatureRequests(String relatedToId) {

        List<String> filters = new List<String>();
        filters.add('Voided__c != TRUE');
        filters.add('(Signed__c = TRUE OR Declined__c = TRUE)');
        filters.add('Processed__c != TRUE');
        if (relatedToId != null) {
            filters.add('Related_To_Id__c = :relatedToId');
        }
        String queryString = 'SELECT Id, Email__c, Print_Name__c, Signature_Date__c, Request_Date__c, Reminder_Sent__c, Accept_Terms_and_Conditions__c, Related_To_Object_Name__c, Related_To_Id__c, Signed__c, Declined__c, Customer_PO_No__c, Customer_Comment__c, Processed__c '
                + ' FROM Signature_Request__c'
                + ' WHERE ' + String.join(filters, ' AND ');
        List<Signature_Request__c> signatureRequests = Database.query(queryString);
        return signatureRequests;
    }
    public static List<Signature_Request__c> getProcessedNotEmailedSignatureRequests(String relatedToId) {

        List<String> filters = new List<String>();
        filters.add('Voided__c != TRUE');
        filters.add('(Signed__c = TRUE OR Declined__c = TRUE)');
        filters.add('Processed__c = TRUE');
        filters.add('PDF_Email_Pending__c = TRUE');
        if (relatedToId != null) {
            filters.add('Related_To_Id__c = :relatedToId');
        }
        String queryString = 'SELECT Id, Email__c, Print_Name__c, Signature_Date__c, Request_Date__c, Reminder_Sent__c, Related_To_Object_Name__c, Related_To_Id__c, Signed__c, Declined__c, Customer_PO_No__c, Customer_Comment__c, Processed__c '
                + ' FROM Signature_Request__c'
                + ' WHERE ' + String.join(filters, ' AND ');
        List<Signature_Request__c> signatureRequests = Database.query(queryString);
        return signatureRequests;
    }


    public static void processCustomerSignaturesByDocument(List<Signature_Request__c> signatureRequests) {
        Savepoint sp = Database.setSavepoint();
        try {
            //check for the source records. This routine process signatures for a single document
            String sourceRecordId;
            for (Signature_Request__c signatureRequest : signatureRequests) {
                if (sourceRecordId != null && sourceRecordId != signatureRequest.Related_To_Id__c) {
                    throw new DataException('processCustomerSignaturesByDocument handle only document per call.');
                }
                sourceRecordId = signatureRequest.Related_To_Id__c;
            }

            Set<Id> signatureRequestIds = new Set<Id>();
            Map<String, Set<Id>> mapSourceRecordIdsByObjectName = new Map<String, Set<Id>>();
            for (Signature_Request__c signatureRequest : signatureRequests) {
                signatureRequestIds.add(signatureRequest.Id);

                Set<Id> sourceRecordIds;
                if (mapSourceRecordIdsByObjectName.containsKey(signatureRequest.Related_To_Object_Name__c)) {
                    sourceRecordIds = mapSourceRecordIdsByObjectName.get(signatureRequest.Related_To_Object_Name__c);
                }
                else {
                    sourceRecordIds = new Set<Id>();
                    mapSourceRecordIdsByObjectName.put(signatureRequest.Related_To_Object_Name__c, sourceRecordIds);
                }
                sourceRecordIds.add(signatureRequest.Related_To_Id__c);
            }

            Map<Id, Signature__c> mapSignaturesBySignatureRequestId = new Map<Id, Signature__c>();
            for (Signature__c signature : [SELECT Id, Signature_Request__c, (SELECT Id FROM Attachments) FROM Signature__c WHERE Signature_Request__c IN :signatureRequestIds]) {
                mapSignaturesBySignatureRequestId.put(signature.Signature_Request__c, signature);
            }

            //attach customer signatures to the signature records
            Map<Id, Attachment> mapAttachmentsBySignatureRequestId = new Map<Id, Attachment>();
            for (Attachment attachment : [SELECT Id, Name, ParentId, Body, ContentType, IsPrivate FROM Attachment WHERE ParentId IN :signatureRequestIds]) {
                mapAttachmentsBySignatureRequestId.put(attachment.ParentId, attachment);
            }

            List<Attachment> newAttachments = new List<Attachment>();
            for (Signature_Request__c signatureRequest : signatureRequests) {
                if (mapSignaturesBySignatureRequestId.containsKey(signatureRequest.Id)) {
                    Signature__c signature = mapSignaturesBySignatureRequestId.get(signatureRequest.Id);

                    signature.Customer_Not_Available__c = false;
                    signature.Signed__c = signatureRequest.Signed__c;
                    signature.Declined__c = signatureRequest.Declined__c;
                    signature.Print_Name__c = signatureRequest.Print_Name__c;
                    signature.Signature_Date__c = signatureRequest.Signature_Date__c;
                    signature.Email__c = signatureRequest.Email__c;
                    signature.Accept_Terms_and_Conditions__c = signatureRequest.Accept_Terms_and_Conditions__c;
                    signature.Customer_Comment__c = signatureRequest.Customer_Comment__c;
                    signature.Customer_PO_No__c = signatureRequest.Customer_PO_No__c;

                    //create attachment
                    if (mapAttachmentsBySignatureRequestId.containsKey(signatureRequest.Id)) {
                        Attachment newAttachment = mapAttachmentsBySignatureRequestId.get(signatureRequest.Id).clone(false, false);
                        if (signature.Attachments.size() > 0) {
                            newAttachment.Id = signature.Attachments[0].Id;
                        } else {
                            newAttachment.ParentId = signature.Id;
                        }
                        newAttachment.Name = 'customer signature';
                        newAttachments.add(newAttachment);
                    }

                    //update signature request
                    signatureRequest.Id = signature.Signature_Request__c;
                    signatureRequest.Signature_Pending__c = false;
                    signatureRequest.PDF_Email_Pending__c = true;
                    signatureRequest.Processed__c = true;
                }
            }

            upsert newAttachments;
            update signatureRequests;
            update mapSignaturesBySignatureRequestId.values();

            //update source records Signature_Request_Pending__c by object type
            for (String objectName : mapSourceRecordIdsByObjectName.keySet()) {
                Set<Id> sourceRecordIds = mapSourceRecordIdsByObjectName.get(objectName);

                List<SObject> sourceRecordsToUpdate = new List<SObject>();
                String queryString = 'SELECT Id, Name, Signature_Request_Pending__c FROM ' + objectName + ' WHERE Id IN :sourceRecordIds';
                for (SObject sourceRecord : Database.query(queryString)) {
                    List<Signature__c> signatures = [SELECT Id, Request_Signature__c, Email__c, Signed__c, Declined__c, Customer_PO_No__c, Customer_Comment__c FROM Signature__c WHERE Related_To_Id__c = :sourceRecord.Id AND Voided__c != TRUE];
                    if ((Boolean)sourceRecord.get('Signature_Request_Pending__c') == true) {
                        Boolean signatureRequestPending = false;
                        String status = null;
                        for (Signature__c signature : signatures) {
                            if (signature.Request_Signature__c == true && signature.Signed__c != true && signature.Declined__c != true) {
                                signatureRequestPending = true;
                            }
                            if (objectName == 'Sales_Order__c') { //there should only be one signature for quote
                                if (signature.Signed__c == true) {
                                    status = 'Customer Accepted';
                                }
                                else if (signature.Declined__c == true) {
                                    status = 'Rejected';
                                }
                                if (status != null) {
                                    sourceRecord.put('Signature_Request_Status__c', status);
                                }
                                if (signature.Customer_PO_No__c != null) {
                                    sourceRecord.put('Customer_PO_No__c', signature.Customer_PO_No__c);
                                }
                                if (signature.Customer_Comment__c != null) {
                                    sourceRecord.put('Customer_Comment__c', signature.Customer_Comment__c);
                                }
                            }
                        }
                        sourceRecord.put('Signature_Request_Pending__c', signatureRequestPending);
                        sourceRecordsToUpdate.add(sourceRecord);
                    }
                }
                update sourceRecordsToUpdate;
            }
        }
        catch (Exception ex) {
            Database.rollback(sp);
            throw ex;
        }
    }

    @future(callout=true)
    public static void processEmailByDocument(Id relatedToId) {
        List<Signature_Request__c> signatureRequests = getProcessedNotEmailedSignatureRequests(relatedToId);
        if (signatureRequests.size() > 0) {
            processEmailByDocument(signatureRequests);
        }
    }

    public static void processEmailByDocument(List<Signature_Request__c> signatureRequests) {
        Savepoint sp = Database.setSavepoint();
        try {
            String sourceRecordId;
            String objectName;
            for (Signature_Request__c signatureRequest : signatureRequests) { //tm can take up to 2 customer signatures
                if (sourceRecordId != null && sourceRecordId != signatureRequest.Related_To_Id__c) {
                    throw new DataException('processEmailByDocument handle only document per call.');
                }
                sourceRecordId = signatureRequest.Related_To_Id__c;
                objectName = signatureRequest.Related_To_Object_Name__c;
            }

            if (objectName == 'TM__c') {
                TM__c tm = [SELECT Id, Name FROM TM__c WHERE Id = :sourceRecordId LIMIT 1];
                Blob pdf = MobileTMController.GenerateFieldTMPDF(tm.Id);
                //ticket 29960 >>
                //MobileTMController.SaveFieldTMPDF(tm, pdf);
                MobileTMController.SaveFieldTMPDF(tm, pdf, tm.Name + '_' + + System.now().format('yyyy_MM_dd_hh_mm_ss') + '_Signed.pdf');
                //ticket 29960 <<
                MobileTMController.sendFieldTMPDF(tm, pdf);
            }
            else if (objectName == 'Sales_Order__c') {
                Signature_Request__c signatureRequest = signatureRequests[0]; // quote only takes one signature from the quote contact

                if (signatureRequest.Signed__c == true) {
                    Sales_Order__c quote = [SELECT Id, Name, CreatedBy.Email FROM Sales_Order__c WHERE Id = :sourceRecordId LIMIT 1];
                    Blob pdf = SalesQuoteEmailing.generateQuotePDF(quote.Id);
                    String filename = quote.Name + '_' + System.now().format('yyyyMMddhhmmss') + '_Signed.pdf';
                    SalesQuoteEmailing.saveQuotePDF(quote, pdf, filename);
                    SalesQuoteEmailing.sendQuotePDF(quote, pdf);
                    SalesQuoteEmailing.notifySignedQuote(signatureRequest);
                }
                else if (signatureRequest.Declined__c == true) {
                    SalesQuoteEmailing.notifyRejectedQuote(signatureRequest);
                }
            }

            for (Signature_Request__c signatureRequest : signatureRequests) {
                signatureRequest.PDF_Email_Pending__c = false;
            }

            update signatureRequests;

        } catch (Exception ex) {
            Database.rollback(sp);
            throw ex;
        }
    }

    public static void sendUnansweredSignatureRequestReminderEmail(List<Signature_Request__c> signatureRequests) {
        try {
            String sourceRecordId;
            String objectName;
            for (Signature_Request__c signatureRequest : signatureRequests) { //tm can take up to 2 customer signatures
                if (sourceRecordId != null && sourceRecordId != signatureRequest.Related_To_Id__c) {
                    throw new DataException('sendUnansweredSignatureRequestReminderEmail handle only document per call.');
                }
                sourceRecordId = signatureRequest.Related_To_Id__c;
                objectName = signatureRequest.Related_To_Object_Name__c;
            }

            if (objectName == 'Sales_Order__c') {
                Signature_Request__c signatureRequest = [SELECT Id, Voided__c, Signed__c, Declined__c, Request_Email_Sent__c, Request_Date__c, Reminder_Sent__c, Related_To_Object_Name__c, Related_To_Id__c, Print_Name__c, Email__c, Processed__c, CreatedById FROM Signature_Request__c WHERE Id = :signatureRequests[0].Id LIMIT 1];
                if (signatureRequest.Request_Email_Sent__c = TRUE && signatureRequest.Voided__c != true && signatureRequest.Signed__c != true
                        && signatureRequest.Declined__c != true && signatureRequest.Processed__c != true && signatureRequest.Reminder_Sent__c != true) {
                    SalesQuoteEmailing.notifyUnansweredSignatureRequest(signatureRequest);
                }


                signatureRequest.Reminder_Sent__c = true;
                signatureRequest.Reminder_Sent_Date__c = Datetime.now();
                update signatureRequest;

                Sales_Order__c quote = new Sales_Order__c();
                quote.Id = sourceRecordId;
                quote.Signature_Request_Status__c = 'Fail to Respond';
                CompanyMgmt.byPassTrigger = true;
                update quote;
            }
        }
        catch (Exception ex) {
            //ignore email error
        }
    }

    //ticket 21113 >>
}