objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order__c/fields/Account_Executives__c.field-meta.xml
<CustomField>
    <fullName>Account_Executives__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Executive</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Account_Executive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Quotes/Orders (Account Executive)</relationshipLabel>
    <relationshipName>Sales_Orders_AE</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Bill_to_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer_No__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill-to Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Prospect, Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Subsidiary_Company__c</field>
            <operation>equals</operation>
            <valueField>$Source.Subsidiary_Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Type</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Certified_PW_Job__c.field-meta.xml
<CustomField>
    <fullName>Certified_PW_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified(PW) Job</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/CMR_Description__c.field-meta.xml
<CustomField>
    <fullName>CMR_Description__c</fullName>
    <label>Job Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CountryList</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Do_Not_Reset_Sync_Flag__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Reset_Sync_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Reset Sync Flag</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Estimated_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Revenue__c</fullName>
    <label>Estimated Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Order__c/fields/Fax_No__c.field-meta.xml
<CustomField>
    <fullName>Fax_No__c</fullName>
    <label>Fax No.</label>
    <type>Phone</type>
</CustomField>

objects/Sales_Order__c/fields/Inter_Company_Job__c.field-meta.xml
<CustomField>
    <fullName>Inter_Company_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inter-Company Job</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Order_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Order_Type_Description__c</fullName>
    <label>Order Type Description</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Phone_No__c.field-meta.xml
<CustomField>
    <fullName>Phone_No__c</fullName>
    <label>Phone No.</label>
    <type>Phone</type>
</CustomField>

objects/Sales_Order__c/fields/Prevailing_Wage_Job__c.field-meta.xml
<CustomField>
    <fullName>Prevailing_Wage_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prevailing Wage Job</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Project_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Project_Coordinator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Salesperson__c.Name</field>
            <operation>notEqual</operation>
            <value>HOU</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Quotes/Orders (Project Manager)</relationshipLabel>
    <relationshipName>Sales_Orders_PC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order__c/fields/Sage_Job_No__c.field-meta.xml
<CustomField>
    <fullName>Sage_Job_No__c</fullName>
    <label>Sage Job No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Sales_Order__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

objects/Sales_Order__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

objects/Sales_Order__c/fields/Sync_d__c.field-meta.xml
<CustomField>
    <fullName>Sync_d__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync'd</label>
    <type>Checkbox</type>
</CustomField>

objects/Sales_Order__c/fields/Synced_with_Coupa__c.field-meta.xml
<CustomField>
    <fullName>Synced_with_Coupa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced with Coupa</label>
    <type>Checkbox</type>
</CustomField>

globalValueSets/Billing_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>T&amp;M</fullName>
        <default>true</default>
        <label>T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Per Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Lump Sum</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Plus</fullName>
    </customValue>
    <masterLabel>Billing Type</masterLabel>
</GlobalValueSet>

globalValueSets/CountryList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BEL</fullName>
    </customValue>
    <customValue>
        <fullName>IND</fullName>
    </customValue>
  
     
    <masterLabel>CountryList</masterLabel>
</GlobalValueSet>

classes/SalesOrder_BeforeUpdateTriggerHandler.cls
public class SalesOrder_BeforeUpdateTriggerHandler extends TriggerHandlerBase{
    public override void mainEntry(){ 
        System.debug('SalesOrder_BeforeUpdateTriggerHandler >> mainEntry()');

        List<Sales_Order__c> SOList = (List<Sales_Order__c>) Trigger.new;
        Map<Id, Sales_Order__c> oldValues = (Map<Id, Sales_Order__c>) Trigger.oldMap;
        Boolean isInsert = Trigger.isInsert;

        SalesOrderTriggersMgt.SOInsertUpdate(SOList, oldValues, isInsert);

        for (Sales_Order__c so : SOList) {
            Sales_Order__c xso = oldValues.get(so.Id);
            if (so.Do_Not_Reset_Sync_Flag__c != true) {
                if (so.Name != xso.Name || so.Bill_to_Customer_No__c != xso.Bill_to_Customer_No__c
                || so.Street__c != xso.Street__c || so.City__c != xso.City__c || so.State__c != xso.State__c
                || so.Postal_Code__c != xso.Postal_Code__c || so.Country__c != xso.Country__c
                || so.Phone_No__c != xso.Phone_No__c || so.Fax_No__c != xso.Fax_No__c
                || so.Document_Status__c != xso.Document_Status__c || so.Billing_Type__c != xso.Billing_Type__c
                || so.Order_Type_Description__c != xso.Order_Type_Description__c || so.Inter_Company_Job__c != xso.Inter_Company_Job__c
                || so.Certified_PW_Job__c != xso.Certified_PW_Job__c || so.Prevailing_Wage_Job__c != xso.Prevailing_Wage_Job__c
                || so.Estimated_Revenue__c != xso.Estimated_Revenue__c || so.Sage_Job_No__c != xso.Sage_Job_No__c
                || so.Project_Coordinator__c != xso.Project_Coordinator__c || so.Account_Executives__c != xso.Account_Executives__c
                || so.CMR_Description__c != xso.CMR_Description__c) {
                    so.Sync_d__c = false;
                }
            }
            so.Do_Not_Reset_Sync_Flag__c = false;

            if(so.Name != xso.Name || so.Document_Status__c != xso.Document_Status__c){
                so.Synced_with_Coupa__c = false;
            }
        }
    }
}