objects/Contract_Line__c/Contract_Line__c.object-meta.xml
<CustomObject>
    <label>Contract Line</label>
    <nameField>
        <label>contract line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Line__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <label>Customer Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_Item_No__c</fullName>
    <label>Customer Item No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Overtime_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Overtime_Description__c</fullName>
    <label>Customer Overtime Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Customer_Overtime_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Customer_Overtime_Item_No__c</fullName>
    <label>Customer Overtime Item No.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Contract_Line__c/fields/Overtime_Rate__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Rate__c</fullName>
    <label>Overtime Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Contract_Line__c/fields/Regular_Rate__c.field-meta.xml
<CustomField>
    <fullName>Regular_Rate__c</fullName>
    <label>Regular Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Contract_Line__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contract_Line__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Contract Lines</relationshipLabel>
    <relationshipName>Contract_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Type</label>
    <referenceTo>Resource_Type__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Resource_Type__c/Resource_Type__c.object-meta.xml
<CustomObject>
    <label>Resource Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Resource_Type__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit of Measure</label>
    <referenceTo>Unit_of_Measure__c</referenceTo>
    <relationshipLabel>Resource Types</relationshipLabel>
    <relationshipName>Resource_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Unit_of_Measure__c/Unit_of_Measure__c.object-meta.xml
<CustomObject>
    <label>Unit of Measure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchDataUploadTest.cls
/******************************************************************************************************************
* Name         :  BatchDataUploadTest 
* Description  :  TestClass for BatchDataUpload class.
*
* Modification Log :
* Developer                 Date                   Description
* ---------------------------------------------------------------------------------------------------------------------
* Vignesh Kumar N         01-15-2024             Initial Version
***********************************************************************************************************************/
@isTest
public class BatchDataUploadTest {
    
    @testSetup static void setupData() {
        NewTestData.createTestData();
        Contract ctrct = [SELECT Id, Name FROM Contract WHERE Name = 'Contract' LIMIT 1];
        Assert.areEqual('Contract', ctrct.Name, 'Contract not created');
    }
    
    @isTest static void batchUploadPositive() {
        Test.startTest();
        Id recordId = [SELECT Id, Name FROM Contract WHERE Name = 'Contract' LIMIT 1].Id;        
        Resource_Type__c rtype = [SELECT Id, Unit_of_Measure__C FROM Resource_Type__c LIMIT 1];
        
        String csvTestData = 'Resource_Type__c,Resource__c,Unit_of_Measure__c,Customer_Item_No__c,Customer_Description__c,Regular_Rate__c,Customer_Overtime_Item_No__c,Customer_Overtime_Description__c,Overtime_Rate__c\n'+
            rtype.Id+', ,'+rtype.Unit_of_Measure__c+', \'Test Customer Item No\', \"Test Customer Desc\",100,150,Test OverTime Desc,200';
        
        ContentVersion cv = createTestContentVersion('Test document', '.csv', csvTestData);        
        DataUploadHandler.executeDataUploadBatch(recordId, cv.Id, 'Contract_Line__c');
        
        Test.stopTest();
    }
    
    @isTest static void batchUploadNegative() {
        Test.startTest();
        Id recordId = [SELECT Id, Name FROM Contract WHERE Name = 'Contract' LIMIT 1].Id;  
        String csvTestDataFail = 'Resource_Type__c,Resource__c,Unit_of_Measure__c,Customer_Item_No__c,Customer_Description__c,Regular_Rate__c,Customer_Overtime_Item_No__c,Customer_Overtime_Description__c,Overtime_Rate__c\n'+
            ' , , , \'Test Customer Item No\', \"Test Customer Desc\",100.2,150.65,Test OverTime Desc,200';
        
        ContentVersion cv1 = createTestContentVersion('Test Document','.csv', csvTestDataFail);         
        DataUploadHandler.executeDataUploadBatch(recordId, cv1.Id, 'Contract_Line__c');
        DataUploadHandler.executeDataUploadBatch(recordId, cv1.Id, 'Contract_Lines__c');
        
        String csvTestDataFail1 = 'Resource_Type__c,Resource__c,Unit_of_Measure__c\n'+
            ' , , ';
        
        ContentVersion cv2 = createTestContentVersion('Test Document','.csv', csvTestDataFail1);     
        DataUploadHandler.executeDataUploadBatch(recordId, cv2.Id, 'Contract_Line__c');
        
        ContentVersion contVer = createTestContentVersion('Test Document','.pdf', 'Test Document pdf');     
        DataUploadHandler.executeDataUploadBatch(recordId, contVer.Id, 'Contract_Line__c');
        
        Test.stopTest();
    }
    
    private static ContentVersion createTestContentVersion(String title, String fileType, String content) {
        ContentVersion contVer = new ContentVersion();
        contVer.Title = title;
        contVer.PathOnClient = title + fileType;
        contVer.VersionData = Blob.valueOf(content);
        contVer.IsMajorVersion = true;
        Insert contVer; 
        return contVer;
    }   
}