objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Sales_Order_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Sales_Order__c</field>
            <operation>equals</operation>
            <valueField>Sales_Order_Job_Task__c.Sales_Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Order_Job_Task__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Sales_Order_Job_Task__c/Sales_Order_Job_Task__c.object-meta.xml
<CustomObject>
    <label>Sales Order Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ACVSalesOrderJobTaskWrapper.cls
global with sharing class ACVSalesOrderJobTaskWrapper {
    @AuraEnabled
    public Sales_Order_Job_Task__c JobTask { set; get; }

    @AuraEnabled
    public List<Sales_Line__c> SalesLines { set; get; }

    @AuraEnabled
    public Boolean Collapsed { set; get; }

    //ticket 20177 <<
    @AuraEnabled
    public Boolean HasTMs { set; get; }
    @AuraEnabled
    public Boolean HasInvoices { set; get; }
    //ticket 20177 >>

    //ticket 19130 05.03.2023 <<
    @AuraEnabled
    public Integer NextSalesLineNo { set; get; }
    //ticket 19130 05.03.2023 >>

    public ACVSalesOrderJobTaskWrapper() {
        this.SalesLines = new List<Sales_Line__c>();
    }

    public ACVSalesOrderJobTaskWrapper(Sales_Order_Job_Task__c jobTask, List<Sales_Line__c> salesLines) {
        this.JobTask = jobTask;
        this.SalesLines = salesLines;
    }
}