objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Lines</relationshipLabel>
    <relationshipName>Sales_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Quote/Order</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes/Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SalesLineController.cls
public with sharing class SalesLineController {
    /*
    private final ApexPages.StandardController theController;
	private String orderId;
    private String salesLineId;
    private Sales_Line__c theSL;
    public SalesLineController(ApexPages.StandardController controller) {
        theController = controller;
        salesLineId = ApexPages.CurrentPage().getParameters().get('id');
        selectSL();
        orderId = theSL.Sales_Order__c;
    }
    
    private void selectSL() {
        Map<String, Schema.SObjectField> fields = Schema.SObjectType.Sales_Line__c.fields.getMap();
        List<String> lstFields = new List<String>();
        for (Schema.SObjectField field : fields.values()) {
            lstFields.add(field.getDescribe().getName());
        }
        String strQuery = 'SELECT ' + String.join(lstFields, ',');
        strQuery += ' FROM Sales_Line__c WHERE Id =: salesLineId';
        theSL = Database.query(strQuery);
    }

    public PageReference cancel() {
        return theController.cancel();

    }
    
    public PageReference returnToSO() {
        PageReference SO = new PageReference('/' + orderId);
        SO.setRedirect(true);
        return SO;
    }
    */
}