objects/Sales_Line__c/Sales_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Subcontractors</fullName>
                <label>Cost Plus Materials, Equipment and Services</label>
            </value>
            <value>
                <fullName>Waste Disposal</fullName>
            </value>
            <value>
                <fullName>Demurrage</fullName>
                <label>Transportation, Demurrage and Fees</label>
            </value>
            <value>
                <fullName>Lump Sum</fullName>
            </value>
            <value>
                <fullName>Bundled</fullName>
            </value>
            <value>
                <fullName>Misc. Charges And Taxes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Sales_Line__c/fields/Line_Amount__c.field-meta.xml
<CustomField>
    <fullName>Line_Amount__c</fullName>
    <label>Line Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Line__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Sales_Line__c/fields/xUnit_Price__c.field-meta.xml
<CustomField>
    <fullName>xUnit_Price__c</fullName>
    <label>xUnit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

classes/SalesOrderLightningDataXFieldsBatchable.cls
public with sharing class SalesOrderLightningDataXFieldsBatchable implements Database.Batchable<Sales_Line__c> {

    public List<Sales_Line__c> start(Database.BatchableContext bc) {
        //return [SELECT Id, Unit_Price__c, xUnit_Price__c, Unit_Cost__c, Line_Cost__c, Line_Amount__c FROM Sales_Line__c WHERE Category__c <> 'Lump Sum' AND Bill_as_Lump_Sum__c <> TRUE AND xUnit_Cost_Updated__c <> TRUE LIMIT 50000];
        return null;
    }

    public void execute(Database.BatchableContext BC, List<Sales_Line__c> salesLines) {
        /*
        try {
            SalesOrderLightningDataManagement.UpdateXFields(salesLines);
        }
        catch(exception ex) {
            System.abortJob(bc.GetJobId());
            throw ex;
        }
        */
    }
    
    public void finish(Database.BatchableContext bc) {

    }

}