objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <label>Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Holiday__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Holiday__c/fields/Holiday__c.field-meta.xml
<CustomField>
    <fullName>Holiday__c</fullName>
    <description>No longer needed, use Holiday Name Map field instead</description>
    <label>Holiday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Holiday_List</valueSetName>
    </valueSet>
</CustomField>

objects/Holiday__c/fields/Holiday_Name_Map__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Name_Map__c</fullName>
    <label>Holiday Name Map</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Holiday_List</valueSetName>
    </valueSet>
</CustomField>

globalValueSets/Holiday_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Christmas Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>CDPWO</fullName>
        <label>Christmas Day PW  Observed</label>
    </customValue>
    <customValue>
        <fullName>Christmas Eve Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Christmas Eve Company</fullName>
    </customValue>
    <customValue>
        <fullName>Columbus Day</fullName>
    </customValue>
    <customValue>
        <fullName>Day After Thanksgiving</fullName>
    </customValue>
    <customValue>
        <fullName>Easter</fullName>
    </customValue>
    <customValue>
        <fullName>Election Day</fullName>
    </customValue>
    <customValue>
        <fullName>Good Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Inauguration Day</fullName>
    </customValue>
    <customValue>
        <fullName>Independence Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Independence Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>IDPWO</fullName>
        <label>Independence Day PW Observed</label>
    </customValue>
    <customValue>
        <fullName>Juneteenth Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Juneteenth PW Observed</fullName>
    </customValue>
    <customValue>
        <fullName>Labor Day</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln&apos;s Birthday Actual</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln&apos;s Birthday PW Observed</fullName>
    </customValue>
    <customValue>
        <fullName>Martin Luther King Day</fullName>
    </customValue>
    <customValue>
        <fullName>Memorial Day</fullName>
    </customValue>
    <customValue>
        <fullName>New Year&apos;s Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>New Year&apos;s Day Company</fullName>
    </customValue>
    <customValue>
        <fullName>NYDPWO</fullName>
        <label>New Year&apos;s Day PW Observed</label>
    </customValue>
    <customValue>
        <fullName>Patriots Day</fullName>
    </customValue>
    <customValue>
        <fullName>Presidential Election Day</fullName>
    </customValue>
    <customValue>
        <fullName>Presidents Day</fullName>
    </customValue>
    <customValue>
        <fullName>Thanksgiving</fullName>
    </customValue>
    <customValue>
        <fullName>Veteran&apos;s Day Actual</fullName>
    </customValue>
    <customValue>
        <fullName>VDPWO</fullName>
        <label>Veteran&apos;s Day PW Observed</label>
    </customValue>
    <masterLabel>Holiday List</masterLabel>
</GlobalValueSet>

classes/HolidaysSelector.cls
public class HolidaysSelector extends fflib_SObjectSelector{

    public static HolidaysSelector newInstance()
    {
        return (HolidaysSelector) Application.Selector.newInstance(Holiday__c.SObjectType);
    }

    public HolidaysSelector()
    {
        super(false);
    }

    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField>{
                Holiday__c.Id,
                Holiday__c.Name,
                Holiday__c.Holiday__c,
                Holiday__c.Date__c,
                Holiday__c.Holiday_Name_Map__c
        };
    }

    public Schema.SObjectType getSObjectType()
    {
        return Holiday__c.SObjectType;
    }

    public List<Holiday__c> selectHolidaysYearBeforeAndAfter()
    {
        Integer year = Date.today().year();
        Date yearBefore = Date.newInstance(year-1,1,1);
        Date yearAfter = Date.newInstance(year+1,12,31);

        return (List<Holiday__c>) Database.query(
                newQueryFactory(true).setCondition('Date__c >= :yearBefore AND Date__c <= :yearAfter AND Holiday_Name_Map__c <> null').toSOQL()
        );
    }

    public Map<Date, Holiday__c> getHolidaysByDates(){
        Map<Date, Holiday__c> holidaysByDates = new Map<Date, Holiday__c>();
        for(Holiday__c holiday:selectHolidaysYearBeforeAndAfter()){
            holidaysByDates.put(holiday.Date__c, holiday);
        }
        return holidaysByDates;
    }

    public List<Holiday__c> selectAll(){
        return (List<Holiday__c>) Database.query(newQueryFactory().setCondition('Holiday_Name_Map__c <> null').setOrdering('Date__c', fflib_QueryFactory.SortOrder.DESCENDING).toSOQL());
    }
}