objects/Payroll__c/Payroll__c.object-meta.xml
<CustomObject>
    <label>Payroll</label>
    <nameField>
        <label>Payroll No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payrolls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payroll__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Payroll__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/Payroll__c/fields/Week_Number__c.field-meta.xml
<CustomField>
    <fullName>Week_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Week Number</label>
    <referenceTo>Week_Number__c</referenceTo>
    <relationshipLabel>Payrolls</relationshipLabel>
    <relationshipName>Payrolls</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Week_Number__c/Week_Number__c.object-meta.xml
<CustomObject>
    <label>Week Number</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Week Numbers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Week_Number__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Week_Number__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/Week_Number__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

classes/PayrollMgmt.cls
public with sharing class PayrollMgmt {
	public static Payroll__c validateWeekNo(Payroll__c thePayroll) {
        if (String.isEmpty(thePayroll.Week_Number__c)) {
            return thePayroll;
        } else {
            Week_Number__c WeekNo = [SELECT Id, Name, Week_Start_Date__c, Week_End_Date__c, Year__c FROM Week_Number__c WHERE Id = :thePayroll.Week_Number__c LIMIT 1];
            thePayroll.Week_Number__r = new Week_Number__c(Id = WeekNo.Id, Name = WeekNo.Name);
            
            thePayroll.Start_Date__c = WeekNo.Week_Start_Date__c;
            thePayroll.End_Date__c = WeekNo.Week_End_Date__c;
            thePayroll.Year__c = WeekNo.Year__c;
        }
        return thePayroll;
    }

    public static Week_Number__c getWeekNumber(Id weekNoId){
        return [SELECT Id, Name, Week_Start_Date__c, Week_End_Date__c FROM Week_Number__c WHERE Id = :weekNoId LIMIT 1];
    }

    //Ticket#24469
    public static Boolean isPayrollBlockoutPeriod(){
        String dayInTheWeek = TimeUtils.getCurrentDayNameInLocalTime();
        Integer blockoutStartHour = CompanyMgmt.zeroIfNull(CompanySettingUtil.acvSetting.Payroll_Blockout_Start_Hour__c).intValue();
        Integer blockoutStartMinute = CompanyMgmt.zeroIfNull(CompanySettingUtil.acvSetting.Payroll_Blockout_Start_Minute__c).intValue();
        Integer blockoutEndMinute = CompanyMgmt.zeroIfNull(CompanySettingUtil.acvSetting.Payroll_Blockout_End_Minute__c).intValue();
        if(dayInTheWeek == 'Mon'){
            Integer currentHr = System.now().hour();
            Integer currentMin = System.now().minute();
            if(currentHr == blockoutStartHour && currentMin >= blockoutStartMinute && currentMin <= blockoutEndMinute){
                return true;
            }
        }
        return false;
    }
}