objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

objects/TM__c/TM__c.object-meta.xml
<CustomObject>
    <label>T&amp;M</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;Ms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TM__c/recordTypes/Void.recordType-meta.xml
<RecordType>
    <fullName>Void</fullName>
    <active>true</active>
    <label>Void</label>
    
    
</RecordType>

objects/TM_Job_Task__c/TM_Job_Task__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Job Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;M Job Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Job_Task__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>TM</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Job Tasks</relationshipLabel>
    <relationshipName>TM_Job_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/TM_Line__c.object-meta.xml
<CustomObject>
    <label>T&amp;M Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;M Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TM_Line__c/fields/TM__c.field-meta.xml
<CustomField>
    <fullName>TM__c</fullName>
    <label>T&amp;M</label>
    <referenceTo>TM__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>TM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TM_Line__c/fields/TM_Job_Task__c.field-meta.xml
<CustomField>
    <fullName>TM_Job_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;M Job Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TM__c</field>
            <operation>equals</operation>
            <valueField>TM_Job_Task__c.TM__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TM_Job_Task__c</referenceTo>
    <relationshipLabel>T&amp;M Lines</relationshipLabel>
    <relationshipName>T_M_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ITMLLinesService.cls
public interface ITMLLinesService {
    Map<Id, String> retrieveContractLinesTMDescription(List<TM_Line__c> theTMLList);
    void initStaticVariables(Map<TM__c, List<TM_Line__c>> tmLinesByTms);
    void validateTMLinesResourceType(List<TM_Line__c> theTMLList);
    void validateTMLinesUnitOfMeasure(List<TM_Line__c> theTMLList);
    void validateTMLinesRestOfFields(List<TM_Line__c> theTMLList);
    void populateLinesInfo(Map<TM__c, List<TM_Line__c>> tmLinesByTMs);
    void calcLineCost(Map<TM__c, List<TM_Line__c>> tmLinesByTms);
    void calcUnitPrice(TM__c tm, TM_Line__c tmLine);
    void calcUnitCost(TM__c tm, TM_Line__c tmLine);
    void calcTotals(Map<TM__c, List<TM_Line__c>> tmLinesByTMs);
    void validateResourceType(TM__c tm, TM_Line__c tmLine);
    void validateResource(TM__c tm, TM_Line__c tmLine);
    void validateContractLine(TM__c tm, TM_Line__c tmLine); //Ticket18265
    Boolean isCalcBaseOnResType(String lineCategory);

    //job task <<
    void validateUnitOfMeasure(TM__c tm, TM_Line__c tmLine);
    //ticket 19130 05.13.2023 <<
    //List<TM_Line__c> calculatePresumptiveChildLines(TM__c tm, TM_Job_Task__c jobTask, TM_Line__c parentLine, Integer nextTMLineNo);
    TM_Line__c calculatePresumptiveChildLines(TM__c tm, ACVTMJobTaskWrapper jobTaskWrapper, TM_Line__c tmLine, Integer nextTMLineNo);
    //ticket 19130 05.13.2023 >>
    //void createFlatPayLines(TM__c tm, ACVTMJobTaskWrapper jobTaskWrapper, Integer nextTMLineNo);
    void createSafetyPlanLine(TM__c tm, ACVTMJobTaskWrapper jobTaskWrapper, Integer nextTMLineNo);
    void calculateManifestFeeLine(TM__c tm, ACVTMJobTaskWrapper jobTaskWrapper, Integer nextTMLineNo);
    void calculateRinseOutFeeLine(TM__c tm, ACVTMJobTaskWrapper jobTaskWrapper, Integer nextTMLineNo);
    //job task >>
}